FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "バトルテント　ハジツゲかいじょうへ\n"
	.string "ようこそ　おいでなされた!\p"
	.string "こちらでは　かちぬきチームバトルの\n"
	.string "あんないを　しておりますぞ!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "かちぬきチームバトルに\n"
	.string "ちょうせん　されますかな?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "またの　ちょうせんを\n"
	.string "おまちして　おりますぞ!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "バトルテント　ハジツゲかいじょうでは\n"
	.string "かちぬきチームバトルを\l"
	.string "おこなって　おりますぞ!\p"
	.string "さんかする　かたには　しゅつじょう　させる\n"
	.string "3ひきの　ポケモンと　たたかいに　だす\l"
	.string "じゅんばんを　きめて　いただきますぞ!\p"
	.string "たたかいの　あいだは\n"
	.string "この　じゅんばん　どおりに\l"
	.string "ポケモンを　だすことに　なりますな!\p"
	.string "たたかいに　いちど　だした　ポケモンは\n"
	.string "けっちゃくが　つくまで\l"
	.string "こうたいさせる　ことが　できませぬ!\p"
	.string "さらに　3ターン　いないに\n"
	.string "たたかいの　けっちゃくが　つかなければ\l"
	.string "はんていと　なりますぞ!\p"
	.string "また　とちゅうで　ちょうせんを\n"
	.string "ちゅうだんしたい　ばあいは\l"
	.string "レポートを　かかないと\l"
	.string "つづけて　ちょうせんが　できないので\l"
	.string "おきをつけ　くだされ!\p"
	.string "みごと　3にんぬきを　なされた　あかつきには\n"
	.string "すてきな　しょうひんを\l"
	.string "おおくり　いたしますぞ!$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "バトルテントへ　おつれする　まえに\n"
	.string "レポートを　かきますが　よろしいですかな?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "レベル50と　レベル100の　へやが\n"
	.string "ありますが　どちらに　まいられますかな?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "では　ちょうせんする　ポケモンを\n"
	.string "3ひき　おえらび　くだされ!$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "おきゃくじん!!\p"
	.string "さんかできる　ポケモンが\n"
	.string "3ひき　おりませんぬ!\p"
	.string "また　もたせる　どうぐも\n"
	.string "すべて　ちがう　どうぐに　してくだされ!\p"
	.string "なお　タマゴ{STR_VAR_1} さんか　させる　ことは　できませぬ!\p"
	.string "じゅんびが　できましたら\n"
	.string "また　おこし　くだされ!$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "おきゃくじん!!\p"
	.string "さんかできる　ポケモンが\n"
	.string "3ひき　おりませぬ!\p"
	.string "さんかする　ためには\n"
	.string "すべて　ちがう　しゅるいの　ポケモンを\l"
	.string "3ひき　よういして　くだされ\p"
	.string "また　もたせる　どうぐも\n"
	.string "すべて　ちがう　どうぐに　してくだされ!\p"
	.string "なお　タマゴ{STR_VAR_1}さんか　させる　ことは　できませぬ!\p"
	.string "じゅんびが　できましたら\n"
	.string "また　おこし　くだされ!$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "では　バトルテントへ\n"
	.string "おつれいたしますぞ!$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "おきゃくじん!\p"
	.string "ぜんかい　レポートを　かいて\n"
	.string "しゅうりょう　しませんでしたな?\p"
	.string "ざんねんですが　その　ばあい\n"
	.string "ちょうせんは　むこうと　なりますぞ!\p"
	.string "また　はじめから\n"
	.string "ちょうせん　してくだされ!!$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "3にんぬき　たっせい\n"
	.string "おみごとで　ございました!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "レポートを　かきますので\n"
	.string "おまちくだされ!$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "3にんぬきを　たっせい　されましたので\n"
	.string "この　しょうひんを　おうけとり　くだされ!$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}は\n"
	.string "{STR_VAR_1}を　もらった！$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "……おおっ!\n"
	.string "どうぐが　いっぱいの　ようですな!\p"
	.string "どうぐを　せいりしてから\n"
	.string "また　おこしくだされ!$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "おつかれさまでした!\p"
	.string "レポートを　かきますので\n"
	.string "おまちくだされ!$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "またの　ちょうせんを\n"
	.string "おまちして　おりますぞ!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "バトルテントに　おつれする　まえに\n"
	.string "レポートを　かきますので　おまちくだされ!$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "バトルテント\n"
	.string "シダケかいじょうへ　ようこそ\p"
	.string "ここでは　トレーナーの\n"
	.string "しんらいの　こころを　ためしておる$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "バトルテント　シダケかいじょうに\n"
	.string "ちょうせん　するか?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "バトルテント　シダケかいじょうでの\n"
	.string "たたかいには　まもらなければ　ならない\l"
	.string "ひとつの　おきてが　ある\p"
	.string "ここでは　ポケモンは\n"
	.string "いれかえ　しか　できない!\p"
	.string "それいがいの　めいれいは\n"
	.string "いっさい　きんし　して　おるのだ!\p"
	.string "ポケモンには　おのれの　せいかくの　ままに\n"
	.string "かんがえ　こうどう　して　もらう!\p"
	.string "おぬしは　じぶんの\n"
	.string "ポケモンたちを　しんじて\l"
	.string "たたかいを　みまもって　やれ\p"
	.string "みごと　3にんの　トレーナーを\n"
	.string "うちやぶることが　できれば\l"
	.string "しょうひんを　さしあげよう\p"
	.string "また　とちゅうで　ちょうせんを\n"
	.string "ちゅうだん　したい　ときは\l"
	.string "きちんと　レポートを　かかないと\l"
	.string "つづけて　ちょうせん　できん　からな\l"
	.string "きを　つけてくれ……$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "おのれの　こころと　ポケモンを　きたえたら\n"
	.string "また　くるがよい……$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "レベル50の　へやと　レベル100の　へやが\n"
	.string "あるが　どちらに　ちょうせん　するのだ?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "おぬし……\p"
	.string "ちょうせん　できる　ポケモンが\n"
	.string "3ひき　おらんぞ!\p"
	.string "ちょうせん　するには\n"
	.string "すべて　ちがう　しゅるいの　ポケモンを\l"
	.string "3ひき　ようい　してくれ\p"
	.string "また　もたせる　どうぐも\n"
	.string "すべて　ちがう　もので　なければ　いかん\p"
	.string "なお　タマゴ{STR_VAR_1}ちょうせん　させる　ことは　できん!\p"
	.string "じゅんびを　ととのえてから　また　きなさい$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "おぬし……\p"
	.string "ちょうせん　できる　ポケモンが\n"
	.string "3ひき　おらんぞ!\p"
	.string "ちょうせん　するには\n"
	.string "すべて　ちがう　しゅるいの　ポケモンを\p"
	.string "3ひき　ようい　してくれ\p"
	.string "また　もたせる　どうぐも\n"
	.string "すべて　ちがう　もので　なければ　いかん\p"
	.string "そして　タマゴ{STR_VAR_1}ちょうせん\n"
	.string "させる　ことは　できん!\p"
	.string "じゅんびを　ととえてから　また　きなさい$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "では　ちょうせんする　ポケモンを\n"
	.string "3ひき　えらんでくれ$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "バトルテントへ　むかうまえに\n"
	.string "レポートを　かくが　よろしいか?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "それでは\n"
	.string "わしに　ついてこい……$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "よいものを　みせて　もらった\p"
	.string "それでは　レポートを　かこう……\n"
	.string "しばし　またれよ……"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "3にんぬき　たっせい　とは……\p"
	.string "おぬしと　ポケモンの　こころの　きずなは\n"
	.string "まことの　ようじゃな……$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "レポートに　かくぞ\n"
	.string "しばし　またれよ……$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "3にんぬきの　あかしに\n"
	.string "こちらを　さしあげよう……$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "バトルテント　カイナかいじょうへ\n"
	.string "ようこそ!\p"
	.string "バトルトレードの\n"
	.string "ごあんないは　こちらです!$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "バトルトレードに\n"
	.string "ちょうせん　しますか?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "バトルテント　カイナかいじょうでは\n"
	.string "レンタルポケモンを　つかった\l"
	.string "バトルトレード　という　イベントを\l"
	.string "おこなっています!\p"
	.string "まずは　バトルトレード　せんようの\n"
	.string "ポケモン　3ひきを　おかし　します!\p"
	.string "つぎに　そちらの　3ひきの　ポケモンを\n"
	.string "つかって　シングルバトルを\l"
	.string "おこなって　いただきます!\p"
	.string "みごと　たたかいに　しょうりすると\n"
	.string "たたかった　トレーナーと　ポケモンを\l"
	.string "トレード　することが　できます!\p"
	.string "トレードと　たたかいを　くりかえし\n"
	.string "みごと　3れんしょう　したら\l"
	.string "すてきな　しょうひんを　さしあげます!\p"
	.string "なお　とちゅうで　ちょうせんを\n"
	.string "ちゅうだん　したい　ときには\l"
	.string "きちんと　レポートを　かかないと\l"
	.string "つづけて　ちょうせんが　できません!\p"
	.string "くれぐれも　きをつけて　くださいね!$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "またの　ごりようを　おまちしていますよ!$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "レベル50と　レベル100の　イベント\n"
	.string "どちらに　ちょうせん　しますか?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "では　ちょうせんを　はじめる　まえに\n"
	.string "レポートを　かきますが　よろしいですか?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "それでは　ポケモンを\n"
	.string "おあずかり　します!$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "さあさあ　こちらに　どうぞ!$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "おつかれさまでした!\p"
	.string "レンタルポケモンと\n"
	.string "おあずかり　していた　ポケモンを\l"
	.string "こうかん　します!\p"
	.string "レポートを　かきますので\n"
	.string "しょうしょう　おまちください!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "レンタルポケモンと\n"
	.string "おあずかり　していた　ポケモンを\l"
	.string "こうかん　します!$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "3れんしょう　おめでとう　ございます!\p"
	.string "レンタルポケモンと\n"
	.string "おあずかり　していた　ポケモンを\l"
	.string "こうかん　します!\p"
	.string "レポートを　かきますので\n"
	.string "しょうしょう　おまちください!$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "3れんしょうを　きねんして"
	.string "こちらを　さしあげます!$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "おやや?\n"
	.string "どうぐが　いっぱい　ですねー\p"
	.string "どうぐを　せいり　してから\n"
	.string "また　きてください!$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "ちょうせんを　さいかいする　まえに\n"
	.string "レポートを　かきます!$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "おきゃくさまー!!\p"
	.string "ぜんかい　ちゃんと　レポートを　かいて\n"
	.string "しゅうりょう　しませんでしたね!\p"
	.string "ざんねんですが\n"
	.string "ちょうせんは　むこうと　なります!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "おきゃくさまの　ポケモンを\n"
	.string "おかえしします!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}は\n"
	.string "{STR_VAR_1}を　もらった！$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "バトルトレードの　ルールが　かかれてる!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "どの　せつめいを　よみますか?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "バトルトレードで　つかうことの　できる\n"
	.string "ポケモンは　3ひき　まで　です\p"
	.string "レンタルするとき　トレードするとき\n"
	.string "どちらの　ときも\l"
	.string "おなじ　しゅるいの　ポケモンを\m"
	.string "2ひき　いじょう　もつことは　できません$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "トレードが　できる　あいては\n"
	.string "あなたが　たたかいで\l
	.string "たおした　トレーナーです\p"
	.string "トレードで　うけとる　ことが　できるのは\n"
	.string "トレーナーが　つかっていた　ポケモンです$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "いちど　たたかいに　かつ　たびに\n"
	.string "1かい　1ひき　だけ　ポケモンを\l
	.string "トレード　することが　できます\p"
	.string "1かいの　ちょうせんで\n"
	.string "トレードが　できるのは\l
	.string "2にんめの　トレーナーまで　です$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "トレードを　おこなう　ときには\n"
	.string "2つ　ちゅういする　ことが　あります\p"
	.string "その1　トレードを　おこなう　ときは\n"
	.string "あいてから　うけとる　ポケモンの\l"
	.string "つよさは　かくにん　できません\p"
	.string "その2　ちょうせんを　はじめた　ときに\n"
	.string "かりた　レンタルポケモンの　じゅんばんが\l"
	.string "トレードの　あとの　たたかいにも\l"
	.string "ひきつがれます$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "バトルテント　カイナの　ポケモンは\n"
	.string "すべて　レンタルポケモン　です\p"
	.string "レンタルポケモンの　レベルは\n"
	.string "すべて　30に　なります$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "バトルテント　シダケかいじょうの\n"
	.string "ルールが　かかれている!$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "どの　せつめいを　よみますか?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "バトルテント　シダケかいじょう　では\n"
	.string "ポケモンたちが　じぶんで\l"
	.string "かんがえ　たたかいます\p"
	.string "じゅんすいな　やせいの　ときとは　ちがって\n"
	.string "ひとと　くらしている　ポケモンは\l"
	.string "せいかくに　よって　どんな　こうどうを\l"
	.string "するかが　かわるのです$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "とにかく　こうげきが\n"
	.string "すきな　せいかく\p"
	.string "じぶんの　みを　まもることが\n"
	.string "すきな　せいかく\p"
	.string "あいてを　こまらせたり\n"
	.string "かわったことが　すきな　せいかく\p"
	.string "ポケモンは　せいかくに　よって\n"
	.string "すきで　とくいな　わざと\l"
	.string "きらいで　にがてな　わざが　ちがいます$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "あいてに　むかって　じぶんから\n"
	.string "ちょくせつ　ダメージを　あたえる\l"
	.string "こうげきの　わざ\p"
	.string "たたかいの　じゅんびや　キズついた　からだの\n"
	.string "かいふくを　する　ぼうぎょの　わざ\p"
	.string "あいての　のうりょくを　さげたり\n"
	.string "どくや　まひに　したり　など\l"
	.string "すこし　かわった　ことを　する　わざ\p"
	.string "ポケモンは　すべての　わざを\n"
	.string "おおきく　3つの　しゅるいに　わけて\l"
	.string "どんな　わざを　だすか　かんがえて　います$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "トレーナーの　めいれいを　うけて　いない\n"
	.string "ポケモンは　うまく　わざを\l"
	.string "だせない　ことが　あります\p"
	.string "ポケモンは　きらいな　わざを\n"
	.string "つかうのは　とくいでは　ありません\p"
	.string "せいかくに　あわない　わざ　ばかりを\n"
	.string "おぼえさせて　いると　たたかいで\l"
	.string "ポケモンが　じぶんの　ちからを　はっき\l"
	.string "できない　ことが　おおく　なります$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "ポケモンの　せいかくの　なかには\n"
	.string "ピンチに　なることで　もともとの\l"
	.string "せいかくとは　ちがう　タイプの\l"
	.string "わざを　つかう　ように\l"
	.string "なるものが　あります\p"
	.string "ピンチに　なって　すこし　かわった\n"
	.string "こうどうを　はじめた　ポケモンには\l"
	.string "じゅうぶん　ちゅうい　しましょう$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "バトルテントでは\n"
	.string "あなたの　ポケモンの　レベルに　あわせて\l"
	.string "たいせんする　トレーナーの　ポケモンの\l"
	.string "レベルが　かわります\p"
	.string "ただし　レベル30より　ひくい　レベルの\n"
	.string "ポケモンを　つれた　トレーナーが\l"
	.string "とうじょう　することは　ありません$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "バトルテント　シダケかいじょうの\n"
	.string "ルールが　かかれている!$"
