gText_Birch_Welcome::
	.string "{JPN}いやー おまたせ おまたせ!\p"
	.string "{JPN}ポケットモンスターの せかいへ\n"
	.string "{JPN}ようこそ!\p"
	.string "{JPN}わたしの なまえは オダマキ!\p"
	.string "{JPN}でも みんな からは\n"
	.string "{JPN}ポケモンはかせと よばれて いるよ!\p"

gText_Birch_Pokemon::

	.string "$"

gText_Birch_MainSpeech::
	.string "{JPN}この せかいには\n"
	.string "{JPN}ポケモンと よばれる いきもの たちが\l"
	.string "{JPN}いたるところに すんでいる!\p"
	.string "{JPN}われわれ にんげんは\n"
	.string "{JPN}ポケモンと なかよく あそんだり\l"
	.string "{JPN}たすけあって しごとを したり\p"
	.string "{JPN}ときには ちからを あわせて\n"
	.string "{JPN}たたかったり しながら\p"
	.string "{JPN}いっしょに くらして いるんだ!\p"
	.string "{JPN}……しかし われわれは ポケモンの\n"
	.string "{JPN}すべてを しっている わけでは ない\p"
	.string "{JPN}ポケモンの ひみつは\n"
	.string "{JPN}まだまだ いっぱい ある!\p"
	.string "{JPN}その ひみつを ときあかす ため\n"
	.string "{JPN}わたしは けんきゅうを つづけている\l"
	.string "{JPN}という わけなんだ!\p$"

gText_Birch_AndYouAre::
	.string "{JPN}ところで きみは……?$"

gText_Birch_BoyOrGirl::
	.string "{JPN}おとこのこ?\n"
	.string "{JPN}それとも おんなのこ?$"

gText_Birch_WhatsYourName::
	.string "{JPN}なまえも おしえて くれるかい!$"

gText_Birch_SoItsPlayer::
	.string "{JPN}{PLAYER}{KUN} だね?$"

gText_Birch_YourePlayer::
	.string "{JPN}……そうか!\p"
	.string "{JPN}きみが こんど わたしの すむ まち\n"
	.string "{JPN}ミシロタウンに ひっこして くる\l"
	.string "{JPN}{PLAYER}{KUN} だったのか!\p$"

gText_Birch_AreYouReady::
	.string "{JPN}よーし じゅんびは いいかい?\p"
	.string "{JPN}これから きみ だけの ものがたりが\n"
	.string "{JPN}はじまろうと している!\p"
	.string "{JPN}ゆめと ぼうけんと であいに みちた\n"
	.string "{JPN}ポケットモンスターの せかいへ\l"
	.string "{JPN}ゆうきを もって とびこんで みてくれ!\p"
	.string "{JPN}では また あとで あおう!\n"
	.string "{JPN}けんきゅうじょで まって いるぞ!\p$"
