gText_Birch_Welcome::
	.string "はじめまして！\p"
	.string "ポケットモンスターの せかいへ\n"
	.string "ようこそ！\p"
	.string "わたしは オダマキ。\p"
	.string "みんなからは ポケモンはかせと\n"
	.string "よばれて いるよ。$"

gText_Birch_Pokemon::
	.string "これが ポケモンだよ。\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "この せかいには ポケモンと\n"
	.string "よばれる いきものが いる。\p"
	.string "ひとは ポケモンと なかよく\n"
	.string "くらして いるんだ。$"

gText_Birch_AndYouAre::
	.string "さて きみのことを\n"
	.string "おしえて くれるかな？$"

gText_Birch_BoyOrGirl::
	.string "きみは おとこのこ？\n"
	.string "それとも おんなのこ？$"

gText_Birch_WhatsYourName::
	.string "では きみの なまえを\n"
	.string "おしえて くれるかな？$"

gText_Birch_SoItsPlayer::
	.string "ふむ……\n"
	.string "{PLAYER} で いいかな？$"

gText_Birch_YourePlayer::
	.string "そうか！\p"
	.string "きみの なまえは\n"
	.string "{PLAYER} なんだね。\p"
	.string "よろしく！$"

gText_Birch_AreYouReady::
	.string "きみの ものがたりが\n"
	.string "いま はじまる！\p"
	.string "さあ いっておいで！$"
