gText_Birch_Welcome::
	.string "いやー　おまたせ　おまたせ!\p"
	.string "ポケットモンスターの　せかいへ\n"
	.string "ようこそ!\p"
	.string "わたしの　なまえは　オダマキ!\p"
	.string "でも　みんな　からは\n"
	.string "「ポケモンはかせ」と　よばれて　いるよ!\p"
	.string "いやー　おまたせ　おまたせ!\p$"

gText_Birch_Pokemon::
	.string "ポケットモンスター\n"
	.string "……すなわち　ポケモン\p$"

gText_Birch_MainSpeech::
	.string "この　せかいには\n"
	.string "ポケモンと　よばれる　いきもの　たちが\l"
	.string "いたるところに　すんでいる!\p"
	.string "われわれ　にんげんは\n"
	.string "ポケモンと　なかよく　あそんだり\l"
	.string "たすけあって　しごとを　したり\p"
	.string "ときには　ちからを　あわせて\n"
	.string "たたかったり　しながら\p"
	.string "いっしょに　くらして　いるんだ!\p"
	.string "……しかし　われわれは　ポケモンの\n"
	.string "すべてを　しっている　わけでは　ない\p"
	.string "ポケモンの　ひみつは\n"
	.string "まだまだ　いっぱい　ある!\p"
	.string "その　ひみつを　ときあかす　ため\n"
	.string "わたしは　けんきゅうを　つづけている\l"
	.string "という　わけなんだ!\p$"

gText_Birch_AndYouAre::
	.string "ところで　きみは……?$"

gText_Birch_BoyOrGirl::
	.string "おとこのこ?\n"
	.string "それとも　おんなのこ?$"

gText_Birch_WhatsYourName::
	.string "なまえも　おしえて　くれるかい!$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}　だね?$"

gText_Birch_YourePlayer::
	.string "……そうか!\p"
	.string "きみが　こんど　わたしの　すむ　まち\n"
	.string "ミシロタウンに　ひっこして　くる\l"
	.string "{PLAYER}{KUN}　だったのか!\p$"

gText_Birch_AreYouReady::
	.string "よーし　じゅんびは　いいかい?\p"
	.string これから　きみ　だけの　ものがたりが\n"
	.string "はじまろうと　している!\p"
	.string "ゆめと　ぼうけんと　であいに　みちた\n"
	.string "ポケットモンスターの　せかいへ\m"
	.string "ゆうきを　もって　とびこんで　みてくれ!\p"
	.string "では　また　あとで　あおう!\n"
	.string "けんきゅうじょで　まって　いるぞ!\p$"
