BerryBlender_Text_BlendWithTheBlendMaster:
	.string "めいじん『いかにも!\n"
	.string "わしが　ブレンドめいじん　じゃ!\p"
	.string "いっしょに　まわして\n"
	.string "わしの　すごい　わざを　みるがよい$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "めいじん『ふむむむっ!　おぬし\n"
	.string "わしの　すごい　わざを　みたいのじゃな?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "ふむむむっ!\p"
	.string "いまは　いそがしいのじゃな!\p"
	.string "あんしん　するのじゃ!\n"
	.string "わしは　きょう　ずっと　ここに　おる\l"
	.string "ようが　すんだら　すぐに　くるのじゃぞ!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "ふむむむっ!\p"
	.string "おぬし　きのみを　もっておらんぞ!\p"
	.string "わしは　きょう　ずっと　ここに　おるから\n"
	.string "はやく　きのみを　みつけて　くるのじゃぞ!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "そうじゃろう!\n"
	.string "そうじゃろう!\p"
	.string "とろころで　おぬし……\n"
	.string "むろん　ポロックの　つくりかたは\l"
	.string "しっておる　じゃろうな?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "ふむむむっ!\p"
	.string "まあ　かんたんな　ことじゃ!\p"
	.string "きのみ　ブレンダーの　マークが\n"
	.string "じぶんの　ところに　きたら\l"
	.string "ボタンを　おせば　いいだけじゃ!\p"
	.string "わしの　かんぺきな　おしかたを　みれば\n"
	.string "すぐに　わかるはずじゃ!$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "よしっ!\p"
	.string "では　はじめるぞ!\p"
	.string "めいじんと　いっしょに\n"
	.string "レッツ　きのみブレンダー!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "ふむむむっ!\p"
	.string "おぬし　ポロックケースを\n"
	.string "まだ　もっておらん　ようじゃぞ!\p"
	.string "わしは　きょう　ずっと　ここに　おるから\n"
	.string "ポロックケースを　もらってから\l"
	.string "また　くるのじゃ!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "ふむむむっ!\p"
	.string "おぬし　ポロックケースが\n"
	.string "いっぱいの　ようじゃぞ!\p"
	.string "わしは　きょう　ずっと　ここに　おるから\n"
	.string "ポロックを　へらしてから\l"
	.string "また　くるのじゃ!$"

BerryBlender_Text_WhoaAwesome:
	.string "すげぇー!$"

BerryBlender_Text_WickedlyFast:
	.string "はぇー!$"

BerryBlender_Text_WhatAnExpert:
	.string "うめぇー!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "めいじんと　いっしょに　やったら\n"
	.string "とっても　すごい　ポロック　できたの$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "やじるしを　おっていく\n"
	.string "スキのない　めの　うごき!\p"
	.string "ボタンを　おすときの\n"
	.string "せいかくな　ての　うごき!\p"
	.string "この　ふたつを　あわせもつ\n"
	.string "めいじんは　ホント　すごいね!$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "めいじんは　どこかの　やまおくで\n"
	.string "しゅぎょう　しているらしいの\p"
	.string "そして　ときどき\n"
	.string "ミナモシティに　やってきて\l"
	.string "きのみブレンダーを　1にちじゅう\l"
	.string "するらしいわ$"

