Text_PictureBookShelf:
	.string "ポケモンえほんが　そろってる!$"

Text_BookShelf:
	.string "いろんな　ほんが　いっぱいだ!$"

Text_PokemonCenterBookShelf:
	.string "ポケモンざっしが　ならんでる!\p"
	.string "……「ポケモンのとも」\n"
	.string "……「ポケモン　てちょう」\l"
	.string "……「かわいい　ポケモン」$"

Text_Vase:
	.string "たかそうな　つぼが　ある!\n"
	.string "のぞきこむと……\p"
	.string "なかは　からっぽ　だ!$"

Text_EmptyTrashCan:
	.string "なかは　からっぽ　だ!$"

Text_ShopShelf:
	.string "たくさんの　ポケモン　グッズが\n"
	.string "ところせましと　ならべられてる!$"

Text_Blueprint:
	.string "なにかの　せっけいず……?\n"
	.string "みても　チンプンカンプン!$"
