EventTicket_Text_OldSeaMapTooFar:
	.string "なんだ?\n"
	.string "ボロっちい　ちずを　もってきたってのは\l"
	.string "おまえさんか?　みせてみな!\p"
	.string "……　……　……\p"
	.string "こりゃ　また　ずいぶん　とおいなあ\n"
	.string "わりいが　ほかを　あたったほうが……$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "ハギ『こら!　わしの　おんじんの\n"
	.string "ねがいを　ことわるとは　なにごとだ!$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}　すまなかったね\n"
	.string "このふねを　たよって　きて　くれたのに……\l"
	.string "もちろん　いますぐに　しゅっこうだ!\p"
	.string "さあいくぞ!\n"
	.string "かいずに　ある　しまへ　しゅっぱつ!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "みょうな　チケットを\n"
	.string "もってきたのは　おまえさんか?\p"
	.string "おまえが　いこうと　しているのは\n"
	.string "とおく　はなれた　ちほうの　しま……\l"
	.string "そこには　なにが　まっているのか\l"
	.string "しって　いるやつは　いねえ……\l"
	.string "ううむ　ふなのりの　ちが　さわぐぜ!\p"
	.string "さあ　のりな!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "まったく　ハギ　せんちょうの\n"
	.string "きまぐれにも　まいるよなあ……\p"
	.string "もう　ミナモへ　かえるのかい?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "ふしぎな　かたちの　しまだなあ\n"
	.string "もう　ミナモへ　かえるか?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "ヘンテコな　チケットを\n"
	.string "いくつも　もってきたのは　おまえさんか?\p"
	.string "……　……　……ふむ\p"
	.string "こいつらで　いける　ところは\n"
	.string "どこも　ここから　とおい　しま\l"
	.string "そこでは　なにが　おきるのか\l"
	.string "なにが　まっているのか\l"
	.string "しっている　やつは　いねえ……\l"
	.string "ううむ　ふなのりの　ちが　さわぐぜ!\p"
	.string "さあ　のりな!\n"
	.string "まずは　どこから　いってみるかい?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "な……　なんか　おくふかくから\n"
	.string "ひくい　うなりが　きこえたような……\p"
	.string "だ　だいじょうぶか?\n"
	.string "もう　かえった　ほうが　いいんじゃないか?$"

FarawayIsland_Entrance_Text_Sign:
	.string "なんねんも　まえに　かかれたような\n"
	.string "ふるい　かきおきが　ある……\p"
	.string "……がつ　6か\n"
	.string "ここに　たちいる　にんげ……が\l"
	.string "ふたたび　……らわれると　すれば\l"
	.string "こころ　やさし……で　あらんことを\p"
	.string "……こに　その　ねがいを　しるし\n"
	.string "この　……を　あとにする\p"
	.string "……ジ$"

FarawayIsland_Interior_Text_Mew:
	.string "ミュー……$"
