EventTicket_Text_ShowOldSeaMap:
	.string "カイナいき　れんらくせん……\p"
	.string "え?　この　ちずの　とおりに\n"
	.string "いってくれって?\p"
	.string "わたしでは　よく　わからないので\n"
	.string "おまちください$"

EventTicket_Text_ThatPass:
	.string "カイナいき　れんらくせん……\p"
	.string "あら?\n"
	.string "その　チケットは……!$"

EventTicket_Text_ShowEonTicket:
	.string "ヘンテコな　チケットを\n"
	.string "もってきたのは　おまえさんか?\p"
	.string "おまえが　いこうと　しているのは\n"
	.string "みなみの　はての　ちっぽけな　しま……\p"
	.string "そこでは　なにが　おこるのか\n"
	.string "だれも　わからねえ……\l"
	.string "ううむ　ふなのりの　ちが　さわぐぜ!\p"
	.string "さあ　のりな!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "なにもねえ　ちんけな　しま　だな……\n"
	.string "ミナモへ　かえるか?$"

EventTicket_Text_SailHome:
	.string "よし!　かえると　するか!$"

EventTicket_Text_AsYouLike:
	.string "そうかい\n"
	.string "まあ　すきにするが　いいさ$"

SouthernIsland_Interior_Text_Sign:
	.string "すべての　ゆめは　もうひとつの　げんじつ\n"
	.string "それを　わすれるべからず……$"

SouthernIsland_Exterior_Text_Sign:
	.string "きおく　かすみし　ものは\n"
	.string "こころに　きざみつける　ことを　のぞむ……$"
