LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Tこちらは　ポケモンくじ\n"
	.string "ちゅうせん　コーナーです\p"
	.string "とうデパートに　おこし　いただいた　かたに\n"
	.string "もれなく　ポケモンくじを\l"
	.string "ひいて　いただいて　います!\p"
	.string "ひいた　くじの　ナンバーと\n"
	.string "おきゃくさまの　ポケモンの　IDが\l"
	.string "あっていましたら　すてきな　しょうひんを\l"
	.string "プレゼント　いたします!\p"
	.string "ポケモンくじを　ひかれますか?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "また　あした　いこう\n"
	.string "おこし　ください$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "それでは　また　おこし　ください$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "では　くじを　ひいて　ください\n"
	.string "…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "くじの　ナンバーは　{STR_VAR_1}です!\p"
	.string "ナンバーが　あなたの　ポケモンの　IDと\n"
	.string "いっちしているか　おしらべ　いたしますので\l"
	.string "しょうしょう　おまちください$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "おめでとう　ございます!\p"
	.string "あなたが　つれている\n"
	.string "{STR_VAR_1}ちゃんの　IDが　みごとに\l"
	.string "くじの　ナンバーと　いっち　しました!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "おめでとう　ございます!\p"
	.string "パソコンに　あずけている\n"
	.string "{STR_VAR_1}ちゃんの　IDが　みごとに\l"
	.string "くじの　ナンバーと　いっち　しました!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "ざんねんでした\n"
	.string "すべて　はずれの　ようです$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "2ケタ　あって　いましたので\n"
	.string "3とう　です!\l"
	.string "{STR_VAR_1}を　さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "3ケタ　あって　いましたので\n"
	.string "2とう　です!\l"
	.string "{STR_VAR_1}を　さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "4ケタ　あって　いましたので\n"
	.string "1とう　です!\l"
	.string "{STR_VAR_1}を　さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "なんと　5ケタ　すべて\n"
	.string "あって　いました!!\p"
	.string "とくとうです!!\n"
	.string "{STR_VAR_1}を　さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "………あら?\n"
	.string "どうぐが　いっぱいの　ようですね\p"
	.string "どうぐを　せいりしてから　もういちど\n"
	.string "おこし　ください.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}さん　ですね\n"
	.string "おまちして　おりました!\p"
	.string "では　しょうひんを\n"
	.string "おわたし　いたします$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "それでは　また　おこし　ください$"
