MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "この　わざを　おしえて　もらえるのは\n"
	.string "いちど　だけですが　いいですか?$"

MoveTutor_Text_SwaggerTeach:
	.string "ふふーん\n"
	.string "おれの　ポケモンは　すごいのさ!\l"
	.string "どの　ポケモンよりも　かっこいいのさ!\p"
	.string "……って　いばってたら\n"
	.string "もう　いばらない　ことに　したから\n"
	.string "かわりに　おまえの　ポケモンに\l"
	.string "いばる　わざを　おしえて　やってもいいぜ$"

MoveTutor_Text_SwaggerDeclined:
	.string "えー\n"
	.string "なんだよ　つきあい　わるいな$"

MoveTutor_Text_SwaggerWhichMon:
	.string "おう!\n"
	.string "どの　ポケモンが　いばりたいんだ?$"

MoveTutor_Text_SwaggerTaught:
	.string "こんどっから　いばる　かわりに\n"
	.string "じまん　するだけに　しておくよ……$"

MoveTutor_Text_RolloutTeach:
	.string "ねえ　ここから　あっちに　むかって\n"
	.string "いちども　まがらずに　ずーっと\l"
	.string "あるいて　いけるって　しってた?\l"
	.string "ぼく　なら　ころがって　いけるかも……!\p"
	.string "きみの　ポケモンも　ころがって　みる?\n"
	.string "ころがる　なら　おしえて　あげられるよ$"

MoveTutor_Text_RolloutDeclined:
	.string "えんりょ　いらないのに!\n"
	.string "ごろ　ごろ$"

MoveTutor_Text_RolloutWhichMon:
	.string "えへへ　いいよ!\n"
	.string "ぼく　そっくりの　ポケモンだと　いいな$"

MoveTutor_Text_RolloutTaught:
	.string "くさに　ねころがると　しあわせだなー\n"
	.string "ごろ　ごろ$"

MoveTutor_Text_FuryCutterTeach:
	.string "おなじ　わざをさ\n"
	.string "つづけて　なんども　だすと\l"
	.string "どんどん　つよくなる　わざが　あるの!\l"
	.string "しかも　むしタイプで　かっこいいの!\p"
	.string "れんぞくぎりって　いうんだけど\n"
	.string "おぼえて　みたい?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "きが　あわないねぇ$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "わーい!\n"
	.string "じゃ　おぼえさせる　ポケモンを　おしえてね$"

MoveTutor_Text_FuryCutterTaught:
	.string "れんぞくして　あたるか　どうかの\n"
	.string "スリルが　たのしいんだよねぇ$"

MoveTutor_MimicTeach:
	.string "おお　おわかいの!\n"
	.string "わしは　こども　じゃが\l"
	.string "このまちの　じいちゃんや　ばあちゃんの\l"
	.string "はなしかたを　ものまね　しておるのじゃ!\p"
	.string "どうかね?　おわかいの\n"
	.string "おぬしの　ポケモンに　わしが\l"
	.string "ものまねを　おしえて　やろうかね?$"

MoveTutor_MimicDeclined:
	.string "ちぇっ　なーんだ!\n"
	.string "ボク　ものまね　おしえたいのにな!$"

MoveTutor_Text_MimicWhichMon:
	.string "ふぉっ　ふぉっ!　よかろう!\n"
	.string "おしえさせる　ポケモンを　みせてみぃ$"

MoveTutor_Text_MimicTaught:
	.string "ものまねは　おくの　ふかい　わざじゃ!\n"
	.string "ボ…　わしの　ように\l"
	.string "うまく　できるかな?$"

MoveTutor_Text_MetronomeTeach:
	.string "あーん　ほしいものが　いっぱい!\n"
	.string "でも　おこづかいは　なくなっちゃったし……\p"
	.string "ゆびを　ふれば　まほうで\n"
	.string "おこづかい　でてくれば　いーのにな!\l"
	.string "なんてね　エヘヘ……\p"
	.string "しかたが　ないから\n"
	.string "あなたの　ポケモンに\l"
	.string "ゆびをふる　でも　おしえて　あげよっか?$"

MoveTutor_Text_MetronomeDeclined:
	.string "そっか\n"
	.string "きが　むいたら　またおいでよ!$"

MoveTutor_Text_MetronomeWhichMon:
	.string "うん!　じゃ　おしえるね\n"
	.string "どのコが　いいのかな?$"

MoveTutor_Text_MetronomeTaught:
	.string "ゆびをふると　ステキな　ことが\n"
	.string "いっぱい　おきるんだよー!\p"
	.string "わたしたちも　つかえたら　いーのにね!$"

MoveTutor_Text_SleepTalkTeach:
	.string "ふん……　ばあさんめ\n"
	.string "めざめるパワー　などに\l"
	.string "たより　おって……\p"
	.string "ワシと　いっしょに　おひるね　して\n"
	.string "ねごとでも　いってたほうが　たのしいのに\p"
	.string "もう　あんたの　ポケモンでも　ええわ\n"
	.string "ねごとを　おぼえて　つかってみんか?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "そうかい　そうかい……\n"
	.string "みんな　めざめるパワーが　だいすきかい$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "むぉう!　ものわかりの　いい　こどもよ!\n"
	.string "さて　ポケモンは　どいつが　いいかな?$"

MoveTutor_Text_SleepTalkTaught:
	.string "ワシ　ばあさんの　コイン\n"
	.string "いちども　あてたことが　なくてな……\l"
	.string "ねごとでも　ええから　あたらんかな$"

MoveTutor_Text_SubstituteTeach:
	.string "ふう\n"
	.string "こうやって　おくじょうから\l"
	.string "ひろい　せかいを　みていると……\p"
	.string "なんにんもの　じぶんが　いて\n"
	.string "いくつもの　じんせいを　たのしめたらなー\l"
	.string "って　おもうの!\l"
	.string "って　おもうの!\l"
	.string "そうだわ　あなたの　ポケモンちゃん!\n"
	.string "みがわりの　わざ　おぼえてみない?$"

MoveTutor_Text_SubstituteDeclined:
	.string "あら　そう?\n"
	.string "ポケモンなら　じぶんの　ぶんしんを\l"
	.string "つくる　ことが　できるのに$"

MoveTutor_Text_SubstituteWhichMon:
	.string "うふふ\n"
	.string "どの　ポケモンちゃんが　いいかしら?$"

MoveTutor_Text_SubstituteTaught:
	.string "わたしたち　にんげんは\n"
	.string "じぶんの　じんせいを\l"
	.string "おもいきり　たのしまなきゃ　ね!\l"
	.string "あなたも　そうなるように　いのってる!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "もう　できんわ!\p"
	.string "ぜったい　ムリだわ!\p"
	.string "かくとうタイプの　オレは\n"
	.string "トクサネの　ジムでは\l"
	.string "ぜんぜん　かてんわ!\p"
	.string "ちきしょーっ!　ボカ　ボカ!\n"
	.string "ボカ　ボカ!　ボカ　ボカ!\p"
	.string "なんだよ\n"
	.string "じめんを　なぐってる　だけだろ!\p"
	.string "それとも　おまえの　ポケモンに\n"
	.string "ばくれつパンチを　おしえて　ほしいのかよ?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "ちきしょー　おまえまで\n"
	.string "オレを　ばかに　するかっ!?\l
	.string "ボカ　ボカ!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "うぉー!　ほんとか!　いいやつだな!\n"
	.string "どのポケモンに　おしえれば　いい?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "なあ　ばくれつパンチ　つかって\n"
	.string "トクサネジムで　かって　きてくれよ!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "あーあ\n"
	.string "ルネシティの　ジムリーダーって\l"
	.string "すっごく　すてきだから\l"
	.string "ライバルが　いっぱい　なのよねー\p"
	.string "この　あたしが　すてみで　ぶつかっても\n"
	.string "ダメだったわ!\p"
	.string "ねえ　あなた!\n"
	.string "じきでんの　すてみタックル!\l"
	.string "あなたの　ポケモンに　おしえさせてよ!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "うん　もう!\n"
	.string "あなたに　まで　ふられちゃったわ$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "ん　じゃあ\n"
	.string "どの　ポケモンが　いいか　きめてよ$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "もう　いいわっ!\n"
	.string "あたしも　こいを　すてて\l"
	.string "つよい　オンナに　なってやるっ!$"

MoveTutor_Text_ExplosionTeach:
	.string "ぼかぁ　こんな　イナカで\n"
	.string "いつまでも　くすぶっとる　つもりは\l"
	.string "まったく　ないんじゃあー!\p"
	.string "みとれよ　いつか　トカイに　でて\n"
	.string "ドッカーンと　はでに　やって　やるわい!\p"
	.string "おいっ!　おまえ　きいとったん　なら\n"
	.string "けいきよく　だいばくはつを　おしえさせろ!$"

MoveTutor_Text_ExplosionDeclined:
	.string "がーっ!\n"
	.string "イナカもん　だからって　ことわるなあ!$"

MoveTutor_Text_ExplosionWhichMon:
	.string "ぃよーし　ドッカーンと　おぼえさせるか!\n"
	.string "どの　ポケモンが　ぶちかますんか?$"

MoveTutor_Text_ExplosionTaught:
	.string "いつも　ポケモンに　ばっか\n"
	.string "だいばくはつを　おしえとって\l"
	.string "かんじんの　ぼくは　いつまでも\l"
	.string "ばくはつ　できん……\p"
	.string "でも　ほんとは\n"
	.string "このまちに　いつまでも　いたいから\l"
	.string "かも　しれん……$"
