Text_BootUpPC:
	.string "{PLAYER}は\n"
	.string "パソコンの　スイッチを　いれた$"

gText_WhichPCShouldBeAccessed::
	.string "どこの　パソコンに　せつぞく　して\n"
	.string "つうしん　しますか?$"

gText_AccessedSomeonesPC::
	.string "だれかの　パソコンに　せつぞく　した!$"

gText_StorageSystemOpened::
	.string "ポケモンの　あずかり　システムを\n"
	.string "よびだした!$"

gText_AccessedPlayersPC::
	.string "{PLAYER}の　パソコンに　せつぞくした!$"

gText_AccessedLanettesPC::
	.string "マユミの　パソコンに　せつぞく　した!$"

gText_AccessedBillsPC::
	.string "マサキの　パソコンに　せつぞく　した!$"
