gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2}は　だれかのパソコンの\n"
	.string "ボックス『{STR_VAR_1}』に\l"
	.string "てんそう　された!$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2}は　"
#if IS_FRLG
	.string "マサキのパソコンの\n"
#else
	.string "マユミのパソコンの\n"
#endif
	.string "ボックス『{STR_VAR_1} 』に\l"
	.string "てんそう　された!$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "だれかのパソコンの\n"
	.string "ボックス『{STR_VAR_3}』が\l"
	.string "いっぱいだ!!\p"
	.string "{STR_VAR_2}は\n"
	.string "ボックス『{STR_VAR_1}』に\l"
	.string "てんそう　された!$"

gText_PkmnTransferredLanettesPCBoxFull::
#if IS_FRLG
	.string "マサキのパソコンの\n"
#else
	.string "マユミのパソコンの\n"
#endif
	.string "ボックス『{STR_VAR_3}』が\n"
	.string "いっぱいだ!!"
	.string "{STR_VAR_2}は\n"
	.string "ボックス『{STR_VAR_1}』に\l"
	.string "てんそう　された!$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2}は　{B_PC_CREATOR_NAME}のパソコンの\n"
	.string "ボックス『{STR_VAR_1}』に\l
	.string "てんそう　された!$"

gText_PlayerObtainedTheMon::
	.string "{PLAYER} obtained\n"
	.string "the {STR_VAR_1}!$"

gText_NoMoreRoomForPokemon::
	.string "ポケモンを　もちきれません!\p"
	.string "ボックスも　いっぱいで\n"
	.string "てんそう　できません$"

gText_NicknameThisPokemon::
	.string "{STR_VAR_1}に\n"
	.string "ニックネームを　つけますか?$"
