gText_PkmnTransferredSomeonesPC::
	.string "{JPN}{STR_VAR_2}は だれかのパソコンの\n"
	.string "{JPN}ボックス『{STR_VAR_1}』に\l"
	.string "{JPN}てんそう された!$"

gText_PkmnTransferredLanettesPC::
	.string "{JPN}{STR_VAR_2}は "
#if IS_FRLG
	.string "{JPN}マサキのパソコンの\n"
#else
	.string "{JPN}マユミのパソコンの\n"
#endif
	.string "{JPN}ボックス『{STR_VAR_1} 』に\l"
	.string "{JPN}てんそう された!$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "{JPN}だれかのパソコンの\n"
	.string "{JPN}ボックス『{STR_VAR_3}』が\l"
	.string "{JPN}いっぱいだ!!\p"
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}ボックス『{STR_VAR_1}』に\l"
	.string "{JPN}てんそう された!$"

gText_PkmnTransferredLanettesPCBoxFull::
#if IS_FRLG
	.string "{JPN}マサキのパソコンの\n"
#else
	.string "{JPN}マユミのパソコンの\n"
#endif
	.string "{JPN}ボックス『{STR_VAR_3}』が\n"
	.string "{JPN}いっぱいだ!!"
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}ボックス『{STR_VAR_1}』に\l"
	.string "{JPN}てんそう された!$"

gText_PkmnSentToPCAfterCatch::
	.string "{JPN}{STR_VAR_2}は {B_PC_CREATOR_NAME}のパソコンの\n"
	.string "{JPN}ボックス『{STR_VAR_1}』に\l"
	.string "{JPN}てんそう された!$"

gText_PlayerObtainedTheMon::
	.string "{JPN}{PLAYER}は {STR_VAR_1}を\n"
	.string "{JPN}てにいれた!$"

gText_NoMoreRoomForPokemon::
	.string "{JPN}ポケモンを もちきれません!\p"
	.string "{JPN}ボックスも いっぱいで\n"
	.string "{JPN}てんそう できません$"

gText_NicknameThisPokemon::
	.string "{JPN}{STR_VAR_1}に\n"
	.string "{JPN}ニックネームを つけますか?$"
