gText_WouldYouLikeToRestYourPkmn::
	.string "おつかれさまです!\n"
	.string "ポケモン　センター　です\p"
	.string "ここでは　ポケモンの\n"
	.string "たいりょく　かいふくを　します\p"
	.string "あなたの　ポケモンを\n"
	.string "やすませて　あげますか?$"

gText_IllTakeYourPkmn::
	.string "それでは\n"
	.string "おあずかり　いたします!$"

gText_RestoredPkmnToFullHealth::
	.string "おまちどおさま!\p"
	.string "おあずかり　した　ポケモンは\n"
	.string "みんな　げんきに　なりましたよ!$"

gText_WeHopeToSeeYouAgain::
	.string "またの\n"
	.string "ごりようを　おまち　してます!$"

gText_WelcomeCutShort::
	.string "おつかれさまです!\n"
	.string "ポケモン　センター　です\p"
	.string "ここでは　ポケモンの\n"
	.string "たいりょく　かいふくを　します\p"
	.string "あなたの　ポケモンを……$"

gText_NoticesGoldCard::
	.string "そ　それは……\n"
	.string "ひょっとして　ゴールドカード!?\p"
	.string "ああ……　きんいろが　まぶしい!\n"
	.string "4つの　ほしが　かがやかしい!\p"
	.string "わたしも　これまでに\n"
	.string "シルバーカードの　トレーナーさんなら\l"
	.string "なんにんか　みてきましたが\l"
	.string "ゴールドカードを　おもちの　かたは\l"
	.string "{PLAYER}さんが　はじめて　ですよ!\p"
	.string "さあ　{PLAYER}さんの\n"
	.string "ポケモンを　やすませて　あげましょう!$"

gText_YouWantTheUsual::
	.string "{PLAYER}さん　おつかれさまです!\n"
	.string "いつもので　よろしい　ですね!$"

gText_IllTakeYourPkmn2::
	.string "では　おあずかりさせて　いただきます!$"

gText_ThankYouForWaiting::
	.string "たいへん　おまたせ　いたしました!$"

gText_WeHopeToSeeYouAgain2::
	.string "また　いつでも　おこしください!$"

