	.align 2
gText_ConfirmSave::
	.string "{JPN}ここまでの かつやくを\n"
	.string "{JPN}ポケモンレポートに かきこみますか?$"

gText_AlreadySavedFile::
	.string "{JPN}まえに かかれた レポートに\n"
	.string "{JPN}うえから かいても いいですか?$"

gText_SavingDontTurnOff::
	.string "{JPN}ポケモンレポートに かきこんでいます\n"
	.string "{JPN}でんげんを きらないで ください$"

gText_PlayerSavedGame::
	.string "{JPN}{PLAYER} は\n"
	.string "{JPN}レポートに しっかり かきのこした$"

gText_DifferentSaveFile::
	.string "{JPN}ちゅうい!!\p"
	.string "{JPN}『つづきから はじめる』で\n"
	.string "{JPN}ぼうけん していた レポートが\l"
	.string "{JPN}かかれています!\p"
	.string "{JPN}そちらで プレイしていた ぼうけんや\n"
	.string "{JPN}すべての ポケモン どうぐ などが\l"
	.string "{JPN}きえてしまいます……\p"
	.string "{JPN}ほんとうに\n"
	.string "{JPN}うえから かいても いいですか?$"

gText_SaveError::
	.string "{JPN}レポートが かけませんでした\p"
	.string "{JPN}バックアップカートリッジを\n"
	.string "{JPN}こうかんしてください!$"

gText_SavingDontTurnOffPower::
	.string "{JPN}ポケモンレポートに かきこんでいます\n"
	.string "{JPN}でんげんを きらないで ください$"
