	.align 2
gText_ConfirmSave::
	.string "ここまでの　かつやくを\n"
	.string "ポケモンレポートに　かきこみますか?$"

gText_AlreadySavedFile::
	.string "まえに　かかれた　レポートに\n"
	.string "うえから　かいても　いいですか?$"

gText_SavingDontTurnOff::
	.string "ポケモンレポートに　かきこんでいます\n"
	.string "でんげんを　きらないで　ください$"

gText_PlayerSavedGame::
	.string "{PLAYER}　は\n"
	.string "レポートに　しっかり　かきのこした$"

gText_DifferentSaveFile::
	.string "ちゅうい!!\p"
	.string "『つづきから　はじめる』で\n"
	.string "ぼうけん　していた　レポートが\l"
	.string "かかれています!\p"
	.string "そちらで　プレイしていた　ぼうけんや\n"
	.string "すべての　ポケモン　どうぐ　などが\l
	.string "きえてしまいます……\p"
	.string "ほんとうに\n"
	.string "うえから　かいても　いいですか?$"

gText_SaveError::
	.string "レポートが　かけませんでした\p"
	.string "バックアップカートリッジを\n"
	.string "こうかんしてください!$"

gText_SavingDontTurnOffPower::
	.string "ポケモンレポートに　かきこんでいます\n"
	.string "でんげんを　きらないで　ください$"
