ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "このさきに　すすむのかね?\p"
	.string "もし　よかったら\n"
	.string "あさせのしおと　あさせのかいがらを\l"
	.string "あつめてきて　くれないか\p"
	.string "ざいりょうが　あつまったら\n"
	.string "わたしが　いいもの　つくるんだがね$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "あさせのしおと　あさせのかいがら\n"
	.string "それぞれ　4つ　あれば\l"
	.string "かいがらのすずが　つくれるんだが……\p"
	.string "かいがらのすずの　ざいりょう　なら\n"
	.string "まいにち　とれるよ$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "お!　あさせのしおと　あさせのかいがら!\n"
	.string "りょうも　じゅうぶんだ!\p"
	.string "これで　かいがらのすず\n"
	.string "つくっても　いいかね?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "かいがらのすず\n"
	.string "さっそく　つくらせて　もらうよ\p"
	.string "……　……　……\n"
	.string "……　……　……\p"
	.string "よし　できたっ!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "ポケモンに　もたせてあげると　よろこぶよ\p"
	.string "なんたって　かいがらのすずの　ねいろは\n"
	.string "てんか　いっぴん　だからね\p"
	.string "かいがらのすずの　ざいりょう　なら\n"
	.string "まいにち　とれるから\l"
	.string "そろえば　また　つくらせて　もらうよ$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "そうかね……\n"
	.string "かいがらのすず　つくりたかった……$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "つくっても　バッグが　いっぱいで\n"
	.string "もてない　ようだね……\p"
	.string "せいりして　また　くると　いいよ$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "あさせのしおを　とった　あと……\n"
	.string "いまは　なにも　ない……$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "あさせのかいがらを　みつけた　あと……\n"
	.string "いまは　なにも　ない……$"
