Route102_Text_CalvinIntro:
	.string "{JPN}ポケモン つれていれば\nキミも りっぱな ポケモントレーナー!\lボクの ちょうせん うけるよね!$"

Route102_Text_CalvinDefeated:
	.string "{JPN}ああ まけた……\nもっと そだてておけば よかったよ$"

Route102_Text_CalvinPostBattle:
	.string "{JPN}キミ つよいなら つよいって\nさいしょから いって くれよな!$"

Route102_Text_CalvinRegister:
	.string "{JPN}ボク あれから がんばってるよ!\nこんど たたかいたい から\lポケナビ とうろく してよ!$"

Route102_Text_CalvinRegisterShort:
	.string "{JPN}こんど また たたかいたい から\nポケナビ とうろく してよ!$"

Route102_Text_CalvinRematchIntro:
	.string "{JPN}キミに まけてから ひっしに\nポケモン そだてたんだ! もちろん\lボクの ちょうせん うけるよね!$"

Route102_Text_CalvinRematchDefeated:
	.string "{JPN}ああ まけた……\nそだてかた わるいのかな$"

Route102_Text_CalvinRematchPostBattle:
	.string "{JPN}キミが つよくなるなら\nボクも もっと つよくなって みせるよ!$"

Route102_Text_AllenIntro:
	.string "{JPN}きみ トレーナーに なったばかり?\nおたがい しょしんしゃ だね!$"

Route102_Text_AllenDefeated:
	.string "{JPN}かてると おもったから\nこえを かけたのに!$"

Route102_Text_AllenPostBattle:
	.string "{JPN}まだ 1かいも かってない……\nはやく かちたいなあ……$"

Route102_Text_RickIntro:
	.string "{JPN}おっと! めが あったな!\nむしポケモンで あいてを するぜ!$"

Route102_Text_RickDefeated:
	.string "{JPN}まけてしまった!$"

Route102_Text_RickPostBattle:
	.string "{JPN}めが あった トレーナーには\nしょうぶを いどむのが きまりさ!$"

Route102_Text_TianaIntro:
	.string "{JPN}わたしは どんどん かちぬいて\nさいきょうの トレーナーを めざすのよ!\pあなたも きょうりょく してね!$"

Route102_Text_TianaDefeated:
	.string "{JPN}わたしが あなたに\nきょうりょく しちゃった みたいね……$"

Route102_Text_TianaPostBattle:
	.string "{JPN}どんどん かちぬくには\nもっと たくさん ポケモンを\lつかまえないと いけない みたいね!$"

Route103_Text_DaisyIntro:
	.string "{JPN}こころ やすらぐ かおりに\nあなたも さそわれたのですね……$"

Route103_Text_DaisyDefeated:
	.string "{JPN}わたくしの かおりに\nまどわされませんでしたね……$"

Route103_Text_DaisyPostBattle:
	.string "{JPN}アロマとは かおりのこと……\nかおりは こころと からだを いやすのです$"

Route103_Text_AmyIntro:
	.string "{JPN}クミ『あたしは クミ!\nこっちは いもうとの ルミ!\lふたりで いっしょに たたかうのよ!$"

Route103_Text_AmyDefeated:
	.string "{JPN}クミ『まけっちゃったよぉ……$"

Route103_Text_AmyPostBattle:
	.string "{JPN}クミ『ふたりを あいてに するのって\nいろんな ことを かんがえるよね!$"

Route103_Text_AmyNotEnoughPokemon:
	.string "{JPN}クミ『あら?\nポケモン 1ひきしか つれてないんだね!\lそれじゃあ あたしたちと たたかえないわ!$"

Route103_Text_LivIntro:
	.string "{JPN}ルミ『あたしたちは ふたりで ひとり\nいっしょに たたかうんだよ!$"

Route103_Text_LivDefeated:
	.string "{JPN}ルミ『まけちゃったよぉ おねえちゃぁん……$"

Route103_Text_LivPostBattle:
	.string "{JPN}ルミ『おねえちゃんと あたしは\nいきが ぴったり あってるのに……\pまけちゃったよぉ……$"

Route103_Text_AmyLivRegister:
	.string "{JPN}ルミ『あたしたち ほんとは\nもっと つよいんだもん……\lほんとうだから! こんど みせるから!$"

Route103_Text_LivNotEnoughPokemon:
	.string "{JPN}ルミ『あたしたちと たたかいたいなら\nポケモンを 2ひき つれてないと ダメよ!\lじゃないと しょうぶに ならないんだから!$"

Route103_Text_AmyRematchIntro:
	.string "{JPN}クミ『あたしは クミ!\nこっちは いもうとの ルミ!\lふたりで いっしょに たたかうのよ!$"

Route103_Text_AmyRematchDefeated:
	.string "{JPN}クミ『くやしい……\nまた かてなかったよぉ……$"

Route103_Text_AmyRematchPostBattle:
	.string "{JPN}クミ『ふたりを あいてに するのって\nいろんな ことを かんがえるよね!$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "{JPN}クミ『あら?\nポケモン 1ひきしか つれてないんだね!\lそれじゃあ あたしたちと たたかえないわ!$"

Route103_Text_LivRematchIntro:
	.string "{JPN}ルミ『あたしたちは ふたりで ひとり\nいつも いっしょに たたかうんだよ!$"

Route103_Text_LivRematchDefeated:
	.string "{JPN}ルミ『また まけちゃったよぉ\nおねえちゃぁん……$"

Route103_Text_LivRematchPostBattle:
	.string "{JPN}ルミ『おねえちゃんと あたしは\nいきが ぴったり あってるのに……\pどうして また まけちゃったの?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "{JPN}ルミ『あたしたちと たたかいたいなら\nポケモンを 2ひき つれてないと ダメよ!\lじゃないと しょうぶに ならないんだから!$"

Route103_Text_AndrewIntro:
	.string "{JPN}つりいとが からまって イライラするーっ!\nええいっ しょうぶだっ!$"

Route103_Text_AndrewDefeated:
	.string "{JPN}まけたっ!\nよけいに イライラするぞーっ!$"

Route103_Text_AndrewPostBattle:
	.string "{JPN}ええい はらだたしい……!\nイライライライラ……$"

Route103_Text_MiguelIntro:
	.string "{JPN}わたしの ポケモンちゃん\nすごく かわいいから みていきたまえ!$"

Route103_Text_MiguelDefeated:
	.string "{JPN}あわわ……\nわたしの ポケモンちゃん!$"

Route103_Text_MiguelPostBattle:
	.string "{JPN}かわいい ポケモンちゃんは\nやられた すがたも かわいいな……$"

Route103_Text_MiguelRegister:
	.string "{JPN}なんどでも かわいい ポケモンちゃんを\nみにきて もらうんだからね!$"

Route103_Text_MiguelRematchIntro:
	.string "{JPN}きみ! わたしの ポケモンちゃん\nさらに かわいく なったのだ!$"

Route103_Text_MiguelRematchDefeated:
	.string "{JPN}ああ!\nわたしの ポケモンちゃん!$"

Route103_Text_MiguelRematchPostBattle:
	.string "{JPN}いっしょに いれば いるほど\nポケモンが かわいくなって たまらん!$"

Route103_Text_PeteIntro:
	.string "{JPN}この くらいの きょり\nおよいで わたれば いーのにさ!$"

Route103_Text_PeteDefeated:
	.string "{JPN}おお やるじゃん$"

Route103_Text_PetePostBattle:
	.string "{JPN}なーるほど\pそれ ほど たよれる ポケモンなら\nおもわず なみのり したくなる ってもんだ$"

Route103_Text_IsabelleIntro:
	.string "{JPN}きゃあ ぶつかるわ!\nあぶないっ!$"

Route103_Text_IsabelleDefeated:
	.string "{JPN}んん……$"

Route103_Text_IsabellePostBattle:
	.string "{JPN}わたし およぎが へたで\nれんしゅう してたのよ……\lぶつかりそうに なって ゴメンね$"

Route103_Text_RhettIntro:
	.string "{JPN}うぉっ!\nなぜ こんな せまいところに!?$"

Route103_Text_RhettDefeated:
	.string "{JPN}うぉっ できる!$"

Route103_Text_RhettPostBattle:
	.string "{JPN}せまい ところが\nすき なのかい きみは?$"

Route103_Text_MarcosIntro:
	.string "{JPN}おれっちの ギターに さそわれて\nやって きたのかーい?$"

Route103_Text_MarcosDefeated:
	.string "{JPN}おれっちの ひとりショーが だいなしだよ$"

Route103_Text_MarcosPostBattle:
	.string "{JPN}ひとの すくない ところで\nギターを ひいていたのに\lこんなにも あつまって きたぜ!\pぷ プロを めざして みるか!$"

Route104_Text_GinaIntro:
	.string "{JPN}ナオ『よーし!\nあたしたちの ポケモンと たたかうです!$"

Route104_Text_GinaDefeat:
	.string "{JPN}ナオ『まけて すごく くやしいです$"

Route104_Text_GinaPostBattle:
	.string "{JPN}ナオ『うわー {STR_VAR_1} つよいです!\nあたしたち もっと しゅぎょう するです$"

Route104_Text_GinaNotEnoughMons:
	.string "{JPN}ナオ『あら? ポケモン 1ひき だけですか!\nじゃあ あたしたち たたかわない です!\pだって ポケモン 1ひき だけだと\nポケモンが さびしそうで かわいそう です!$"

Route104_Text_MiaIntro:
	.string "{JPN}ミオ『あたしたち ふたご だから\nポケモンしょうぶも いっしょに するです!$"

Route104_Text_MiaDefeat:
	.string "{JPN}ミオ『ふたりで しょうぶ したのに\nまけちゃったです……$"

Route104_Text_MiaPostBattle:
	.string "{JPN}ミオ『もっと ポケモン そだてて\n{STR_VAR_1} みたいに つよく なるです!$"

Route104_Text_MiaNotEnoughMons:
	.string "{JPN}ミオ『あたしたちと たたかうですか?\pじゃあ ポケモンを\n2ひき つれてないと ダメですよ!\lだって あたしたち つよいもん!$"

Route104_Text_IvanIntro:
	.string "{JPN}みずポケモンの エキスパートとは\nなにを かくそう オレのこと!\p……え?\nしらないの?$"

Route104_Text_IvanDefeat:
	.string "{JPN}けっこう つよいと おもってたんだけどな\nじぶんのこと…… がっかり……$"

Route104_Text_IvanPostBattle:
	.string "{JPN}つりに むちゅうに なってて\nポケモン そだてるのを わすれてたよ……$"

Route104_Text_BillyIntro:
	.string "{JPN}すなはまに あしあと つけるのって\nたのしーよねー!$"

Route104_Text_BillyDefeat:
	.string "{JPN}うへーっ!\n"
	.string "{JPN}クツに すなが はいって ジャリジャリする!$"

Route104_Text_BillyPostBattle:
	.string "{JPN}すなはまを ボクの あしあとで\nいっぱいに したいんだけど\lすぐに きえちゃうんだよなぁ$"

Route104_Text_HaleyIntro:
	.string "{JPN}しょうぶ しようかな……\nやめとこうかな……\pえーい! たたかっちゃえ!$"

Route104_Text_HaleyDefeat:
	.string "{JPN}たたかわなければ よかったかな……$"

Route104_Text_HaleyPostBattle:
	.string "{JPN}どっちに しようか まよってる とき\nじぶんで きめないで たにんに まかせると\lどっちに なっても こうかいするね……$"

Route104_Text_HaleyRegister1:
	.string "{JPN}あなた つよいけど\nポケナビに とうろく しようかな……\lやめとこうかな……\pえーい! とうろくしちゃえ!$"

Route104_Text_HaleyRegister2:
	.string "{JPN}あなた つよいけど\nポケナビに とうろく しようかな……\lやめとこうかな……\pえーい! とうろくしちゃえ!$"

Route104_Text_HaleyRematchIntro:
	.string "{JPN}あたしと しょうぶ してもらうわよ!$"

Route104_Text_HaleyRematchDefeat:
	.string "{JPN}うーん……\nかてると おもったのにな$"

Route104_Text_HaleyPostRematch:
	.string "{JPN}たたかうって じぶんで きめたから\nまけても すっきり してるわ!\p……もちろん まけて くやしいけどね$"

Route104_Text_WinstonIntro:
	.string "{JPN}ボクが あいてして あげるよ\nこの おかねもちの ボクがね$"

Route104_Text_WinstonDefeat:
	.string "{JPN}どうして かてないんだ……!?$"

Route104_Text_WinstonPostBattle:
	.string "{JPN}おかねじゃ かてない ものが ある……\nそれが ポケモンなんだね……$"

Route104_Text_WinstonRegister1:
	.string "{JPN}ん? きみ ポケナビを てにいれたね!\pボクが とうろくして あげよう\nこの おかねもちの ボクがね$"

Route104_Text_WinstonRegister2:
	.string "{JPN}ん? きみ ポケナビを てにいれたね!\pボクが とうろくして あげよう\nこの おかねもちの ボクがね$"

Route104_Text_WinstonRematchIntro:
	.string "{JPN}きみに まけてから いろいろ\nポケモンのこと べんきょう したんだ!$"

Route104_Text_WinstonRematchDefeat:
	.string "{JPN}また まけた……\nどうして かてないんだ……!?$"

Route104_Text_WinstonPostRematch:
	.string "{JPN}おかねもちの ボク なのに\nなかなか ポケモンに かてない……\pなんて おくが ふかいんだろう\nポケモンって……$"

Route104_Text_CindyIntro:
	.string "{JPN}あなたと であったのも なにかの ごえん\nおてあわせを おねがい できるかしら$"

Route104_Text_CindyDefeat:
	.string "{JPN}まあ!$"

Route104_Text_CindyPostBattle:
	.string "{JPN}であいは わかれの はじまり……\nまた どこかで おあいしましょう$"

Route104_Text_CindyRegister1:
	.string "{JPN}あら…… また おあい しましたわね\pこんなに ごえんが あるんですもの\nポケナビに とうろく して くださいませ$"

Route104_Text_CindyRegister2:
	.string "{JPN}この ごえんを きねんして\nポケナビに とうろく して くださいませ$"

Route104_Text_CindyRematchIntro:
	.string "{JPN}また おあい しましたわね\nおてあわせ おねがい できるかしら$"

Route104_Text_CindyRematchDefeat:
	.string "{JPN}あら……\nわたくし ベストを つくしましたのに……$"

Route104_Text_CindyPostRematch:
	.string "{JPN}であいは わかれの はじまり……\nまた どこかで おあいしましょう$"

Route104_Text_DarianIntro:
	.string "{JPN}つよそうな ポケモンが つれたっ!\nさかなの おうさま って かんじだ!\lこれは つよそうだぞっ!$"

Route104_Text_DarianDefeat:
	.string "{JPN}なっにい$"

Route104_Text_DarianPostBattle:
	.string "{JPN}おい なまえ まけ してるじゃないか\nおれの コイキングよ!$"

Route105_Text_FosterIntro:
	.string "{JPN}この あたりに\nふしぎな いわが あるらしいが\lきみ しらないかい?$"

Route105_Text_FosterDefeated:
	.string "{JPN}いわのこと ばかり かんがえて\nポケモン よわいまま だったか……$"

Route105_Text_FosterPostBattle:
	.string "{JPN}すてきな いわ だったら\nなんじかん みていても あきないよ……$"

Route105_Text_LuisIntro:
	.string "{JPN}よかった! こどもが\nおぼれているのかと しんぱい したよ!\pだいじょうぶ そうだから しょうぶ だな!$"

Route105_Text_LuisDefeated:
	.string "{JPN}ゴボゴボ……$"

Route105_Text_LuisPostBattle:
	.string "{JPN}すなはまに むかって かたてを ふるのが\nおぼれたときの サインだぜ!$"

Route105_Text_DominikIntro:
	.string "{JPN}あおい うみで およいでいると\nさいこうの きぶん だな!$"

Route105_Text_DominikDefeated:
	.string "{JPN}まけた……\nブルーな きぶん……$"

Route105_Text_DominikPostBattle:
	.string "{JPN}うみが あおい りゆう!?\pカイナの はくぶつかんで きいたけど\nそんなの わすれちまったよ!$"

Route105_Text_BeverlyIntro:
	.string "{JPN}みずに はいると からだが かるくなるわね\nなんだか スリムに なったみたい!$"

Route105_Text_BeverlyDefeated:
	.string "{JPN}ぷかぷか……$"

Route105_Text_PostBattle:
	.string "{JPN}みずの なかでは たいじゅうが\n10ぶんの1 くらいに なるのよ\pと すると いま わたしは……\nいけない! たいじゅうが バレちゃうわ!$"

Route105_Text_ImaniIntro:
	.string "{JPN}あおい そら……\nひろい うみ……\lのどか よねー……$"

Route105_Text_ImaniDefeated:
	.string "{JPN}なごんでいる うちに\nまけちゃったわーっ!$"

Route105_Text_ImaniPostBattle:
	.string "{JPN}あたしと いると なごむって いわれたいの\nうふふふふ!$"

Route105_Text_AndresIntro:
	.string "{JPN}うみに こそ なにかが あると\nかくしんが ある!$"

Route105_Text_AndresDefeated:
	.string "{JPN}うん…… わし\nしょうぶは よわいんだよ$"

Route105_Text_AndresPostBattle:
	.string "{JPN}せかいじゅうの うみには\nまだまだ ひみつが あるはずだ!\lぜんぶ さがしまくるぞ!$"

Route105_Text_AndresRegister:
	.string "{JPN}ん? こんな よわい わしでも\nポケナビ とうろくして くれるのか?$"

Route105_Text_AndresRematchIntro:
	.string "{JPN}しょうぶは よわいと いっているのに……\nわし なんかで いいのか?$"

Route105_Text_AndresRematchDefeated:
	.string "{JPN}うん…… やっぱり かてないな$"

Route105_Text_AndresRematchPostBattle:
	.string "{JPN}しょうぶは よわいが\nたんきゅうしんは きみにも まけん!\lせかいじゅうの うみを たび するぞ!$"

Route105_Text_JosueIntro:
	.string "{JPN}なれない およぎで つかれたー\nきばらしに ポケモンしょうぶ じゃい!$"

Route105_Text_JosueDefeated:
	.string "{JPN}うみで たたかった から まけたんだ$"

Route105_Text_JosuePostBattle:
	.string "{JPN}やっぱりさ おれには\nうみより そらが にあってるんだよ$"

Route106_Text_ElliotIntro:
	.string "{JPN}うみづりと かわづり\nキミは どっちが すき?$"

Route106_Text_ElliotDefeated:
	.string "{JPN}まるで うみづりの ように\nごうかいに まけたぞーっ!$"

Route106_Text_ElliotPostBattle:
	.string "{JPN}うみでも かわでも つりは サイコーだ!\nキミも そう おもうだろ!?$"

Route106_Text_ElliotRegister:
	.string "{JPN}つりも いいけど しょうぶも いいな!\nキミ よかったら また たのむよ!$"

Route106_Text_ElliotRematchIntro:
	.string "{JPN}ポケモン つりまくったからね\nすごい しょうぶを してみせるぞー!$"

Route106_Text_ElliotRematchDefeated:
	.string "{JPN}また ごうかいに まけたぞーっ!$"

Route106_Text_ElliotRematchPostBattle:
	.string "{JPN}かっても まけても ポケモンは サイコーだ!\nキミも そう おもうだろ!?$"

Route106_Text_NedIntro:
	.string "{JPN}トイレに いきたくなったとき\nみんなは どうしてるんだろう……?\pトイレに いっている あいだに\nもし おおものが かかったらと おもうと……$"

Route106_Text_NedDefeated:
	.string "{JPN}トイレを がまん してたから\nまけたんだよ きっと……$"

Route106_Text_NedPostBattle:
	.string "{JPN}ああっ!\nおおものが つれそうな よかん……!$"

Route106_Text_DouglasIntro:
	.string "{JPN}はっはっはっ!\nりくでは はやく はしれないが\lみずの なかなら まけないぞ!$"

Route106_Text_DouglasDefeated:
	.string "{JPN}まいりましたーっ!$"

Route106_Text_DouglasPostBattle:
	.string "{JPN}すいえいの きょうそうなら まけないのに……$"

Route106_Text_KylaIntro:
	.string "{JPN}うみは わたしの にわ\nこども だからって てかげん しないわよ!$"

Route106_Text_KylaDefeated:
	.string "{JPN}ひょっとして\nてかげん してないよね?$"

Route106_Text_KylaPostBattle:
	.string "{JPN}なみに ゆられて ただようのが だいすき\nあなたも やってみない?$"

Route107_Text_DarrinIntro:
	.string "{JPN}むにゃむにゃ……\pなみに ゆられてたら きもちよくなって\nうっかり ねてしまった!$"

Route107_Text_DarrinDefeated:
	.string "{JPN}あはは まけた……\nまた ねますか……$"

Route107_Text_DarrinPostBattle:
	.string "{JPN}うみに うかんで なみに ゆられてると\nふかふかの ベッドで ねてる みたいだよ!$"

Route107_Text_TonyIntro:
	.string "{JPN}うみは オレの にわ みたいな もの!\nしょうぶ しようぜ!$"

Route107_Text_TonyDefeated:
	.string "{JPN}ホームグラウンドで まけた……\nショック!$"

Route107_Text_TonyPostBattle:
	.string "{JPN}おおきな ユメを いっぱい つめてー\nでっかい うみを ひとおよぎー\pさぁて まだまだ およぐぞー!$"

Route107_Text_TonyRegister:
	.string "{JPN}ショックを うけたオレを\nきみが わすれない ために……!$"

Route107_Text_TonyRematchIntro:
	.string "{JPN}でっかい うみを およいでいたら\nポケモンが すっごく つよくなったぞー!$"

Route107_Text_TonyRematchDefeated:
	.string "{JPN}ショック!!\pポケモンは つよくなったが\nトレーナーの おれが よわいまま!?$"

Route107_Text_TonyRematchPostBattle:
	.string "{JPN}たたかいの なかで おぼえたことが\nトレーナーとしての つよさに つながる!\lでっかい うみが そう いっていたぞー!$"

Route107_Text_DeniseIntro:
	.string "{JPN}ムロタウン っていう\nちいさな まちを しってる?$"

Route107_Text_DeniseDefeated:
	.string "{JPN}ヤダ もーっ!$"

Route107_Text_DenisePostBattle:
	.string "{JPN}ムロタウンの しゅうかいじょで\nふしぎな ことばが はやって いるのよ!$"

Route107_Text_BethIntro:
	.string "{JPN}わたしと しょうぶが したいの?\nいいわ! あいてに なって あげる!$"

Route107_Text_BethDefeated:
	.string "{JPN}わたしじゃ あいてに ならなかったわ!$"

Route107_Text_BethPostBattle:
	.string "{JPN}あなた まだまだ つよく なりそうね\nわたしも がんばろうっと!$"

Route107_Text_LisaIntro:
	.string "{JPN}ユミ『あたしたち きょうだい ふたりで\nしょうぶを させてもらうわ!$"

Route107_Text_LisaDefeated:
	.string "{JPN}ユミ『すごいわ\nつよさの レベルが ちがうのね$"

Route107_Text_LisaPostBattle:
	.string "{JPN}ユミ『あなたは いっしょに\nうみに あそびに いくような\lおともだち いるのかしら?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "{JPN}ユミ『アタシたちと たたかうなら\nポケモン もっと つれてきなさいな$"

Route107_Text_RayIntro:
	.string "{JPN}シン『いつも きょうだいで\nポケモンしょうぶ してるんだ!\p……いっつも おれが まけるけど\n2たい2なら きみに かてるよ!$"

Route107_Text_RayDefeated:
	.string "{JPN}シン『ひゃー\nつよさの レベルが ちがいすぎるや$"

Route107_Text_RayPostBattle:
	.string "{JPN}シン『おれの ポケモン\nねえちゃんから もらって そだてた\lだいじな あいぼう なんだぜ!$"

Route107_Text_RayNotEnoughPokemon:
	.string "{JPN}シン『オレらと たたかうなら\nもっと ポケモン つれてきてよ!$"

Route107_Text_CamronIntro:
	.string "{JPN}トライアスロンの とちゅう だが\nぜんぜん つかれて いないぜ!$"

Route107_Text_CamronDefeated:
	.string "{JPN}いまので つかれて しまった$"

Route107_Text_CamronPostBattle:
	.string "{JPN}こ このあと まだ\nすいえい ランニングが のこっているぜ\lだいじょうぶか おれ……?$"

Route108_Text_JeromeIntro:
	.string "{JPN}オレの ユメは せかいに ある\n7つのうみ すべてで およぐこと!$"

Route108_Text_JeromeDefeated:
	.string "{JPN}これじゃ\n7つのうみ すべてで およげない……$"

Route108_Text_JeromePostBattle:
	.string "{JPN}うみの ポケモンと あそぶことも\nおよいでいる ときの たのしみだね!$"

Route108_Text_MatthewIntro:
	.string "{JPN}なあ キミ!\nキミも すてられた ふねに いくのかい?$"

Route108_Text_MatthewDefeated:
	.string "{JPN}ああ ぼくが しずむ……\nぶくぶく……$"

Route108_Text_MatthewPostBattle:
	.string "{JPN}すてられぶねの なかに\nはいっていく やつらが いるんだよ!$"

Route108_Text_TaraIntro:
	.string "{JPN}ウソつきな カレに いわれたのよ\nビキニが にあってて カワイイって……$"

Route108_Text_TaraDefeated:
	.string "{JPN}いやん まけたわーっ!$"

Route108_Text_TaraPostBattle:
	.string "{JPN}ウソでも いいから カワイイって いわれたい\nふくざつな おんなごころ……$"

Route108_Text_MissyIntro:
	.string "{JPN}うみって だいすき!\nおよいでいれば イヤなことも わすれるわ!$"

Route108_Text_MissyDefeated:
	.string "{JPN}しょうぶに まけると\nストレスが たまるーっ!$"

Route108_Text_MissyPostBattle:
	.string "{JPN}ストレスは およいで はっさん!\nけんこうてき よねー!$"

Route108_Text_CoryIntro:
	.string "{JPN}みずポケモンが だいすきだー!\nほかの ポケモンも だいすきだー!$"

Route108_Text_CoryDefeated:
	.string "{JPN}わー まけたー!\nわーわー!$"

Route108_Text_CoryPostBattle:
	.string "{JPN}おおごえで さけべば\nスッキリ するなあーっ!$"

Route108_Text_CoryRegister:
	.string "{JPN}つよい トレーナーも だいすきだー!\nポケナビの とうろくを してくれー!$"

Route108_Text_CoryRematchIntro:
	.string "{JPN}かっても まけても\nうみ での しょうぶが だいすきだー!$"

Route108_Text_CoryRematchDefeated:
	.string "{JPN}わーっ また まけた!\nわー わー!$"

Route108_Text_CoryRematchPostBattle:
	.string "{JPN}きみも いきづまった ときは\nなにかを うみに むかって さけべーっ!$"

Route108_Text_CarolinaIntro:
	.string "{JPN}じまんの ポケモンたちで\nスピーディに たたかうわよ!$"

Route108_Text_CarolinaDefeated:
	.string "{JPN}あら かわいくないわね!$"

Route108_Text_CarolinaPostBattle:
	.string "{JPN}せっかくの うみ だし\nピンクの フリフリの ビキニも\lちょっと きてみたい……$"

Route109_Text_DavidIntro:
	.string "{JPN}うりゃーっ!!\nみごとに われた ふっきんを みろーっ!!$"

Route109_Text_DavidDefeated:
	.string "{JPN}うりゃーっ!!\nまけたーっ!!$"

Route109_Text_DavidPostBattle:
	.string "{JPN}うりゃーっ!!\pふっきんと ポケモンの しょうぶは\nかんけい ないぞーっ!!$"

Route109_Text_AliceIntro:
	.string "{JPN}ひやけ たいさく\nあなたは してる?$"

Route109_Text_AliceDefeated:
	.string "{JPN}あちちちちっ!$"

Route109_Text_AlicePostBattle:
	.string "{JPN}ほっぺの あたりが いちばん\nひやけ しやすい ばしょ なのよ!$"

Route109_Text_HueyIntro:
	.string "{JPN}せかいじゅうの みなとを おとずれたが\nカイナは さいこーの みなとまち だぜ!$"

Route109_Text_HueyDefeated:
	.string "{JPN}あんた さいこー だぜ……$"

Route109_Text_HueyPostBattle:
	.string "{JPN}さいこーの みなとまちには\nさいこーの トレーナーが いたぜ……$"

Route109_Text_EdmondIntro:
	.string "{JPN}ううう……\nしょうぶ するの? オレと?$"

Route109_Text_EdmondDefeated:
	.string "{JPN}げろげろ……$"

Route109_Text_EdmondPostBattle:
	.string "{JPN}いつもは もっと つよいんだぞ!\nふなよいで ちょうしが わるいだけだ!\pふなのり だけど……$"

Route109_Text_RickyIntro:
	.string "{JPN}のどが かわいたよ……\nうみのいえで サイコソーダ のみたいな……$"

Route109_Text_RickyDefeated:
	.string "{JPN}うーん……$"

Route109_Text_RickyPostBattle:
	.string "{JPN}おなかも へってきた……\nうきわが おっきな ドーナッツに みえるよ$"

Route109_Text_RickyRegister:
	.string "{JPN}こんど のどが かわいて ないときに\nもういっかい しょうぶ してくれる?$"

Route109_Text_RickyRematchIntro:
	.string "{JPN}おなか へってるけど\nしょうぶ するなら げんき だよ!$"

Route109_Text_RickyRematchDefeated:
	.string "{JPN}まけた……\nおなかが へってるからだ$"

Route109_Text_RickyRematchPostBattle:
	.string "{JPN}すなはまで たべると\nなんでも おいしく おもえるよね$"

Route109_Text_LolaIntro:
	.string "{JPN}ビーチパラソルって\nおおきな おはな みたいよねー!$"

Route109_Text_LolaDefeated:
	.string "{JPN}ママーっ!$"

Route109_Text_LolaPostBattle:
	.string "{JPN}おそらの うえから すなはまを みたら\nおはなばたけ みたいに みえるのよ!$"

Route109_Text_LolaRegister:
	.string "{JPN}わたし だったら\nまいにち ここに きているよ!$"

Route109_Text_LolaRematchIntro:
	.string "{JPN}もう あなたには まけません!\nそのために うきわ してるんだから!$"

Route109_Text_LolaRematchDefeated:
	.string "{JPN}ママーっ!$"

Route109_Text_LolaRematchPostBattle:
	.string "{JPN}うきわ もってると あたしと ポケモンの\nかわいさが ぐぐーんと アップするの!$"

Route109_Text_AustinaIntro:
	.string "{JPN}うきわが ないと およげないけど\nポケモンなら だれにも まけないよ!$"

Route109_Text_AustinaDefeated:
	.string "{JPN}うきわが あるから まけちゃったのかな?$"

Route109_Text_AustinaPostBattle:
	.string "{JPN}あたしの うきわ\nオシャレだから てばなせないの$"

Route109_Text_GwenIntro:
	.string "{JPN}そこの トレーナーさん\nあたしと たたかう でちゅ!$"

Route109_Text_GwenDefeated:
	.string "{JPN}つよいでちゅね……$"

Route109_Text_GwenPostBattle:
	.string "{JPN}どうしたら そんなに\nつよくなれる でちゅか……?$"

Route109_Text_CarterIntro:
	.string "{JPN}わはは!\nおじさん おおもの つっちゃうぞ!$"

Route109_Text_CarterDefeated:
	.string "{JPN}おじさん まけちゃったな……$"

Route109_Text_CarterPostBattle:
	.string "{JPN}たしかに きみは おおもの だな!\nいや きっと おおものに なるぞ!$"

Route109_Text_PaulIntro:
	.string "{JPN}リキ『やあ こまったなあ\pふたりっきりの じかん\nじゃま して ほしくないなあ$"

Route109_Text_PaulDefeated:
	.string "{JPN}リキ『やあ まいったな……$"

Route109_Text_PaulPostBattle:
	.string "{JPN}リキ『やあ ぼくたちが ここに いること\nだれにも いわないで くれよ!\lふたりっきりの せかい なんだからさ!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "{JPN}リキ『ぼくたち ラブラブ だからね\nぼくたちの ポケモンも\l2ひき いっしょに たたかわせるんだ!$"

Route109_Text_MelIntro:
	.string "{JPN}シキ『あたしたちが ラブラブだから\nホウエンは あっついのよお!$"

Route109_Text_MelDefeated:
	.string "{JPN}シキ『あたしの せいで まけたんだわ……\nこんなんじゃ リキに きらわれちゃう!$"

Route109_Text_MelPostBattle:
	.string "{JPN}シキ『ねえ リキ\nあたしのこと おこってない?\lおこっちゃ いやよ$"

Route109_Text_MelNotEnoughPokemon:
	.string "{JPN}シキ『あたしたち ラブラブ だからね\nあたしたちの ポケモンも\l2ひき いっしょに たたかわせるんだ!$"

Route109_Text_ChandlerIntro:
	.string "{JPN}じゃーん!\nボクの うきわ まるいでしょーっ!$"

Route109_Text_ChandlerDefeated:
	.string "{JPN}あーあ! ざんねん$"

Route109_Text_ChandlerPostBattle:
	.string "{JPN}せっかく まるい うきわを\nみせて あげたのにさ$"

Route109_Text_HaileyIntro:
	.string "{JPN}およげない から\nおよぐ ふりを してるの!$"

Route109_Text_HaileyDefeated:
	.string "{JPN}やっぱね!\nかてないって おもってたんだ$"

Route109_Text_HaileyPostBattle:
	.string "{JPN}およげるように なったら\nポケモンも つよく なると おもう!$"

Route109_Text_ElijahIntro:
	.string "{JPN}こうはの おれさまには\nこんな ポケモンが おにあいだぜ!$"

Route109_Text_ElijahDefeated:
	.string "{JPN}まけても カッコ いいだろ?$"

Route109_Text_ElijahPostBattle:
	.string "{JPN}こうはの おれさまには\nみなとまちが おにあいだぜ!\lカイナシティに いってくるか$"

Route110_Text_JacobIntro:
	.string "{JPN}おっと あぶない!\nバイク レースに なれてない ようだな!$"

Route110_Text_JacobDefeated:
	.string "{JPN}キキーッ!\nブレーキが こしょうした!$"

Route110_Text_JacobPostBattle:
	.string "{JPN}タイヤの パンクや\nブレーキの こしょうは ケガのもと\lちゃんと てんけん しないとな$"

Route110_Text_AnthonyIntro:
	.string "{JPN}ヘイ ユー!\nワタシの スピードに ついてこれるかな!?$"

Route110_Text_AnthonyDefeated:
	.string "{JPN}オー マイ ガッ!$"

Route110_Text_AnthonyPostBattle:
	.string "{JPN}スピードだけじゃ ポケモンしょうぶ\nかてませーん! ハンセイしまーす!$"

Route110_Text_BenjaminIntro:
	.string "{JPN}じてんしゃの スピード でても\nあせっちゃ いけないよ!$"

Route110_Text_BenjaminDefeated:
	.string "{JPN}ポケモンしょうぶも\nあせっちゃ いけないな……$"

Route110_Text_BenjaminPostBattle:
	.string "{JPN}あせらず のんびり いこうよ\nじかんは たっぷり あるからね!$"

Route110_Text_BenjaminRegister:
	.string "{JPN}あせらずに また がんばるか!\nよかったらさ れんらく くれよな$"

Route110_Text_BenjaminRematchIntro:
	.string "{JPN}おっ! スピード だしすぎ じゃない?\nちょっと のんびり しょうぶ しようよ!$"

Route110_Text_BenjaminRematchDefeated:
	.string "{JPN}べつに あせってないけど\nなぜだか まけて しまうな……$"

Route110_Text_BenjaminRematchPostBattle:
	.string "{JPN}あせらず のんびり いこうよ\nじかんは たっぷり あるからね!$"

Route110_Text_AbigailIntro:
	.string "{JPN}トライアスロンは ハードな スポーツ\nすいえい じてんしゃ マラソンの\l3しゅもくを こなすのよ!$"

Route110_Text_AbigailDefeated:
	.string "{JPN}ポケモン しょうぶも ハードだわ!$"

Route110_Text_AbigailPostBattle:
	.string "{JPN}つかれたから ひとやすみ\nきゅうけいは たいせつ なのよ$"

Route110_Text_AbigailRegister:
	.string "{JPN}あなた きにいったわ!\nまた サイクリングロードで たたかいましょ$"

Route110_Text_AbigailRematchIntro:
	.string "{JPN}じてんしゃに のりながら\nポケモンしょうぶ ってのも いいものよね!$"

Route110_Text_AbigailRematchDefeated:
	.string "{JPN}うわー\nどうして そんなに つよいの?$"

Route110_Text_AbigailRematchPostBattle:
	.string "{JPN}ひょっとして きろくに\nちょうせん していたのかしら?\pだったら ジャマして ゴメンねー$"

Route110_Text_JasmineIntro:
	.string "{JPN}じてんしゃを こぎつづけて\nふとももが パンパンに なっちゃった$"

Route110_Text_JasmineDefeated:
	.string "{JPN}きんにくつうが しんぱいだわ……$"

Route110_Text_JasminePostBattle:
	.string "{JPN}ジムの バッチを もってるの?\nどうりで つよい はずだわ!$"

Route110_Text_EdwardIntro:
	.string "{JPN}おまえの さくせんは すべて みえた!\nわたしが まけるはず ない!$"

Route110_Text_EdwardDefeated:
	.string "{JPN}じぶんの はいぼくは みえなかった……!$"

Route110_Text_EdwardPostBattle:
	.string "{JPN}おまえの みらいが みえる……\pふうむ……\nあかるい ひかりが みえるぞ……!$"

Route110_Text_JaclynIntro:
	.string "{JPN}おほほほほっ!\nわたくしの ミラクルを みせてあげるわ!$"

Route110_Text_JaclynDefeated:
	.string "{JPN}ミラクルに まけたーっ!$"

Route110_Text_JaclynPostBattle:
	.string "{JPN}わたくしに かったことが ミラクル……\nそう きせき なのよ!\lいつでも かてるなんて おもわないことね!$"

Route110_Text_EdwinIntro:
	.string "{JPN}キミの ポケモン みせてくれない?\nひとめで いいから おねがい!$"

Route110_Text_EdwinDefeated:
	.string "{JPN}コンプリート したかった……!$"

Route110_Text_EdwinPostBattle:
	.string "{JPN}みたことのない ポケモンに であうと\nボクの コレクターだましいが もえるなぁ!$"

Route110_Text_EdwinRegister:
	.string "{JPN}ぼく エントリーコールも\nたくさん あつめたいんだよねぇ$"

Route110_Text_EdwinRematchIntro:
	.string "{JPN}ねえ キミ\nあたらしい ポケモン つかまえた?\pよかったら ポケモン みせてくれない?\nひとめで いいから おねがい!$"

Route110_Text_EdwinRematchDefeated:
	.string "{JPN}キミの ポケモン\nうらやましいな……$"

Route110_Text_EdwinRematchPostBattle:
	.string "{JPN}ああ! とにかく めずらしい ポケモン\nぜんぶ ボクの ものに したいよー!$"

Route110_Text_DaleIntro:
	.string "{JPN}ええーい!\nうしろから はなしかけるなー!$"

Route110_Text_DaleDefeated:
	.string "{JPN}まけたっ!\nくやしいっ!!$"

Route110_Text_DalePostBattle:
	.string "{JPN}すいめんに うかぶ うきを じっと みる……\nしゅうちゅうりょくが たいせつ なんだ$"

Route110_Text_IsabelIntro:
	.string "{JPN}おほほ! だいじな ポケモンを\nじまん するためなら どこにでも いきますわ$"

Route110_Text_IsabelDefeated:
	.string "{JPN}あら まあ イヤですわ$"

Route110_Text_IsabelPostBattle:
	.string "{JPN}しょうぶ させるよりも\nだいすきクラブで じまんして こようかしら$"

Route110_Text_IsabelRegister:
	.string "{JPN}わたしの じまんは こんなんじゃ\nおわりませんわ!\lなんかいも つきあって もらいますわよ$"

Route110_Text_IsabelRematchIntro:
	.string "{JPN}おほほ! だいじな ポケモンなら\nなんどだって じまん しますわ!$"

Route110_Text_IsabelRematchDefeated:
	.string "{JPN}あら まあ イヤですわ$"

Route110_Text_IsabelRematchPostBattle:
	.string "{JPN}ポケモンじまんも やめられないけど\nしょうぶ するのも すきなのよ!$"

Route110_Text_TimmyIntro:
	.string "{JPN}この あたりの くさむらで\nかっこいい ポケモン みつけたんだぜ!$"

Route110_Text_TimmyDefeated:
	.string "{JPN}かっこいい だけじゃ だめかぁ……$"

Route110_Text_TimmyPostBattle:
	.string "{JPN}つかまえた ばかりの ポケモンじゃ\nうまく たたかえないや!$"

Route110_Text_AlyssaIntro:
	.string "{JPN}サイクリングロード から おちちゃった!\nはずかしい…… しょうぶで まぎらわすわ!$"

Route110_Text_AlyssaDefeated:
	.string "{JPN}ひぇ まけて しまったわ!$"

Route110_Text_AlyssaPostBattle:
	.string "{JPN}おっこちるは まけるはで\nはずかし すぎます! わたし!$"

Route110_Text_JosephIntro:
	.string "{JPN}よぉぉし とばして いくぜえェ!\nノリの わるいやつは おいてくぜェ!$"

Route110_Text_JosephDefeated:
	.string "{JPN}ノリが いいね あんた……$"

Route110_Text_JosephPostBattle:
	.string "{JPN}こんなこと では へこたれないぜェ!\nおれは まけて またひとつ\lいいオトコに なったぜェ!$"

Route110_Text_KalebIntro:
	.string "{JPN}かわいい ポケモンたちが\nたすけあう ところは かわいいぞーーっ!$"

Route110_Text_KalebDefeated:
	.string "{JPN}きみは ちも なみだも ないんだな$"

Route110_Text_KalebPostBattle:
	.string "{JPN}おう よしよし\nよくやったよ かわいい おまえたち$"

Route111_Text_DrewIntro:
	.string "{JPN}おっ! ゴーゴーゴーグル にあってるね!\nでも ぼくの ほうが にあってるだろ?\lどっちが にあうか しょうぶだよ!$"

Route111_Text_DrewDefeat:
	.string "{JPN}ゴーゴーゴーグルで まわりが\nよく わからなかったよ$"

Route111_Text_DrewPostBattle:
	.string "{JPN}ゴーゴーゴーグルが あると\nさばくの すなあらしも へいき だから\lそれだけで うれしくなるよ!$"

Route111_Text_HeidiIntro:
	.string "{JPN}さばくの なかでも ピクニック!\pどんな ところでも トレーナー いるから\nしょうぶも できるもんね!$"

Route111_Text_HeidiDefeat:
	.string "{JPN}いやーん いじわるー!$"

Route111_Text_HeidiPostBattle:
	.string "{JPN}すなあらしの なかで たたかうなら\nポケモンの たいりょくに きを つけないと\lすぐに きぜつ しちゃうわよ!$"

Route111_Text_BeauIntro:
	.string "{JPN}ゴーゴーゴーグルを つけてると\nなんとなく ヒーローきぶん!\lいまの ぼくなら だれにだって かてるさ!$"

Route111_Text_BeauDefeat:
	.string "{JPN}きぶん だけじゃ かてないか……$"

Route111_Text_BeauPostBattle:
	.string "{JPN}いつかは ほんものの ヒーローに なる!\nそのために もっと がんばって\lポケモンと じぶんを きたえてみせるよ$"

Route111_Text_BeckyIntro:
	.string "{JPN}さばくで カセキが みつかるって きいたけど\nどこに あるのかなあ?$"

Route111_Text_BeckyDefeat:
	.string "{JPN}いまいち だわ……$"

Route111_Text_BeckyPostBattle:
	.string "{JPN}さばくで カセキが みつかると いうことは\nむかし ここは うみ だったのね!$"

Route111_Text_DustyIntro:
	.string "{JPN}いせきを さがして 30ねん!\nそんな わたしと たたかうのかね?$"

Route111_Text_DustyDefeat:
	.string "{JPN}いせきを さがしてるけど\nつよい ポケモンは さがしてないんだ$"

Route111_Text_DustyPostBattle:
	.string "{JPN}いせきを さがして 30ねん!\pいや もう 40ねん さがしているか?\nあれ どうだったかな?$"

Route111_Text_DustyRegister:
	.string "{JPN}つよい ポケモンは さがしてないけど\nなぜだか ポケナビは おきにいり なんだ!$"

Route111_Text_DustyRematchIntro:
	.string "{JPN}いせきを さがして 30ねん!\pいや いせきを さがして 40ねん!\nそんな わたしと たたかうのかね?$"

Route111_Text_DustyRematchDefeat:
	.string "{JPN}いせきは みつからない\nつよい ポケモンも みつからない$"

Route111_Text_DustyPostRematch:
	.string "{JPN}いせきを さがして 30ねん!\pいや もう 40ねん さがしているか?\pうーん 50ねん だった きもする……\nあれ どうだったかな?$"

Route111_Text_TravisIntro:
	.string "{JPN}ぼくも げんき いっぱい!\nポケモンも げんき いっぱい だよ!$"

Route111_Text_TravisDefeat:
	.string "{JPN}ポケモンの げんき なくなったよ$"

Route111_Text_TravisPostBattle:
	.string "{JPN}げんき いっぱいに はしりまわる\nトレーナーが いると\lつい そっちを みちゃうよね!$"

Route111_Text_IreneIntro:
	.string "{JPN}どこに いくのか しらないけど\nちょっと しょうぶ してみない?$"

Route111_Text_IreneDefeat:
	.string "{JPN}にくらしいほど つよいのね!$"

Route111_Text_IrenePostBattle:
	.string "{JPN}えんとつやまに いこうかな? って\nおもって いるんだけど\lこのあたりの けしきも いいのよね!$"

Route111_Text_DaisukeIntro:
	.string "{JPN}おのれを きたえるため\nであう にんげん すべてに\lしょうぶを もうしこんでるッス!$"

Route111_Text_DaisukeDefeat:
	.string "{JPN}まいったッス……!$"

Route111_Text_DaisukePostBattle:
	.string "{JPN}おぬしの ように\nつよい トレーナーに かてるまで\lしゅぎょう あるのみッス!$"

Route111_Text_WiltonIntro:
	.string "{JPN}きみが ポケモンを どこまで\nきたえているか みせて もらおう!$"

Route111_Text_WiltonDefeat:
	.string "{JPN}なるほど\nかなり きたえてるね!$"

Route111_Text_WiltonPostBattle:
	.string "{JPN}ポケモンも トレーナーも\nたたかうことで いろんなことを まなぶ!\pだいじ なのは\nまけても あきらめないことさ!$"

Route111_Text_WiltonRegister:
	.string "{JPN}きみの きたえかた さんこうに なるな!\nきが むいたら さいど たたかってほしい$"

Route111_Text_WiltonRematchIntro:
	.string "{JPN}ぼくたちは さらなる たかみを めざして\nここで ポケモンを きたえている\lきみも いっしょに しゅぎょう しよう!$"

Route111_Text_WiltonRematchDefeat:
	.string "{JPN}なかなか やるな!$"

Route111_Text_WiltonPostRematch:
	.string "{JPN}そんなに つよいなら\nポケモンリーグを めざすと いいよ!$"

Route111_Text_BrookeIntro:
	.string "{JPN}あら あなたの ポケモン\nかなり つよそうだわ!\lぜひ おてあわせ してくれない?$"

Route111_Text_BrookeDefeat:
	.string "{JPN}つよそう じゃなくて\nつよいのね!$"

Route111_Text_BrookePostBattle:
	.string "{JPN}あたしも がんばって\nポケモン そだてた つもりだけど\lまだ やること いっぱい あるわね!$"

Route111_Text_BrookeRegister:
	.string "{JPN}あなた みたいな つよいひとと\nおともだちに なりたいわ!$"

Route111_Text_BrookeRematchIntro:
	.string "{JPN}ポケモンは つかう わざによって\nつよくなったり よわくなったりも するわ!\pあなたの ポケモン\nどんな わざを おぼえているの?$"

Route111_Text_BrookeRematchDefeat:
	.string "{JPN}いい わざを おぼえているのね!$"

Route111_Text_BrookePostRematch:
	.string "{JPN}あたしの ポケモン しんか させずに\nさきに わざを おぼえさせてから\lそだてた ほうが よかったかな?$"

Route111_Text_CeliaIntro:
	.string "{JPN}こんな ところで\nピクニックを するんじゃ なかった!$"

Route111_Text_CeliaDefeat:
	.string "{JPN}もー\nほんとに くるんじゃ なかった!$"

Route111_Text_CeliaPostBattle:
	.string "{JPN}この すなあらし じゃ\nゴーゴーゴーグルを つけて いても\lおべんとうが ひろげられないんだもん……$"

Route111_Text_BryanIntro:
	.string "{JPN}きみの つよさは どのくらいか?\nその ナゾを ときあかそう!$"

Route111_Text_BryanDefeat:
	.string "{JPN}おお そのつよさ\nナゾに みちておる!$"

Route111_Text_BryanPostBattle:
	.string "{JPN}この さばくには\nナゾが おおい ですぞーっ!$"

Route111_Text_BrandenIntro:
	.string "{JPN}ぼくに まけて くれたら\nサンドイッチ わけて あげるよ!$"

Route111_Text_BrandenDefeat:
	.string "{JPN}ちぇっ!\nサンドイッチに つられると おもったのに$"

Route111_Text_BrandenPostBattle:
	.string "{JPN}ぼくの サンドも\nサンドイッチ だいすき なんだ$"

Route111_Text_TyronIntro:
	.string "{JPN}ぼくは こんな ポケモンが すきなんだ!$"

Route111_Text_TyronDefeat:
	.string "{JPN}ちょっと! ぼくの ポケモン\nちゃんと みてくれてた!?$"

Route111_Text_TyronPostBattle:
	.string "{JPN}しょうぶを する ときって\nじぶんの ポケモンを みせびらかす\lたのしみが ゼッタイ あるよねー$"

Route111_Text_CelinaIntro:
	.string "{JPN}うふん……\nわたくしを ドキドキ させてね!$"

Route111_Text_CelinaDefeat:
	.string "{JPN}す ……ごい\nなんて つよいの$"

Route111_Text_CelinaPostBattle:
	.string "{JPN}ま まだ ドキドキ しているわ\nあなたって…… ステキな トレーナーね$"

Route111_Text_HaydenIntro:
	.string "{JPN}おいらは いま はらが へっている\nだから ようしゃは しないぞ!$"

Route111_Text_HaydenDefeat:
	.string "{JPN}ぐうぅ……$"

Route111_Text_HaydenPostBattle:
	.string "{JPN}はらが なった!\nきのみでも やいて たべようかナ?$"

Route111_Text_BiancaIntro:
	.string "{JPN}あなたは キンセツの ほうから きたの?\nじゃ たいりょくも バッチリね!$"

Route111_Text_BiancaDefeat:
	.string "{JPN}あらら すごいんだー$"

Route111_Text_BiancaPostBattle:
	.string "{JPN}この さきの みちのりは\nけっこう ながいわよ!$"

Route112_Text_BriceIntro:
	.string "{JPN}わっはっはっ!\nどうだ?\lオレと しょうぶ しないか?\lわっはっはっ!$"

Route112_Text_BriceDefeat:
	.string "{JPN}まけた……\nわっはっはっ!$"

Route112_Text_BricePostBattle:
	.string "{JPN}いろあざやかな キノコを たべたら……\nわ わらいが とまらない!\lわっはっはっ!$"

Route112_Text_TrentIntro:
	.string "{JPN}やまのぼりで きたえた オレの あしこし\nちょっとや そっとじゃ くじけないぜ!$"

Route112_Text_TrentDefeat:
	.string "{JPN}あ……\nあしが つった……$"

Route112_Text_TrentPostBattle:
	.string "{JPN}なんじゅっキロも ある にもつを せおって\nやまみちを あるき つづけるんだ\lからだが じょうぶに なるぞ!$"

Route112_Text_TrentRegister:
	.string "{JPN}つった あしが いたい……\nちょっと オレの リュックから\lほうたいを だしてくれ\pって ちがうよ それは ポケナビだろ!\nもういいよ とうろく するから$"

Route112_Text_TrentRematchIntro:
	.string "{JPN}やまのぼりで きたえてるからな\nかなり パワフルだぞ!$"

Route112_Text_TrentRematchDefeat:
	.string "{JPN}パワーで まけたか?$"

Route112_Text_TrentRematchPostBattle:
	.string "{JPN}えんとつやまの うえには\nすごい トレーナーが いるらしいぞ!\lこんど しょうぶに いくつもりだ!$"

Route112_Text_LarryIntro:
	.string "{JPN}ぼくは つよいんだ……\nまけても ないたり しないぞ……!$"

Route112_Text_LarryDefeat:
	.string "{JPN}うわーーーん!$"

Route112_Text_LarryPostBattle:
	.string "{JPN}おかあさんに あえなくて\nさみしいから ないてるんじゃ ないよ!\lぐすん……$"

Route112_Text_CarolIntro:
	.string "{JPN}ピクニックと いえば うた!\nさあ いっしょに うたいましょ!$"

Route112_Text_CarolDefeat:
	.string "{JPN}こんなに つよいなんて……!$"

Route112_Text_CarolPostBattle:
	.string "{JPN}うたも ポケモンしょうぶも\nうまい へた なんて かんけい ないよ!\lたのしんだ ほうが かち なのよ!$"

Route112_Text_BryantIntro:
	.string "{JPN}ほのおの ぬけみちで つかまえた\nホカホカの ポケモン みせてやろー!$"

Route112_Text_BryantDefeat:
	.string "{JPN}おお ボコボコだ$"

Route112_Text_BryantPostBattle:
	.string "{JPN}ナカナカ すてきな\nたたかいかたじゃ ないか きみぃ!$"

Route112_Text_ShaylaIntro:
	.string "{JPN}アラ! すてきな トレーナーさん\nロマンチックな しょうぶを おねがいね!\lマアマア つよいわよ わたし!$"

Route112_Text_ShaylaDefeat:
	.string "{JPN}なんて つよいのかしら\nおねえさん おどろいちゃった!$"

Route112_Text_ShaylaPostBattle:
	.string "{JPN}ねえ いま いそがしいの?\nえっと もし よかったら\lさっそく 2かいせん と おもって……\lん? いそがしいなら いいわ$"

Route113_Text_JaylenIntro:
	.string "{JPN}この あたりが わりと すずしいの\nなんでか しってるかい?$"

Route113_Text_JaylenDefeat:
	.string "{JPN}ぴゅーっ!\nまけたーっ!$"

Route113_Text_JaylenPostBattle:
	.string "{JPN}かざんばいが たいようの ひかりを\nさえぎってるから ひえるんだね!\lあつがりの オレには たすかるよ!$"

Route113_Text_DillonIntro:
	.string "{JPN}やまの ふんかは\nちきゅうが いきている しょうこ!$"

Route113_Text_DillonDefeat:
	.string "{JPN}つよいな おまえーっ!$"

Route113_Text_DillonPostBattle:
	.string "{JPN}ごほ がへっ!\nはいが はいに はいった……\pうけなかった……\nさむい…… ブルブル……$"

Route113_Text_MadelineIntro:
	.string "{JPN}あたしの ドンメルちゃんに\nかざんばいが かからないように\lパラソルを さしているの$"

Route113_Text_MadelineDefeat:
	.string "{JPN}はあ はあ……\nつかれましたわ……$"

Route113_Text_MadelinePostBattle:
	.string "{JPN}とても おつよいのね\nおねえさん かんしん しちゃったわ$"

Route113_Text_MadelineRegister:
	.string "{JPN}ね ちょっと パラソルに はいって\nポケナビを とうろく していって!$"

Route113_Text_MadelineRematchIntro:
	.string "{JPN}おひさしぶりね\nよろしかったら しょうぶ しません?$"

Route113_Text_MadelineRematchDefeat:
	.string "{JPN}おみごと ですわ$"

Route113_Text_MadelinePostRematch:
	.string "{JPN}あいかわらず おつよいのね\nおねえさん かんしん しちゃったわ$"

Route113_Text_LaoIntro:
	.string "{JPN}はいの なかから ドロロンッ!!\nしょうぶで ござる!$"

Route113_Text_LaoDefeat:
	.string "{JPN}まいったで ござる$"

Route113_Text_LaoPostBattle:
	.string "{JPN}もっと かくれかたを けんきゅう しよう\nそれでは しつれいするで ござる$"

Route113_Text_LaoRegister:
	.string "{JPN}やあ! にんぽう\nポケナビ とうろくのじゅつで ござる!$"

Route113_Text_LaoRematchIntro:
	.string "{JPN}はいの なかから ドロロロンッ!!\nしょうぶで ござる!$"

Route113_Text_LaoRematchDefeat:
	.string "{JPN}まいったで ござる$"

Route113_Text_LaoPostRematch:
	.string "{JPN}かくれかたは よかったが\nしょうぶが いまいち だった……\pそれでは しつれいするで ござる$"

Route113_Text_LungIntro:
	.string "{JPN}みつけてくれて ありがとう!\nでも しょうぶは べつだよ!$"

Route113_Text_LungDefeat:
	.string "{JPN}にんぽう かざんばい がくれ!\p…… って もう おわり?$"

Route113_Text_LungPostBattle:
	.string "{JPN}かくれていて なにが しんぱいって\nだれも とおらないと さびしいんだよね$"

Route113_Text_ToriIntro:
	.string "{JPN}ナナ『ふたりで かざんばい あつめてるよ\nでも ポケモンしょうぶも するんだよ!$"

Route113_Text_ToriDefeat:
	.string "{JPN}ナナ『まけちゃった\nつまんないから かざんばい あつめよ!$"

Route113_Text_ToriPostBattle:
	.string "{JPN}ナナ『かざんばい どれくらい たまったかな?\nしろいビードロ つくれると いいのにね!$"

Route113_Text_ToriNotEnoughMons:
	.string "{JPN}ナナ『あたしたち 2たい2で たたかいたいの\nそうしないと まけちゃうもん!$"

Route113_Text_TiaIntro:
	.string "{JPN}ネネ『ふたりで かざんばい あつめてるよ\nでも ポケモンしょうぶも するんだよ!$"

Route113_Text_TiaDefeat:
	.string "{JPN}ネネ『かてなかった\nつまんないから かざんばい あつめよ!$"

Route113_Text_TiaPostBattle:
	.string "{JPN}ネネ『かざんばい けっこう たまったよ!\nもう しろいビードロ つくれるよ きっと!$"

Route113_Text_TiaNotEnoughMons:
	.string "{JPN}ネネ『あたしたち 2たい2で たたかいたいの\nそうしないと かてないもん!$"

Route113_Text_CobyIntro:
	.string "{JPN}おまえ なんか この つばさで\nふきとばして やるぜっ!$"

Route113_Text_CobyDefeat:
	.string "{JPN}え あれ?$"

Route113_Text_CobyPostBattle:
	.string "{JPN}そんなに あっさり かたれると\nなにを いって いいか わからない……$"

Route113_Text_SophieIntro:
	.string "{JPN}あったかくて ねむく なっちゃう\nねむけ ざましに あいてを してよ!$"

Route113_Text_SophieDefeat:
	.string "{JPN}きっと これは ユメなのよ……$"

Route113_Text_SophiePostBattle:
	.string "{JPN}まけて くやしい から\nもう ここで フテね しちゃうわ!\lぐーぐー$"

Route113_Text_LawrenceIntro:
	.string "{JPN}もしかして かざんばい あつめの\nとちゅう だった?$"

Route113_Text_LawrenceDefeat:
	.string "{JPN}えへへ まけちゃったね$"

Route113_Text_LawrencePostBattle:
	.string "{JPN}ぼくも はいに もぐっちゃおう かしら$"

Route113_Text_WyattIntro:
	.string "{JPN}ぼ ボクと たたかうって いうんですか!\nまだ つかまえた ばかりなのに!$"

Route113_Text_WyattDefeat:
	.string "{JPN}か かって うれしい ですか!\nこんな ボクに かって うれしいですか!$"

Route113_Text_WyattPostBattle:
	.string "{JPN}はいしゃに こえを かけて くれるって\nいうんですか!\lか カッコいい ですね! ふん!$"

Route114_Text_LennyIntro:
	.string "{JPN}やっほーっ!\p……\pこだまの かわりに\nやっほー! って いってくれよ!$"

Route114_Text_LennyDefeat:
	.string "{JPN}やっほーっ!$"

Route114_Text_LennyPostBattle:
	.string "{JPN}こどものころ こだま って\nむこうの やまにいる モノマネさんが\lやっほー! って いってると おもってた$"

Route114_Text_LucasIntro:
	.string "{JPN}じゅんびを おこたる もの\nやまに のぼるべからず!$"

Route114_Text_LucasDefeat:
	.string "{JPN}やまは こわい ところだ……$"

Route114_Text_LucasPostBattle:
	.string "{JPN}ふゆの やまは なだれや ふぶきで\nそうなんする きけんが おおいぞ!$"

Route114_Text_ShaneIntro:
	.string "{JPN}キャンプの たのしみと いえば\nつりに はなびに きもだめし!\pだけど いちばんは\nポケモンしょうぶ だね!$"

Route114_Text_ShaneDefeat:
	.string "{JPN}つよすぎるーっ!$"

Route114_Text_ShanePostBattle:
	.string "{JPN}ぼくね ポケモンと いっしょに\nキャンプ できるだけで しあわせ だよ$"

Route114_Text_NancyIntro:
	.string "{JPN}しょくごの うんどう!\nわたしと しょうぶ しましょうよ!$"

Route114_Text_NancyDefeat:
	.string "{JPN}まけちゃったー!$"

Route114_Text_NancyPostBattle:
	.string "{JPN}おいしい ごはんも たべたし\nなんだか ねむくなって きたわ……$"

Route114_Text_SteveIntro:
	.string "{JPN}うふふふふふ……\nボクの ポケモンと しょうぶしない?$"

Route114_Text_SteveDefeat:
	.string "{JPN}ボ ボクの ポケモン……$"

Route114_Text_StevePostBattle:
	.string "{JPN}からだが おおきくて ゴツゴツ かたくて\nおおきな ツノと するどい キバ……\lうふふふふ……\lそんな ポケモンが ほしいなぁ……$"

Route114_Text_SteveRegister:
	.string "{JPN}お おぼえてろっ! ……いや\nわすれられない ように こうしてやる!$"

Route114_Text_SteveRematchIntro:
	.string "{JPN}うふふふふふ……\nボクの ポケモンと しょうぶ しようよ$"

Route114_Text_SteveRematchDefeat:
	.string "{JPN}ああ ポケモン みることが できて\nしあわせ だ……$"

Route114_Text_StevePostRematch:
	.string "{JPN}うふふふふふ……\pポケモンの たたかっている すがたに\nぞくぞく するんだ ボク$"

Route114_Text_BernieIntro:
	.string "{JPN}キャンプファイヤー するとき\nはなびを するとき\lみずを ようい しておけよ!$"

Route114_Text_BernieDefeat:
	.string "{JPN}しょうか かつどう\nありがとう! ってか$"

Route114_Text_BerniePostBattle:
	.string "{JPN}ほんと ひのようじん だけは おこたるな!\nひを あまく みるんじゃないぜ!$"

Route114_Text_BernieRegister:
	.string "{JPN}もえあがった きもちの まま\nポケナビに とうろく しあおう!$"

Route114_Text_BernieRematchIntro:
	.string "{JPN}キャンプファイヤー するとき\nはなびを するとき\lみずを ようい するように なったか!?$"

Route114_Text_BernieRematchDefeat:
	.string "{JPN}もえあがる まえに\nけされた! ってか$"

Route114_Text_BerniePostRematch:
	.string "{JPN}ほんと ひのようじん だけは おこたるな!\nひを あまく みるんじゃないぜ!$"

Route114_Text_ClaudeIntro:
	.string "{JPN}つりで しょうぶ すると\nきみには かちめが ないだろう\lポケモンで かかってきなさい!$"

Route114_Text_ClaudeDefeat:
	.string "{JPN}つりの しょうぶなら かってた……$"

Route114_Text_ClaudePostBattle:
	.string "{JPN}りゅうせいのたきで\nおおものでも つると しようかな\lあそこの たきには なにか いそうだからね$"

Route114_Text_NolanIntro:
	.string "{JPN}つりも すき だが\nしょうぶも すき!\pしょうぶを いどまれたら\nつりの さいちゅうでも ことわらないよ!$"

Route114_Text_NolanDefeat:
	.string "{JPN}しょうぶは すき だが\nつよい わけじゃ ないんだ……$"

Route114_Text_NolanPostBattle:
	.string "{JPN}こんどこそ!\pと おもっちゃうから\nつりも しょうぶも やめられない$"

Route114_Text_TyraIntro:
	.string "{JPN}カヨ『そうね\nなんとなく そんな きぶん だから\lあなたにも ポケモン おしえたげよっか$"

Route114_Text_TyraDefeat:
	.string "{JPN}カヨ『すごい たたかいかた!$"

Route114_Text_TyraPostBattle:
	.string "{JPN}カヨ『コウハイの イヨに あたしが\nポケモンを おしえて あげたの!$"

Route114_Text_TyraNotEnoughMons:
	.string "{JPN}カヨ『うふふ!\nあたしたちと しょうぶ するなら\lポケモン いっぴきじゃ ダメなのよ!$"

Route114_Text_IvyIntro:
	.string "{JPN}イヨ『あなた\nだれに ポケモン おそわったの?$"

Route114_Text_IvyDefeat:
	.string "{JPN}イヨ『すごい たたかいかた!$"

Route114_Text_IvyPostBattle:
	.string "{JPN}イヨ『あたしが\nポケモン はじめた きっかけは\lセンパイが おしえてくれた からなの!$"

Route114_Text_IvyNotEnoughMons:
	.string "{JPN}イヨ『ポケモン いっぴき だけなの?\nなんだか さみしい かんじ しちゃうね$"

Route114_Text_KaiIntro:
	.string "{JPN}でっかいの つれたっ でっかいの!$"

Route114_Text_KaiDefeat:
	.string "{JPN}あれー\nおおきさで まけたんかな$"

Route114_Text_KaiPostBattle:
	.string "{JPN}よっしゃー!\nもっと おおきいの つるもんね!$"

Route114_Text_CharlotteIntro:
	.string "{JPN}あたし!\nかわいい だけじゃ ないんだから!$"

Route114_Text_CharlotteDefeat:
	.string "{JPN}かわいく なーいっ!$"

Route114_Text_CharlottePostBattle:
	.string "{JPN}かわいい だけの ポケモンなんて いや!\nかわいくて ひとクセ あるコが すき!$"

Route114_Text_AngelinaIntro:
	.string "{JPN}あなたの ポケモンって\nどの くらい しんか させてる?$"

Route114_Text_AngelinaDefeat:
	.string "{JPN}ふーん\nなるほどね$"

Route114_Text_AngelinaPostBattle:
	.string "{JPN}しんか させると\nみためが ものすごく かわって\lビックリする ポケモンが いるよね!$"

Route115_Text_TimothyIntro:
	.string "{JPN}ふむ……\nなかなか できそうだな……\lわたしが あいてを してあげよう!$"

Route115_Text_TimothyDefeat:
	.string "{JPN}そうぞう いじょうの つよさだ……!$"

Route115_Text_TimothyPostBattle:
	.string "{JPN}てんさい など いない\nすべては どりょく!\lわたしは そう しんじている……$"

Route115_Text_TimothyRegister:
	.string "{JPN}ふむ……\nこんな まけかたも ひさかたぶりだ\lできれば また あいてを してほしい$"

Route115_Text_TimothyRematchIntro:
	.string "{JPN}ふむ……\nあいかわらずの みのこなし\lわたしの あいてを してもらおう!$"

Route115_Text_TimothyRematchDefeat:
	.string "{JPN}あいかわらずの つよさだ……!$"

Route115_Text_TimothyPostRematch:
	.string "{JPN}どりょく あるのみ!\pまけたのは まだまだ\nどりょくが たりないからだ!$"

Route115_Text_KoichiIntro:
	.string "{JPN}おれのッ!\pワンリキーがッ!\pたたかいを のぞんでいるッ!$"

Route115_Text_KoichiDefeat:
	.string "{JPN}いててててっ!$"

Route115_Text_KoichiPostBattle:
	.string "{JPN}おれの ワンリキー たちがッ!\pつよさを のぞむかぎり\pおれたちは どこまでも つよくなるぜッ!$"

Route115_Text_NobIntro:
	.string "{JPN}オレの とくいわざは\nずつきで レンガを くだく ことだ!$"

Route115_Text_NobDefeat:
	.string "{JPN}うがーっ!\nあたまが くだけたーっ!$"

Route115_Text_NobPostBattle:
	.string "{JPN}ポケモンに カラテを おしえてるんだが\nオレより つよく なりそうで\lちょっと たのしみ なんだ!$"

Route115_Text_NobRegister:
	.string "{JPN}きみは すげえな!\nきたえなおして もういちど しょうぶだ!$"

Route115_Text_NobRematchIntro:
	.string "{JPN}きみに まけてから がんばって\nポケモンと おのれを きたえなおしたぞ!\lさあ もういちど しょうぶ!$"

Route115_Text_NobRematchDefeat:
	.string "{JPN}うがーっ!\nまた まけたーっ!$"

Route115_Text_NobPostRematch:
	.string "{JPN}おれの ポケモンは まだまだ つよくなる!\nがんばって きたえるぞ!$"

Route115_Text_CyndyIntro:
	.string "{JPN}この すなはまは わたしの\nヒミツの しゅぎょう ばしょ!\lかってに はいって こないでよ!$"

Route115_Text_CyndyDefeat:
	.string "{JPN}しゅぎょうが たりないわ……!$"

Route115_Text_CyndyPostBattle:
	.string "{JPN}すなが クッションに なるから\nからだを いためないの\lさいこうの しゅぎょう ばしょね!$"

Route115_Text_CyndyRegister:
	.string "{JPN}いいわ あなたが ここに はいるの\nみとめてあげる!\lそのかわり また あいてを たのむわよ!$"

Route115_Text_CyndyRematchIntro:
	.string "{JPN}さあ ポケモンしょうぶ いくわよ!$"

Route115_Text_CyndyRematchDefeat:
	.string "{JPN}わたしは たたかえるけど\nポケモンが……$"

Route115_Text_CyndyPostRematch:
	.string "{JPN}まけても ちょっと たのしいのは\nほんとうに ポケモンが すき だからかな?$"

Route115_Text_HectorIntro:
	.string "{JPN}ぼく めずらしい ポケモン もってるんだ!\nよかったら みせて あげようか$"

Route115_Text_HectorDefeat:
	.string "{JPN}きみ……\nぼくの ポケモン ほしいでしょ?$"

Route115_Text_HectorPostBattle:
	.string "{JPN}こんなに めずらしい ポケモン もってるんだ\nそれだけで ぼくは まんぞく なのさ!$"

Route115_Text_KyraIntro:
	.string "{JPN}はしりながら しょうぶを するわよッ!\nあなたも ついて きなさーい!$"

Route115_Text_KyraDefeat:
	.string "{JPN}はぁ はぁ……$"

Route115_Text_KyraPostBattle:
	.string "{JPN}はしりながら たたかおうと したのが\nまちがい だったわよ!\lひとっぱしり して アタマ ひやすかな$"

Route115_Text_JaidenIntro:
	.string "{JPN}くらえーっ\nにんぽう すごポケモンの じゅつ!$"

Route115_Text_JaidenDefeat:
	.string "{JPN}わーん しっぱいだ!$"

Route115_Text_JaidenPostBattle:
	.string "{JPN}でも ぼくの ポケモン\nすごポケモン だった でしょ?$"

Route115_Text_HeleneIntro:
	.string "{JPN}ふふっ あたしの ポケモンたちは\nくろおび クラスの つよさよ!$"

Route115_Text_HeleneDefeat:
	.string "{JPN}くやしすぎるわ!$"

Route115_Text_HelenePostBattle:
	.string "{JPN}あたしより つよい ひとなんて\nめったに あわないのに……\pわかった!\nあなた ジムリーダー でしょ!$"

Route115_Text_AlixIntro:
	.string "{JPN}めが あったからには にがさないわよ!$"

Route115_Text_AlixDefeat:
	.string "{JPN}くっ…… なかなか!$"

Route115_Text_AlixPostBattle:
	.string "{JPN}あーあ!\nテレポートで おうちに かえろうかしら$"

Route115_Text_MarleneIntro:
	.string "{JPN}めいそうの じゃまを したわね……\nおしおき させて もらうわ!$"

Route115_Text_MarleneDefeat:
	.string "{JPN}こころが みだれて しまう!$"

Route115_Text_MarlenePostBattle:
	.string "{JPN}ここで ポケモンたちと\nめいそうを していたの!\lでも あまり おちつかない ところね$"

Route116_Text_ClarkIntro:
	.string "{JPN}トンネルが つうじて いないなら\nやまを こえて いけば いいのだ!$"

Route116_Text_ClarkDefeat:
	.string "{JPN}ぜえ…… ぜえ……\nまけて つかれて しまった$"

Route116_Text_ClarkPostBattle:
	.string "{JPN}トンネルなど なくても かまわん\nやまおとこは やまが みち なのだ!$"

Route116_Text_JoeyIntro:
	.string "{JPN}おれの ポケモン つえーぞ!\nちょっと みてみろよ!$"

Route116_Text_JoeyDefeat:
	.string "{JPN}あいたたたたっ! キズが できた!\nバンソーコー はらなきゃ!$"

Route116_Text_JoeyPostBattle:
	.string "{JPN}バンソーコーは おとこの くんしょう!\nまた ひとつ ふえたぜ!$"

Route116_Text_JoseIntro:
	.string "{JPN}ぼくの むしポケモンは つよいよ!\nしょうぶ しようよ!$"

Route116_Text_JoseDefeat:
	.string "{JPN}まけた……!\nかてると おもったのに……!$"

Route116_Text_JosePostBattle:
	.string "{JPN}むしポケモンは しんかが はやいから\nつよく なるのも はやい!$"

Route116_Text_JaniceIntro:
	.string "{JPN}わたしの かわいい ポケモンの つよさ\nじっくりと おしえて あげるわ!$"

Route116_Text_JaniceDefeat:
	.string "{JPN}キミの ほうが いちまい うわてね……$"

Route116_Text_JanicePostBattle:
	.string "{JPN}かわいさと つよさを かねそなえた ポケモン\nそれが わたしの りそうなの!$"

Route116_Text_JerryIntro:
	.string "{JPN}トレーナーズ スクールで\nいろいろ べんきょう したからね\lじっせんで たしかめるよ!$"

Route116_Text_JerryDefeat:
	.string "{JPN}べんきょう さぼってたから\nまけちゃったよ$"

Route116_Text_JerryPostBattle:
	.string "{JPN}トレーナーズ スクールで\nもういちど べんきょう しなおさなきゃ\lツツジさんに おこられちゃうよ$"

Route116_Text_JerryRegister1:
	.string "{JPN}ポケナビには トレーナーが\nとうろく できるん だって\lトレーナーズ スクールで ならったんだ!\pよく わからないから やってみてよ!$"

Route116_Text_JerryRegister2:
	.string "{JPN}ポケナビには トレーナーが\nとうろく できるん だって\lトレーナーズ スクールで ならったんだ!\pよく わからないから やってみてよ!$"

Route116_Text_JerryRematchIntro:
	.string "{JPN}あれから トレーナーズ スクールで\nまじめに べんきょう したからね\lこのまえ みたいに まけたりしないよ!$"

Route116_Text_JerryRematchDefeat:
	.string "{JPN}あれー?\nきちんと べんきょう したのに$"

Route116_Text_JerryPostRematch:
	.string "{JPN}トレーナーズ スクールで\nもういちど べんきょう しなおさなきゃ\lツツジさんに おこられちゃうよ$"

Route116_Text_KarenIntro:
	.string "{JPN}スクールでも べんきょう\nかえりみち でも べんきょうよ!$"

Route116_Text_KarenDefeat:
	.string "{JPN}ショック\nまけちゃったよ$"

Route116_Text_KarenPostBattle:
	.string "{JPN}ああん! これじゃ ツツジさまのように\nエレガントな トレーナーに なれないわ!$"

Route116_Text_KarenRegister1:
	.string "{JPN}あーっ それ ポケナビね!\nあたしも もってるから とうろくして!$"

Route116_Text_KarenRegister2:
	.string "{JPN}あーっ それ ポケナビね!\nあたしも もってるから とうろくして!$"

Route116_Text_KarenRematchIntro:
	.string "{JPN}あれから ものすっごく べんきょう したの!\nその せいか みてもらうからね!$"

Route116_Text_KarenRematchDefeat:
	.string "{JPN}ショック\nまた まけちゃったよ$"

Route116_Text_KarenPostRematch:
	.string "{JPN}ツツジさまに かったことが あるの?\nそれじゃ いまの あたしには かてないわ$"

Route116_Text_SarahIntro:
	.string "{JPN}わたくし いままで\nひとに なにかで まけた ことって\lありませんの!$"

Route116_Text_SarahDefeat:
	.string "{JPN}まあ\nこんなの はじめてですわ!$"

Route116_Text_SarahPostBattle:
	.string "{JPN}なにふじゆう ない くらし ですけど\nポケモンの ことだけは\lおもいどおりに なりません のね$"

Route116_Text_DawsonIntro:
	.string "{JPN}ぼくの ポケモンの\nうつくしい けなみに みとれて\lキミは なにも できない!$"

Route116_Text_DawsonDefeat:
	.string "{JPN}そりゃないぜ ベイビー$"

Route116_Text_DawsonPostBattle:
	.string "{JPN}ああっ\nポケモンの けなみと\lぼくの ヘアーが みだれた!\lびよういん よやく しなきゃ$"

Route116_Text_DevanIntro:
	.string "{JPN}ガツンと いってみようかあ!$"

Route116_Text_DevanDefeat:
	.string "{JPN}あああ\nしょうぶに ならんな こりゃ$"

Route116_Text_DevanPostBattle:
	.string "{JPN}たまには ほかの タイプの\nポケモンも つかって みるかなあ?$"

Route116_Text_JohnsonIntro:
	.string "{JPN}この さきって いきどまりなんだ\nつまんない から しょうぶ してね$"

Route116_Text_JohnsonDefeat:
	.string "{JPN}まけた けど おもしろかったよ!$"

Route116_Text_JohnsonPostBattle:
	.string "{JPN}まけちゃった から\nぼくの たんパン かしてあげても いーよ!$"

Route117_Text_IsaacIntro:
	.string "{JPN}オレが そだてている ポケモンと\nしょうぶ してくれないか?$"

Route117_Text_IsaacDefeat:
	.string "{JPN}みごとに そだててるね……$"

Route117_Text_IsaacPostBattle:
	.string "{JPN}つよさ だけが ポケモンじゃないよ!\nポケモンの こせいを みがきあげるのも\lたのしみかたの ひとつ だね!$"

Route117_Text_IsaacRegister:
	.string "{JPN}よーし ますます がんばって そだてるぞ!\nきみ そしたら みにきて くれるだろ?$"

Route117_Text_IsaacRematchIntro:
	.string "{JPN}オレが そだてている ポケモン\nあいかわらず いい かんじ だよ!$"

Route117_Text_IsaacRematchDefeat:
	.string "{JPN}いい そだてかた してるね……\nきみには そだてやの さいのう あるかも$"

Route117_Text_IsaacPostRematch:
	.string "{JPN}いい ぐあいに そだってるね!\nミナモシティの ポケモンコンテストに\lでることを おすすめ するよ!$"

Route117_Text_LydiaIntro:
	.string "{JPN}ポケモンを ちゃんと そだててるか\nわたしが たしかめて あげますね$"

Route117_Text_LydiaDefeat:
	.string "{JPN}ちゃんと そだってますね$"

Route117_Text_LydiaPostBattle:
	.string "{JPN}ポケモンの こせいにも きをくばって\nそだてて みて くださいね$"

Route117_Text_LydiaRegister:
	.string "{JPN}よい トレーナーさんに あえて よかった!\nこれからも よろしく おねがいしますね$"

Route117_Text_LydiaRematchIntro:
	.string "{JPN}ポケモンを ちゃんと そだててるか\nまた わたしが たしかめて あげますね$"

Route117_Text_LydiaRematchDefeat:
	.string "{JPN}みごとに そだってますね$"

Route117_Text_LydiaPostRematch:
	.string "{JPN}ポケモンの せいかくに よって\nすきな ポロックが あるみたいなの$"

Route117_Text_DylanIntro:
	.string "{JPN}トライアスロンの まっさいちゅう だけど\nさくっと しょうぶ しようじゃ ないか!$"

Route117_Text_DylanDefeat:
	.string "{JPN}たいりょく なくなった!$"

Route117_Text_DylanPostBattle:
	.string "{JPN}まいったな……\pいまの しょうぶの あいだに\nビリに なっちゃったかも……?$"

Route117_Text_DylanRegister:
	.string "{JPN}ポケモンも つよく なくちゃ ダメか?\nきみさ たまに ぼくを きたえてよ!$"

Route117_Text_DylanRematchIntro:
	.string "{JPN}トライアスロンの まっさいちゅう だけど\nぼくには よゆうが あるからね\lさくっと しょうぶ しようじゃ ないか!$"

Route117_Text_DylanRematchDefeat:
	.string "{JPN}また たいりょく なくなった!$"

Route117_Text_DylanPostRematch:
	.string "{JPN}およぎと じてんしゃでは トップだったけど\nポケモンは いまいち じしんが ないよ$"

Route117_Text_MariaIntro:
	.string "{JPN}トライアスロンの れんしゅう\nポケモンと いっしょに してるからさ\lスピードに じしん あるよ!$"

Route117_Text_MariaDefeat:
	.string "{JPN}れんしゅうが たりなかったかな?$"

Route117_Text_MariaPostBattle:
	.string "{JPN}れんしゅうは つづけてこそ\nいみが あるのよね\pよーし! また れんしゅうよ\nあしたから!$"

Route117_Text_MariaRegister:
	.string "{JPN}あなたは れんしゅう してる?\nよかったら わたしが あいてになるわ!$"

Route117_Text_MariaRematchIntro:
	.string "{JPN}どう れんしゅう つづけてる?\nあたしは もちろん つづけてるわ\lその しょうこ みせちゃうから!$"

Route117_Text_MariaRematchDefeat:
	.string "{JPN}れんしゅうが たりなかったかな?$"

Route117_Text_MariaPostRematch:
	.string "{JPN}あしたから また れんしゅう するから\nよかったら また しょうぶ してね!$"

Route117_Text_DerekIntro:
	.string "{JPN}むかしは むしとりしょうねん!\nいまは こんちゅうマニア!\pでも ポケモンを あいする きもちは\nずっと かわらないぜ!$"

Route117_Text_DerekDefeat:
	.string "{JPN}ポケモンの よわさも かわらない……$"

Route117_Text_DerekPostBattle:
	.string "{JPN}すきな ことばかり していたら\nいつのまにか マニアって よばれてるよ!\pまあ むしポケモンに くわしいからね\nマニアと よばれて とうぜん なのさっ!$"

Route117_Text_AnnaIntro:
	.string "{JPN}ミホ『かわいい コウハイの まえ だもん\nいいところ みせちゃうんだから!$"

Route117_Text_AnnaDefeat:
	.string "{JPN}ミホ『もう!\nコウハイの まえ だから かたせてよ!$"

Route117_Text_AnnaPostBattle:
	.string "{JPN}ミホ『あなたの ポケモン\nなかなかの コンビネーション してる!\pそうね あたしたちの\nつぎ ぐらいに すごいんじゃない?$"

Route117_Text_AnnaAndMegRegister:
	.string "{JPN}ミホ『まけっぱなしでは\nひきさがれない わたしたち!\lまた きて くれるわよね?$"

Route117_Text_AnnaNotEnoughMons:
	.string "{JPN}ミホ『あたしたちと しょうぶ したいなら\nポケモンを 2ひきは もってきてね!$"

Route117_Text_MegIntro:
	.string "{JPN}リコ『すてきな センパイとの タッグで\nあなたを まかしちゃうから!$"

Route117_Text_MegDefeat:
	.string "{JPN}リコ『やーん\nセンパイ ごめんなさい!$"

Route117_Text_MegPostBattle:
	.string "{JPN}リコ『あたしが センパイの\nあしを ひっぱっちゃったの……\pそうでなきゃ あんた かってないわよ!$"

Route117_Text_MegNotEnoughMons:
	.string "{JPN}リコ『ポケモン 1ぴき しか いないの?\nじゃあ しょうぶは できないわね\pあたしたち 2たい2の\nしょうぶを たのしみたいの!$"

Route117_Text_AnnaRematchIntro:
	.string "{JPN}ミホ『コウハイの まえで\nなんども まけてられないのよね$"

Route117_Text_AnnaRematchDefeat:
	.string "{JPN}ミホ『ちょうしが でなかったのよ$"

Route117_Text_AnnaPostRematch:
	.string "{JPN}ミホ『あなたの ポケモン\nなかなかの コンビネーションしてる!\pそうね あたしたちの\nつぎ ぐらいに すごいんじゃない?$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "{JPN}ミホ『あたしたちと しょうぶ したいなら\nポケモンを 2ひきは もってきてね!$"

Route117_Text_MegRematchIntro:
	.string "{JPN}リコ『センパイとの タッグで\nこんどこそ あなたを まかしちゃうから!$"

Route117_Text_MegRematchDefeat:
	.string "{JPN}リコ『つよすぎるわ$"

Route117_Text_MegPostRematch:
	.string "{JPN}リコ『センパイと いっしょに たたかったのに\nまけるだなんて…… おちこんじゃう!$"

Route117_Text_MegRematchNotEnoughMons:
	.string "{JPN}リコ『ポケモン 1ぴき しか いないの?\nじゃあ しょうぶは できないわね\pあたしたち 2たい2の\nしょうぶを たのしみたいの!$"

Route117_Text_MelinaIntro:
	.string "{JPN}すてきな おはなを みながら\nしょうぶする なんて すてきよね!$"

Route117_Text_MelinaDefeat:
	.string "{JPN}へーえ いいカンジね あんた!$"

Route117_Text_MelinaPostBattle:
	.string "{JPN}おはなを みながら はしると\nきもちいいわよ!$"

Route117_Text_BrandiIntro:
	.string "{JPN}エスパーポケモンに\nひめられた ちからを おみせするわ!$"

Route117_Text_BrandiDefeat:
	.string "{JPN}おどろいたわ$"

Route117_Text_BrandiPostBattle:
	.string "{JPN}エスパーポケモンは おくが ふかいの\nあなたも つかまえて ごらんなさい$"

Route117_Text_AishaIntro:
	.string "{JPN}かつこと だけを かんがえて たたかうわ!$"

Route117_Text_AishaDefeat:
	.string "{JPN}まけても くやしがったり しない!\nそんなひまが あったら とっくんよ$"

Route117_Text_AishaPostBattle:
	.string "{JPN}まけるかな?と しんぱい すると\nよけいに まけちゃうと おもうのよね$"

Route118_Text_RoseIntro:
	.string "{JPN}はなの かおりは ふしぎな ちから\nからだも こころも きれいに なるわ$"

Route118_Text_RoseDefeat:
	.string "{JPN}あらら\nまけちゃったわね$"

Route118_Text_RosePostBattle:
	.string "{JPN}はなも ポケモンも\nいい かおりの ものが だいすき!\lクサイにおいは…… かんべんね$"

Route118_Text_RoseRegister:
	.string "{JPN}あら その においは ポケナビね\nぜひとも とうろく しあいましょう!$"

Route118_Text_RoseRematchIntro:
	.string "{JPN}いい かおりに さそわれて\nいらしたのかしら?$"

Route118_Text_RoseRematchDefeat:
	.string "{JPN}においの こうか……\nあんまり きかなかったわね$"

Route118_Text_RosePostRematch:
	.string "{JPN}あまいかおりを うまく つかうと\nポケモンが さそわれて やってくるわね$"

Route118_Text_PerryIntro:
	.string "{JPN}かれいに おおぞらを まう\nとりポケモンが さいこう だぜ!$"

Route118_Text_PerryDefeat:
	.string "{JPN}うう…… まけた……$"

Route118_Text_PerryPostBattle:
	.string "{JPN}きみも いい ポケモンを もってるね!\nぼくも まけずに そだてよっと!$"

Route118_Text_ChesterIntro:
	.string "{JPN}はばたけ!\nおいらの とりポケモン!$"

Route118_Text_ChesterDefeat:
	.string "{JPN}はばたいたけど……$"

Route118_Text_ChesterPostBattle:
	.string "{JPN}もっと つよくなると\nじゆうに とべるように なるのにな!$"

Route118_Text_BarnyIntro:
	.string "{JPN}あたしゃ つりびとだが トレーナーでもある\nつった ポケモン ちゃんと そだててるよ!$"

Route118_Text_BarnyDefeat:
	.string "{JPN}そだてたはず なんだが……?$"

Route118_Text_BarnyPostBattle:
	.string "{JPN}つりを しながら\nポケモン そだてても かてなかった……\lどっちも はんぱ だったのか!?$"

Route118_Text_WadeIntro:
	.string "{JPN}つりびとに だいじ なのは どうぐ!\nトレーナーに だいじ なのは\lもちろん ポケモンと ハートだな!$"

Route118_Text_WadeDefeat:
	.string "{JPN}ハートの しょうぶで まけたのか?$"

Route118_Text_WadePostBattle:
	.string "{JPN}つり というのも\nひとと ポケモンとの\lしんけん しょうぶ だな!$"

Route118_Text_DaltonIntro:
	.string "{JPN}ぼくの メロディ\nあなたの こころに とどけるよ$"

Route118_Text_DaltonDefeat:
	.string "{JPN}ルー ルルルー$"

Route118_Text_DaltonPostBattle:
	.string "{JPN}エレキギターって\nただ うるさい だけじゃ ないんだ……\pこうして こころに しみる\nメロディも かなでられるのさ……$"

Route118_Text_DaltonRegister:
	.string "{JPN}もっと いい メロディが できたら\nききにおいでよ!$"

Route118_Text_DaltonRematchIntro:
	.string "{JPN}ぼくと ポケモンの メロディ\nあなたの こころに とどけるよ$"

Route118_Text_DaltonRematchDefeat:
	.string "{JPN}ルー ルルルー$"

Route118_Text_DaltonPostRematch:
	.string "{JPN}ひいてるときの ぼくの きもちが\nエレキギターを とおして\lあなたに とどく はずなのさ……$"

Route118_Text_DeandreIntro:
	.string "{JPN}いけいけー!\nボクの ポケモン 1ごう 2ごう 3ごう!$"

Route118_Text_DeandreDefeat:
	.string "{JPN}ああ だいじょうぶか!?\nボクの ポケモン 1ごう 2ごう 3ごう!$"

Route118_Text_DeandrePostBattle:
	.string "{JPN}ボクの ポケモン せんたい\nカッコいい だろー!\lまね しても いーぜー!$"

Route119_Text_BrentIntro:
	.string "{JPN}ボクらは モノマネサークル!\nキミの うごきを マネするよ!$"

Route119_Text_BrentDefeat:
	.string "{JPN}うわあ まけたーっ!$"

Route119_Text_BrentPostBattle:
	.string "{JPN}マネを して なにが たのしいか……\pふふふ……\nキミには わからない だろうよ$"

Route119_Text_DonaldIntro:
	.string "{JPN}ようやく であえたね!\nぼくの むしポケモンが あいて するよ!$"

Route119_Text_DonaldDefeat:
	.string "{JPN}であわなければ よかった……$"

Route119_Text_DonaldPostBattle:
	.string "{JPN}もっと キミの マネを したい!\nほら はやく うごいてよ!$"

Route119_Text_TaylorIntro:
	.string "{JPN}きみが まえに すすんだら\nぼくらも すすむ\pきみが みぎへ まがれば\nぼくらも まがる……$"

Route119_Text_TaylorDefeat:
	.string "{JPN}キミが かっても\nぼくは まける……$"

Route119_Text_TaylorPostBattle:
	.string "{JPN}うーん しょうぶの しょうはい だけは\nマネ できないよなあ……\lなんか くやしい……$"

Route119_Text_DougIntro:
	.string "{JPN}やっと ボクを つかまえられたね!\nそれとも にげようと していたのかな?$"

Route119_Text_DougDefeat:
	.string "{JPN}すばらしい たたかい だったな!$"

Route119_Text_DougPostBattle:
	.string "{JPN}ボクらは モノマネサークル!\nたのしんで もらえたかな?$"

Route119_Text_GregIntro:
	.string "{JPN}ボクが だれなのか わからないだろう?\p……まあ ボクも キミのこと しらないから\nこうして たたかうんだけどね!$"

Route119_Text_GregDefeat:
	.string "{JPN}けっこう つよい じゃんか!$"

Route119_Text_GregPostBattle:
	.string "{JPN}キミが どこかに いくまで\nボクらは マネを つづけるよ!$"

Route119_Text_KentIntro:
	.string "{JPN}モノマネ だいすきな ひとが\nあつまって つくった モノマネサークル!\pであった そのとき\nしょうぶが はじまる!$"

Route119_Text_KentDefeat:
	.string "{JPN}まいりましたーっ!$"

Route119_Text_KentPostBattle:
	.string "{JPN}キミも モノマネサークルに はいらない?$"

Route119_Text_JacksonIntro:
	.string "{JPN}サバイバルに ひつような\nちしきと ぎじゅつを もつ もの!\lそれが ポケモンレンジャーさ!$"

Route119_Text_JacksonDefeat:
	.string "{JPN}ポケモンの ちしきは たらなかった……$"

Route119_Text_JacksonPostBattle:
	.string "{JPN}ぶんめい から はなれて\nにんげんの やせいを めざめさせる!\lそれが オレたちの テーマさ!$"

Route119_Text_JacksonRegister:
	.string "{JPN}ちしきぶそくと わらわずに\nこんど また あいてを してやってくれよな$"

Route119_Text_JacksonRematchIntro:
	.string "{JPN}ポケモンと いることで\nやせいを とりもどすのさ!$"

Route119_Text_JacksonRematchDefeat:
	.string "{JPN}あいかわらず つよいな!$"

Route119_Text_JacksonPostRematch:
	.string "{JPN}とにかく ポケモンを しんじろ!\nじぶんを しんじろ!\lそうすれば みちは ひらける!$"

Route119_Text_CatherineIntro:
	.string "{JPN}あら あなた……\nぼうけんを している わりには\lずいぶん みがるな かっこうね!$"

Route119_Text_CatherineDefeat:
	.string "{JPN}じゅんび ぶそくは じこの もと……$"

Route119_Text_CatherinePostBattle:
	.string "{JPN}ずいぶん みがるな かっこう だけど\nひつような どうぐは もってるし\lきりょく たいりょく じゅうぶんね!$"

Route119_Text_CatherineRegister:
	.string "{JPN}トレーナーの ひつじゅひん ポケナビは\nちゃんと もってる?\pあっ もってるわね! とうろくしましょ$"

Route119_Text_CatherineRematchIntro:
	.string "{JPN}ポケモンと いっしょの ぼうけんは\nうまく いってるかしら?$"

Route119_Text_CatherineRematchDefeat:
	.string "{JPN}まだ なにかが\nたりなかったわね……$"

Route119_Text_CatherinePostRematch:
	.string "{JPN}トレーナーの あなたが\nポケモンを たよって いるように\lポケモンも あなたを たよっているのよ!$"

Route119_Text_HughIntro:
	.string "{JPN}おおぞらは おとこの ロマン!\pじゆうに そらを とぶ きもちよさは\nなにごとにも かえがたい!$"

Route119_Text_HughDefeat:
	.string "{JPN}まけたーっ!$"

Route119_Text_HughPostBattle:
	.string "{JPN}そらを とびまわる ユメは\nとりポケモンの おかげで かなえられたよ!$"

Route119_Text_PhilIntro:
	.string "{JPN}ぼくの とりポケモンの じつりょくを\nみせて あげるよ!$"

Route119_Text_PhilDefeat:
	.string "{JPN}じつりょく ぶそく だった……$"

Route119_Text_PhilPostBattle:
	.string "{JPN}ぼくは ちいさい ころから\nとりポケモンに あこがれて いたんだ!$"

Route119_Text_YasuIntro:
	.string "{JPN}かげに ひそみ やみに いきる\nそれが オレの さだめ……!\lいざ ポケモンしょうぶ!$"

Route119_Text_YasuDefeat:
	.string "{JPN}まいった……!$"

Route119_Text_YasuPostBattle:
	.string "{JPN}しょうぶに やぶれた ものは\nいさぎよく かげに もどる……\lそれも さだめ……$"

Route119_Text_TakashiIntro:
	.string "{JPN}ゆだん してると\nいたい めに あうぜ!$"

Route119_Text_TakashiDefeat:
	.string "{JPN}つよいな きみーっ!$"

Route119_Text_TakashiPostBattle:
	.string "{JPN}きしゅう さくせんは シッパイだった……$"

Route119_Text_HideoIntro:
	.string "{JPN}きを かくすなら もりのなか!$"

Route119_Text_HideoDefeat:
	.string "{JPN}つわもので ござるな$"

Route119_Text_HideoPostBattle:
	.string "{JPN}きを かくすなら もりのなか!\nポケモンを かくすなら ポケモンのなか!\pとくに いみは ないでござる$"

Route119_Text_ChrisIntro:
	.string "{JPN}わたしに はなしかけた……\nつまり しょうぶを いどむ つもりだな!\pよーし! なみのり しながら\nつりあげた ポケモンで たたかうぞ!$"

Route119_Text_ChrisDefeat:
	.string "{JPN}かつための ポイントが\nちっとも わからん!$"

Route119_Text_ChrisPostBattle:
	.string "{JPN}なみのりを つかう!\pポケモンの せなかに のって\nつりを たのしむ!\pなんて ゆうがな ひととき だろう!$"

Route119_Text_FabianIntro:
	.string "{JPN}デケデケデケデケ\nかつぜーヘ おれたちーヒ かつぜーヘ$"

Route119_Text_FabianDefeat:
	.string "{JPN}まけたぜーヘ あっさりーヒ まけたぜーヘ$"

Route119_Text_FabianPostBattle:
	.string "{JPN}デケデケデケデケ\nにどとーホ おれにーヒ かまうなよーホ$"

Route119_Text_DaytonIntro:
	.string "{JPN}ホッホッホー!\nこども トレーナーは だいすきだぞ!\lおじちゃんと たたかおうっ!$"

Route119_Text_DaytonDefeat:
	.string "{JPN}やるなー ホッホッホ!$"

Route119_Text_DaytonPostBattle:
	.string "{JPN}ホッホッホー!\nこども トレーナーの げんきを\lみならって おじちゃん がんばるぞ!$"

Route119_Text_RachelIntro:
	.string "{JPN}いつでも どこでも\nパラソルを てばなさないの!$"

Route119_Text_RachelDefeat:
	.string "{JPN}いやん そんなあ$"

Route119_Text_RachelPostBattle:
	.string "{JPN}パラソルが おもく ないかって?\nキミの バッグの ほうが\lいっぱい はいってるじゃない$"

Route120_Text_ColinIntro:
	.string "{JPN}そらを とんでいる ポケモンに\nダメージを あたえる ワザを もってる?$"

Route120_Text_ColinDefeat:
	.string "{JPN}キミの ほうが\nいちまい うわて だった!$"

Route120_Text_ColinPostBattle:
	.string "{JPN}そらをとぶ って ワザは べんりだな!\pそらを とんでいる あいだは\nほとんどの ワザが あたらないだろ?$"

Route120_Text_RobertIntro:
	.string "{JPN}ボクの ポケモンは つよいぜ!\nキミの ポケモンは どうかな?$"

Route120_Text_RobertDefeat:
	.string "{JPN}キミの ポケモンの ほうが\nつよかった……!$"

Route120_Text_RobertPostBattle:
	.string "{JPN}どんどん つよくなる ポケモンは\nほんと たよりに なるよなー!$"

Route120_Text_RobertRegister:
	.string "{JPN}キミって きたい できそうだなー!\nポケナビに とうろく しておきたい!$"

Route120_Text_RobertRematchIntro:
	.string "{JPN}どんどん つよくなる ポケモンは\nほんと たよりに なるよなー!$"

Route120_Text_RobertRematchDefeat:
	.string "{JPN}キミの ポケモン\nほんとうに つよいんだな……$"

Route120_Text_RobertPostRematch:
	.string "{JPN}ポケモンが つよくなるのと いっしょに\nおれも つよくならないとなー!$"

Route120_Text_LorenzoIntro:
	.string "{JPN}きみの ポケモン\nそうなん しないか みてあげよう!$"

Route120_Text_LorenzoDefeat:
	.string "{JPN}そんなに つよい ポケモンと いっしょなら\nそうなんの おそれは ないな!$"

Route120_Text_LorenzoPostBattle:
	.string "{JPN}ポケモンと いっしょに どこまでもいく\nトレーナーの よろこびと いえるだろう!$"

Route120_Text_JennaIntro:
	.string "{JPN}あなたの たいりょく どう?\nたいりょく ぶそくだと\lいざと いうとき こまるわよ!$"

Route120_Text_JennaDefeat:
	.string "{JPN}たいりょく だけは あったのに……$"

Route120_Text_JennaPostBattle:
	.string "{JPN}たいりょく づくりが わたしの にっか\nまいにち ポケモンと ランニングよ!$"

Route120_Text_JeffreyIntro:
	.string "{JPN}…… …… ……\n…… …… ……\lしょうぶ する……?$"

Route120_Text_JeffreyDefeat:
	.string "{JPN}…… …… ……\nまけた……$"

Route120_Text_JeffreyPostBattle:
	.string "{JPN}…… …… ……\n…… …… ……\lがんばろう……$"

Route120_Text_JeffreyRegister:
	.string "{JPN}…… …… ……\n…… …… ……\lポケナビ もってる……?$"

Route120_Text_JeffreyRematchIntro:
	.string "{JPN}…… …… ……\n…… …… ……\lまた しょうぶ する……?$"

Route120_Text_JeffreyRematchDefeat:
	.string "{JPN}…… …… ……\nまた まけた……$"

Route120_Text_JeffreyPostRematch:
	.string "{JPN}…… …… ……\n…… …… ……\lまた がんばろう……\lだいじな むしポケモンの ために……$"

Route120_Text_JenniferIntro:
	.string "{JPN}ポケモンには いろんな とくせいが ある\nそれを かんがえてこそ\lいちりゅうの トレーナーに なれるのよ!$"

Route120_Text_JenniferDefeat:
	.string "{JPN}なかなか かんがえてるのね$"

Route120_Text_JenniferPostBattle:
	.string "{JPN}そう ポケモンの とくせいに よって\nたたかいかたも いろいろ かわってくるわ!$"

Route120_Text_ChipIntro:
	.string "{JPN}なんだね きみは?\pもしかして ひょっとすると\nあるかもしれない といわれる\lこだいの いせきを さがしに きたのかね!?$"

Route120_Text_ChipDefeat:
	.string "{JPN}まいったね こりゃ$"

Route120_Text_ChipPostBattle:
	.string "{JPN}あの おおきな いわ\nわたしは いせき だと おもいたいが\lそれにしては いりぐちが ないね……$"

Route120_Text_ClarissaIntro:
	.string "{JPN}あたしが パラソルを もってる りゆう?\pうふふ あたしに かてたら\nおしえて あげても いいかな?$"

Route120_Text_ClarissaDefeat:
	.string "{JPN}パラソルで ポケモンの こうげきは\nしのげないのね……$"

Route120_Text_ClarissaPostBattle:
	.string "{JPN}あたしの ポケモンたちも\nあつい ひざしは にがてだと おもうの\lだから こうして パラソルを もってるのよ$"

Route120_Text_AngelicaIntro:
	.string "{JPN}あたしと ポケモンと パラソル\nどれか ひとつ かけていても\lうつくしさが そこなわれるんだわ$"

Route120_Text_AngelicaDefeat:
	.string "{JPN}うつくしさが\nだいなしに なっちゃったわ$"

Route120_Text_AngelicaPostBattle:
	.string "{JPN}あなたに パラソルは にあわないわ!\pだって こんなの もっていたら\nすっごく ジャマに なりそう なんだもの$"

Route120_Text_KeigoIntro:
	.string "{JPN}ポケモンの うごきを とりいれて\nあたらしい にんぽうを あみだすんだ!$"

Route120_Text_KeigoDefeat:
	.string "{JPN}あたらしい にんぽう\nかんせいまで まだまだ かかりそうだ$"

Route120_Text_KeigoPostBattle:
	.string "{JPN}ニンジャの せんせいを さがして\nでしいり しようかな?$"

Route120_Text_RileyIntro:
	.string "{JPN}ぼくたち ニンジャごっこの かくれぬの!\nどこに いるのか わからなかっただろ!$"

Route120_Text_RileyDefeat:
	.string "{JPN}まけた!\nかくれぬので かくれるか?$"

Route120_Text_RileyPostBattle:
	.string "{JPN}ぼくたち ニンジャごっこの かくれぬの!\nこれって てづくり なんだぜ!$"

Route120_Text_CallieIntro:
	.string "{JPN}よそみ してると ケガするよ!$"

Route120_Text_CallieDefeat:
	.string "{JPN}いたいめに あったのは あたしのほうか$"

Route120_Text_CalliePostBattle:
	.string "{JPN}やっぱり しんか させようかな?\nこのままでも かわいい けど$"

Route120_Text_LeonelIntro:
	.string "{JPN}きみの てもち ポケモン\nいろんな タイプが そろって いるか?$"

Route120_Text_LeonelDefeat:
	.string "{JPN}きみの こだわり みせてもらったよ!$"

Route120_Text_LeonelPostBattle:
	.string "{JPN}すきな ポケモン だけで\nつよいって いうのが さいこうだね$"

Route121_Text_VanessaIntro:
	.string "{JPN}あたしの とっても プリティな\nポケモンを かわいがってよ!$"

Route121_Text_VanessaDefeat:
	.string "{JPN}かわいがるの いみが ちがうわ!$"

Route121_Text_VanessaPostBattle:
	.string "{JPN}ミナモの コンテストに いくのよ\nあたしの ポケモンなら\lマスター ランクでも らくしょうよ!$"

Route121_Text_WalterIntro:
	.string "{JPN}せかい かっこくを\nポケモンと いっしょに まわってきた\pすこしは うでに じしんが ありますよ!$"

Route121_Text_WalterDefeat:
	.string "{JPN}おみごと ですな$"

Route121_Text_WalterPostBattle:
	.string "{JPN}また ポケモンと いっしょに\nせかいを まわってみたい ものです$"

Route121_Text_WalterRegister:
	.string "{JPN}あなたの うでまえは たいしたものだ\nぜひ きねんに とうろくを……$"

Route121_Text_WalterRematchIntro:
	.string "{JPN}せかい かっこくを\nポケモンと いっしょに まわってきた\pすこしは うでに じしんが ありますよ!$"

Route121_Text_WalterRematchDefeat:
	.string "{JPN}おみごと ですな!$"

Route121_Text_WalterPostRematch:
	.string "{JPN}あなたと その ポケモンなら\nがいこくでも つよいと いわれるでしょう!$"

Route121_Text_TammyIntro:
	.string "{JPN}よの なかには ふしぎな ちからが\nいっぱい あるの……$"

Route121_Text_TammyDefeat:
	.string "{JPN}あたし まけたのね……$"

Route121_Text_TammyPostBattle:
	.string "{JPN}おくりびやま……\nあそこに ふしぎな ちからが あるの……$"

Route121_Text_KateIntro:
	.string "{JPN}マナ『ふたり そろえば こわいもの なし!\nあたしたちの つよさ みせつけちゃうから!$"

Route121_Text_KateDefeat:
	.string "{JPN}マナ『コウハイの まえで かっこわるいわ……$"

Route121_Text_KatePostBattle:
	.string "{JPN}マナ『あたしって たよられちゃうと\nつい かっこいい ところ\lみせたく なっちゃうのよね……$"

Route121_Text_KateNotEnoughMons:
	.string "{JPN}マナ『ポケモン 1ぴき しか いないのね\nじゃあ しょうぶは できないわ!\pだって よわいもの いじめに なるもの$"

Route121_Text_JoyIntro:
	.string "{JPN}ユイ『ふたり そろえば こわいもの なし!\nあたしたちの つよさ みせつけちゃうから!$"

Route121_Text_JoyDefeat:
	.string "{JPN}ユイ『センパイ ごめんなさーい$"

Route121_Text_JoyPostBattle:
	.string "{JPN}ユイ『えへっ!\nまた センパイと いっしょに とっくんね!$"

Route121_Text_JoyNotEnoughMons:
	.string "{JPN}ユイ『あたしたちに しょうぶを いどむなら\nポケモン 2ひきは ひつよう だからね!$"

Route121_Text_JessicaIntro:
	.string "{JPN}あたくしの だいじな ポケモン\nちょっと みなさいよ!$"

Route121_Text_JessicaDefeat:
	.string "{JPN}ぷんぷん!\nなによ ほんき だしちゃって!$"

Route121_Text_JessicaPostBattle:
	.string "{JPN}サファリで あたらしい ポケモン\nつかまえようかな?$"

Route121_Text_JessicaRegister:
	.string "{JPN}きょうは てかげん してあげたのよ\nつぎは こうは いかないからね!$"

Route121_Text_JessicaRematchIntro:
	.string "{JPN}だいじな ポケモン そだったのよ!\nちょっと みていきなさいよ!$"

Route121_Text_JessicaRematchDefeat:
	.string "{JPN}ぷんぷん!\nまた てかげん してくれないのね!$"

Route121_Text_JessicaPostRematch:
	.string "{JPN}サファリで あたらしい ポケモン\nつかまえようかな?$"

Route121_Text_CristinIntro:
	.string "{JPN}1にちに 5にんずつ\nたおす ことが にっかよ!\lあなたが その 5にんめ!$"

Route121_Text_CristinDefeat:
	.string "{JPN}いやっ ひどいわ!$"

Route121_Text_CristinPostBattle:
	.string "{JPN}こんなに あっさり まけるなんて……\nつぎは わたしが かつから!$"

Route121_Text_CristinRegister:
	.string "{JPN}くつじょく てき だわ!\nあなたの こと わすれないんだから……\lポケナビを かしなさい!$"

Route121_Text_CristinRematchIntro:
	.string "{JPN}1にちに 10にんずつ\nたおす ことが にっかよ!\lあなたが その 10にんめ!$"

Route121_Text_CristinRematchDefeat:
	.string "{JPN}ちょっ……\nひどい やりなおしてよ!$"

Route121_Text_CristinPostRematch:
	.string "{JPN}こんなに かてない あいてが いるなんて……\nグスっ しんじられない$"

Route121_Text_CaleIntro:
	.string "{JPN}いま にもつが いっぱい なんですけど!\nこんな じょうたいで たたかえと?$"

Route121_Text_CaleDefeat:
	.string "{JPN}そりゃ まけますよ\nりょうてが ふさがってるんだもん$"

Route121_Text_CalePostBattle:
	.string "{JPN}この さきの ミナモデパートで\nかいもの しすぎたんだ!\lきみの みたいな バッグが ほしいな$"

Route121_Text_MylesIntro:
	.string "{JPN}みんなの そだてた ポケモンが\nみてみたーーい!$"

Route121_Text_MylesDefeat:
	.string "{JPN}すごーーい!$"

Route121_Text_MylesPostBattle:
	.string "{JPN}いいなーー! きみの ポケモン!\nどうやって そだてているの?$"

Route121_Text_PatIntro:
	.string "{JPN}わたしの そだてた ポケモンたち\nみんなに みてほしいの!$"

Route121_Text_PatDefeat:
	.string "{JPN}すごいなァ!$"

Route121_Text_PatPostBattle:
	.string "{JPN}どんな ポケモンでも おなじように\nかわいがって そだてているの!$"

Route121_Text_MarcelIntro:
	.string "{JPN}わたしの ポケモンは まけしらず!\nこんど かったら つぎは コンテストだ!$"

Route121_Text_MarcelDefeat:
	.string "{JPN}あっと どうしたことだ?$"

Route121_Text_MarcelPostBattle:
	.string "{JPN}コンテストの まえに\nもうすこし きたえないと ダメかな$"

Route123_Text_WendyIntro:
	.string "{JPN}あなたの じつりょくが\nどれほどの ものか……\lわたしが たしかめて あげる!$"

Route123_Text_WendyDefeat:
	.string "{JPN}すばらしいわ……!$"

Route123_Text_WendyPostBattle:
	.string "{JPN}わたしに かつなんて……\nあなたの じつりょくも そうとうな もの!$"

Route123_Text_BraxtonIntro:
	.string "{JPN}たくさん ジムの バッジを\nもっている みたいだね!\pほんとうに それだけの ちからが あるか\nたしかめさせて もらうよ!$"

Route123_Text_BraxtonDefeat:
	.string "{JPN}たしかに ちからは ある!$"

Route123_Text_BraxtonPostBattle:
	.string "{JPN}ジムバッジに はじない\nたたかい だったよ!$"

Route123_Text_VioletIntro:
	.string "{JPN}たのしい ことが あるとき って\nいい においで いっぱいに なってるのね$"

Route123_Text_VioletDefeat:
	.string "{JPN}あぁ\nかなしみの におい だわ……$"

Route123_Text_VioletPostBattle:
	.string "{JPN}きのみ めいじんの はなばたけ\nすっごく いいかんじの においで いっぱい!$"

Route123_Text_CameronIntro:
	.string "{JPN}サイキックとは きもちの つよさ……\pそう ぼくは だれにも まけないと\nおもっているから つよいよ!$"

Route123_Text_CameronDefeat:
	.string "{JPN}しょんぼり……$"

Route123_Text_CameronPostBattle:
	.string "{JPN}サイキックとは きもちの つよさ\nきみには まけないと おもっていたのに……$"

Route123_Text_CameronRegister:
	.string "{JPN}ぼくには わかる!\nぼくと きみとは また しょうぶする!\lかてるか わかんない けど……\pポケナビを だして!$"

Route123_Text_CameronRematchIntro:
	.string "{JPN}ぼくは もう だれにも まけないと\nおもっているから つよいよ!!$"

Route123_Text_CameronRematchDefeat:
	.string "{JPN}しょんぼり……$"

Route123_Text_CameronPostRematch:
	.string "{JPN}おくりびやまで しゅぎょうでも しようかな\nこのままじゃ ずっと きみに かてないよ$"

Route123_Text_JackiIntro:
	.string "{JPN}ポケモンも ちょうのうりょくも\nつかえるだけじゃ いみ ないわ\lきたえてこそ ほんものに なるのよ$"

Route123_Text_JackiDefeat:
	.string "{JPN}すごい!$"

Route123_Text_JackiPostBattle:
	.string "{JPN}だれでも ちょうのうりょくを もっているの\nただ つかいかたを わすれている だけよ$"

Route123_Text_JackiRegister:
	.string "{JPN}もういちど しょうぶして みたいわ!\nいいでしょう?$"

Route123_Text_JackiRematchIntro:
	.string "{JPN}どう? あなたの なかの\nちょうのうりょく めばえたり した?$"

Route123_Text_JackiRematchDefeat:
	.string "{JPN}すごいわ!$"

Route123_Text_JackiPostRematch:
	.string "{JPN}あなたの つよさ\nそれも ちょうのうりょく かもね$"

Route123_Text_MiuIntro:
	.string "{JPN}ミウ『トレーナーさんの ポケモン\nまけても なかないで くださいね!$"

Route123_Text_MiuDefeat:
	.string "{JPN}ミウ『まけちゃったね……$"

Route123_Text_MiuPostBattle:
	.string "{JPN}ミウ『トレーナーさんの ポケモン\nなかが いいから つよいんですね!$"

Route123_Text_MiuNotEnoughMons:
	.string "{JPN}ミウ『ポケモンさん 2ひきは いないと\nたたかっても つまらないもん!$"

Route123_Text_YukiIntro:
	.string "{JPN}ユキ『よーし!\nトレーナーさんの ポケモン やっつけます!$"

Route123_Text_YukiDefeat:
	.string "{JPN}ユキ『まけちゃったね……$"

Route123_Text_YukiPostBattle:
	.string "{JPN}ユキ『どーして そんなに つよいの?\nあたちたち たたかって まけたの はじめて!$"

Route123_Text_YukiNotEnoughMons:
	.string "{JPN}ユキ『ポケモンさん 2ひきは いないと\nたたかっても つまらないもん!$"

Route123_Text_KindraIntro:
	.string "{JPN}おくりびやまは……\nポケモンの たましいが ねむるところ……\lあなたの ポケモンも ねむる……?$"

Route123_Text_KindraDefeat:
	.string "{JPN}げんき いっぱいね……$"

Route123_Text_KindraPostBattle:
	.string "{JPN}おくりびやまは……\nポケモンの たましいが ねむるところ……\pきっと たましいを なぐさめる\nちからに あふれてるのよ……$"

Route123_Text_FernandoIntro:
	.string "{JPN}いっきょく かなでる あいだに\nパッと たおしちゃうゼ!$"

Route123_Text_FernandoDefeat:
	.string "{JPN}おいおい まだ イントロだゼ!$"

Route123_Text_FernandoPostBattle:
	.string "{JPN}きみ やるじゃん\nきみの きょくを つくって みたいよ$"

Route123_Text_FernandoRegister:
	.string "{JPN}こんど あった ときには\nフルコーラス きいて くれヨ!$"

Route123_Text_FernandoRematchIntro:
	.string "{JPN}よし きょうこそ!\n1ばんを うたっている あいだに\lサッと たおしちゃうゼ!$"

Route123_Text_FernandoRematchDefeat:
	.string "{JPN}おいおい まだ サビまで いってないゼ!$"

Route123_Text_FernandoPostRematch:
	.string "{JPN}オレの うたに ききほれて\nまけちゃう って おもってたんだけど$"

Route123_Text_DavisIntro:
	.string "{JPN}ぼくの おにいちゃんに とってもらった\nじまんの むしポケモンだよ!$"

Route123_Text_DavisDefeat:
	.string "{JPN}わーん バカーっ!$"

Route123_Text_DavisPostBattle:
	.string "{JPN}まけちゃった こと\nぼくの おにいちゃんには ひみつ だよ!$"

Route123_Text_JazmynIntro:
	.string "{JPN}みるからに つよそうな あなたを\nたおせば じしんが つくわね!$"

Route123_Text_JazmynDefeat:
	.string "{JPN}じしん なくしました……$"

Route123_Text_JazmynPostBattle:
	.string "{JPN}ヒトは みためには よらないと いうけど\nけっこう みためどおりの ことも あるわね$"

Route123_Text_FrederickIntro:
	.string "{JPN}おい きみきみ\nじいちゃんと ちょっと あそぼうか$"

Route123_Text_FrederickDefeat:
	.string "{JPN}つよいこ じゃな\nこづかいを やるか$"

Route123_Text_FrederickPostBattle:
	.string "{JPN}え こづかい?\nしょうきんを もらったから いいじゃろ!$"

Route123_Text_AlbertoIntro:
	.string "{JPN}オレ マジ とりポケモンが すき!\nとりイカス! とりサイコー!$"

Route123_Text_AlbertoDefeat:
	.string "{JPN}まけた とりポケモンも イカス!$"

Route123_Text_AlbertoPostBattle:
	.string "{JPN}しょうぶの あいだに ちらばった\nとりポケモンの ハネを あつめて\lぼうしを つくる つもりなんだ!$"

Route123_Text_EdIntro:
	.string "{JPN}トレーナーが いない ときは\nじぶんの ポケモンどうしを\lたたかわせて ながめて いるぞぅ$"

Route123_Text_EdDefeat:
	.string "{JPN}きみの ポケモンも いいねぃ$"

Route123_Text_EdPostBattle:
	.string "{JPN}へへへ きみの たたかいかたの\nアイディア いただき!\lつよく なれそう だよぅ$"

Route123_Text_JonasIntro:
	.string "{JPN}まちぶせ していたら\nトレーナーが かかったで ござる!$"

Route123_Text_JonasDefeat:
	.string "{JPN}まけて くれなきゃ\nニンジャごっこ できないよ$"

Route123_Text_JonasPostBattle:
	.string "{JPN}つぎは もっと よわそうな トレーナーを\nまちぶせ してみるで ござるよ$"

Route123_Text_KayleyIntro:
	.string "{JPN}かった ばかりの パラソルで\nわたしも 3わりましで かわいい はず!$"

Route123_Text_KayleyDefeat:
	.string "{JPN}わたしの 5ばい くらい つよいわね$"

Route123_Text_KayleyPostBattle:
	.string "{JPN}こもの づかいも おしゃれの ひけつよ!$"

Route124_Text_SpencerIntro:
	.string "{JPN}おっと みちに まよったのか?\pわたしの ポケモンに かてたら\nみずさき あんないにんに なってあげようか?$"

Route124_Text_SpencerDefeat:
	.string "{JPN}たたかいかたを まよってしまった……$"

Route124_Text_SpencerPostBattle:
	.string "{JPN}うみで まよってしまう ひとは おおい!\pそんな ひとは ポケナビで\nマップを たしかめながら すすむと いい!$"

Route124_Text_RolandIntro:
	.string "{JPN}むっ! じぶんで およがずに\nポケモンに のっている……\pなんて うらやましいんだ!$"

Route124_Text_RolandDefeat:
	.string "{JPN}ああ!\nダメだ……!$"

Route124_Text_RolandPostBattle:
	.string "{JPN}からだが ひえてきた……\nながいこと みずの なかに いるからだ\pきみのように ポケモンに のりたいよ$"

Route124_Text_JennyIntro:
	.string "{JPN}こうして うみに うかんでいると\nポケモンたちが あそびに くるのよ!$"

Route124_Text_JennyDefeat:
	.string "{JPN}あーあ\nまけちゃった……$"

Route124_Text_JennyPostBattle:
	.string "{JPN}うみを およいでいると\nおそってくる ポケモンと\lただ みているだけの ポケモンが いるの\pポケモンにも こせいが あるのね!$"

Route124_Text_JennyRegister:
	.string "{JPN}なんとなく だけど\nポケナビ とうろく してもらおうかな……$"

Route124_Text_JennyRematchIntro:
	.string "{JPN}こうして うみに うかんでいると\nトレーナーが いどんで くるのよね!$"

Route124_Text_JennyRematchDefeat:
	.string "{JPN}おかしいなあ\nまた まけちゃった……$"

Route124_Text_JennyPostRematch:
	.string "{JPN}なんとなく だけど\nカラクリやしきに いってみようかな……$"

Route124_Text_GraceIntro:
	.string "{JPN}およぐのにも あきた ところだし……\nわたしと しょうぶ しようよ!$"

Route124_Text_GraceDefeat:
	.string "{JPN}こんなに つよいなんて\nおもいも しなかったわ!$"

Route124_Text_GracePostBattle:
	.string "{JPN}ずっと がんばって きたことが\nあなたの つよさなのね……!$"

Route124_Text_ChadIntro:
	.string "{JPN}うふふふふ\nオレは モグリの スイマー\lもぐりは とくいちゅうの とくいだぜ!$"

Route124_Text_ChadDefeat:
	.string "{JPN}ゴボゴボゴボ……\nしずんでいく……$"

Route124_Text_ChadPostBattle:
	.string "{JPN}うみの そこに もぐれる ポイントが\nこの あたりには あるらしいぜ!\lモグリの ちが さわぐなあ……$"

Route124_Text_LilaIntro:
	.string "{JPN}カコ『はーあ\pせっかくの うみ なのに\nいっしょに いるのが おとうと なんて……\pあなた きばらしに ポケモン しようか!?$"

Route124_Text_LilaDefeat:
	.string "{JPN}カコ『コウの せいで まけたのよ!\nあとで おしおき だかんね!!$"

Route124_Text_LilaPostBattle:
	.string "{JPN}カコ『はーあ\pとなりに いるのが おとうと じゃなくて\nすてきな かれし だったら いいのに……$"

Route124_Text_LilaNotEnoughMons:
	.string "{JPN}カコ『あたしたちと たたかう つもり?\nポケモン 2ひき いないと ダメよ$"

Route124_Text_RoyIntro:
	.string "{JPN}コウ『オレの ねえちゃん\nポケモン つよいぞ!\lまけて ないたり するなよ!$"

Route124_Text_RoyDefeat:
	.string "{JPN}コウ『うわぁ……\nあとで ねえちゃんに おこられる……$"

Route124_Text_RoyPostBattle:
	.string "{JPN}コウ『オレの ねえちゃん\nおこると むちゃくちゃ こわいんだ……\pだから こいびと いないんだぜ……$"

Route124_Text_LilaRoyRegister:
	.string "{JPN}コウ『また こんど しょうぶしてよ\n……そのときは てかげんして くれよ!$"

Route124_Text_RoyNotEnoughMons:
	.string "{JPN}コウ『オレらと たたかう つもり?\nポケモン 2ひき つれてきなよ!$"

Route124_Text_LilaRematchIntro:
	.string "{JPN}カコ『はーあ\pせっかくの うみ なのに\nいっしょに いるのが おとうと なんて……\pあら あなた ひさしぶりね\nきばらしに ポケモン しようか!?$"

Route124_Text_LilaRematchDefeat:
	.string "{JPN}カコ『コウったら!\nあんたの せいで また まけたでしょ!\lあとで とっくん だかんね!!$"

Route124_Text_LilaPostRematch:
	.string "{JPN}カコ『はーあ\pあたしに すてきな かれしが いたらなぁ\nすてきな コンビネーションで\lどんな あいてにでも かっちゃうのに$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "{JPN}カコ『あたしたちと たたかう つもり?\nポケモン 2ひき いないと ダメよ$"

Route124_Text_RoyRematchIntro:
	.string "{JPN}コウ『まけたら オレが おこられるから\nむちゃくちゃ ほんきで がんばるぞ!$"

Route124_Text_RoyRematchDefeat:
	.string "{JPN}コウ『うわぁ……\nまた ねえちゃんに おこられる……$"

Route124_Text_RoyPostRematch:
	.string "{JPN}コウ『オレの ねえちゃん\nおこると むちゃくちゃ こわいんだ……\pあとで オレと ポケモン\nもうとっくん だよ……$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "{JPN}コウ『オレらと たたかう つもり?\nポケモン 2ひき つれてきなよ!$"

Route124_Text_DeclanIntro:
	.string "{JPN}こんな きれいな うみで\nひとりで およいでいる オレ!\lはっきりいって かなしすぎます!$"

Route124_Text_DeclanDefeat:
	.string "{JPN}かなしい\nそらの あおさが かなしい$"

Route124_Text_DeclanPostBattle:
	.string "{JPN}ビキニのおねえさんを さそって\nえんえいと しゃれこんで みようかな?$"

Route124_Text_IsabellaIntro:
	.string "{JPN}なみのりトレーナー なんかに まけないわ!$"

Route124_Text_IsabellaDefeat:
	.string "{JPN}ううっ ポタポタ\nこ これは すいてきよ! ないてないわよ!$"

Route124_Text_IsabellaPostBattle:
	.string "{JPN}きれいな いろの カケラが\nこの あたりで みつかることが あるわよ$"

Route125_Text_NolenIntro:
	.string "{JPN}キミが やってくる おとが\nきこえて いたから まってたよ!$"

Route125_Text_NolenDefeat:
	.string "{JPN}まいりました……!$"

Route125_Text_NolenPostBattle:
	.string "{JPN}くうきちゅう よりも\nすいちゅうの ほうが おとの つたわる\lスピードが はやいんだよ!$"

Route125_Text_StanIntro:
	.string "{JPN}おらーっ!!\nおれの かわいい ポケモンだー!!$"

Route125_Text_StanDefeat:
	.string "{JPN}まいったぜ……!$"

Route125_Text_StanPostBattle:
	.string "{JPN}タッツーの みりょくに まいって\nおれも およぐように なったんだー!$"

Route125_Text_TanyaIntro:
	.string "{JPN}およぎ つかれちゃった!\nわたしと ひとしょうぶ どう?$"

Route125_Text_TanyaDefeat:
	.string "{JPN}あんた つよすぎ!$"

Route125_Text_TanyaPostBattle:
	.string "{JPN}ふう ふう……\nトクサネシティは どっち だったっけ?$"

Route125_Text_SharonIntro:
	.string "{JPN}わたしの そだてた みずポケモンと\nたたかって みない?$"

Route125_Text_SharonDefeat:
	.string "{JPN}まけた……$"

Route125_Text_SharonPostBattle:
	.string "{JPN}あなたの つよさは ホンモノね!\nおどろいたわ!$"

Route125_Text_ErnestIntro:
	.string "{JPN}オレさまは たくましい ふなのり!\nせかいの うみを わたりあるく おとこ!$"

Route125_Text_ErnestDefeat:
	.string "{JPN}ぐおおおーっ!\nかてねえ……!$"

Route125_Text_ErnestPostBattle:
	.string "{JPN}あさせのほらあな は じかんによって\nしおが みちたり ひいたり するんだ!\pちなみに みちしお から ひきしお まで\nおよそ 6じかんだぞ! しっていたか?$"

Route125_Text_ErnestRegister:
	.string "{JPN}ポケナビ とうろく して くれたら\nいいことを おしえて やるよ!$"

Route125_Text_ErnestRematchIntro:
	.string "{JPN}おっと ここで あったが 100ねんめ!\nとにかく ポケモンしょうぶ だっ!$"

Route125_Text_ErnestRematchDefeat:
	.string "{JPN}かてねえ\nちっとも かてねえよ!$"

Route125_Text_ErnestRematchPostBattle:
	.string "{JPN}あさせのほらあな……\pしおの みちひきに よって\nいけたり いけなかったり する\lばしょが あるんだよな\pちなみに みちしお から ひきしお まで\nおよそ 6じかんだぞ! おぼえておけよ!$"

Route125_Text_KimIntro:
	.string "{JPN}マホ『あさせのほらあなに\nへんな じいさんが いるんだって!\lあなたも あいにいく とちゅう?$"

Route125_Text_KimDefeat:
	.string "{JPN}マホ『かてると おもったのに$"

Route125_Text_KimPostBattle:
	.string "{JPN}マホ『あさせのほらあなに\nへんな じいさんが いるんでしょ?\pさっ ナホちゃん あいに いくよ!$"

Route125_Text_KimNotEnoughMons:
	.string "{JPN}マホ『ダメだって!\nポケモン 2ひき いないと ダメだって!$"

Route125_Text_IrisIntro:
	.string "{JPN}ナホ『センパイ\nこんな ところに なにが あるんですかぁ?$"

Route125_Text_IrisDefeat:
	.string "{JPN}ナホ『とちゅう おしいところ あったのに$"

Route125_Text_IrisPostBattle:
	.string "{JPN}ナホ『センパイ…… ほんとに\nあさせのほらあなに はいりますぅ?\lぬれちゃいますよぉ?$"

Route125_Text_IrisNotEnoughMons:
	.string "{JPN}ナホ『2たい1で しょうぶ なんて\nそんな まね あたしたちに できないわ$"

Route125_Text_PresleyIntro:
	.string "{JPN}とりつかいの ボクが\nなぜ うみにまで きているかと いうと……$"

Route125_Text_PresleyDefeat:
	.string "{JPN}わかった\nなんで ここに いるか おしえてやるよ$"

Route125_Text_PresleyPostBattle:
	.string "{JPN}あきビンに メールを いれて\nさっき うみに ながしたんだ!\pきっと かわいい ビキニの おんなのコが\nひろって くれるぜ!$"

Route125_Text_AuronIntro:
	.string "{JPN}こらーッ! おぬしかッ\nうみに ゴミを すてたのは!$"

Route125_Text_AuronDefeat:
	.string "{JPN}おぬしでは なかったか$"

Route125_Text_AuronPostBattle:
	.string "{JPN}さっき この あたりで\nこきたない ビンを ひろったんじゃ!\lうみに ゴミを すてるとは なっとらん!$"

Route126_Text_BarryIntro:
	.string "{JPN}すいえいは ぜんしん うんどう!\nたいりょくが つくぞー!$"

Route126_Text_BarryDefeat:
	.string "{JPN}まけましたーっ!$"

Route126_Text_BarryPostBattle:
	.string "{JPN}まいにち およいでる おかげで\nみよ! この きんにくっ!!$"

Route126_Text_DeanIntro:
	.string "{JPN}この しろく そびえる いわやまが\nルネシティ なんだぜー!$"

Route126_Text_DeanDefeat:
	.string "{JPN}やられたか!?$"

Route126_Text_DeanPostBattle:
	.string "{JPN}ルネシティの いりぐちが みつからん!\nどこに あるんだ?$"

Route126_Text_NikkiIntro:
	.string "{JPN}おほほほっ\nわたしは にんぎょ!$"

Route126_Text_NikkiDefeat:
	.string "{JPN}アワと なって きえていく……\nぶくぶくぶく……$"

Route126_Text_NikkiPostBattle:
	.string "{JPN}こっぴどく やられちゃったわ……\nアワくって にげだしたい きぶん……$"

Route126_Text_BrendaIntro:
	.string "{JPN}ねえ ねえ\nおねえさんと しょうぶ しない?$"

Route126_Text_BrendaDefeat:
	.string "{JPN}いやーんっ!$"

Route126_Text_BrendaPostBattle:
	.string "{JPN}こうして ポケモンと\nうみで あそぶのが だいすきなの!$"

Route126_Text_PabloIntro:
	.string "{JPN}からておう より たくましい\nこの にくたいびを みよ!$"

Route126_Text_PabloDefeat:
	.string "{JPN}おわっ つよいな\nいいね! いいね!$"

Route126_Text_PabloPostBattle:
	.string "{JPN}まけて いい しげきに なったよ!\nからだも ポケモンも もっと きたえるぜ$"

Route126_Text_PabloRegister:
	.string "{JPN}いやー いいね!\nぜひとも おちかづきに なっておきたいね!$"

Route126_Text_PabloRematchIntro:
	.string "{JPN}ビキニのおねえさん より うつくしい\nこの にくたいびを みよ!$"

Route126_Text_PabloRematchDefeat:
	.string "{JPN}おわっ ほんと つよいな\nいいね! いいね!$"

Route126_Text_PabloPostRematch:
	.string "{JPN}よし もっともっと きたえるぜ!\nきみは いい しげきに なるから\lまた きてくれよ!$"

Route126_Text_LeonardoIntro:
	.string "{JPN}きょねん まで およげなかった オレも\nかいパンやろうに なれたんだ\lいまなら なんでも できる きがする!$"

Route126_Text_LeonardoDefeat:
	.string "{JPN}てへっ よくばりすぎちゃ ダメだよな$"

Route126_Text_LeonardoPostBattle:
	.string "{JPN}なんでも れんしゅう すれば\nうまく なるんだ!\pキミも わかい うちから\nいろいろ やっておけよ!$"

Route126_Text_IsobelIntro:
	.string "{JPN}はなに かいすいが はいると\nすっごく つらいよね?$"

Route126_Text_IsobelDefeat:
	.string "{JPN}ああっ!\nく くやし……ごほッ!$"

Route126_Text_IsobelPostBattle:
	.string "{JPN}かいすいを ちょっと のんじゃった……!\nからいーッ にがいーッ!$"

Route126_Text_SiennaIntro:
	.string "{JPN}わたしの ハートを ぶつけるわ!$"

Route126_Text_SiennaDefeat:
	.string "{JPN}ハートで まけたわ!$"

Route126_Text_SiennaPostBattle:
	.string "{JPN}あつく なっちゃった\nちょっと もぐって こようかな$"

Route127_Text_CamdenIntro:
	.string "{JPN}オレと しょうぶ したいって\nかおに かいてあるぜ!$"

Route127_Text_CamdenDefeat:
	.string "{JPN}あわわわわ……$"

Route127_Text_CamdenPostBattle:
	.string "{JPN}いい しょうぶを した あとは\nすがすがしい きもちに なるなー$"

Route127_Text_DonnyIntro:
	.string "{JPN}あいつには まけたくない って\nライバル きみには いるの?$"

Route127_Text_DonnyDefeat:
	.string "{JPN}あぁ すっごく くやしい!$"

Route127_Text_DonnyPostBattle:
	.string "{JPN}ライバルが いると\nつよくなりたい って きもちが\lどんどん あふれて くるよね$"

Route127_Text_JonahIntro:
	.string "{JPN}つりを することで てにいれた\nおだやかな こころ……\lそれを みせて あげましょう……$"

Route127_Text_JonahDefeat:
	.string "{JPN}…… まけても\nこころは おだやかです$"

Route127_Text_JonahPostBattle:
	.string "{JPN}つれなくても かまいません\nずっと いとを たらしているのです……$"

Route127_Text_HenryIntro:
	.string "{JPN}おっと!? なみのり している\nポケモンを つりあげて しまったか?$"

Route127_Text_HenryDefeat:
	.string "{JPN}かなわん!$"

Route127_Text_HenryPostBattle:
	.string "{JPN}きみの ポケモン つよそうだから\nつりあげたら かなりの てごたえ だろうな!$"

Route127_Text_RogerIntro:
	.string "{JPN}よーし!\nポケモンずきと つりずきの たいけつだ!$"

Route127_Text_RogerDefeat:
	.string "{JPN}わあ! いとが からまった!\nまさに あとの まつり$"

Route127_Text_RogerPostBattle:
	.string "{JPN}つりでは いとが からまることを\nマツリ と いうんだよ$"

Route127_Text_AidanIntro:
	.string "{JPN}とりポケモンは すごく めが いい!\nおおぞら たかくから えものを みつけるぜ!$"

Route127_Text_AidanDefeat:
	.string "{JPN}ふぅ…… まいったぜ$"

Route127_Text_AidanPostBattle:
	.string "{JPN}この ちかくには いっぱい\nもぐれそうな ところが あるな!\pそらから みてると\nうみの いろが ちがうから よくわかる!$"

Route127_Text_KojiIntro:
	.string "{JPN}はだしで かけまわると\nあしの うらが きたえられるぞ!$"

Route127_Text_KojiDefeat:
	.string "{JPN}いってェ!\nツメの あいだに こいしが……$"

Route127_Text_KojiPostBattle:
	.string "{JPN}はだし さいこう!\nだが おまえの その ズックも いいな!$"

Route127_Text_KojiRegister:
	.string "{JPN}おれに かったり するやつは こうだーっ!\nまた よろしくおねがいします!$"

Route127_Text_KojiRematchIntro:
	.string "{JPN}きょうも はだしで かけまわって\nあしの うらを きたえまくりだ!$"

Route127_Text_KojiRematchDefeat:
	.string "{JPN}いってェ!\nつちふまずに ジャリが……$"

Route127_Text_KojiPostRematch:
	.string "{JPN}しばらく おまえの ズックと\nおれの はだし こうかん してみないか?$"

Route127_Text_AthenaIntro:
	.string "{JPN}じっくり ゆっくり しょうぶしましょう\nよろしくね!$"

Route127_Text_AthenaDefeat:
	.string "{JPN}せんりゃくを ねる ひまも なかったわ$"

Route127_Text_AthenaPostBattle:
	.string "{JPN}あおい いろに かこまれていると\nじかんが すぎるのが\lゆっくりに かんじられる のよ$"

Route128_Text_IsaiahIntro:
	.string "{JPN}サイユウシティは まだ とおい……$"

Route128_Text_IsaiahDefeat:
	.string "{JPN}ボクの はつしょうりも とおい……$"

Route128_Text_IsaiahPostBattle:
	.string "{JPN}まけつづけている じんせい ですが\nけっして あきらめませんよ……!$"

Route128_Text_IsaiahRegister:
	.string "{JPN}こんな ボク ですけど\nいつかは かてると おもうんです\lポケナビの とうろくを してください……!$"

Route128_Text_IsaiahRematchIntro:
	.string "{JPN}まだまだ げんき ですからね\nサイユウシティ めざして およぎますよ!$"

Route128_Text_IsaiahRematchDefeat:
	.string "{JPN}また はつしょうり ならず……$"

Route128_Text_IsaiahPostRematch:
	.string "{JPN}あきらめなきゃ いつかは かてる\nサイユウシティにも たどりつく……!$"

Route128_Text_KatelynIntro:
	.string "{JPN}トライアスロンは\nすいえい じてんしゃ マラソン\p3つの しゅもくを つづけて こなす\nかこくな レースなの!$"

Route128_Text_KatelynDefeat:
	.string "{JPN}ポケモンしょうぶも かこく よね……$"

Route128_Text_KatelynPostBattle:
	.string "{JPN}つぎは じてんしゃ だけど……\nくじけそうだわ……$"

Route128_Text_KatelynRegister:
	.string "{JPN}まあ せっかく だし\nまたいつか しょうぶを しましょうよ!$"

Route128_Text_KatelynRematchIntro:
	.string "{JPN}トライアスロンも ながいけど\nポケモン チャンピオンを めざすのも\lながい みちのり なのね!$"

Route128_Text_KatelynRematchDefeat:
	.string "{JPN}ほんとっ\nポケモンしょうぶ って きびしい……$"

Route128_Text_KatelynPostRematch:
	.string "{JPN}そろそろ チャンピオンロードに\nちょうせん してみるのも あり かな?$"

Route128_Text_AlexaIntro:
	.string "{JPN}ポケモンリーグに ちょうせん するため\nいままで がんばって きた……\pここで まけるわけには いかないわ!$"

Route128_Text_AlexaDefeat:
	.string "{JPN}ああっ!\nなんてこと$"

Route128_Text_AlexaPostBattle:
	.string "{JPN}ここまで きたんですもの\nいちど まけたからって あきらめない$"

Route128_Text_RubenIntro:
	.string "{JPN}わたしの ように つよい\nポケモントレーナーは ほかに いない!$"

Route128_Text_RubenDefeat:
	.string "{JPN}なんて ことだ……!$"

Route128_Text_RubenPostBattle:
	.string "{JPN}きみの ように つよい\nポケモントレーナーは ほかに いないだろう!$"

Route128_Text_WayneIntro:
	.string "{JPN}サイユウに いってみたいから\nたきのぼりを おぼえた\lポケモンを つりあげたんだよ!$"

Route128_Text_WayneDefeat:
	.string "{JPN}その いきおい\nまさに たきのぼり!$"

Route128_Text_WaynePostBattle:
	.string "{JPN}しまった!\pたきのぼりを おぼえた ポケモン つっても\nルネの ジムバッジ もってない!$"

Route128_Text_HarrisonIntro:
	.string "{JPN}きみが また つよそーだもんね!\nオレ かてっかな?$"

Route128_Text_HarrisonDefeat:
	.string "{JPN}あっひゃ\nやっぱ かてんわな$"

Route128_Text_HarrisonPostBattle:
	.string "{JPN}サイユウシティの まわりは\nつよそーな トレーナーが いっぱいだぜ!\lオレ ばちがいじゃ ないよな?$"

Route128_Text_CarleeIntro:
	.string "{JPN}この へんは ひざしが\nいちだんと つよいわねえ!$"

Route128_Text_CarleeDefeat:
	.string "{JPN}まぶしくて よく みえなかったの!$"

Route128_Text_CarleePostBattle:
	.string "{JPN}そろそろ もどって\nひやけどめ ぬりなおさなきゃ$"

Route129_Text_ChaseIntro:
	.string "{JPN}オレは しょしんしゃ トライアスリート\nはじめての レースで きんちょう!$"

Route129_Text_ChaseDefeat:
	.string "{JPN}うおー!\nまけてしまったーっ!$"

Route129_Text_ChasePostBattle:
	.string "{JPN}きんちょう していたら\nじつりょくが だせないよな!$"

Route129_Text_AllisonIntro:
	.string "{JPN}トライアスロンの とちゅう だけど……\nポケモンしょうぶを しようよ!$"

Route129_Text_AllisonDefeat:
	.string "{JPN}かてると おもったのにーっ!$"

Route129_Text_AllisonPostBattle:
	.string "{JPN}だいしぜんを あいてに\nじぶんの ちからを ためす ことも\lトライアスロンの だいごみ!$"

Route129_Text_ReedIntro:
	.string "{JPN}ホラホラ!\nとっとと しょうぶ しようぜ!$"

Route129_Text_ReedDefeat:
	.string "{JPN}まけた まけたよ\nとっとと おわろうぜ!$"

Route129_Text_ReedPostBattle:
	.string "{JPN}まけたら なにも ないさ\nとっとと かえると するか!$"

Route129_Text_TishaIntro:
	.string "{JPN}のーんびり のーんびり やりましょうか?$"

Route129_Text_TishaDefeat:
	.string "{JPN}あらら\nもっと のんびり したかったなあ$"

Route129_Text_TishaPostBattle:
	.string "{JPN}あせって ミスを するのって イヤでしょ?\nのんびり やることに してるのよ$"

Route129_Text_ClarenceIntro:
	.string "{JPN}なみのりも けっこう たいへんだろ?$"

Route129_Text_ClarenceDefeat:
	.string "{JPN}かつのって むずかしいなあ$"

Route129_Text_ClarencePostBattle:
	.string "{JPN}ポケモンリーグを めざしてるのか?\nがんばれ がんばれよ!$"

Route130_Text_RodneyIntro:
	.string "{JPN}うみの ドまんなかで\nトレーナーに であうとは めずらしいな\lイッパツ しょうぶ するか!?$"

Route130_Text_RodneyDefeat:
	.string "{JPN}なんて つよい こどもだ……$"

Route130_Text_RodneyPostBattle:
	.string "{JPN}きびしい たたかいを くぐりぬけてきた\nいい めを しているぜ!$"

Route130_Text_KatieIntro:
	.string "{JPN}あおい うみ\nブルーな こころ\lいやされる……$"

Route130_Text_KatieDefeat:
	.string "{JPN}うみ ひろく\nポケモン せかい\lまた ひろし……$"

Route130_Text_KatiePostBattle:
	.string "{JPN}こどもたち\nポケモン チャンプ\lめざしてる……$"

Route130_Text_SantiagoIntro:
	.string "{JPN}なにも ない うみに うかんでると……\nへいわだなあー……$"

Route130_Text_SantiagoDefeat:
	.string "{JPN}へいわボケ してて まけました!$"

Route130_Text_SantiagoPostBattle:
	.string "{JPN}こうして およいだり しょうぶしたり……\nオレ しあわせだなあー……$"

Route131_Text_RichardIntro:
	.string "{JPN}うみには ポケモンが たくさん いるからね\nおよいで わたるのも くろう するよ!$"

Route131_Text_RichardDefeat:
	.string "{JPN}トレーナーの そだてた ポケモンは\nホントに つよいなぁ……$"

Route131_Text_RichardPostBattle:
	.string "{JPN}ひいひい…… つかれた……\nいきは よいよい かえりは こわい……\lかえりの たいりょく のこってるかなあ……$"

Route131_Text_HermanIntro:
	.string "{JPN}うみ うみ うみ……\nみわたす かぎり うみ……\lうみは もう あきたぞーっ!$"

Route131_Text_HermanDefeat:
	.string "{JPN}ひょえええええっ!$"

Route131_Text_HermanPostBattle:
	.string "{JPN}うみに あきても\nおよぎ つづけるしか ないのか\pそんな オレは\nねっからの スイマー……$"

Route131_Text_SusieIntro:
	.string "{JPN}ちょっと あんた\nわたしと しょうぶ しましょ!$"

Route131_Text_SusieDefeat:
	.string "{JPN}みかけに よらず\nつよいわねーっ!$"

Route131_Text_SusiePostBattle:
	.string "{JPN}あっちで うみは あきた とか いってる\nおとこが いるでしょ?\pアレ くちだけ なのよ\nホントは うみが すきで しょうがないの!$"

Route131_Text_KaraIntro:
	.string "{JPN}なんで オトコって\nビキニが すき なのかしらね!\pみんな わたしの こと\nジロジロ みるのよ!$"

Route131_Text_KaraDefeat:
	.string "{JPN}じつりょくが ちがい すぎるわ……!$"

Route131_Text_KaraPostBattle:
	.string "{JPN}みんな ビキニを みてるんじゃなくて\nわたしの びぼうが げんいん かしら……?$"

Route131_Text_ReliIntro:
	.string "{JPN}アミ『きょうだい ちからを あわせて\nがんばっちゃおうかな!?$"

Route131_Text_ReliDefeat:
	.string "{JPN}アミ『きょうだいで ちからを あわせても\nかてなかったわ$"

Route131_Text_ReliPostBattle:
	.string "{JPN}アミ『キナギの にんげんは\nうまれた ときから\lうみと ポケモンと いっしょ なんだ$"

Route131_Text_ReliNotEnoughMons:
	.string "{JPN}アミ『ポケモン 2ひき いないの?\nポケモンしょうぶ たのしめないわね$"

Route131_Text_IanIntro:
	.string "{JPN}カツ『きょうだい ちからを あわせて\nがんばりまーす!!$"

Route131_Text_IanDefeat:
	.string "{JPN}カツ『あねきと がんばったのに\nかてなかったよ……$"

Route131_Text_IanPostBattle:
	.string "{JPN}カツ『キナギって うみの うえに\nうかんでる まち だろ?\pだから うみが つづくかぎり\nそこは キナギ なんだよ!$"

Route131_Text_IanNotEnoughMons:
	.string "{JPN}カツ『ポケモン 2ひき いたら\nポケモンしょうぶ してやるよ!$"

Route131_Text_TaliaIntro:
	.string "{JPN}わたしに かてたら\nすごい じょうほう おしえてあげる!$"

Route131_Text_TaliaDefeat:
	.string "{JPN}あら まけちゃったのね$"

Route131_Text_TaliaPostBattle:
	.string "{JPN}この そばに ふしぎな ばしょが あるわよ\nたかい とうが そびえているの!\lみてきたら どうかしら?$"

Route131_Text_KevinIntro:
	.string "{JPN}キナギには おおらかな やつ ばかりだぜ!\nぜったい おこったり しないんだ\lもちろん オレもな$"

Route131_Text_KevinDefeat:
	.string "{JPN}あ……っ$"

Route131_Text_KevinPostBattle:
	.string "{JPN}ちっ! ……じゃ なかった\nお おこってない おこってないよ!\p……ハハ つよいね きみは!\nはっハッは!$"

Route132_Text_GilbertIntro:
	.string "{JPN}ちいさい ころは よく カゼを ひいたけど\nすいえいを はじめて こんなに じょうぶ!$"

Route132_Text_GilbertDefeat:
	.string "{JPN}もっと つよくなりたい……!$"

Route132_Text_GilbertPostBattle:
	.string "{JPN}ポケモン トレーナーも\nのやまを あるき まわるから\lとっても けんこうてき だよねー!$"

Route132_Text_DanaIntro:
	.string "{JPN}ながれの つよい ところでは\nおよがないように しているのよ$"

Route132_Text_DanaDefeat:
	.string "{JPN}いやああああんっ!$"

Route132_Text_DanaPostBattle:
	.string "{JPN}ながされると じぶんが どこに いるのか\nわからなく なっちゃうの……$"

Route132_Text_RonaldIntro:
	.string "{JPN}かつか まけるか\nやれば わかることだろ!$"

Route132_Text_RonaldDefeat:
	.string "{JPN}わーん\nまけて しまった$"

Route132_Text_RonaldPostBattle:
	.string "{JPN}かてると わかる しょうぶは しない!\nかつか まけるか\lその ギリギリの かんじが いいんだ!$"

Route132_Text_KiyoIntro:
	.string "{JPN}24じかん ポケモンのこと かんがえてる\nそんな おれに かてると おもうか!?$"

Route132_Text_KiyoDefeat:
	.string "{JPN}まけた\nおまえさんには まけたわ$"

Route132_Text_KiyoPostBattle:
	.string "{JPN}くう……\nおまえも ポケモンばか だな!\p24じかん ポケモンのこと ばかり\nかんがえて いるんだろ!$"

Route132_Text_MakaylaIntro:
	.string "{JPN}いつも いっしょの じいさんが\nいなくても かてるわい!$"

Route132_Text_MakaylaDefeat:
	.string "{JPN}あら やっぱり ダメかね$"

Route132_Text_MakaylaPostBattle:
	.string "{JPN}あの わかい おとこのこ\nじいさんの わかい ころに そっくりじゃ\lポッ……$"

Route132_Text_JonathanIntro:
	.string "{JPN}さっき から へんな しせんを\nかんじると おもったら キミか?$"

Route132_Text_JonathanDefeat:
	.string "{JPN}へえ! つよいね!$"

Route132_Text_JonathanPostBattle:
	.string "{JPN}だれかが ぼくの ことを\nみているきが して おちつかないっ!$"

Route132_Text_PaxtonIntro:
	.string "{JPN}いつも いっしょの ばあさんは どこかな?\nひとりで かてるじゃろか$"

Route132_Text_PaxtonDefeat:
	.string "{JPN}ああ やっぱり ダメかね$"

Route132_Text_PaxtonPostBattle:
	.string "{JPN}ばあさんも わしを さがしてるじゃろ\nはよう みつけて やらんと$"

Route132_Text_DarcyIntro:
	.string "{JPN}ひとりで この ばしょで\nしゅぎょう するのが すきだったのに!\lおおぜい やって くるんだもの ひどい!$"

Route132_Text_DarcyDefeat:
	.string "{JPN}わかったわよ\nみんなで つかえば いいんでしょ$"

Route132_Text_DarcyPostBattle:
	.string "{JPN}とりあえず そこの おじいさんと くんで\nむこうの チームに いどんで みようかな?$"

Route133_Text_FranklinIntro:
	.string "{JPN}キミも しおに ながされて きたの?\nこれも なにかの えんだね\lしょうぶ しようよ!$"

Route133_Text_FranklinDefeat:
	.string "{JPN}つよい!\nつよすぎっ!$"

Route133_Text_FranklinPostBattle:
	.string "{JPN}キミみたいな つよい トレーナーが\nながされて くるなんて……\lオレも ツキが ないなぁ……$"

Route133_Text_DebraIntro:
	.string "{JPN}わたしは かなしい おんな……\nながれ ながれて ここまで きたの……$"

Route133_Text_DebraDefeat:
	.string "{JPN}まけたぁ……$"

Route133_Text_DebraPostBattle:
	.string "{JPN}ながされる だけの じんせい なんて……\nもう イヤっ!$"

Route133_Text_LindaIntro:
	.string "{JPN}いらっしゃーい!\nおまち してましたわ!$"

Route133_Text_LindaDefeat:
	.string "{JPN}いやーん!$"

Route133_Text_LindaPostBattle:
	.string "{JPN}つよい こどもの トレーナーなんて……\nおねえさん こまっちゃうぅ!$"

Route133_Text_WarrenIntro:
	.string "{JPN}かちたいから って\nひとと おなじように そだては しないぜ!$"

Route133_Text_WarrenDefeat:
	.string "{JPN}くそー!\nおれの やりかたは まだまだ あまい!$"

Route133_Text_WarrenPostBattle:
	.string "{JPN}ひとと おなじこと するより\nじぶんの したいこと したほうが\lたのしいに きまってるだろ!$"

Route133_Text_BeckIntro:
	.string "{JPN}とりポケモンと いっしょに\nこんな ところまで きました$"

Route133_Text_BeckDefeat:
	.string "{JPN}きみ……\nなんて かっこいいんだ!$"

Route133_Text_BeckPostBattle:
	.string "{JPN}そろそろ ヒワマキに かえりたいけど\nなんとなく ここ すきに なっちゃったぞ!?$"

Route133_Text_MollieIntro:
	.string "{JPN}いままでに なんぜんかい\nポケモン しょうぶを したかねえ$"

Route133_Text_MollieDefeat:
	.string "{JPN}なんぜんかい まけても\nくやしい もんは くやしいでね$"

Route133_Text_MolliePostBattle:
	.string "{JPN}わたいや じいさんのような\nたつじんを めざして がんばんなせえ$"

Route133_Text_ConorIntro:
	.string "{JPN}わかい やつらは\nながされて ばっかりで なさけねぇ!$"

Route133_Text_ConorDefeat:
	.string "{JPN}きみは しっかりしとるな$"

Route133_Text_ConorPostBattle:
	.string "{JPN}まわりに ながされず\nしっかりした おとなに なんなさい!$"

Route134_Text_JackIntro:
	.string "{JPN}およぎの とくいな ポケモンだって\nながされる しおの ながれだ!$"

Route134_Text_JackDefeat:
	.string "{JPN}ひえーっ!$"

Route134_Text_JackPostBattle:
	.string "{JPN}ポケモンたちは この ながれを\nたのしんでる みたいだよ!$"

Route134_Text_LaurelIntro:
	.string "{JPN}わたしの ラブカスたちと\nたのしく しょうぶ しましょうよ!$"

Route134_Text_LaurelDefeat:
	.string "{JPN}あらららららっ!$"

Route134_Text_LaurelPostBattle:
	.string "{JPN}どこかの マニアが\nラブカスの ウロコを あつめてるのよねー$"

Route134_Text_AlexIntro:
	.string "{JPN}よーしっ! きゅうけい おわり!\nポケモンしょうぶ しようぜ!$"

Route134_Text_AlexDefeat:
	.string "{JPN}また バテた……$"

Route134_Text_AlexPostBattle:
	.string "{JPN}オレの とりポケモンたち……\nながいあいだ とぶと すぐに バテるんだ$"

Route134_Text_HitoshiIntro:
	.string "{JPN}ポケモントレーナーなら\nだまって ポケモンしょうぶ!$"

Route134_Text_HitoshiDefeat:
	.string "{JPN}…… …… ……\n…… …… ……$"

Route134_Text_HitoshiPostBattle:
	.string "{JPN}じぶんから しょうぶを いどんでおいて\nまけるとは…… はずかしすぎる……$"

Route134_Text_AaronIntro:
	.string "{JPN}このあたりの はげしい しおの ながれ!\nそれもまた おれたちを きたえてくれる!$"

Route134_Text_AaronDefeat:
	.string "{JPN}すなおに まけを みとめよう$"

Route134_Text_AaronPostBattle:
	.string "{JPN}りゅうせいのたきで\nしゅぎょう しなおすと しよう!\pよければ きみも いってみたまえ\nきっと いまより つよくなる!$"

Route134_Text_KelvinIntro:
	.string "{JPN}ふ ふねが\nながされて しまったんです$"

Route134_Text_KelvinDefeat:
	.string "{JPN}あわわわわ\nやめてください やめてくださいよ!$"

Route134_Text_KelvinPostBattle:
	.string "{JPN}このうえ なみのり まで できなかったら\nかえれないじゃ ないですか!\p……まあ ひんしでも なみのり できますけど\nきぶんてきに よろしくなくて$"

Route134_Text_MarleyIntro:
	.string "{JPN}すばやい こうげきを かわせますこと?$"

Route134_Text_MarleyDefeat:
	.string "{JPN}そんな てが あるなんて……!\nかんぱい ですわ$"

Route134_Text_MarleyPostBattle:
	.string "{JPN}すばやさへの こだわりは すてきれないの\nもっと がんばって みますわ!$"

Route134_Text_ReynaIntro:
	.string "{JPN}あたいの ポケモンは\nちょっとや そっとじゃ たおせないよ!$"

Route134_Text_ReynaDefeat:
	.string "{JPN}うっそだろ!\nあたいが まけるなんて!$"

Route134_Text_ReynaPostBattle:
	.string "{JPN}ははっ あんたにゃ まけたよ!\pそこらへんの トレーナーでも たおして\nいちから しゅぎょう しなおすよ!$"

Route134_Text_HudsonIntro:
	.string "{JPN}なあ このへんで\nもうひとり ふなのりを みなかった?$"

Route134_Text_HudsonDefeat:
	.string "{JPN}おー すごいな$"

Route134_Text_HudsonPostBattle:
	.string "{JPN}おれたちの ふねが ながされちゃってさ!\pあいぼうが きの よわい やつだから\nしんぱい してるんだ$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "{JPN}バッテリーが たりない!\nじゅうでん かんりょうまで\lあと {STR_VAR_1}ほ{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "{JPN}ちかくに たたかえる トレーナーは\nみあたらない…\lつかうのを あきらめた{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "{JPN}しょうぶの じゅんびが\nできていない みたい\lまた あとに しよう!$"
