Route102_Text_CalvinIntro:
	.string "{JPN}ポケモン つれていれば\n"
	.string "{JPN}キミも りっぱな ポケモントレーナー!\l"
	.string "{JPN}ボクの ちょうせん うけるよね!$"

Route102_Text_CalvinDefeated:
	.string "{JPN}ああ まけた……\n"
	.string "{JPN}もっと そだてておけば よかったよ$"

Route102_Text_CalvinPostBattle:
	.string "{JPN}キミ つよいなら つよいって\n"
	.string "{JPN}さいしょから いって くれよな!$"

Route102_Text_CalvinRegister:
	.string "{JPN}ボク あれから がんばってるよ!\n"
	.string "{JPN}こんど たたかいたい から\l"
	.string "{JPN}ポケナビ とうろく してよ!$"

Route102_Text_CalvinRegisterShort:
	.string "{JPN}こんど また たたかいたい から\n"
	.string "{JPN}ポケナビ とうろく してよ!$"

Route102_Text_CalvinRematchIntro:
	.string "{JPN}キミに まけてから ひっしに\n"
	.string "{JPN}ポケモン そだてたんだ! もちろん\l"
	.string "{JPN}ボクの ちょうせん うけるよね!$"

Route102_Text_CalvinRematchDefeated:
	.string "{JPN}ああ まけた……\n"
	.string "{JPN}そだてかた わるいのかな$"

Route102_Text_CalvinRematchPostBattle:
	.string "{JPN}キミが つよくなるなら\n"
	.string "{JPN}ボクも もっと つよくなって みせるよ!$"

Route102_Text_AllenIntro:
	.string "{JPN}きみ トレーナーに なったばかり?\n"
	.string "{JPN}おたがい しょしんしゃ だね!$"

Route102_Text_AllenDefeated:
	.string "{JPN}かてると おもったから\n"
	.string "{JPN}こえを かけたのに!$"

Route102_Text_AllenPostBattle:
	.string "{JPN}まだ 1かいも かってない……\n"
	.string "{JPN}はやく かちたいなあ……$"

Route102_Text_RickIntro:
	.string "{JPN}おっと! めが あったな!\n"
	.string "{JPN}むしポケモンで あいてを するぜ!$"

Route102_Text_RickDefeated:
	.string "{JPN}まけてしまった!$"

Route102_Text_RickPostBattle:
	.string "{JPN}めが あった トレーナーには\n"
	.string "{JPN}しょうぶを いどむのが きまりさ!$"

Route102_Text_TianaIntro:
	.string "{JPN}わたしは どんどん かちぬいて\n"
	.string "{JPN}さいきょうの トレーナーを めざすのよ!\p"
	.string "{JPN}あなたも きょうりょく してね!$"

Route102_Text_TianaDefeated:
	.string "{JPN}わたしが あなたに\n"
	.string "{JPN}きょうりょく しちゃった みたいね……$"

Route102_Text_TianaPostBattle:
	.string "{JPN}どんどん かちぬくには\n"
	.string "{JPN}もっと たくさん ポケモンを\l"
	.string "{JPN}つかまえないと いけない みたいね!$"

Route103_Text_DaisyIntro:
	.string "{JPN}こころ やすらぐ かおりに\n"
	.string "{JPN}あなたも さそわれたのですね……$"

Route103_Text_DaisyDefeated:
	.string "{JPN}わたくしの かおりに\n"
	.string "{JPN}まどわされませんでしたね……$"

Route103_Text_DaisyPostBattle:
	.string "{JPN}アロマとは かおりのこと……\n"
	.string "{JPN}かおりは こころと からだを いやすのです$"

Route103_Text_AmyIntro:
	.string "{JPN}クミ『あたしは クミ!\n"
	.string "{JPN}こっちは いもうとの ルミ!\l"
	.string "{JPN}ふたりで いっしょに たたかうのよ!$"

Route103_Text_AmyDefeated:
	.string "{JPN}クミ『まけっちゃったよぉ……$"

Route103_Text_AmyPostBattle:
	.string "{JPN}クミ『ふたりを あいてに するのって\n"
	.string "{JPN}いろんな ことを かんがえるよね!$"

Route103_Text_AmyNotEnoughPokemon:
	.string "{JPN}クミ『あら?\n"
	.string "{JPN}ポケモン 1ひきしか つれてないんだね!\l"
	.string "{JPN}それじゃあ あたしたちと たたかえないわ!$"

Route103_Text_LivIntro:
	.string "{JPN}ルミ『あたしたちは ふたりで ひとり\n"
	.string "{JPN}いっしょに たたかうんだよ!$"

Route103_Text_LivDefeated:
	.string "{JPN}ルミ『まけちゃったよぉ おねえちゃぁん……$"

Route103_Text_LivPostBattle:
	.string "{JPN}ルミ『おねえちゃんと あたしは\n"
	.string "{JPN}いきが ぴったり あってるのに……\p"
	.string "{JPN}まけちゃったよぉ……$"

Route103_Text_AmyLivRegister:
	.string "{JPN}ルミ『あたしたち ほんとは\n"
	.string "{JPN}もっと つよいんだもん……\l"
	.string "{JPN}ほんとうだから! こんど みせるから!$"

Route103_Text_LivNotEnoughPokemon:
	.string "{JPN}ルミ『あたしたちと たたかいたいなら\n"
	.string "{JPN}ポケモンを 2ひき つれてないと ダメよ!\l"
	.string "{JPN}じゃないと しょうぶに ならないんだから!$"

Route103_Text_AmyRematchIntro:
	.string "{JPN}クミ『あたしは クミ!\n"
	.string "{JPN}こっちは いもうとの ルミ!\l"
	.string "{JPN}ふたりで いっしょに たたかうのよ!$"

Route103_Text_AmyRematchDefeated:
	.string "{JPN}クミ『くやしい……\n"
	.string "{JPN}また かてなかったよぉ……$"

Route103_Text_AmyRematchPostBattle:
	.string "{JPN}クミ『ふたりを あいてに するのって\n"
	.string "{JPN}いろんな ことを かんがえるよね!$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "{JPN}クミ『あら?\n"
	.string "{JPN}ポケモン 1ひきしか つれてないんだね!\l"
	.string "{JPN}それじゃあ あたしたちと たたかえないわ!$"

Route103_Text_LivRematchIntro:
	.string "{JPN}ルミ『あたしたちは ふたりで ひとり\n"
	.string "{JPN}いつも いっしょに たたかうんだよ!$"

Route103_Text_LivRematchDefeated:
	.string "{JPN}ルミ『また まけちゃったよぉ\n"
	.string "{JPN}おねえちゃぁん……$"

Route103_Text_LivRematchPostBattle:
	.string "{JPN}ルミ『おねえちゃんと あたしは\n"
	.string "{JPN}いきが ぴったり あってるのに……\p"
	.string "{JPN}どうして また まけちゃったの?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "{JPN}ルミ『あたしたちと たたかいたいなら\n"
	.string "{JPN}ポケモンを 2ひき つれてないと ダメよ!\l"
	.string "{JPN}じゃないと しょうぶに ならないんだから!$"

Route103_Text_AndrewIntro:
	.string "{JPN}つりいとが からまって イライラするーっ!\n"
	.string "{JPN}ええいっ しょうぶだっ!$"

Route103_Text_AndrewDefeated:
	.string "{JPN}まけたっ!\n"
	.string "{JPN}よけいに イライラするぞーっ!$"

Route103_Text_AndrewPostBattle:
	.string "{JPN}ええい はらだたしい……!\n"
	.string "{JPN}イライライライラ……$"

Route103_Text_MiguelIntro:
	.string "{JPN}わたしの ポケモンちゃん\n"
	.string "{JPN}すごく かわいいから みていきたまえ!$"

Route103_Text_MiguelDefeated:
	.string "{JPN}あわわ……\n"
	.string "{JPN}わたしの ポケモンちゃん!$"

Route103_Text_MiguelPostBattle:
	.string "{JPN}かわいい ポケモンちゃんは\n"
	.string "{JPN}やられた すがたも かわいいな……$"

Route103_Text_MiguelRegister:
	.string "{JPN}なんどでも かわいい ポケモンちゃんを\n"
	.string "{JPN}みにきて もらうんだからね!$"

Route103_Text_MiguelRematchIntro:
	.string "{JPN}きみ! わたしの ポケモンちゃん\n"
	.string "{JPN}さらに かわいく なったのだ!$"

Route103_Text_MiguelRematchDefeated:
	.string "{JPN}ああ!\n"
	.string "{JPN}わたしの ポケモンちゃん!$"

Route103_Text_MiguelRematchPostBattle:
	.string "{JPN}いっしょに いれば いるほど\n"
	.string "{JPN}ポケモンが かわいくなって たまらん!$"

Route103_Text_PeteIntro:
	.string "{JPN}この くらいの きょり\n"
	.string "{JPN}およいで わたれば いーのにさ!$"

Route103_Text_PeteDefeated:
	.string "{JPN}おお やるじゃん$"

Route103_Text_PetePostBattle:
	.string "{JPN}なーるほど\p"
	.string "{JPN}それ ほど たよれる ポケモンなら\n"
	.string "{JPN}おもわず なみのり したくなる ってもんだ$"

Route103_Text_IsabelleIntro:
	.string "{JPN}きゃあ ぶつかるわ!\n"
	.string "{JPN}あぶないっ!$"

Route103_Text_IsabelleDefeated:
	.string "{JPN}んん……$"

Route103_Text_IsabellePostBattle:
	.string "{JPN}わたし およぎが へたで\n"
	.string "{JPN}れんしゅう してたのよ……\l"
	.string "{JPN}ぶつかりそうに なって ゴメンね$"

Route103_Text_RhettIntro:
	.string "{JPN}うぉっ!\n"
	.string "{JPN}なぜ こんな せまいところに!?$"

Route103_Text_RhettDefeated:
	.string "{JPN}うぉっ できる!$"

Route103_Text_RhettPostBattle:
	.string "{JPN}せまい ところが\n"
	.string "{JPN}すき なのかい きみは?$"

Route103_Text_MarcosIntro:
	.string "{JPN}おれっちの ギターに さそわれて\n"
	.string "{JPN}やって きたのかーい?$"

Route103_Text_MarcosDefeated:
	.string "{JPN}おれっちの ひとりショーが だいなしだよ$"

Route103_Text_MarcosPostBattle:
	.string "{JPN}ひとの すくない ところで\n"
	.string "{JPN}ギターを ひいていたのに\l"
	.string "{JPN}こんなにも あつまって きたぜ!\p"
	.string "{JPN}ぷ プロを めざして みるか!$"

Route104_Text_GinaIntro:
	.string "{JPN}ナオ『よーし!\n"
	.string "{JPN}あたしたちの ポケモンと たたかうです!$"

Route104_Text_GinaDefeat:
	.string "{JPN}ナオ『まけて すごく くやしいです$"

Route104_Text_GinaPostBattle:
	.string "{JPN}ナオ『うわー {STR_VAR_1} つよいです!\n"
	.string "{JPN}あたしたち もっと しゅぎょう するです$"

Route104_Text_GinaNotEnoughMons:
	.string "{JPN}ナオ『あら? ポケモン 1ひき だけですか!\n"
	.string "{JPN}じゃあ あたしたち たたかわない です!\p"
	.string "{JPN}だって ポケモン 1ひき だけだと\n"
	.string "{JPN}ポケモンが さびしそうで かわいそう です!$"

Route104_Text_MiaIntro:
	.string "{JPN}ミオ『あたしたち ふたご だから\n"
	.string "{JPN}ポケモンしょうぶも いっしょに するです!$"

Route104_Text_MiaDefeat:
	.string "{JPN}ミオ『ふたりで しょうぶ したのに\n"
	.string "{JPN}まけちゃったです……$"

Route104_Text_MiaPostBattle:
	.string "{JPN}ミオ『もっと ポケモン そだてて\n"
	.string "{JPN}{STR_VAR_1} みたいに つよく なるです!$"

Route104_Text_MiaNotEnoughMons:
	.string "{JPN}ミオ『あたしたちと たたかうですか?\p"
	.string "{JPN}じゃあ ポケモンを\n"
	.string "{JPN}2ひき つれてないと ダメですよ!\l"
	.string "{JPN}だって あたしたち つよいもん!$"

Route104_Text_IvanIntro:
	.string "{JPN}みずポケモンの エキスパートとは\n"
	.string "{JPN}なにを かくそう オレのこと!\p"
	.string "{JPN}……え?\n"
	.string "{JPN}しらないの?$"

Route104_Text_IvanDefeat:
	.string "{JPN}けっこう つよいと おもってたんだけどな\n"
	.string "{JPN}じぶんのこと…… がっかり……$"

Route104_Text_IvanPostBattle:
	.string "{JPN}つりに むちゅうに なってて\n"
	.string "{JPN}ポケモン そだてるのを わすれてたよ……$"

Route104_Text_BillyIntro:
	.string "{JPN}すなはまに あしあと つけるのって\n"
	.string "{JPN}たのしーよねー!$"

Route104_Text_BillyDefeat:
	.string "{JPN}うへーっ!\n"
	.string "{JPN}クツに すなが はいって ジャリジャリする!$"

Route104_Text_BillyPostBattle:
	.string "{JPN}すなはまを ボクの あしあとで\n"
	.string "{JPN}いっぱいに したいんだけど\l"
	.string "{JPN}すぐに きえちゃうんだよなぁ$"

Route104_Text_HaleyIntro:
	.string "{JPN}しょうぶ しようかな……\n"
	.string "{JPN}やめとこうかな……\p"
	.string "{JPN}えーい! たたかっちゃえ!$"

Route104_Text_HaleyDefeat:
	.string "{JPN}たたかわなければ よかったかな……$"

Route104_Text_HaleyPostBattle:
	.string "{JPN}どっちに しようか まよってる とき\n"
	.string "{JPN}じぶんで きめないで たにんに まかせると\l"
	.string "{JPN}どっちに なっても こうかいするね……$"

Route104_Text_HaleyRegister1:
	.string "{JPN}あなた つよいけど\n"
	.string "{JPN}ポケナビに とうろく しようかな……\l"
	.string "{JPN}やめとこうかな……\p"
	.string "{JPN}えーい! とうろくしちゃえ!$"

Route104_Text_HaleyRegister2:
	.string "{JPN}あなた つよいけど\n"
	.string "{JPN}ポケナビに とうろく しようかな……\l"
	.string "{JPN}やめとこうかな……\p"
	.string "{JPN}えーい! とうろくしちゃえ!$"

Route104_Text_HaleyRematchIntro:
	.string "{JPN}あたしと しょうぶ してもらうわよ!$"

Route104_Text_HaleyRematchDefeat:
	.string "{JPN}うーん……\n"
	.string "{JPN}かてると おもったのにな$"

Route104_Text_HaleyPostRematch:
	.string "{JPN}たたかうって じぶんで きめたから\n"
	.string "{JPN}まけても すっきり してるわ!\p"
	.string "{JPN}……もちろん まけて くやしいけどね$"

Route104_Text_WinstonIntro:
	.string "{JPN}ボクが あいてして あげるよ\n"
	.string "{JPN}この おかねもちの ボクがね$"

Route104_Text_WinstonDefeat:
	.string "{JPN}どうして かてないんだ……!?$"

Route104_Text_WinstonPostBattle:
	.string "{JPN}おかねじゃ かてない ものが ある……\n"
	.string "{JPN}それが ポケモンなんだね……$"

Route104_Text_WinstonRegister1:
	.string "{JPN}ん? きみ ポケナビを てにいれたね!\p"
	.string "{JPN}ボクが とうろくして あげよう\n"
	.string "{JPN}この おかねもちの ボクがね$"

Route104_Text_WinstonRegister2:
	.string "{JPN}ん? きみ ポケナビを てにいれたね!\p"
	.string "{JPN}ボクが とうろくして あげよう\n"
	.string "{JPN}この おかねもちの ボクがね$"

Route104_Text_WinstonRematchIntro:
	.string "{JPN}きみに まけてから いろいろ\n"
	.string "{JPN}ポケモンのこと べんきょう したんだ!$"

Route104_Text_WinstonRematchDefeat:
	.string "{JPN}また まけた……\n"
	.string "{JPN}どうして かてないんだ……!?$"

Route104_Text_WinstonPostRematch:
	.string "{JPN}おかねもちの ボク なのに\n"
	.string "{JPN}なかなか ポケモンに かてない……\p"
	.string "{JPN}なんて おくが ふかいんだろう\n"
	.string "{JPN}ポケモンって……$"

Route104_Text_CindyIntro:
	.string "{JPN}あなたと であったのも なにかの ごえん\n"
	.string "{JPN}おてあわせを おねがい できるかしら$"

Route104_Text_CindyDefeat:
	.string "{JPN}まあ!$"

Route104_Text_CindyPostBattle:
	.string "{JPN}であいは わかれの はじまり……\n"
	.string "{JPN}また どこかで おあいしましょう$"

Route104_Text_CindyRegister1:
	.string "{JPN}あら…… また おあい しましたわね\p"
	.string "{JPN}こんなに ごえんが あるんですもの\n"
	.string "{JPN}ポケナビに とうろく して くださいませ$"

Route104_Text_CindyRegister2:
	.string "{JPN}この ごえんを きねんして\n"
	.string "{JPN}ポケナビに とうろく して くださいませ$"

Route104_Text_CindyRematchIntro:
	.string "{JPN}また おあい しましたわね\n"
	.string "{JPN}おてあわせ おねがい できるかしら$"

Route104_Text_CindyRematchDefeat:
	.string "{JPN}あら……\n"
	.string "{JPN}わたくし ベストを つくしましたのに……$"

Route104_Text_CindyPostRematch:
	.string "{JPN}であいは わかれの はじまり……\n"
	.string "{JPN}また どこかで おあいしましょう$"

Route104_Text_DarianIntro:
	.string "{JPN}つよそうな ポケモンが つれたっ!\n"
	.string "{JPN}さかなの おうさま って かんじだ!\l"
	.string "{JPN}これは つよそうだぞっ!$"

Route104_Text_DarianDefeat:
	.string "{JPN}なっにい$"

Route104_Text_DarianPostBattle:
	.string "{JPN}おい なまえ まけ してるじゃないか\n"
	.string "{JPN}おれの コイキングよ!$"

Route105_Text_FosterIntro:
	.string "{JPN}この あたりに\n"
	.string "{JPN}ふしぎな いわが あるらしいが\l"
	.string "{JPN}きみ しらないかい?$"

Route105_Text_FosterDefeated:
	.string "{JPN}いわのこと ばかり かんがえて\n"
	.string "{JPN}ポケモン よわいまま だったか……$"

Route105_Text_FosterPostBattle:
	.string "{JPN}すてきな いわ だったら\n"
	.string "{JPN}なんじかん みていても あきないよ……$"

Route105_Text_LuisIntro:
	.string "{JPN}よかった! こどもが\n"
	.string "{JPN}おぼれているのかと しんぱい したよ!\p"
	.string "{JPN}だいじょうぶ そうだから しょうぶ だな!$"

Route105_Text_LuisDefeated:
	.string "{JPN}ゴボゴボ……$"

Route105_Text_LuisPostBattle:
	.string "{JPN}すなはまに むかって かたてを ふるのが\n"
	.string "{JPN}おぼれたときの サインだぜ!$"

Route105_Text_DominikIntro:
	.string "{JPN}あおい うみで およいでいると\n"
	.string "{JPN}さいこうの きぶん だな!$"

Route105_Text_DominikDefeated:
	.string "{JPN}まけた……\n"
	.string "{JPN}ブルーな きぶん……$"

Route105_Text_DominikPostBattle:
	.string "{JPN}うみが あおい りゆう!?\p"
	.string "{JPN}カイナの はくぶつかんで きいたけど\n"
	.string "{JPN}そんなの わすれちまったよ!$"

Route105_Text_BeverlyIntro:
	.string "{JPN}みずに はいると からだが かるくなるわね\n"
	.string "{JPN}なんだか スリムに なったみたい!$"

Route105_Text_BeverlyDefeated:
	.string "{JPN}ぷかぷか……$"

Route105_Text_PostBattle:
	.string "{JPN}みずの なかでは たいじゅうが\n"
	.string "{JPN}10ぶんの1 くらいに なるのよ\p"
	.string "{JPN}と すると いま わたしは……\n"
	.string "{JPN}いけない! たいじゅうが バレちゃうわ!$"

Route105_Text_ImaniIntro:
	.string "{JPN}あおい そら……\n"
	.string "{JPN}ひろい うみ……\l"
	.string "{JPN}のどか よねー……$"

Route105_Text_ImaniDefeated:
	.string "{JPN}なごんでいる うちに\n"
	.string "{JPN}まけちゃったわーっ!$"

Route105_Text_ImaniPostBattle:
	.string "{JPN}あたしと いると なごむって いわれたいの\n"
	.string "{JPN}うふふふふ!$"

Route105_Text_AndresIntro:
	.string "{JPN}うみに こそ なにかが あると\n"
	.string "{JPN}かくしんが ある!$"

Route105_Text_AndresDefeated:
	.string "{JPN}うん…… わし\n"
	.string "{JPN}しょうぶは よわいんだよ$"

Route105_Text_AndresPostBattle:
	.string "{JPN}せかいじゅうの うみには\n"
	.string "{JPN}まだまだ ひみつが あるはずだ!\l"
	.string "{JPN}ぜんぶ さがしまくるぞ!$"

Route105_Text_AndresRegister:
	.string "{JPN}ん? こんな よわい わしでも\n"
	.string "{JPN}ポケナビ とうろくして くれるのか?$"

Route105_Text_AndresRematchIntro:
	.string "{JPN}しょうぶは よわいと いっているのに……\n"
	.string "{JPN}わし なんかで いいのか?$"

Route105_Text_AndresRematchDefeated:
	.string "{JPN}うん…… やっぱり かてないな$"

Route105_Text_AndresRematchPostBattle:
	.string "{JPN}しょうぶは よわいが\n"
	.string "{JPN}たんきゅうしんは きみにも まけん!\l"
	.string "{JPN}せかいじゅうの うみを たび するぞ!$"

Route105_Text_JosueIntro:
	.string "{JPN}なれない およぎで つかれたー\n"
	.string "{JPN}きばらしに ポケモンしょうぶ じゃい!$"

Route105_Text_JosueDefeated:
	.string "{JPN}うみで たたかった から まけたんだ$"

Route105_Text_JosuePostBattle:
	.string "{JPN}やっぱりさ おれには\n"
	.string "{JPN}うみより そらが にあってるんだよ$"

Route106_Text_ElliotIntro:
	.string "{JPN}うみづりと かわづり\n"
	.string "{JPN}キミは どっちが すき?$"

Route106_Text_ElliotDefeated:
	.string "{JPN}まるで うみづりの ように\n"
	.string "{JPN}ごうかいに まけたぞーっ!$"

Route106_Text_ElliotPostBattle:
	.string "{JPN}うみでも かわでも つりは サイコーだ!\n"
	.string "{JPN}キミも そう おもうだろ!?$"

Route106_Text_ElliotRegister:
	.string "{JPN}つりも いいけど しょうぶも いいな!\n"
	.string "{JPN}キミ よかったら また たのむよ!$"

Route106_Text_ElliotRematchIntro:
	.string "{JPN}ポケモン つりまくったからね\n"
	.string "{JPN}すごい しょうぶを してみせるぞー!$"

Route106_Text_ElliotRematchDefeated:
	.string "{JPN}また ごうかいに まけたぞーっ!$"

Route106_Text_ElliotRematchPostBattle:
	.string "{JPN}かっても まけても ポケモンは サイコーだ!\n"
	.string "{JPN}キミも そう おもうだろ!?$"

Route106_Text_NedIntro:
	.string "{JPN}トイレに いきたくなったとき\n"
	.string "{JPN}みんなは どうしてるんだろう……?\p"
	.string "{JPN}トイレに いっている あいだに\n"
	.string "{JPN}もし おおものが かかったらと おもうと……$"

Route106_Text_NedDefeated:
	.string "{JPN}トイレを がまん してたから\n"
	.string "{JPN}まけたんだよ きっと……$"

Route106_Text_NedPostBattle:
	.string "{JPN}ああっ!\n"
	.string "{JPN}おおものが つれそうな よかん……!$"

Route106_Text_DouglasIntro:
	.string "{JPN}はっはっはっ!\n"
	.string "{JPN}りくでは はやく はしれないが\l"
	.string "{JPN}みずの なかなら まけないぞ!$"

Route106_Text_DouglasDefeated:
	.string "{JPN}まいりましたーっ!$"

Route106_Text_DouglasPostBattle:
	.string "{JPN}すいえいの きょうそうなら まけないのに……$"

Route106_Text_KylaIntro:
	.string "{JPN}うみは わたしの にわ\n"
	.string "{JPN}こども だからって てかげん しないわよ!$"

Route106_Text_KylaDefeated:
	.string "{JPN}ひょっとして\n"
	.string "{JPN}てかげん してないよね?$"

Route106_Text_KylaPostBattle:
	.string "{JPN}なみに ゆられて ただようのが だいすき\n"
	.string "{JPN}あなたも やってみない?$"

Route107_Text_DarrinIntro:
	.string "{JPN}むにゃむにゃ……\p"
	.string "{JPN}なみに ゆられてたら きもちよくなって\n"
	.string "{JPN}うっかり ねてしまった!$"

Route107_Text_DarrinDefeated:
	.string "{JPN}あはは まけた……\n"
	.string "{JPN}また ねますか……$"

Route107_Text_DarrinPostBattle:
	.string "{JPN}うみに うかんで なみに ゆられてると\n"
	.string "{JPN}ふかふかの ベッドで ねてる みたいだよ!$"

Route107_Text_TonyIntro:
	.string "{JPN}うみは オレの にわ みたいな もの!\n"
	.string "{JPN}しょうぶ しようぜ!$"

Route107_Text_TonyDefeated:
	.string "{JPN}ホームグラウンドで まけた……\n"
	.string "{JPN}ショック!$"

Route107_Text_TonyPostBattle:
	.string "{JPN}おおきな ユメを いっぱい つめてー\n"
	.string "{JPN}でっかい うみを ひとおよぎー\p"
	.string "{JPN}さぁて まだまだ およぐぞー!$"

Route107_Text_TonyRegister:
	.string "{JPN}ショックを うけたオレを\n"
	.string "{JPN}きみが わすれない ために……!$"

Route107_Text_TonyRematchIntro:
	.string "{JPN}でっかい うみを およいでいたら\n"
	.string "{JPN}ポケモンが すっごく つよくなったぞー!$"

Route107_Text_TonyRematchDefeated:
	.string "{JPN}ショック!!\p"
	.string "{JPN}ポケモンは つよくなったが\n"
	.string "{JPN}トレーナーの おれが よわいまま!?$"

Route107_Text_TonyRematchPostBattle:
	.string "{JPN}たたかいの なかで おぼえたことが\n"
	.string "{JPN}トレーナーとしての つよさに つながる!\l"
	.string "{JPN}でっかい うみが そう いっていたぞー!$"

Route107_Text_DeniseIntro:
	.string "{JPN}ムロタウン っていう\n"
	.string "{JPN}ちいさな まちを しってる?$"

Route107_Text_DeniseDefeated:
	.string "{JPN}ヤダ もーっ!$"

Route107_Text_DenisePostBattle:
	.string "{JPN}ムロタウンの しゅうかいじょで\n"
	.string "{JPN}ふしぎな ことばが はやって いるのよ!$"

Route107_Text_BethIntro:
	.string "{JPN}わたしと しょうぶが したいの?\n"
	.string "{JPN}いいわ! あいてに なって あげる!$"

Route107_Text_BethDefeated:
	.string "{JPN}わたしじゃ あいてに ならなかったわ!$"

Route107_Text_BethPostBattle:
	.string "{JPN}あなた まだまだ つよく なりそうね\n"
	.string "{JPN}わたしも がんばろうっと!$"

Route107_Text_LisaIntro:
	.string "{JPN}ユミ『あたしたち きょうだい ふたりで\n"
	.string "{JPN}しょうぶを させてもらうわ!$"

Route107_Text_LisaDefeated:
	.string "{JPN}ユミ『すごいわ\n"
	.string "{JPN}つよさの レベルが ちがうのね$"

Route107_Text_LisaPostBattle:
	.string "{JPN}ユミ『あなたは いっしょに\n"
	.string "{JPN}うみに あそびに いくような\l"
	.string "{JPN}おともだち いるのかしら?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "{JPN}ユミ『アタシたちと たたかうなら\n"
	.string "{JPN}ポケモン もっと つれてきなさいな$"

Route107_Text_RayIntro:
	.string "{JPN}シン『いつも きょうだいで\n"
	.string "{JPN}ポケモンしょうぶ してるんだ!\p"
	.string "{JPN}……いっつも おれが まけるけど\n"
	.string "{JPN}2たい2なら きみに かてるよ!$"

Route107_Text_RayDefeated:
	.string "{JPN}シン『ひゃー\n"
	.string "{JPN}つよさの レベルが ちがいすぎるや$"

Route107_Text_RayPostBattle:
	.string "{JPN}シン『おれの ポケモン\n"
	.string "{JPN}ねえちゃんから もらって そだてた\l"
	.string "{JPN}だいじな あいぼう なんだぜ!$"

Route107_Text_RayNotEnoughPokemon:
	.string "{JPN}シン『オレらと たたかうなら\n"
	.string "{JPN}もっと ポケモン つれてきてよ!$"

Route107_Text_CamronIntro:
	.string "{JPN}トライアスロンの とちゅう だが\n"
	.string "{JPN}ぜんぜん つかれて いないぜ!$"

Route107_Text_CamronDefeated:
	.string "{JPN}いまので つかれて しまった$"

Route107_Text_CamronPostBattle:
	.string "{JPN}こ このあと まだ\n"
	.string "{JPN}すいえい ランニングが のこっているぜ\l"
	.string "{JPN}だいじょうぶか おれ……?$"

Route108_Text_JeromeIntro:
	.string "{JPN}オレの ユメは せかいに ある\n"
	.string "{JPN}7つのうみ すべてで およぐこと!$"

Route108_Text_JeromeDefeated:
	.string "{JPN}これじゃ\n"
	.string "{JPN}7つのうみ すべてで およげない……$"

Route108_Text_JeromePostBattle:
	.string "{JPN}うみの ポケモンと あそぶことも\n"
	.string "{JPN}およいでいる ときの たのしみだね!$"

Route108_Text_MatthewIntro:
	.string "{JPN}なあ キミ!\n"
	.string "{JPN}キミも すてられた ふねに いくのかい?$"

Route108_Text_MatthewDefeated:
	.string "{JPN}ああ ぼくが しずむ……\n"
	.string "{JPN}ぶくぶく……$"

Route108_Text_MatthewPostBattle:
	.string "{JPN}すてられぶねの なかに\n"
	.string "{JPN}はいっていく やつらが いるんだよ!$"

Route108_Text_TaraIntro:
	.string "{JPN}ウソつきな カレに いわれたのよ\n"
	.string "{JPN}ビキニが にあってて カワイイって……$"

Route108_Text_TaraDefeated:
	.string "{JPN}いやん まけたわーっ!$"

Route108_Text_TaraPostBattle:
	.string "{JPN}ウソでも いいから カワイイって いわれたい\n"
	.string "{JPN}ふくざつな おんなごころ……$"

Route108_Text_MissyIntro:
	.string "{JPN}うみって だいすき!\n"
	.string "{JPN}およいでいれば イヤなことも わすれるわ!$"

Route108_Text_MissyDefeated:
	.string "{JPN}しょうぶに まけると\n"
	.string "{JPN}ストレスが たまるーっ!$"

Route108_Text_MissyPostBattle:
	.string "{JPN}ストレスは およいで はっさん!\n"
	.string "{JPN}けんこうてき よねー!$"

Route108_Text_CoryIntro:
	.string "{JPN}みずポケモンが だいすきだー!\n"
	.string "{JPN}ほかの ポケモンも だいすきだー!$"

Route108_Text_CoryDefeated:
	.string "{JPN}わー まけたー!\n"
	.string "{JPN}わーわー!$"

Route108_Text_CoryPostBattle:
	.string "{JPN}おおごえで さけべば\n"
	.string "{JPN}スッキリ するなあーっ!$"

Route108_Text_CoryRegister:
	.string "{JPN}つよい トレーナーも だいすきだー!\n"
	.string "{JPN}ポケナビの とうろくを してくれー!$"

Route108_Text_CoryRematchIntro:
	.string "{JPN}かっても まけても\n"
	.string "{JPN}うみ での しょうぶが だいすきだー!$"

Route108_Text_CoryRematchDefeated:
	.string "{JPN}わーっ また まけた!\n"
	.string "{JPN}わー わー!$"

Route108_Text_CoryRematchPostBattle:
	.string "{JPN}きみも いきづまった ときは\n"
	.string "{JPN}なにかを うみに むかって さけべーっ!$"

Route108_Text_CarolinaIntro:
	.string "{JPN}じまんの ポケモンたちで\n"
	.string "{JPN}スピーディに たたかうわよ!$"

Route108_Text_CarolinaDefeated:
	.string "{JPN}あら かわいくないわね!$"

Route108_Text_CarolinaPostBattle:
	.string "{JPN}せっかくの うみ だし\n"
	.string "{JPN}ピンクの フリフリの ビキニも\l"
	.string "{JPN}ちょっと きてみたい……$"

Route109_Text_DavidIntro:
	.string "{JPN}うりゃーっ!!\n"
	.string "{JPN}みごとに われた ふっきんを みろーっ!!$"

Route109_Text_DavidDefeated:
	.string "{JPN}うりゃーっ!!\n"
	.string "{JPN}まけたーっ!!$"

Route109_Text_DavidPostBattle:
	.string "{JPN}うりゃーっ!!\p"
	.string "{JPN}ふっきんと ポケモンの しょうぶは\n"
	.string "{JPN}かんけい ないぞーっ!!$"

Route109_Text_AliceIntro:
	.string "{JPN}ひやけ たいさく\n"
	.string "{JPN}あなたは してる?$"

Route109_Text_AliceDefeated:
	.string "{JPN}あちちちちっ!$"

Route109_Text_AlicePostBattle:
	.string "{JPN}ほっぺの あたりが いちばん\n"
	.string "{JPN}ひやけ しやすい ばしょ なのよ!$"

Route109_Text_HueyIntro:
	.string "{JPN}せかいじゅうの みなとを おとずれたが\n"
	.string "{JPN}カイナは さいこーの みなとまち だぜ!$"

Route109_Text_HueyDefeated:
	.string "{JPN}あんた さいこー だぜ……$"

Route109_Text_HueyPostBattle:
	.string "{JPN}さいこーの みなとまちには\n"
	.string "{JPN}さいこーの トレーナーが いたぜ……$"

Route109_Text_EdmondIntro:
	.string "{JPN}ううう……\n"
	.string "{JPN}しょうぶ するの? オレと?$"

Route109_Text_EdmondDefeated:
	.string "{JPN}げろげろ……$"

Route109_Text_EdmondPostBattle:
	.string "{JPN}いつもは もっと つよいんだぞ!\n"
	.string "{JPN}ふなよいで ちょうしが わるいだけだ!\p"
	.string "{JPN}ふなのり だけど……$"

Route109_Text_RickyIntro:
	.string "{JPN}のどが かわいたよ……\n"
	.string "{JPN}うみのいえで サイコソーダ のみたいな……$"

Route109_Text_RickyDefeated:
	.string "{JPN}うーん……$"

Route109_Text_RickyPostBattle:
	.string "{JPN}おなかも へってきた……\n"
	.string "{JPN}うきわが おっきな ドーナッツに みえるよ$"

Route109_Text_RickyRegister:
	.string "{JPN}こんど のどが かわいて ないときに\n"
	.string "{JPN}もういっかい しょうぶ してくれる?$"

Route109_Text_RickyRematchIntro:
	.string "{JPN}おなか へってるけど\n"
	.string "{JPN}しょうぶ するなら げんき だよ!$"

Route109_Text_RickyRematchDefeated:
	.string "{JPN}まけた……\n"
	.string "{JPN}おなかが へってるからだ$"

Route109_Text_RickyRematchPostBattle:
	.string "{JPN}すなはまで たべると\n"
	.string "{JPN}なんでも おいしく おもえるよね$"

Route109_Text_LolaIntro:
	.string "{JPN}ビーチパラソルって\n"
	.string "{JPN}おおきな おはな みたいよねー!$"

Route109_Text_LolaDefeated:
	.string "{JPN}ママーっ!$"

Route109_Text_LolaPostBattle:
	.string "{JPN}おそらの うえから すなはまを みたら\n"
	.string "{JPN}おはなばたけ みたいに みえるのよ!$"

Route109_Text_LolaRegister:
	.string "{JPN}わたし だったら\n"
	.string "{JPN}まいにち ここに きているよ!$"

Route109_Text_LolaRematchIntro:
	.string "{JPN}もう あなたには まけません!\n"
	.string "{JPN}そのために うきわ してるんだから!$"

Route109_Text_LolaRematchDefeated:
	.string "{JPN}ママーっ!$"

Route109_Text_LolaRematchPostBattle:
	.string "{JPN}うきわ もってると あたしと ポケモンの\n"
	.string "{JPN}かわいさが ぐぐーんと アップするの!$"

Route109_Text_AustinaIntro:
	.string "{JPN}うきわが ないと およげないけど\n"
	.string "{JPN}ポケモンなら だれにも まけないよ!$"

Route109_Text_AustinaDefeated:
	.string "{JPN}うきわが あるから まけちゃったのかな?$"

Route109_Text_AustinaPostBattle:
	.string "{JPN}あたしの うきわ\n"
	.string "{JPN}オシャレだから てばなせないの$"

Route109_Text_GwenIntro:
	.string "{JPN}そこの トレーナーさん\n"
	.string "{JPN}あたしと たたかう でちゅ!$"

Route109_Text_GwenDefeated:
	.string "{JPN}つよいでちゅね……$"

Route109_Text_GwenPostBattle:
	.string "{JPN}どうしたら そんなに\n"
	.string "{JPN}つよくなれる でちゅか……?$"

Route109_Text_CarterIntro:
	.string "{JPN}わはは!\n"
	.string "{JPN}おじさん おおもの つっちゃうぞ!$"

Route109_Text_CarterDefeated:
	.string "{JPN}おじさん まけちゃったな……$"

Route109_Text_CarterPostBattle:
	.string "{JPN}たしかに きみは おおもの だな!\n"
	.string "{JPN}いや きっと おおものに なるぞ!$"

Route109_Text_PaulIntro:
	.string "{JPN}リキ『やあ こまったなあ\p"
	.string "{JPN}ふたりっきりの じかん\n"
	.string "{JPN}じゃま して ほしくないなあ$"

Route109_Text_PaulDefeated:
	.string "{JPN}リキ『やあ まいったな……$"

Route109_Text_PaulPostBattle:
	.string "{JPN}リキ『やあ ぼくたちが ここに いること\n"
	.string "{JPN}だれにも いわないで くれよ!\l"
	.string "{JPN}ふたりっきりの せかい なんだからさ!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "{JPN}リキ『ぼくたち ラブラブ だからね\n"
	.string "{JPN}ぼくたちの ポケモンも\l"
	.string "{JPN}2ひき いっしょに たたかわせるんだ!$"

Route109_Text_MelIntro:
	.string "{JPN}シキ『あたしたちが ラブラブだから\n"
	.string "{JPN}ホウエンは あっついのよお!$"

Route109_Text_MelDefeated:
	.string "{JPN}シキ『あたしの せいで まけたんだわ……\n"
	.string "{JPN}こんなんじゃ リキに きらわれちゃう!$"

Route109_Text_MelPostBattle:
	.string "{JPN}シキ『ねえ リキ\n"
	.string "{JPN}あたしのこと おこってない?\l"
	.string "{JPN}おこっちゃ いやよ$"

Route109_Text_MelNotEnoughPokemon:
	.string "{JPN}シキ『あたしたち ラブラブ だからね\n"
	.string "{JPN}あたしたちの ポケモンも\l"
	.string "{JPN}2ひき いっしょに たたかわせるんだ!$"

Route109_Text_ChandlerIntro:
	.string "{JPN}じゃーん!\n"
	.string "{JPN}ボクの うきわ まるいでしょーっ!$"

Route109_Text_ChandlerDefeated:
	.string "{JPN}あーあ! ざんねん$"

Route109_Text_ChandlerPostBattle:
	.string "{JPN}せっかく まるい うきわを\n"
	.string "{JPN}みせて あげたのにさ$"

Route109_Text_HaileyIntro:
	.string "{JPN}およげない から\n"
	.string "{JPN}およぐ ふりを してるの!$"

Route109_Text_HaileyDefeated:
	.string "{JPN}やっぱね!\n"
	.string "{JPN}かてないって おもってたんだ$"

Route109_Text_HaileyPostBattle:
	.string "{JPN}およげるように なったら\n"
	.string "{JPN}ポケモンも つよく なると おもう!$"

Route109_Text_ElijahIntro:
	.string "{JPN}こうはの おれさまには\n"
	.string "{JPN}こんな ポケモンが おにあいだぜ!$"

Route109_Text_ElijahDefeated:
	.string "{JPN}まけても カッコ いいだろ?$"

Route109_Text_ElijahPostBattle:
	.string "{JPN}こうはの おれさまには\n"
	.string "{JPN}みなとまちが おにあいだぜ!\l"
	.string "{JPN}カイナシティに いってくるか$"

Route110_Text_JacobIntro:
	.string "{JPN}おっと あぶない!\n"
	.string "{JPN}バイク レースに なれてない ようだな!$"

Route110_Text_JacobDefeated:
	.string "{JPN}キキーッ!\n"
	.string "{JPN}ブレーキが こしょうした!$"

Route110_Text_JacobPostBattle:
	.string "{JPN}タイヤの パンクや\n"
	.string "{JPN}ブレーキの こしょうは ケガのもと\l"
	.string "{JPN}ちゃんと てんけん しないとな$"

Route110_Text_AnthonyIntro:
	.string "{JPN}ヘイ ユー!\n"
	.string "{JPN}ワタシの スピードに ついてこれるかな!?$"

Route110_Text_AnthonyDefeated:
	.string "{JPN}オー マイ ガッ!$"

Route110_Text_AnthonyPostBattle:
	.string "{JPN}スピードだけじゃ ポケモンしょうぶ\n"
	.string "{JPN}かてませーん! ハンセイしまーす!$"

Route110_Text_BenjaminIntro:
	.string "{JPN}じてんしゃの スピード でても\n"
	.string "{JPN}あせっちゃ いけないよ!$"

Route110_Text_BenjaminDefeated:
	.string "{JPN}ポケモンしょうぶも\n"
	.string "{JPN}あせっちゃ いけないな……$"

Route110_Text_BenjaminPostBattle:
	.string "{JPN}あせらず のんびり いこうよ\n"
	.string "{JPN}じかんは たっぷり あるからね!$"

Route110_Text_BenjaminRegister:
	.string "{JPN}あせらずに また がんばるか!\n"
	.string "{JPN}よかったらさ れんらく くれよな$"

Route110_Text_BenjaminRematchIntro:
	.string "{JPN}おっ! スピード だしすぎ じゃない?\n"
	.string "{JPN}ちょっと のんびり しょうぶ しようよ!$"

Route110_Text_BenjaminRematchDefeated:
	.string "{JPN}べつに あせってないけど\n"
	.string "{JPN}なぜだか まけて しまうな……$"

Route110_Text_BenjaminRematchPostBattle:
	.string "{JPN}あせらず のんびり いこうよ\n"
	.string "{JPN}じかんは たっぷり あるからね!$"

Route110_Text_AbigailIntro:
	.string "{JPN}トライアスロンは ハードな スポーツ\n"
	.string "{JPN}すいえい じてんしゃ マラソンの\l"
	.string "{JPN}3しゅもくを こなすのよ!$"

Route110_Text_AbigailDefeated:
	.string "{JPN}ポケモン しょうぶも ハードだわ!$"

Route110_Text_AbigailPostBattle:
	.string "{JPN}つかれたから ひとやすみ\n"
	.string "{JPN}きゅうけいは たいせつ なのよ$"

Route110_Text_AbigailRegister:
	.string "{JPN}あなた きにいったわ!\n"
	.string "{JPN}また サイクリングロードで たたかいましょ$"

Route110_Text_AbigailRematchIntro:
	.string "{JPN}じてんしゃに のりながら\n"
	.string "{JPN}ポケモンしょうぶ ってのも いいものよね!$"

Route110_Text_AbigailRematchDefeated:
	.string "{JPN}うわー\n"
	.string "{JPN}どうして そんなに つよいの?$"

Route110_Text_AbigailRematchPostBattle:
	.string "{JPN}ひょっとして きろくに\n"
	.string "{JPN}ちょうせん していたのかしら?\p"
	.string "{JPN}だったら ジャマして ゴメンねー$"

Route110_Text_JasmineIntro:
	.string "{JPN}じてんしゃを こぎつづけて\n"
	.string "{JPN}ふとももが パンパンに なっちゃった$"

Route110_Text_JasmineDefeated:
	.string "{JPN}きんにくつうが しんぱいだわ……$"

Route110_Text_JasminePostBattle:
	.string "{JPN}ジムの バッチを もってるの?\n"
	.string "{JPN}どうりで つよい はずだわ!$"

Route110_Text_EdwardIntro:
	.string "{JPN}おまえの さくせんは すべて みえた!\n"
	.string "{JPN}わたしが まけるはず ない!$"

Route110_Text_EdwardDefeated:
	.string "{JPN}じぶんの はいぼくは みえなかった……!$"

Route110_Text_EdwardPostBattle:
	.string "{JPN}おまえの みらいが みえる……\p"
	.string "{JPN}ふうむ……\n"
	.string "{JPN}あかるい ひかりが みえるぞ……!$"

Route110_Text_JaclynIntro:
	.string "{JPN}おほほほほっ!\n"
	.string "{JPN}わたくしの ミラクルを みせてあげるわ!$"

Route110_Text_JaclynDefeated:
	.string "{JPN}ミラクルに まけたーっ!$"

Route110_Text_JaclynPostBattle:
	.string "{JPN}わたくしに かったことが ミラクル……\n"
	.string "{JPN}そう きせき なのよ!\l"
	.string "{JPN}いつでも かてるなんて おもわないことね!$"

Route110_Text_EdwinIntro:
	.string "{JPN}キミの ポケモン みせてくれない?\n"
	.string "{JPN}ひとめで いいから おねがい!$"

Route110_Text_EdwinDefeated:
	.string "{JPN}コンプリート したかった……!$"

Route110_Text_EdwinPostBattle:
	.string "{JPN}みたことのない ポケモンに であうと\n"
	.string "{JPN}ボクの コレクターだましいが もえるなぁ!$"

Route110_Text_EdwinRegister:
	.string "{JPN}ぼく エントリーコールも\n"
	.string "{JPN}たくさん あつめたいんだよねぇ$"

Route110_Text_EdwinRematchIntro:
	.string "{JPN}ねえ キミ\n"
	.string "{JPN}あたらしい ポケモン つかまえた?\p"
	.string "{JPN}よかったら ポケモン みせてくれない?\n"
	.string "{JPN}ひとめで いいから おねがい!$"

Route110_Text_EdwinRematchDefeated:
	.string "{JPN}キミの ポケモン\n"
	.string "{JPN}うらやましいな……$"

Route110_Text_EdwinRematchPostBattle:
	.string "{JPN}ああ! とにかく めずらしい ポケモン\n"
	.string "{JPN}ぜんぶ ボクの ものに したいよー!$"

Route110_Text_DaleIntro:
	.string "{JPN}ええーい!\n"
	.string "{JPN}うしろから はなしかけるなー!$"

Route110_Text_DaleDefeated:
	.string "{JPN}まけたっ!\n"
	.string "{JPN}くやしいっ!!$"

Route110_Text_DalePostBattle:
	.string "{JPN}すいめんに うかぶ うきを じっと みる……\n"
	.string "{JPN}しゅうちゅうりょくが たいせつ なんだ$"

Route110_Text_IsabelIntro:
	.string "{JPN}おほほ! だいじな ポケモンを\n"
	.string "{JPN}じまん するためなら どこにでも いきますわ$"

Route110_Text_IsabelDefeated:
	.string "{JPN}あら まあ イヤですわ$"

Route110_Text_IsabelPostBattle:
	.string "{JPN}しょうぶ させるよりも\n"
	.string "{JPN}だいすきクラブで じまんして こようかしら$"

Route110_Text_IsabelRegister:
	.string "{JPN}わたしの じまんは こんなんじゃ\n"
	.string "{JPN}おわりませんわ!\l"
	.string "{JPN}なんかいも つきあって もらいますわよ$"

Route110_Text_IsabelRematchIntro:
	.string "{JPN}おほほ! だいじな ポケモンなら\n"
	.string "{JPN}なんどだって じまん しますわ!$"

Route110_Text_IsabelRematchDefeated:
	.string "{JPN}あら まあ イヤですわ$"

Route110_Text_IsabelRematchPostBattle:
	.string "{JPN}ポケモンじまんも やめられないけど\n"
	.string "{JPN}しょうぶ するのも すきなのよ!$"

Route110_Text_TimmyIntro:
	.string "{JPN}この あたりの くさむらで\n"
	.string "{JPN}かっこいい ポケモン みつけたんだぜ!$"

Route110_Text_TimmyDefeated:
	.string "{JPN}かっこいい だけじゃ だめかぁ……$"

Route110_Text_TimmyPostBattle:
	.string "{JPN}つかまえた ばかりの ポケモンじゃ\n"
	.string "{JPN}うまく たたかえないや!$"

Route110_Text_AlyssaIntro:
	.string "{JPN}サイクリングロード から おちちゃった!\n"
	.string "{JPN}はずかしい…… しょうぶで まぎらわすわ!$"

Route110_Text_AlyssaDefeated:
	.string "{JPN}ひぇ まけて しまったわ!$"

Route110_Text_AlyssaPostBattle:
	.string "{JPN}おっこちるは まけるはで\n"
	.string "{JPN}はずかし すぎます! わたし!$"

Route110_Text_JosephIntro:
	.string "{JPN}よぉぉし とばして いくぜえェ!\n"
	.string "{JPN}ノリの わるいやつは おいてくぜェ!$"

Route110_Text_JosephDefeated:
	.string "{JPN}ノリが いいね あんた……$"

Route110_Text_JosephPostBattle:
	.string "{JPN}こんなこと では へこたれないぜェ!\n"
	.string "{JPN}おれは まけて またひとつ\l"
	.string "{JPN}いいオトコに なったぜェ!$"

Route110_Text_KalebIntro:
	.string "{JPN}かわいい ポケモンたちが\n"
	.string "{JPN}たすけあう ところは かわいいぞーーっ!$"

Route110_Text_KalebDefeated:
	.string "{JPN}きみは ちも なみだも ないんだな$"

Route110_Text_KalebPostBattle:
	.string "{JPN}おう よしよし\n"
	.string "{JPN}よくやったよ かわいい おまえたち$"

Route111_Text_DrewIntro:
	.string "{JPN}Oh, hey! Those GO-GOGGLES suit you.\n"
	.string "{JPN}But I think they look better on me.\p"
	.string "{JPN}Let's decide who they look better on\n"
	.string "{JPN}with a battle!$"

Route111_Text_DrewDefeat:
	.string "{JPN}I couldn't see what was happening at\n"
	.string "{JPN}my sides because of the GO-GOGGLES.$"

Route111_Text_DrewPostBattle:
	.string "{JPN}The GO-GOGGLES make it possible to\n"
	.string "{JPN}get through sandstorms.\l"
	.string "{JPN}That makes me happy!$"

Route111_Text_HeidiIntro:
	.string "{JPN}I'm having a picnic in the desert.\p"
	.string "{JPN}You can always find a TRAINER,\n"
	.string "{JPN}so I can enjoy a battle here, too!$"

Route111_Text_HeidiDefeat:
	.string "{JPN}Ohhh! You're mean!$"

Route111_Text_HeidiPostBattle:
	.string "{JPN}When you're battling in a sandstorm,\n"
	.string "{JPN}watch out for your POKEMON's HP.\p"
	.string "{JPN}It can faint if you don't keep\n"
	.string "{JPN}an eye on it!$"

Route111_Text_BeauIntro:
	.string "{JPN}Wearing these GO-GOGGLES makes me\n"
	.string "{JPN}feel like a superhero.\l"
	.string "{JPN}Right now, nobody can beat me!$"

Route111_Text_BeauDefeat:
	.string "{JPN}I can't win on spirit alone...$"

Route111_Text_BeauPostBattle:
	.string "{JPN}I'm going to be a real hero one day.\n"
	.string "{JPN}I'm going to work harder to make me\l"
	.string "{JPN}and my POKEMON stronger.$"

Route111_Text_BeckyIntro:
	.string "{JPN}I heard there are fossils to be found\n"
	.string "{JPN}in the desert. Where could they be?$"

Route111_Text_BeckyDefeat:
	.string "{JPN}I came up short...$"

Route111_Text_BeckyPostBattle:
	.string "{JPN}If they can find fossils in the desert,\n"
	.string "{JPN}it must have been a sea before.$"

Route111_Text_DustyIntro:
	.string "{JPN}For thirty years I have searched for\n"
	.string "{JPN}ancient ruins!\l"
	.string "{JPN}I am to be challenged?$"

Route111_Text_DustyDefeat:
	.string "{JPN}While I have searched for ruins,\n"
	.string "{JPN}I've not searched for strong POKEMON.$"

Route111_Text_DustyPostBattle:
	.string "{JPN}For thirty years I have searched for\n"
	.string "{JPN}ancient ruins!\p"
	.string "{JPN}No, wait, was that forty years?\n"
	.string "{JPN}Which was it now?$"

Route111_Text_DustyRegister:
	.string "{JPN}I haven't been searching for any\n"
	.string "{JPN}tough POKEMON.\p"
	.string "{JPN}But, for some reason, I sure do like\n"
	.string "{JPN}POKeNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "{JPN}For thirty years I have searched for\n"
	.string "{JPN}ancient ruins!\p"
	.string "{JPN}No, wait, was that forty years?\n"
	.string "{JPN}Anyway, am I to be challenged?$"

Route111_Text_DustyRematchDefeat:
	.string "{JPN}I've found no ruins, nor have I found\n"
	.string "{JPN}any strong POKEMON...$"

Route111_Text_DustyPostRematch:
	.string "{JPN}For thirty years I have searched for\n"
	.string "{JPN}ancient ruins!\p"
	.string "{JPN}No, wait, was that forty years\n"
	.string "{JPN}I've searched?\p"
	.string "{JPN}Hmm... It could even be fifty...\n"
	.string "{JPN}How long have I been at this?$"

Route111_Text_TravisIntro:
	.string "{JPN}I'm full of pep!\n"
	.string "{JPN}And my POKEMON is peppy, too!$"

Route111_Text_TravisDefeat:
	.string "{JPN}My POKEMON lost its pep...$"

Route111_Text_TravisPostBattle:
	.string "{JPN}When I see a TRAINER with a lot of pep,\n"
	.string "{JPN}I can't help looking.$"

Route111_Text_IreneIntro:
	.string "{JPN}I don't know where you're going,\n"
	.string "{JPN}but would you like to battle?$"

Route111_Text_IreneDefeat:
	.string "{JPN}Oh, you're disgustingly good!$"

Route111_Text_IrenePostBattle:
	.string "{JPN}I'm thinking that I should go to\n"
	.string "{JPN}MT. CHIMNEY, but the view around\l"
	.string "{JPN}here is very nice, too.$"

Route111_Text_DaisukeIntro:
	.string "{JPN}To train myself, I challenge all\n"
	.string "{JPN}whom I meet!$"

Route111_Text_DaisukeDefeat:
	.string "{JPN}Uncle! I give up!$"

Route111_Text_DaisukePostBattle:
	.string "{JPN}All I can do is keep training until\n"
	.string "{JPN}I can defeat strong TRAINERS such\l"
	.string "{JPN}as yourself.$"

Route111_Text_WiltonIntro:
	.string "{JPN}Show me how much you've toughened\n"
	.string "{JPN}your POKEMON.$"

Route111_Text_WiltonDefeat:
	.string "{JPN}I see, you've toughened them\n"
	.string "{JPN}considerably.$"

Route111_Text_WiltonPostBattle:
	.string "{JPN}POKEMON and TRAINERS learn much\n"
	.string "{JPN}through battling.\p"
	.string "{JPN}What's important is to never give up\n"
	.string "{JPN}even if you lose.$"

Route111_Text_WiltonRegister:
	.string "{JPN}There is much to be learned from\n"
	.string "{JPN}your training style.\p"
	.string "{JPN}I request a rematch if it\n"
	.string "{JPN}behooves you.$"

Route111_Text_WiltonRematchIntro:
	.string "{JPN}We're training here to elevate our\n"
	.string "{JPN}game to the next level.\l"
	.string "{JPN}Stay and train with us!$"

Route111_Text_WiltonRematchDefeat:
	.string "{JPN}Ooh, you're decent!$"

Route111_Text_WiltonPostRematch:
	.string "{JPN}Since you're that strong, you should\n"
	.string "{JPN}aim for the POKEMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "{JPN}Oh, your POKEMON look like serious\n"
	.string "{JPN}actors.\l"
	.string "{JPN}I have to ask you for an engagement.$"

Route111_Text_BrookeDefeat:
	.string "{JPN}They didn't just look strong,\n"
	.string "{JPN}they are strong!$"

Route111_Text_BrookePostBattle:
	.string "{JPN}I thought I was raising my POKEMON\n"
	.string "{JPN}diligently, but, oh no, there is still\l"
	.string "{JPN}much to be done.$"

Route111_Text_BrookeRegister:
	.string "{JPN}I wish I could become friends with\n"
	.string "{JPN}more strong people like you!$"

Route111_Text_BrookeRematchIntro:
	.string "{JPN}You can make POKEMON stronger or\n"
	.string "{JPN}weaker depending on the moves you\l"
	.string "{JPN}teach them.\p"
	.string "{JPN}What kinds of moves do your POKEMON\n"
	.string "{JPN}know?$"

Route111_Text_BrookeRematchDefeat:
	.string "{JPN}You've taught them good moves!$"

Route111_Text_BrookePostRematch:
	.string "{JPN}Maybe I should have stopped my\n"
	.string "{JPN}POKEMON from evolving until they\l"
	.string "{JPN}learned better moves...$"

Route111_Text_CeliaIntro:
	.string "{JPN}I shouldn't have come to a place like\n"
	.string "{JPN}this for a picnic!$"

Route111_Text_CeliaDefeat:
	.string "{JPN}Aww!\n"
	.string "{JPN}I really shouldn't have come!$"

Route111_Text_CeliaPostBattle:
	.string "{JPN}In a sandstorm like this, I can't set\n"
	.string "{JPN}the places for a picnic even with my\l"
	.string "{JPN}GO-GOGGLES on...$"

Route111_Text_BryanIntro:
	.string "{JPN}How tough are you?\n"
	.string "{JPN}We shall expose that secret!$"

Route111_Text_BryanDefeat:
	.string "{JPN}Oh! Your strength!\n"
	.string "{JPN}It is shrouded in mystery!$"

Route111_Text_BryanPostBattle:
	.string "{JPN}This desert hoards mysteries in\n"
	.string "{JPN}its shifting sands!$"

Route111_Text_BrandenIntro:
	.string "{JPN}I'll give you some of my sandwich\n"
	.string "{JPN}if you'll lose.$"

Route111_Text_BrandenDefeat:
	.string "{JPN}Tch! I thought a sandwich would be\n"
	.string "{JPN}enough of a bribe...$"

Route111_Text_BrandenPostBattle:
	.string "{JPN}My SANDSHREW loves eating\n"
	.string "{JPN}my sandwiches.$"

Route111_Text_TyronIntro:
	.string "{JPN}This is my favorite kind of POKEMON!$"

Route111_Text_TyronDefeat:
	.string "{JPN}Wait!\n"
	.string "{JPN}Did you get a good look at my POKEMON?$"

Route111_Text_TyronPostBattle:
	.string "{JPN}When having a battle, I get a kick out\n"
	.string "{JPN}of showing off my POKEMON.\p"
	.string "{JPN}I bet everyone feels that way when\n"
	.string "{JPN}they enter a battle!$"

Route111_Text_CelinaIntro:
	.string "{JPN}Show me how to put a little excitement\n"
	.string "{JPN}into my life.$"

Route111_Text_CelinaDefeat:
	.string "{JPN}Oh... My...\n"
	.string "{JPN}That was too much excitement.$"

Route111_Text_CelinaPostBattle:
	.string "{JPN}My pulse is still racing.\n"
	.string "{JPN}You're one fabulous TRAINER.$"

Route111_Text_HaydenIntro:
	.string "{JPN}When you're as famished as I am,\n"
	.string "{JPN}there is no room for pity!$"

Route111_Text_HaydenDefeat:
	.string "{JPN}Groan...$"

Route111_Text_HaydenPostBattle:
	.string "{JPN}My stomach is grumbling!\n"
	.string "{JPN}Maybe I can grill some BERRIES...$"

Route111_Text_BiancaIntro:
	.string "{JPN}Did you come from MAUVILLE?\n"
	.string "{JPN}Then you should be full of energy!$"

Route111_Text_BiancaDefeat:
	.string "{JPN}Ooh lala!\n"
	.string "{JPN}That's a lot to take!$"

Route111_Text_BiancaPostBattle:
	.string "{JPN}This road here...\n"
	.string "{JPN}You have quite a ways to travel.$"

Route112_Text_BriceIntro:
	.string "{JPN}Hahahaha!\n"
	.string "{JPN}How about we have a battle?\l"
	.string "{JPN}You and me!\l"
	.string "{JPN}Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "{JPN}I lost!\n"
	.string "{JPN}Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "{JPN}Hahahahaha! Something flew up my nose!\n"
	.string "{JPN}Hahahaha-hatchoo!$"

Route112_Text_TrentIntro:
	.string "{JPN}My legs are solid from pounding up\n"
	.string "{JPN}and down the mountains.\p"
	.string "{JPN}They're not going to buckle easily,\n"
	.string "{JPN}friend!$"

Route112_Text_TrentDefeat:
	.string "{JPN}Ouch! My legs cramped up!$"

Route112_Text_TrentPostBattle:
	.string "{JPN}Try hiking, and I mean really\n"
	.string "{JPN}pounding, on these mountain trails\l"
	.string "{JPN}with a heavy pack weighing dozens of\l"
	.string "{JPN}pounds.\p"
	.string "{JPN}That, my friend, will get your body\n"
	.string "{JPN}into serious shape.$"

Route112_Text_TrentRegister:
	.string "{JPN}Ow, my legs have cramped up.\n"
	.string "{JPN}Can you grab me some bandages from\l"
	.string "{JPN}my backpack?\p"
	.string "{JPN}No, that's my POKeNAV!\n"
	.string "{JPN}Oh, fine, I'll register you.$"

Route112_Text_TrentRematchIntro:
	.string "{JPN}I've been keeping fit by hiking.\n"
	.string "{JPN}Power, I have in spades!$"

Route112_Text_TrentRematchDefeat:
	.string "{JPN}I got trumped in power?$"

Route112_Text_TrentRematchPostBattle:
	.string "{JPN}I hear there are some seriously tough\n"
	.string "{JPN}TRAINERS on top of MT. CHIMNEY.\p"
	.string "{JPN}I intend to get up there and give them\n"
	.string "{JPN}a challenge!$"

Route112_Text_LarryIntro:
	.string "{JPN}I'm strong.\n"
	.string "{JPN}I won't cry if I lose.$"

Route112_Text_LarryDefeat:
	.string "{JPN}Waaaah!$"

Route112_Text_LarryPostBattle:
	.string "{JPN}I'm not crying because I miss my mommy!\n"
	.string "{JPN}Snivel...$"

Route112_Text_CarolIntro:
	.string "{JPN}When you're out on a picnic, why,\n"
	.string "{JPN}you simply have to sing!\l"
	.string "{JPN}Come on, sing with me!$"

Route112_Text_CarolDefeat:
	.string "{JPN}Oh, you're so strong!$"

Route112_Text_CarolPostBattle:
	.string "{JPN}It doesn't matter if you're good or bad\n"
	.string "{JPN}at singing or POKEMON.\p"
	.string "{JPN}If you have the most fun, you win!$"

Route112_Text_BryantIntro:
	.string "{JPN}I caught hot POKEMON in FIERY PATH!\n"
	.string "{JPN}Take a look!$"

Route112_Text_BryantDefeat:
	.string "{JPN}What a bumpy ride that was!$"

Route112_Text_BryantPostBattle:
	.string "{JPN}I like the way you battle.\n"
	.string "{JPN}It has a certain flair to it.$"

Route112_Text_ShaylaIntro:
	.string "{JPN}Oh, aren't you an adorable TRAINER!\n"
	.string "{JPN}Please, I need a romantic battle!\l"
	.string "{JPN}I'm somewhat decent!$"

Route112_Text_ShaylaDefeat:
	.string "{JPN}Oh, how strong you are!\n"
	.string "{JPN}You've given me quite a shock!$"

Route112_Text_ShaylaPostBattle:
	.string "{JPN}Are you busy right now?\n"
	.string "{JPN}I was thinking that maybe we can have\l"
	.string "{JPN}a rematch right now...\l"
	.string "{JPN}But it's all right if you're busy.$"

Route113_Text_JaylenIntro:
	.string "{JPN}Can you guess why it's so cool\n"
	.string "{JPN}around here?$"

Route113_Text_JaylenDefeat:
	.string "{JPN}Peeuuw!\n"
	.string "{JPN}That stinks!$"

Route113_Text_JaylenPostBattle:
	.string "{JPN}The volcanic ash blocks the sun,\n"
	.string "{JPN}so it doesn't get very warm.\p"
	.string "{JPN}That's good for me--I can't stand heat!$"

Route113_Text_DillonIntro:
	.string "{JPN}The volcano's eruption is proof that\n"
	.string "{JPN}the earth is alive.$"

Route113_Text_DillonDefeat:
	.string "{JPN}You're some kind of strong!$"

Route113_Text_DillonPostBattle:
	.string "{JPN}Ouch! Owww! I can't see!\n"
	.string "{JPN}I got ashes in my eyelashes!\p"
	.string "{JPN}Get it? Ashes and eyelashes?\p"
	.string "{JPN}Okay, that was bad, sorry...$"

Route113_Text_MadelineIntro:
	.string "{JPN}I use this parasol to ward off this\n"
	.string "{JPN}filthy, yucky volcanic ash from\l"
	.string "{JPN}my dear NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "{JPN}Huff, huff...\n"
	.string "{JPN}I am exhausted...$"

Route113_Text_MadelinePostBattle:
	.string "{JPN}You're very good at this.\n"
	.string "{JPN}I must say I'm impressed!$"

Route113_Text_MadelineRegister:
	.string "{JPN}Here, slide under my parasol.\n"
	.string "{JPN}Let me register you in my POKeNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "{JPN}Oh, hello, hasn't it been a while?\n"
	.string "{JPN}May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat:
	.string "{JPN}Oh, how super!$"

Route113_Text_MadelinePostRematch:
	.string "{JPN}You've remained very good at this.\n"
	.string "{JPN}I must say I'm impressed!$"

Route113_Text_LaoIntro:
	.string "{JPN}From out of the ashes I leap! Hiyah!\n"
	.string "{JPN}I challenge thee!$"

Route113_Text_LaoDefeat:
	.string "{JPN}With honor I admit defeat!$"

Route113_Text_LaoPostBattle:
	.string "{JPN}I must refine the art of concealment.\n"
	.string "{JPN}I bid thee farewell.$"

Route113_Text_LaoRegister:
	.string "{JPN}Yiiyaah! Witness the ancient ninja\n"
	.string "{JPN}technique of POKeNAV registration!$"

Route113_Text_LaoRematchIntro:
	.string "{JPN}From out of the ashes I leap! Hiyah!\n"
	.string "{JPN}I challenge thee!$"

Route113_Text_LaoRematchDefeat:
	.string "{JPN}With honor I admit defeat!$"

Route113_Text_LaoPostRematch:
	.string "{JPN}My flawless concealment was let down\n"
	.string "{JPN}by my immature battle skills...\p"
	.string "{JPN}I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "{JPN}Thanks for finding me!\n"
	.string "{JPN}But we still have to battle!$"

Route113_Text_LungDefeat:
	.string "{JPN}I'll use my ninjutsu on you...\n"
	.string "{JPN}VOLCANIC ASH SWIRL CLOAK!\p"
	.string "{JPN}...What?\n"
	.string "{JPN}It's already over?$"

Route113_Text_LungPostBattle:
	.string "{JPN}You know what's crummy about hiding?\n"
	.string "{JPN}It's lonely if no one comes along.$"

Route113_Text_ToriIntro:
	.string "{JPN}TORI: Both of us, we collect ashes.\n"
	.string "{JPN}We battle POKEMON, too.$"

Route113_Text_ToriDefeat:
	.string "{JPN}TORI: We lost... It's boring, so I'm going\n"
	.string "{JPN}to get some more ashes.$"

Route113_Text_ToriPostBattle:
	.string "{JPN}TORI: How much ash do we have?\n"
	.string "{JPN}Enough for a WHITE FLUTE, I hope.$"

Route113_Text_ToriNotEnoughMons:
	.string "{JPN}TORI: We want to battle 2-on-2.\n"
	.string "{JPN}If we didn't, we would lose!$"

Route113_Text_TiaIntro:
	.string "{JPN}TIA: Both of us, we collect ashes.\n"
	.string "{JPN}We battle POKEMON, too.$"

Route113_Text_TiaDefeat:
	.string "{JPN}TIA: We couldn't win... It's boring,\n"
	.string "{JPN}so I'm getting some more ashes.$"

Route113_Text_TiaPostBattle:
	.string "{JPN}TIA: We have a lot of ashes!\n"
	.string "{JPN}I think enough for a WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "{JPN}TIA: We want to battle 2-on-2.\n"
	.string "{JPN}If we don't, we won't win!$"

Route113_Text_CobyIntro:
	.string "{JPN}Pfft, with these wings I can\n"
	.string "{JPN}flick you away!$"

Route113_Text_CobyDefeat:
	.string "{JPN}A... What?$"

Route113_Text_CobyPostBattle:
	.string "{JPN}I don't know what to say when I get\n"
	.string "{JPN}beaten so easily...$"

Route113_Text_SophieIntro:
	.string "{JPN}The warmth here is making me drowsy.\n"
	.string "{JPN}Battle with me so I can stay awake.$"

Route113_Text_SophieDefeat:
	.string "{JPN}This is a dream.\n"
	.string "{JPN}I'm sure of it...$"

Route113_Text_SophiePostBattle:
	.string "{JPN}Losing burns me up...\n"
	.string "{JPN}I'm just going to sleep right here!\l"
	.string "{JPN}Zzz!$"

Route113_Text_LawrenceIntro:
	.string "{JPN}Were you maybe in the middle\n"
	.string "{JPN}of gathering volcanic ashes?$"

Route113_Text_LawrenceDefeat:
	.string "{JPN}Ehehe.\n"
	.string "{JPN}We got beaten cleanly.$"

Route113_Text_LawrencePostBattle:
	.string "{JPN}I ought to hide under the ashes, too.$"

Route113_Text_WyattIntro:
	.string "{JPN}Y-you want to battle with me?\n"
	.string "{JPN}Even though I just caught my POKEMON?$"

Route113_Text_WyattDefeat:
	.string "{JPN}Y-you're all happy to win?\n"
	.string "{JPN}Even though it's only me?$"

Route113_Text_WyattPostBattle:
	.string "{JPN}Oh, so now you want to say a word to\n"
	.string "{JPN}the loser?\p"
	.string "{JPN}Aren't you just the coolest?\n"
	.string "{JPN}Humph!$"

Route114_Text_LennyIntro:
	.string "{JPN}Yodelayhihoo!\p"
	.string "{JPN}... ...\p"
	.string "{JPN}You're supposed to shout\n"
	.string "{JPN}yodelayhihoo since it doesn't\l"
	.string "{JPN}echo here!$"

Route114_Text_LennyDefeat:
	.string "{JPN}Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "{JPN}When I was a wee tyke, I believed there\n"
	.string "{JPN}was someone copying me and shouting\l"
	.string "{JPN}back, Yodelayhihoo.$"

Route114_Text_LucasIntro:
	.string "{JPN}If you're not prepared, you shouldn't\n"
	.string "{JPN}be up in the mountains!$"

Route114_Text_LucasDefeat:
	.string "{JPN}The mountains are unforgiving...$"

Route114_Text_LucasPostBattle:
	.string "{JPN}In the winter, mountains turn deadly\n"
	.string "{JPN}with blizzards and avalanches.$"

Route114_Text_ShaneIntro:
	.string "{JPN}Camping's fun! You can fish, roast\n"
	.string "{JPN}marshmallows, and tell spooky stories!\p"
	.string "{JPN}But the best of all are the POKEMON\n"
	.string "{JPN}battles!$"

Route114_Text_ShaneDefeat:
	.string "{JPN}Way too strong!$"

Route114_Text_ShanePostBattle:
	.string "{JPN}I think it's great that I can go\n"
	.string "{JPN}camping with my POKEMON.$"

Route114_Text_NancyIntro:
	.string "{JPN}I need to exercise after a meal.\n"
	.string "{JPN}Let's have a match!$"

Route114_Text_NancyDefeat:
	.string "{JPN}Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "{JPN}I just had a tasty meal.\n"
	.string "{JPN}I'm getting drowsy...$"

Route114_Text_SteveIntro:
	.string "{JPN}Ufufufufufu...\n"
	.string "{JPN}Want to battle against my POKEMON?$"

Route114_Text_SteveDefeat:
	.string "{JPN}M-My POKEMON...$"

Route114_Text_StevePostBattle:
	.string "{JPN}A big body that's all lumpy and hard,\n"
	.string "{JPN}enormous horns, and vicious fangs...\p"
	.string "{JPN}Ufufufufu...\n"
	.string "{JPN}I wish I had a POKEMON like that...$"

Route114_Text_SteveRegister:
	.string "{JPN}Don't forget what you've done to me!\n"
	.string "{JPN}I'll make it so you can't forget!$"

Route114_Text_SteveRematchIntro:
	.string "{JPN}Ufufufufufu...\n"
	.string "{JPN}Come on, battle my POKEMON...$"

Route114_Text_SteveRematchDefeat:
	.string "{JPN}I feel so lucky getting to see your\n"
	.string "{JPN}POKEMON...$"

Route114_Text_StevePostRematch:
	.string "{JPN}Ufufufufufu...\p"
	.string "{JPN}When I see POKEMON battling, I get all\n"
	.string "{JPN}shivery and shaky...$"

Route114_Text_BernieIntro:
	.string "{JPN}If you're lighting a campfire,\n"
	.string "{JPN}make sure you have water handy.$"

Route114_Text_BernieDefeat:
	.string "{JPN}Thanks for dousing my fire!$"

Route114_Text_BerniePostBattle:
	.string "{JPN}You really do have to be careful with\n"
	.string "{JPN}any sort of fire in a forest.\p"
	.string "{JPN}Don't ever underestimate the power\n"
	.string "{JPN}of fire.$"

Route114_Text_BernieRegister:
	.string "{JPN}You set my spirit on fire.\n"
	.string "{JPN}Let's register each other!$"

Route114_Text_BernieRematchIntro:
	.string "{JPN}Have you learned to keep water handy\n"
	.string "{JPN}for campfires?$"

Route114_Text_BernieRematchDefeat:
	.string "{JPN}I got hosed down before I could\n"
	.string "{JPN}flare up, I guess.$"

Route114_Text_BerniePostRematch:
	.string "{JPN}You really do have to be careful with\n"
	.string "{JPN}any sort of fire in a forest.\p"
	.string "{JPN}Don't ever underestimate the power\n"
	.string "{JPN}of fire.$"

Route114_Text_ClaudeIntro:
	.string "{JPN}If we were fishing, you wouldn't stand\n"
	.string "{JPN}a chance against me.\l"
	.string "{JPN}So, bring on your POKEMON!$"

Route114_Text_ClaudeDefeat:
	.string "{JPN}If we were fishing, I would've won...$"

Route114_Text_ClaudePostBattle:
	.string "{JPN}I think I'll try my luck at landing\n"
	.string "{JPN}a big one at METEOR FALLS.\p"
	.string "{JPN}There has to be something in there.\n"
	.string "{JPN}I just know it.$"

Route114_Text_NolanIntro:
	.string "{JPN}I like to fish. But I also like to\n"
	.string "{JPN}battle!\p"
	.string "{JPN}If anyone challenges me, I'm there,\n"
	.string "{JPN}even if I'm fishing.$"

Route114_Text_NolanDefeat:
	.string "{JPN}I like to battle, but that doesn't\n"
	.string "{JPN}mean I'm good at it...$"

Route114_Text_NolanPostBattle:
	.string "{JPN}This time I'll do it!\p"
	.string "{JPN}I always think that, so I can't walk\n"
	.string "{JPN}away from fishing or POKEMON.$"

Route114_Text_TyraIntro:
	.string "{JPN}TYRA: Well, sure.\n"
	.string "{JPN}I'm in the mood for it.\l"
	.string "{JPN}I'll teach you a little about POKEMON.$"

Route114_Text_TyraDefeat:
	.string "{JPN}TYRA: What an amazing battle style!$"

Route114_Text_TyraPostBattle:
	.string "{JPN}TYRA: I was teaching my junior IVY\n"
	.string "{JPN}about POKEMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "{JPN}TYRA: Giggle...\n"
	.string "{JPN}If you want to battle with us, just one\l"
	.string "{JPN}POKEMON isn't enough!$"

Route114_Text_IvyIntro:
	.string "{JPN}IVY: Who taught you about POKEMON?$"

Route114_Text_IvyDefeat:
	.string "{JPN}IVY: What an amazing battle style!$"

Route114_Text_IvyPostBattle:
	.string "{JPN}IVY: I started training POKEMON\n"
	.string "{JPN}because TYRA, my student mentor,\l"
	.string "{JPN}taught me!$"

Route114_Text_IvyNotEnoughMons:
	.string "{JPN}IVY: Do you only have one POKEMON?\n"
	.string "{JPN}I think it must feel lonesome.$"

Route114_Text_KaiIntro:
	.string "{JPN}I landed a big one!\n"
	.string "{JPN}A huge one, I tell you!$"

Route114_Text_KaiDefeat:
	.string "{JPN}What was that about?\n"
	.string "{JPN}Did mine lose in size?$"

Route114_Text_KaiPostBattle:
	.string "{JPN}Okay!\n"
	.string "{JPN}I'll just fish me a bigger one!$"

Route114_Text_CharlotteIntro:
	.string "{JPN}Me!\n"
	.string "{JPN}I'm not just a pretty face!$"

Route114_Text_CharlotteDefeat:
	.string "{JPN}That wasn't cute in the least!$"

Route114_Text_CharlottePostBattle:
	.string "{JPN}I don't want a POKEMON that's\n"
	.string "{JPN}just cute.\p"
	.string "{JPN}I adore cute ones that have a quirk\n"
	.string "{JPN}or two!$"

Route114_Text_AngelinaIntro:
	.string "{JPN}Have you made your POKEMON evolve\n"
	.string "{JPN}very much?$"

Route114_Text_AngelinaDefeat:
	.string "{JPN}Oh, I see.\n"
	.string "{JPN}That's good to know.$"

Route114_Text_AngelinaPostBattle:
	.string "{JPN}Some POKEMON change so much when\n"
	.string "{JPN}they evolve, it's startling!$"

Route115_Text_TimothyIntro:
	.string "{JPN}Hm...\n"
	.string "{JPN}You seem rather capable...\l"
	.string "{JPN}Let me keep you company!$"

Route115_Text_TimothyDefeat:
	.string "{JPN}You're much stronger than\n"
	.string "{JPN}I'd imagined!$"

Route115_Text_TimothyPostBattle:
	.string "{JPN}There is no such thing as a born genius.\n"
	.string "{JPN}It all depends on effort!\l"
	.string "{JPN}That is what I believe...$"

Route115_Text_TimothyRegister:
	.string "{JPN}Hmm... A loss this thorough has been\n"
	.string "{JPN}a distant memory.\p"
	.string "{JPN}If you would allow it, I wish for\n"
	.string "{JPN}another opportunity to do battle.$"

Route115_Text_TimothyRematchIntro:
	.string "{JPN}Hm... As always, your agility speaks\n"
	.string "{JPN}for itself.\l"
	.string "{JPN}Come, keep me company!$"

Route115_Text_TimothyRematchDefeat:
	.string "{JPN}As strong as ever!$"

Route115_Text_TimothyPostRematch:
	.string "{JPN}All it takes is effort!\p"
	.string "{JPN}I lost because I haven't put in enough\n"
	.string "{JPN}effort!$"

Route115_Text_KoichiIntro:
	.string "{JPN}You!\p"
	.string "{JPN}My MACHOP!\p"
	.string "{JPN}Demand a battle!$"

Route115_Text_KoichiDefeat:
	.string "{JPN}Ouch, ouch, ouch!$"

Route115_Text_KoichiPostBattle:
	.string "{JPN}My MACHOP crew!\p"
	.string "{JPN}So long as they seek power, I will\n"
	.string "{JPN}grow strong with them!$"

Route115_Text_NobIntro:
	.string "{JPN}My strongest skill is busting bricks\n"
	.string "{JPN}with my forehead!$"

Route115_Text_NobDefeat:
	.string "{JPN}Ugwaaaah!\n"
	.string "{JPN}My head is busted!$"

Route115_Text_NobPostBattle:
	.string "{JPN}I've been teaching my POKEMON karate.\p"
	.string "{JPN}It looks like they'll get a lot better\n"
	.string "{JPN}than me. I'm excited about that.$"

Route115_Text_NobRegister:
	.string "{JPN}You impress me! Give me a rematch\n"
	.string "{JPN}after I redo my training!$"

Route115_Text_NobRematchIntro:
	.string "{JPN}After you beat me, we trained hard to\n"
	.string "{JPN}improve our skills.\l"
	.string "{JPN}Come on, give us a rematch!$"

Route115_Text_NobRematchDefeat:
	.string "{JPN}Ugwaaah!\n"
	.string "{JPN}We lost again!$"

Route115_Text_NobPostRematch:
	.string "{JPN}My POKEMON will grow stronger!\n"
	.string "{JPN}I'll redouble my training!$"

Route115_Text_CyndyIntro:
	.string "{JPN}This beach is my secret training spot!\n"
	.string "{JPN}Don't come butting in!$"

Route115_Text_CyndyDefeat:
	.string "{JPN}I haven't trained enough!$"

Route115_Text_CyndyPostBattle:
	.string "{JPN}The sand acts as a cushion to reduce\n"
	.string "{JPN}impact and prevent injury.\l"
	.string "{JPN}This is the perfect place to train.$"

Route115_Text_CyndyRegister:
	.string "{JPN}Okay, fine, you're free to come here.\n"
	.string "{JPN}In return, I'd like to battle you again.$"

Route115_Text_CyndyRematchIntro:
	.string "{JPN}Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:
	.string "{JPN}I can battle but my POKEMON...$"

Route115_Text_CyndyPostRematch:
	.string "{JPN}Even when I lose, I still get some\n"
	.string "{JPN}enjoyment out of it.\l"
	.string "{JPN}It must be that I love POKEMON.$"

Route115_Text_HectorIntro:
	.string "{JPN}I have a rare POKEMON!\n"
	.string "{JPN}Would you like me to show you?$"

Route115_Text_HectorDefeat:
	.string "{JPN}You...\n"
	.string "{JPN}You want my POKEMON, don't you?$"

Route115_Text_HectorPostBattle:
	.string "{JPN}I have this rare POKEMON.\n"
	.string "{JPN}It's enough to keep me satisfied.$"

Route115_Text_KyraIntro:
	.string "{JPN}I'll battle while I'm running!\n"
	.string "{JPN}Try to keep up with me!$"

Route115_Text_KyraDefeat:
	.string "{JPN}Gasp, gasp...$"

Route115_Text_KyraPostBattle:
	.string "{JPN}I made the mistake of trying to battle\n"
	.string "{JPN}while running!\p"
	.string "{JPN}I should take a run to calm down...$"

Route115_Text_JaidenIntro:
	.string "{JPN}Take that!\n"
	.string "{JPN}Ultra POKEMON ninja attack!$"

Route115_Text_JaidenDefeat:
	.string "{JPN}Waaah!\n"
	.string "{JPN}Our strategy failed!$"

Route115_Text_JaidenPostBattle:
	.string "{JPN}But my POKEMON were ultra,\n"
	.string "{JPN}weren't they?$"

Route115_Text_HeleneIntro:
	.string "{JPN}My POKEMON have black belt-level\n"
	.string "{JPN}strength!$"

Route115_Text_HeleneDefeat:
	.string "{JPN}This is too humiliating!$"

Route115_Text_HelenePostBattle:
	.string "{JPN}I rarely meet anyone who's better\n"
	.string "{JPN}than me...\p"
	.string "{JPN}I get it now!\n"
	.string "{JPN}You're a GYM LEADER, aren't you?$"

Route115_Text_AlixIntro:
	.string "{JPN}Our eyes met!\n"
	.string "{JPN}There's no getting away now!$"

Route115_Text_AlixDefeat:
	.string "{JPN}Gah!\n"
	.string "{JPN}Not bad!$"

Route115_Text_AlixPostBattle:
	.string "{JPN}Oh, well.\n"
	.string "{JPN}I think I will TELEPORT home.$"

Route115_Text_MarleneIntro:
	.string "{JPN}You've disturbed my meditation...\n"
	.string "{JPN}You'll be punished for it.$"

Route115_Text_MarleneDefeat:
	.string "{JPN}You've broken my concentration!$"

Route115_Text_MarlenePostBattle:
	.string "{JPN}I was meditating with my POKEMON.\n"
	.string "{JPN}But this place isn't very peaceful...$"

Route116_Text_ClarkIntro:
	.string "{JPN}If the tunnel doesn't go through, then\n"
	.string "{JPN}I'll just go over the top.$"

Route116_Text_ClarkDefeat:
	.string "{JPN}Gasp... Gasp...\n"
	.string "{JPN}Losing made me tired...$"

Route116_Text_ClarkPostBattle:
	.string "{JPN}It's no big deal if there's no tunnel.\n"
	.string "{JPN}To a HIKER, mountains are roads!$"

Route116_Text_JoeyIntro:
	.string "{JPN}My POKEMON rule!\n"
	.string "{JPN}Check them out!$"

Route116_Text_JoeyDefeat:
	.string "{JPN}Ouch! A scrape!\n"
	.string "{JPN}I have to put on a bandage!$"

Route116_Text_JoeyPostBattle:
	.string "{JPN}Bandages are signs of toughness!\n"
	.string "{JPN}I've got another one!$"

Route116_Text_JoseIntro:
	.string "{JPN}My BUG POKEMON are tough!\n"
	.string "{JPN}Let's battle!$"

Route116_Text_JoseDefeat:
	.string "{JPN}I lost!\n"
	.string "{JPN}I thought I had you!$"

Route116_Text_JosePostBattle:
	.string "{JPN}BUG POKEMON evolve quickly.\n"
	.string "{JPN}So they get strong quickly, too.$"

Route116_Text_JaniceIntro:
	.string "{JPN}Let me teach you how strong my\n"
	.string "{JPN}adorable POKEMON is!$"

Route116_Text_JaniceDefeat:
	.string "{JPN}You're a notch above me...$"

Route116_Text_JanicePostBattle:
	.string "{JPN}POKEMON that possess cuteness and\n"
	.string "{JPN}power, that's ideal, I think.$"

Route116_Text_JerryIntro:
	.string "{JPN}We learn all sorts of things at the\n"
	.string "{JPN}TRAINER'S SCHOOL.\p"
	.string "{JPN}I want to test things out for real!$"

Route116_Text_JerryDefeat:
	.string "{JPN}I slacked off in school...\n"
	.string "{JPN}That's why I lost.$"

Route116_Text_JerryPostBattle:
	.string "{JPN}I'll have to redo some courses at\n"
	.string "{JPN}the TRAINER'S SCHOOL.\l"
	.string "{JPN}If I don't, ROXANNE will be steamed.$"

Route116_Text_JerryRegister1:
	.string "{JPN}I learned at the TRAINER'S SCHOOL\n"
	.string "{JPN}that a POKeNAV can register TRAINERS.\p"
	.string "{JPN}I don't really get what that means,\n"
	.string "{JPN}so can I just try it?$"

Route116_Text_JerryRegister2:
	.string "{JPN}I learned at the TRAINER'S SCHOOL\n"
	.string "{JPN}that a POKeNAV can register TRAINERS.\p"
	.string "{JPN}I don't really get what that means,\n"
	.string "{JPN}so can I just try it?$"

Route116_Text_JerryRematchIntro:
	.string "{JPN}I've been studying seriously at the\n"
	.string "{JPN}TRAINER'S SCHOOL.\l"
	.string "{JPN}I won't lose like I did last time.$"

Route116_Text_JerryRematchDefeat:
	.string "{JPN}Hunh?\n"
	.string "{JPN}I studied diligently.$"

Route116_Text_JerryPostRematch:
	.string "{JPN}I'll have to redo some courses at\n"
	.string "{JPN}the TRAINER'S SCHOOL.\l"
	.string "{JPN}If I don't, ROXANNE will be steamed.$"

Route116_Text_KarenIntro:
	.string "{JPN}I study at school, and I study on\n"
	.string "{JPN}the way home, too!$"

Route116_Text_KarenDefeat:
	.string "{JPN}I'm in shock--I lost?$"

Route116_Text_KarenPostBattle:
	.string "{JPN}Awww, I'll never become an elegant\n"
	.string "{JPN}TRAINER like ROXANNE this way!$"

Route116_Text_KarenRegister1:
	.string "{JPN}Oh, wow! Isn't that a POKeNAV?\n"
	.string "{JPN}I have one, too! Please register me!$"

Route116_Text_KarenRegister2:
	.string "{JPN}Oh, wow! Isn't that a POKeNAV?\n"
	.string "{JPN}I have one, too! Please register me!$"

Route116_Text_KarenRematchIntro:
	.string "{JPN}I studied a whole lot since I saw you.\n"
	.string "{JPN}You must see my achievements!$"

Route116_Text_KarenRematchDefeat:
	.string "{JPN}I'm in shock.\n"
	.string "{JPN}I lost again?$"

Route116_Text_KarenPostRematch:
	.string "{JPN}You've beaten ROXANNE?\n"
	.string "{JPN}I can't beat you, then. Not yet.$"

Route116_Text_SarahIntro:
	.string "{JPN}Just so you know, I've never once been\n"
	.string "{JPN}bested by anyone at anything.$"

Route116_Text_SarahDefeat:
	.string "{JPN}Oh, my goodness.\n"
	.string "{JPN}This is a new experience for me.$"

Route116_Text_SarahPostBattle:
	.string "{JPN}My life of luxury affords me all that\n"
	.string "{JPN}I could possibly desire.\p"
	.string "{JPN}However, when it comes to POKEMON,\n"
	.string "{JPN}my wealth has no meaning.$"

Route116_Text_DawsonIntro:
	.string "{JPN}When you lay your eyes on my POKEMON's\n"
	.string "{JPN}gorgeous fur, their beauty will render\l"
	.string "{JPN}you helpless!$"

Route116_Text_DawsonDefeat:
	.string "{JPN}Oh, baby, say it isn't so!$"

Route116_Text_DawsonPostBattle:
	.string "{JPN}Oh, no, no, no!\n"
	.string "{JPN}You've mussed up my POKEMON's fur!\l"
	.string "{JPN}You've ruined my hairdo, too!\l"
	.string "{JPN}I'll have to call my stylist now!$"

Route116_Text_DevanIntro:
	.string "{JPN}We'll rock you hard!$"

Route116_Text_DevanDefeat:
	.string "{JPN}Aiyiyi!\n"
	.string "{JPN}No contest at all!$"

Route116_Text_DevanPostBattle:
	.string "{JPN}I should try different POKEMON\n"
	.string "{JPN}types, that's what I ought to do.$"

Route116_Text_JohnsonIntro:
	.string "{JPN}It's a dead end up here.\n"
	.string "{JPN}I'm bored, so can we battle?$"

Route116_Text_JohnsonDefeat:
	.string "{JPN}That was fun even though I lost.$"

Route116_Text_JohnsonPostBattle:
	.string "{JPN}Want to stay here and keep\n"
	.string "{JPN}me company?$"

Route117_Text_IsaacIntro:
	.string "{JPN}Listen, could I get you to battle\n"
	.string "{JPN}the POKEMON I'm raising?$"

Route117_Text_IsaacDefeat:
	.string "{JPN}You've raised yours superbly...$"

Route117_Text_IsaacPostBattle:
	.string "{JPN}POKEMON isn't all about power.\p"
	.string "{JPN}Polishing a unique aspect of one's\n"
	.string "{JPN}character is another way of enjoying\l"
	.string "{JPN}POKEMON.$"

Route117_Text_IsaacRegister:
	.string "{JPN}I'm going to redouble my training.\n"
	.string "{JPN}Would you come look in on us?$"

Route117_Text_IsaacRematchIntro:
	.string "{JPN}The POKEMON I've been raising are\n"
	.string "{JPN}looking good, just like before.$"

Route117_Text_IsaacRematchDefeat:
	.string "{JPN}You know how to raise them properly.\n"
	.string "{JPN}You might have DAY CARE skills...$"

Route117_Text_IsaacPostRematch:
	.string "{JPN}Your POKEMON are growing good!\n"
	.string "{JPN}You should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:
	.string "{JPN}Please, allow me to evaluate if you\n"
	.string "{JPN}have raised your POKEMON properly.$"

Route117_Text_LydiaDefeat:
	.string "{JPN}Yes, they are growing properly.$"

Route117_Text_LydiaPostBattle:
	.string "{JPN}Try raising POKEMON with more\n"
	.string "{JPN}attention to their character traits.$"

Route117_Text_LydiaRegister:
	.string "{JPN}I'm glad I met a superb TRAINER in you.\n"
	.string "{JPN}I hope to see you again.$"

Route117_Text_LydiaRematchIntro:
	.string "{JPN}Allow me to reevaluate if you have\n"
	.string "{JPN}raised your POKEMON properly.$"

Route117_Text_LydiaRematchDefeat:
	.string "{JPN}They are growing admirably.$"

Route117_Text_LydiaPostRematch:
	.string "{JPN}POKEMON seem to like different kinds\n"
	.string "{JPN}of ポロックS, depending on their nature.$"

Route117_Text_DylanIntro:
	.string "{JPN}I'm in the middle of a triathlon, but,\n"
	.string "{JPN}whatever, let's have a battle!$"

Route117_Text_DylanDefeat:
	.string "{JPN}I ran out of energy!$"

Route117_Text_DylanPostBattle:
	.string "{JPN}I may have blown it...\p"
	.string "{JPN}I might have dropped to last during\n"
	.string "{JPN}that battle...$"

Route117_Text_DylanRegister:
	.string "{JPN}POKEMON have to be strong, too?\n"
	.string "{JPN}I'd like you to train me!$"

Route117_Text_DylanRematchIntro:
	.string "{JPN}I'm smack in the middle of a triathlon,\n"
	.string "{JPN}but I'm comfortably ahead.\l"
	.string "{JPN}Let's make this a quick battle!$"

Route117_Text_DylanRematchDefeat:
	.string "{JPN}I ran out of energy again!$"

Route117_Text_DylanPostRematch:
	.string "{JPN}I was tops in swimming and cycling,\n"
	.string "{JPN}but I'm not quite that confident with\l"
	.string "{JPN}POKEMON yet.$"

Route117_Text_MariaIntro:
	.string "{JPN}I do my triathlon training with POKEMON,\n"
	.string "{JPN}so I'm pretty confident about my speed.$"

Route117_Text_MariaDefeat:
	.string "{JPN}I need to get more practices in,\n"
	.string "{JPN}I guess.$"

Route117_Text_MariaPostBattle:
	.string "{JPN}Training is meaningful only if you\n"
	.string "{JPN}keep it up regularly.\p"
	.string "{JPN}Okay! I'll resume my training!\n"
	.string "{JPN}Tomorrow!$"

Route117_Text_MariaRegister:
	.string "{JPN}You appear to be training properly...\n"
	.string "{JPN}If you'd like, I'll battle you later!$"

Route117_Text_MariaRematchIntro:
	.string "{JPN}Are you keeping up with your training?\n"
	.string "{JPN}I sure am!\l"
	.string "{JPN}Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:
	.string "{JPN}I need to get more practices in,\n"
	.string "{JPN}I guess.$"

Route117_Text_MariaPostRematch:
	.string "{JPN}I'll resume training tomorrow.\n"
	.string "{JPN}Let's battle again sometime!$"

Route117_Text_DerekIntro:
	.string "{JPN}Once a BUG CATCHER!\n"
	.string "{JPN}And now a BUG MANIAC!\p"
	.string "{JPN}But my love for POKEMON remains\n"
	.string "{JPN}unchanged!$"

Route117_Text_DerekDefeat:
	.string "{JPN}My ineptitude also remains\n"
	.string "{JPN}unchanged...$"

Route117_Text_DerekPostBattle:
	.string "{JPN}All I did was follow my heart, and now\n"
	.string "{JPN}they call me a BUG MANIAC...\p"
	.string "{JPN}Still, I am an expert on BUG POKEMON,\n"
	.string "{JPN}so it's only natural that they call me\l"
	.string "{JPN}a BUG MANIAC.$"

Route117_Text_AnnaIntro:
	.string "{JPN}ANNA: I'm with my pretty junior student\n"
	.string "{JPN}partner. I have to do good!$"

Route117_Text_AnnaDefeat:
	.string "{JPN}ANNA: I'm with my pretty junior student\n"
	.string "{JPN}partner! Let me win!$"

Route117_Text_AnnaPostBattle:
	.string "{JPN}ANNA: Your POKEMON have some good\n"
	.string "{JPN}combinations.\p"
	.string "{JPN}I'd say you're second only to us!$"

Route117_Text_AnnaAndMegRegister:
	.string "{JPN}ANNA: We can't take this lying down!\n"
	.string "{JPN}You will come back, won't you?$"

Route117_Text_AnnaNotEnoughMons:
	.string "{JPN}ANNA: If you want to battle us,\n"
	.string "{JPN}bring two POKEMON with you.$"

Route117_Text_MegIntro:
	.string "{JPN}MEG: I'm going to tag up with my super\n"
	.string "{JPN}senior student partner and beat you!$"

Route117_Text_MegDefeat:
	.string "{JPN}MEG: Oh, no!\n"
	.string "{JPN}I'm sorry, ANNA! I let you down...$"

Route117_Text_MegPostBattle:
	.string "{JPN}MEG: I dragged ANNA down...\n"
	.string "{JPN}If I didn't, she would have won!$"

Route117_Text_MegNotEnoughMons:
	.string "{JPN}MEG: Do you only have one POKEMON?\n"
	.string "{JPN}We can't battle with you, then.\p"
	.string "{JPN}We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:
	.string "{JPN}ANNA: I can't keep losing in front of\n"
	.string "{JPN}my junior partner, right?$"

Route117_Text_AnnaRematchDefeat:
	.string "{JPN}ANNA: I couldn't get into the groove.$"

Route117_Text_AnnaPostRematch:
	.string "{JPN}ANNA: Your POKEMON have some good\n"
	.string "{JPN}combinations.\p"
	.string "{JPN}I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "{JPN}ANNA: If you want to battle us,\n"
	.string "{JPN}bring two POKEMON with you.$"

Route117_Text_MegRematchIntro:
	.string "{JPN}MEG: I'm going to tag up with my\n"
	.string "{JPN}senior partner and win this time!$"

Route117_Text_MegRematchDefeat:
	.string "{JPN}MEG: Too strong!$"

Route117_Text_MegPostRematch:
	.string "{JPN}MEG: I battled together with my\n"
	.string "{JPN}senior partner, but we lost...\p"
	.string "{JPN}That's so discouraging...$"

Route117_Text_MegRematchNotEnoughMons:
	.string "{JPN}MEG: Do you only have one POKEMON?\n"
	.string "{JPN}We can't battle with you, then.\p"
	.string "{JPN}We want to have a 2-on-2 battle.$"

Route117_Text_MelinaIntro:
	.string "{JPN}Isn't it nice? To battle while looking\n"
	.string "{JPN}at pretty flowers?$"

Route117_Text_MelinaDefeat:
	.string "{JPN}Oh, that's quite impressive!$"

Route117_Text_MelinaPostBattle:
	.string "{JPN}It feels wonderful to go for a jog\n"
	.string "{JPN}while looking at flowers.$"

Route117_Text_BrandiIntro:
	.string "{JPN}Let me demonstrate the power\n"
	.string "{JPN}hidden within a PSYCHIC POKEMON!$"

Route117_Text_BrandiDefeat:
	.string "{JPN}Astonishing!$"

Route117_Text_BrandiPostBattle:
	.string "{JPN}PSYCHIC POKEMON are complex.\n"
	.string "{JPN}You should try catching some.$"

Route117_Text_AishaIntro:
	.string "{JPN}Concentrate on getting the win.\n"
	.string "{JPN}That's how I battle!$"

Route117_Text_AishaDefeat:
	.string "{JPN}I don't waste any time being angry\n"
	.string "{JPN}over a loss--I would rather train.$"

Route117_Text_AishaPostBattle:
	.string "{JPN}I think that if you worry about losing,\n"
	.string "{JPN}you're more likely to lose.$"

Route118_Text_RoseIntro:
	.string "{JPN}The aroma of flowers has a magical\n"
	.string "{JPN}power. It cleanses us body and soul.$"

Route118_Text_RoseDefeat:
	.string "{JPN}Oh, dear me.\n"
	.string "{JPN}I seem to have lost.$"

Route118_Text_RosePostBattle:
	.string "{JPN}Flowers, POKEMON...\n"
	.string "{JPN}I love whatever smells nice.\p"
	.string "{JPN}Stinky things...\n"
	.string "{JPN}I'll pass.$"

Route118_Text_RoseRegister:
	.string "{JPN}Sniff... That odor--it's a POKeNAV!\n"
	.string "{JPN}We must register each other!$"

Route118_Text_RoseRematchIntro:
	.string "{JPN}Were you drawn here by the sweet\n"
	.string "{JPN}aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "{JPN}The power of aroma...\n"
	.string "{JPN}It didn't seem to do much.$"

Route118_Text_RosePostRematch:
	.string "{JPN}If you use a sweet aroma properly,\n"
	.string "{JPN}POKEMON will be attracted by it.$"

Route118_Text_PerryIntro:
	.string "{JPN}BIRD POKEMON that FLY elegantly in\n"
	.string "{JPN}the sky... They're the best!$"

Route118_Text_PerryDefeat:
	.string "{JPN}Urgh...\n"
	.string "{JPN}I crashed...$"

Route118_Text_PerryPostBattle:
	.string "{JPN}You've got great POKEMON.\n"
	.string "{JPN}I'll have to train mine better.$"

Route118_Text_ChesterIntro:
	.string "{JPN}Take flight!\n"
	.string "{JPN}My BIRD POKEMON!$"

Route118_Text_ChesterDefeat:
	.string "{JPN}They did take flight...$"

Route118_Text_ChesterPostBattle:
	.string "{JPN}If they'd get stronger, they'd be able\n"
	.string "{JPN}to fly more freely...$"

Route118_Text_BarnyIntro:
	.string "{JPN}I'm a FISHERMAN, but also a TRAINER.\n"
	.string "{JPN}I'm raising the POKEMON I caught.$"

Route118_Text_BarnyDefeat:
	.string "{JPN}I thought I was doing okay in my\n"
	.string "{JPN}training...$"

Route118_Text_BarnyPostBattle:
	.string "{JPN}I couldn't win by training POKEMON\n"
	.string "{JPN}while I fished...\p"
	.string "{JPN}Was I doing things in half measures?$"

Route118_Text_WadeIntro:
	.string "{JPN}For FISHERMEN, equipment is the key.\p"
	.string "{JPN}But for TRAINERS, the key ingredients\n"
	.string "{JPN}are POKEMON and heart, of course!$"

Route118_Text_WadeDefeat:
	.string "{JPN}I was beaten in heart?$"

Route118_Text_WadePostBattle:
	.string "{JPN}Come to think of it, fishing is a battle\n"
	.string "{JPN}between a FISHERMAN and a POKEMON.$"

Route118_Text_DaltonIntro:
	.string "{JPN}Let my melody rock your soul!$"

Route118_Text_DaltonDefeat:
	.string "{JPN}La-lalala...$"

Route118_Text_DaltonPostBattle:
	.string "{JPN}An electric guitar doesn't always\n"
	.string "{JPN}have to be noisy...\p"
	.string "{JPN}It can be strummed to squeeze out\n"
	.string "{JPN}this heart-stirring melody...$"

Route118_Text_DaltonRegister:
	.string "{JPN}When I compose better melodies,\n"
	.string "{JPN}you have to come listen, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "{JPN}A melody from my POKEMON and me...\n"
	.string "{JPN}Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat:
	.string "{JPN}La-lalala...$"

Route118_Text_DaltonPostRematch:
	.string "{JPN}When I play, my emotions should reach\n"
	.string "{JPN}you through my electric guitar...$"

Route118_Text_DeandreIntro:
	.string "{JPN}Go, go, go!\n"
	.string "{JPN}POKEMON 1, 2, and 3!$"

Route118_Text_DeandreDefeat:
	.string "{JPN}Come in, POKEMON! Are you okay?\n"
	.string "{JPN}POKEMON 1, 2, and 3?!$"

Route118_Text_DeandrePostBattle:
	.string "{JPN}Isn't it cool that I have a POKEMON\n"
	.string "{JPN}battle team?\p"
	.string "{JPN}You can copy me--I don't mind!$"

Route119_Text_BrentIntro:
	.string "{JPN}We're the MIMIC CIRCLE!\n"
	.string "{JPN}We MIMIC what you do!$"

Route119_Text_BrentDefeat:
	.string "{JPN}Whoopsie!\n"
	.string "{JPN}I lost!$"

Route119_Text_BrentPostBattle:
	.string "{JPN}What's so good about mimicry?\p"
	.string "{JPN}Fufufu...\n"
	.string "{JPN}You'll never understand...$"

Route119_Text_DonaldIntro:
	.string "{JPN}So, we finally meet!\n"
	.string "{JPN}My BUG POKEMON will keep you company!$"

Route119_Text_DonaldDefeat:
	.string "{JPN}I wish we'd never met...$"

Route119_Text_DonaldPostBattle:
	.string "{JPN}I want to MIMIC you some more.\n"
	.string "{JPN}Can you hurry up and move?$"

Route119_Text_TaylorIntro:
	.string "{JPN}If you step forward, we step forward.\p"
	.string "{JPN}If you turn right, we turn, too...$"

Route119_Text_TaylorDefeat:
	.string "{JPN}But if you win, I lose...$"

Route119_Text_TaylorPostBattle:
	.string "{JPN}I can't MIMIC you winning the match.\n"
	.string "{JPN}That's just impossible...\l"
	.string "{JPN}It's burning me up...$"

Route119_Text_DougIntro:
	.string "{JPN}Yep, you've finally caught me!\n"
	.string "{JPN}Or were you trying to avoid me?$"

Route119_Text_DougDefeat:
	.string "{JPN}Whoop, that was a great match!$"

Route119_Text_DougPostBattle:
	.string "{JPN}We're the MIMIC CIRCLE!\n"
	.string "{JPN}I hope you enjoyed our performance.$"

Route119_Text_GregIntro:
	.string "{JPN}You don't know who I am, do you?\p"
	.string "{JPN}But, I also don't know you.\n"
	.string "{JPN}So, we'll battle!$"

Route119_Text_GregDefeat:
	.string "{JPN}You're pretty strong!$"

Route119_Text_GregPostBattle:
	.string "{JPN}Until you go away somewhere, we'll\n"
	.string "{JPN}keep on mimicking your every move.$"

Route119_Text_KentIntro:
	.string "{JPN}The MIMIC CIRCLE was formed by people\n"
	.string "{JPN}who like to MIMIC.\p"
	.string "{JPN}A battle starts the instant we meet!$"

Route119_Text_KentDefeat:
	.string "{JPN}I give up!$"

Route119_Text_KentPostBattle:
	.string "{JPN}Won't you join our MIMIC CIRCLE?$"

Route119_Text_JacksonIntro:
	.string "{JPN}Who has the knowledge and\n"
	.string "{JPN}the technique for survival?\p"
	.string "{JPN}POKEMON RANGERS, that's who!$"

Route119_Text_JacksonDefeat:
	.string "{JPN}I didn't have enough POKEMON\n"
	.string "{JPN}know-how...$"

Route119_Text_JacksonPostBattle:
	.string "{JPN}To break away from civilization and\n"
	.string "{JPN}awaken the wild spirit within!\p"
	.string "{JPN}That's our vision.$"

Route119_Text_JacksonRegister:
	.string "{JPN}I hope you'll give me a rematch without\n"
	.string "{JPN}mocking my lack of knowledge.$"

Route119_Text_JacksonRematchIntro:
	.string "{JPN}I'm going to regain my wild spirit by\n"
	.string "{JPN}being together with POKEMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "{JPN}You've remained strong!$"

Route119_Text_JacksonPostRematch:
	.string "{JPN}Believe in your POKEMON.\n"
	.string "{JPN}Believe in yourself.\p"
	.string "{JPN}The road will reveal itself to you.$"

Route119_Text_CatherineIntro:
	.string "{JPN}Oh? Look at you.\p"
	.string "{JPN}For someone on an adventure,\n"
	.string "{JPN}you're traveling awfully light.$"

Route119_Text_CatherineDefeat:
	.string "{JPN}Accidents happen when you're not\n"
	.string "{JPN}prepared!$"

Route119_Text_CatherinePostBattle:
	.string "{JPN}You're traveling light but you have\n"
	.string "{JPN}everything you need.\p"
	.string "{JPN}You're on top of things mentally and\n"
	.string "{JPN}physically, too.$"

Route119_Text_CatherineRegister:
	.string "{JPN}Do you have a POKeNAV?\n"
	.string "{JPN}It's a must-have tool for any TRAINER.\p"
	.string "{JPN}Oh, you do have one!\n"
	.string "{JPN}Let's register each other, then!$"

Route119_Text_CatherineRematchIntro:
	.string "{JPN}How's your journey with POKEMON\n"
	.string "{JPN}going?$"

Route119_Text_CatherineRematchDefeat:
	.string "{JPN}I'm still missing something...$"

Route119_Text_CatherinePostRematch:
	.string "{JPN}In the same way that you, as a TRAINER,\n"
	.string "{JPN}rely on your POKEMON, your POKEMON\l"
	.string "{JPN}rely on you.$"

Route119_Text_HughIntro:
	.string "{JPN}The vast sky holds untold promise!\p"
	.string "{JPN}Nothing can compare to the sheer\n"
	.string "{JPN}exhilaration of flight!$"

Route119_Text_HughDefeat:
	.string "{JPN}Down and out!$"

Route119_Text_HughPostBattle:
	.string "{JPN}My BIRD POKEMON made my dreams of\n"
	.string "{JPN}flying come true!$"

Route119_Text_PhilIntro:
	.string "{JPN}I'll show you the true potential of me\n"
	.string "{JPN}and my BIRD POKEMON!$"

Route119_Text_PhilDefeat:
	.string "{JPN}We lacked potential...$"

Route119_Text_PhilPostBattle:
	.string "{JPN}Ever since I was a little kid, I always\n"
	.string "{JPN}admired BIRD POKEMON...$"

Route119_Text_YasuIntro:
	.string "{JPN}To lurk in shadows, and live in\n"
	.string "{JPN}darkness... That is my destiny.\p"
	.string "{JPN}I emerge to challenge you!$"

Route119_Text_YasuDefeat:
	.string "{JPN}I admit defeat!$"

Route119_Text_YasuPostBattle:
	.string "{JPN}Those defeated in battle withdraw\n"
	.string "{JPN}quietly back into the shadows.\l"
	.string "{JPN}That, too, is destiny...$"

Route119_Text_TakashiIntro:
	.string "{JPN}If you're not on your guard,\n"
	.string "{JPN}you're in for some pain!$"

Route119_Text_TakashiDefeat:
	.string "{JPN}You're surprisingly good!$"

Route119_Text_TakashiPostBattle:
	.string "{JPN}My surprise attack ended in\n"
	.string "{JPN}failure...$"

Route119_Text_HideoIntro:
	.string "{JPN}To hide a tree, use a forest!$"

Route119_Text_HideoDefeat:
	.string "{JPN}I bow to your superiority.$"

Route119_Text_HideoPostBattle:
	.string "{JPN}To hide a tree, use a forest!\n"
	.string "{JPN}To hide a POKEMON, use a POKEMON!\p"
	.string "{JPN}There is no deep, hidden meaning\n"
	.string "{JPN}to that.$"

Route119_Text_ChrisIntro:
	.string "{JPN}You spoke to me...\n"
	.string "{JPN}So you want to challenge me!\p"
	.string "{JPN}Sure! I'll try out the POKEMON I caught\n"
	.string "{JPN}while SURFING!$"

Route119_Text_ChrisDefeat:
	.string "{JPN}I don't have a clue about what it\n"
	.string "{JPN}takes to win.$"

Route119_Text_ChrisPostBattle:
	.string "{JPN}Go for a SURF on my POKEMON...\p"
	.string "{JPN}Then fish off its back...\p"
	.string "{JPN}It's an indescribably luxuriant moment!$"

Route119_Text_FabianIntro:
	.string "{JPN}Hit me with a power chord!\n"
	.string "{JPN}Victory is mine!\l"
	.string "{JPN}It's our time to shine, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "{JPN}You showed me who's the boss!\n"
	.string "{JPN}We'll have to take the loss, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "{JPN}Hit me with another power chord!\n"
	.string "{JPN}Leave me alone!\l"
	.string "{JPN}Your win you have to atone!$"

Route119_Text_DaytonIntro:
	.string "{JPN}Hohoho!\n"
	.string "{JPN}I like kid TRAINERS!\l"
	.string "{JPN}Let's have a good one!$"

Route119_Text_DaytonDefeat:
	.string "{JPN}You're pretty amazing!\n"
	.string "{JPN}Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "{JPN}Hohoho!\n"
	.string "{JPN}I'll try emulating the pep of kid\l"
	.string "{JPN}TRAINERS like you!$"

Route119_Text_RachelIntro:
	.string "{JPN}Wherever and whenever I may be,\n"
	.string "{JPN}I always have my parasol in hand.$"

Route119_Text_RachelDefeat:
	.string "{JPN}Oh, but...\n"
	.string "{JPN}That's not fair.$"

Route119_Text_RachelPostBattle:
	.string "{JPN}You're asking if my parasol is heavy?\n"
	.string "{JPN}Your BAG is filled with more junk than\l"
	.string "{JPN}I ever carry around.$"

Route120_Text_ColinIntro:
	.string "{JPN}Do you have any moves that can strike\n"
	.string "{JPN}a flying POKEMON?$"

Route120_Text_ColinDefeat:
	.string "{JPN}You soared above me!$"

Route120_Text_ColinPostBattle:
	.string "{JPN}The move FLY is convenient,\n"
	.string "{JPN}don't you think?\p"
	.string "{JPN}While the POKEMON is flying,\n"
	.string "{JPN}almost no moves can strike it.$"

Route120_Text_RobertIntro:
	.string "{JPN}My POKEMON is strong!\n"
	.string "{JPN}How about yours?$"

Route120_Text_RobertDefeat:
	.string "{JPN}Your POKEMON were stronger...$"

Route120_Text_RobertPostBattle:
	.string "{JPN}A POKEMON that grows steadily is one\n"
	.string "{JPN}you can count on.$"

Route120_Text_RobertRegister:
	.string "{JPN}You can be counted on to get better.\n"
	.string "{JPN}I'd like to register you in my POKeNAV!$"

Route120_Text_RobertRematchIntro:
	.string "{JPN}A POKEMON that grows steadily is one\n"
	.string "{JPN}you can count on.$"

Route120_Text_RobertRematchDefeat:
	.string "{JPN}Your POKEMON are seriously strong.$"

Route120_Text_RobertPostRematch:
	.string "{JPN}My POKEMON are growing stronger.\n"
	.string "{JPN}I have to grow stronger, too.$"

Route120_Text_LorenzoIntro:
	.string "{JPN}I'll check your POKEMON and see if\n"
	.string "{JPN}they're fit for the outdoors.$"

Route120_Text_LorenzoDefeat:
	.string "{JPN}With POKEMON that strong, you're in\n"
	.string "{JPN}no danger of needing rescue!$"

Route120_Text_LorenzoPostBattle:
	.string "{JPN}To travel wherever your heart desires\n"
	.string "{JPN}with POKEMON...\l"
	.string "{JPN}That's the joy of being a TRAINER.$"

Route120_Text_JennaIntro:
	.string "{JPN}How's your physical fitness?\n"
	.string "{JPN}If you're not fit, you could have a\l"
	.string "{JPN}rough time in critical situations.$"

Route120_Text_JennaDefeat:
	.string "{JPN}I'm totally fit, but...$"

Route120_Text_JennaPostBattle:
	.string "{JPN}Fitness training is in my routine.\n"
	.string "{JPN}I always run with my POKEMON.$"

Route120_Text_JeffreyIntro:
	.string "{JPN}... ... ... ... ... ...\n"
	.string "{JPN}... ... ... ... ... ...\l"
	.string "{JPN}Want to battle?$"

Route120_Text_JeffreyDefeat:
	.string "{JPN}Lost it...$"

Route120_Text_JeffreyPostBattle:
	.string "{JPN}... ... ... ... ... ...\n"
	.string "{JPN}... ... ... ... ... ...\l"
	.string "{JPN}I'll try harder...$"

Route120_Text_JeffreyRegister:
	.string "{JPN}... ... ... ... ... ...\n"
	.string "{JPN}... ... ... ... ... ...\l"
	.string "{JPN}Do you have a POKeNAV...?$"

Route120_Text_JeffreyRematchIntro:
	.string "{JPN}... ... ... ... ... ...\n"
	.string "{JPN}... ... ... ... ... ...\l"
	.string "{JPN}Want to battle again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "{JPN}... ... ... ... ... ...\n"
	.string "{JPN}I lost again...$"

Route120_Text_JeffreyPostRematch:
	.string "{JPN}... ... ... ... ... ...\n"
	.string "{JPN}... ... ... ... ... ...\l"
	.string "{JPN}I'll try harder...\l"
	.string "{JPN}For my precious BUG POKEMON...$"

Route120_Text_JenniferIntro:
	.string "{JPN}POKEMON have many special abilities.\n"
	.string "{JPN}If you want to become a first-class\l"
	.string "{JPN}TRAINER, learn about them.$"

Route120_Text_JenniferDefeat:
	.string "{JPN}You're obviously thinking.$"

Route120_Text_JenniferPostBattle:
	.string "{JPN}The special abilities of POKEMON\n"
	.string "{JPN}will make battle styles change.$"

Route120_Text_ChipIntro:
	.string "{JPN}Who might you be?\p"
	.string "{JPN}Are you perhaps searching for ancient\n"
	.string "{JPN}ruins that are rumored to possibly\l"
	.string "{JPN}exist according to legend?$"

Route120_Text_ChipDefeat:
	.string "{JPN}What a disgraceful setback...$"

Route120_Text_ChipPostBattle:
	.string "{JPN}That giant rock... I would like to\n"
	.string "{JPN}believe it may indeed contain ancient\l"
	.string "{JPN}ruins. But I see no entrance.$"

Route120_Text_ClarissaIntro:
	.string "{JPN}Why am I carrying this parasol?\p"
	.string "{JPN}I'll tell you if you can win against me.$"

Route120_Text_ClarissaDefeat:
	.string "{JPN}A parasol can't ward off POKEMON\n"
	.string "{JPN}attacks...$"

Route120_Text_ClarissaPostBattle:
	.string "{JPN}I don't think strong sunlight is good\n"
	.string "{JPN}for my POKEMON.\l"
	.string "{JPN}So I shield them with my parasol.$"

Route120_Text_AngelicaIntro:
	.string "{JPN}Me, POKEMON, and my parasol...\p"
	.string "{JPN}If any one of them is missing,\n"
	.string "{JPN}the picture of beauty will be ruined.$"

Route120_Text_AngelicaDefeat:
	.string "{JPN}You've completely ruined my beauty...$"

Route120_Text_AngelicaPostBattle:
	.string "{JPN}A parasol wouldn't suit you at all.\p"
	.string "{JPN}Why, something like this would only\n"
	.string "{JPN}get in your way.$"

Route120_Text_KeigoIntro:
	.string "{JPN}I will adopt the movements of POKEMON\n"
	.string "{JPN}and create new ninja techniques.$"

Route120_Text_KeigoDefeat:
	.string "{JPN}The creation of new ninja techniques\n"
	.string "{JPN}is but a distant dream...$"

Route120_Text_KeigoPostBattle:
	.string "{JPN}Perhaps I ought to apprentice under\n"
	.string "{JPN}a ninja sensei.$"

Route120_Text_RileyIntro:
	.string "{JPN}We ninja conceal ourselves under our\n"
	.string "{JPN}camouflage cloaks.\l"
	.string "{JPN}I bet you didn't know where I was!$"

Route120_Text_RileyDefeat:
	.string "{JPN}I lost!\n"
	.string "{JPN}I should camouflage my shame!$"

Route120_Text_RileyPostBattle:
	.string "{JPN}Our camouflage cloaks are all\n"
	.string "{JPN}handmade.$"

Route120_Text_CallieIntro:
	.string "{JPN}If you don't pay attention,\n"
	.string "{JPN}you could get hurt!$"

Route120_Text_CallieDefeat:
	.string "{JPN}Ouch!\n"
	.string "{JPN}I was the one to get hurt.$"

Route120_Text_CalliePostBattle:
	.string "{JPN}I wonder... Should I evolve my POKEMON?\n"
	.string "{JPN}They're cute the way they are, though.$"

Route120_Text_LeonelIntro:
	.string "{JPN}Your party POKEMON...\n"
	.string "{JPN}Do you have different types?$"

Route120_Text_LeonelDefeat:
	.string "{JPN}I've seen your policy in action!$"

Route120_Text_LeonelPostBattle:
	.string "{JPN}I think it's awesome you're so strong\n"
	.string "{JPN}battling with your favorite POKEMON.$"

Route121_Text_VanessaIntro:
	.string "{JPN}Will you play with my delightfully\n"
	.string "{JPN}pretty POKEMON?$"

Route121_Text_VanessaDefeat:
	.string "{JPN}This isn't what I meant!$"

Route121_Text_VanessaPostBattle:
	.string "{JPN}I'm going to a CONTEST in LILYCOVE.\p"
	.string "{JPN}My POKEMON should have no problem\n"
	.string "{JPN}sweeping the MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "{JPN}With my POKEMON, I have traveled\n"
	.string "{JPN}to the world's four corners.\p"
	.string "{JPN}You might say I have some confidence\n"
	.string "{JPN}in my abilities.$"

Route121_Text_WalterDefeat:
	.string "{JPN}Ah, well played.$"

Route121_Text_WalterPostBattle:
	.string "{JPN}I would like to circle the globe once\n"
	.string "{JPN}again with my POKEMON.$"

Route121_Text_WalterRegister:
	.string "{JPN}Your POKEMON prowess is remarkable.\n"
	.string "{JPN}Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "{JPN}With my POKEMON, I have traveled\n"
	.string "{JPN}to the world's four corners.\p"
	.string "{JPN}You might say I have some confidence\n"
	.string "{JPN}in my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "{JPN}Ah, well played.$"

Route121_Text_WalterPostRematch:
	.string "{JPN}Your POKEMON and you...\p"
	.string "{JPN}Your prowess together will be\n"
	.string "{JPN}considered strong, even overseas.$"

Route121_Text_TammyIntro:
	.string "{JPN}There are powers beyond our\n"
	.string "{JPN}understanding in the world...$"

Route121_Text_TammyDefeat:
	.string "{JPN}I have lost...$"

Route121_Text_TammyPostBattle:
	.string "{JPN}MT. PYRE...\n"
	.string "{JPN}There is a mysterious power\l"
	.string "{JPN}at work there...$"

Route121_Text_KateIntro:
	.string "{JPN}KATE: Together, we're fearless!\n"
	.string "{JPN}We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:
	.string "{JPN}KATE: I blew it in front of my junior\n"
	.string "{JPN}student partner...$"

Route121_Text_KatePostBattle:
	.string "{JPN}KATE: When someone's relying on me,\n"
	.string "{JPN}I get this urge to look cool in front\l"
	.string "{JPN}of them...$"

Route121_Text_KateNotEnoughMons:
	.string "{JPN}KATE: If you've only got one POKEMON,\n"
	.string "{JPN}we can't battle with you.\p"
	.string "{JPN}That would be bullying.$"

Route121_Text_JoyIntro:
	.string "{JPN}JOY: Together, we're fearless!\n"
	.string "{JPN}We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:
	.string "{JPN}JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:
	.string "{JPN}JOY: Ehehe, I'll have to train with KATE,\n"
	.string "{JPN}my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "{JPN}JOY: You need at least two POKEMON\n"
	.string "{JPN}if you're going to challenge us!$"

Route121_Text_JessicaIntro:
	.string "{JPN}Stop! Have a good look at my precious\n"
	.string "{JPN}POKEMON!$"

Route121_Text_JessicaDefeat:
	.string "{JPN}Oh, how dare you!\n"
	.string "{JPN}Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:
	.string "{JPN}Maybe I'll go catch more POKEMON at\n"
	.string "{JPN}the SAFARI.$"

Route121_Text_JessicaRegister:
	.string "{JPN}I took it easy on you this time!\n"
	.string "{JPN}It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro:
	.string "{JPN}My precious POKEMON grew!\n"
	.string "{JPN}Have a good look!$"

Route121_Text_JessicaRematchDefeat:
	.string "{JPN}Oh, how dare you!\n"
	.string "{JPN}You still won't take it easy!$"

Route121_Text_JessicaPostRematch:
	.string "{JPN}Maybe I'll go catch more POKEMON at\n"
	.string "{JPN}the SAFARI.$"

Route121_Text_CristinIntro:
	.string "{JPN}I have this routine.\n"
	.string "{JPN}Defeat five TRAINERS a day.\l"
	.string "{JPN}Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "{JPN}No!\n"
	.string "{JPN}You're horrid!$"

Route121_Text_CristinPostBattle:
	.string "{JPN}I didn't expect to lose this easily...\n"
	.string "{JPN}I'll win next time!$"

Route121_Text_CristinRegister:
	.string "{JPN}That was total humiliation!\n"
	.string "{JPN}I won't forget you...\l"
	.string "{JPN}Hand over your POKeNAV!$"

Route121_Text_CristinRematchIntro:
	.string "{JPN}I have this new routine.\n"
	.string "{JPN}Defeat ten TRAINERS a day.\l"
	.string "{JPN}Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "{JPN}Wait! That's nasty!\n"
	.string "{JPN}I demand a rematch!$"

Route121_Text_CristinPostRematch:
	.string "{JPN}An opponent I just can't beat...\n"
	.string "{JPN}Snivel...\l"
	.string "{JPN}I can't believe this is happening...$"

Route121_Text_CaleIntro:
	.string "{JPN}Can't you see that I have all this\n"
	.string "{JPN}stuff with me?\p"
	.string "{JPN}Despite that, you still insist that\n"
	.string "{JPN}we battle?$"

Route121_Text_CaleDefeat:
	.string "{JPN}Of course I lost!\n"
	.string "{JPN}I'm holding stuff in both hands!$"

Route121_Text_CalePostBattle:
	.string "{JPN}I bought too much stuff at\n"
	.string "{JPN}the LILYCOVE DEPT. STORE.\p"
	.string "{JPN}It's up the road from here.\n"
	.string "{JPN}I wish I had a BAG like yours.$"

Route121_Text_MylesIntro:
	.string "{JPN}There's nothing I love more than\n"
	.string "{JPN}checking out other people's POKEMON!$"

Route121_Text_MylesDefeat:
	.string "{JPN}Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "{JPN}They're great, your POKEMON!\n"
	.string "{JPN}How do you raise them?$"

Route121_Text_PatIntro:
	.string "{JPN}I want everybody to see the POKEMON\n"
	.string "{JPN}I've raised!$"

Route121_Text_PatDefeat:
	.string "{JPN}Wow!\n"
	.string "{JPN}Spectacular!$"

Route121_Text_PatPostBattle:
	.string "{JPN}I raise every POKEMON with the same\n"
	.string "{JPN}love and care--I don't pick favorites.$"

Route121_Text_MarcelIntro:
	.string "{JPN}My POKEMON have never tasted defeat!\n"
	.string "{JPN}On their next win, I'm entering them\l"
	.string "{JPN}in CONTESTS.$"

Route121_Text_MarcelDefeat:
	.string "{JPN}Oh, now what happened here?$"

Route121_Text_MarcelPostBattle:
	.string "{JPN}I may have to train my gang some more\n"
	.string "{JPN}before entering any CONTEST.$"

Route123_Text_WendyIntro:
	.string "{JPN}Want to determine how strong you are?\n"
	.string "{JPN}I'll be the test!$"

Route123_Text_WendyDefeat:
	.string "{JPN}You passed with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "{JPN}To best even me...\n"
	.string "{JPN}Your strength is marvelous!$"

Route123_Text_BraxtonIntro:
	.string "{JPN}You seem to have a big collection\n"
	.string "{JPN}of GYM BADGES.\p"
	.string "{JPN}Let me see if you're actually worthy of\n"
	.string "{JPN}those BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "{JPN}Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "{JPN}You did your BADGES proud in that\n"
	.string "{JPN}match!$"

Route123_Text_VioletIntro:
	.string "{JPN}They say that good times are filled\n"
	.string "{JPN}with good aromas.$"

Route123_Text_VioletDefeat:
	.string "{JPN}Oh...\n"
	.string "{JPN}I smell the bitter scent of misery...$"

Route123_Text_VioletPostBattle:
	.string "{JPN}The BERRY MASTER's garden is filled\n"
	.string "{JPN}with uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "{JPN}Being a psychic is about willpower.\p"
	.string "{JPN}I've willed myself not to lose to\n"
	.string "{JPN}anyone. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "{JPN}I feel sad...$"

Route123_Text_CameronPostBattle:
	.string "{JPN}Being a psychic is about willpower.\n"
	.string "{JPN}I thought I wouldn't lose to you...$"

Route123_Text_CameronRegister:
	.string "{JPN}I sense it!\n"
	.string "{JPN}You and I shall battle again!\l"
	.string "{JPN}I can't tell if I'll win, though...\p"
	.string "{JPN}Let's see your POKeNAV.$"

Route123_Text_CameronRematchIntro:
	.string "{JPN}I've convinced myself that I won't\n"
	.string "{JPN}lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "{JPN}I feel sad...$"

Route123_Text_CameronPostRematch:
	.string "{JPN}I should train at MT. PYRE...\n"
	.string "{JPN}I'll never beat you this way...$"

Route123_Text_JackiIntro:
	.string "{JPN}Don't be too happy if your POKEMON\n"
	.string "{JPN}develop psychic powers.\p"
	.string "{JPN}You need to refine those powers to\n"
	.string "{JPN}make them really useful.$"

Route123_Text_JackiDefeat:
	.string "{JPN}Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "{JPN}We all have psychic powers.\n"
	.string "{JPN}We've just forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "{JPN}I would like to face you again.\n"
	.string "{JPN}Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "{JPN}Have you awoken the psychic powers\n"
	.string "{JPN}within you?$"

Route123_Text_JackiRematchDefeat:
	.string "{JPN}Astounding!$"

Route123_Text_JackiPostRematch:
	.string "{JPN}Your power with POKEMON...\n"
	.string "{JPN}That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "{JPN}MIU: Hello, TRAINER. I hope your\n"
	.string "{JPN}POKEMON won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "{JPN}MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "{JPN}MIU: TRAINER, your POKEMON are\n"
	.string "{JPN}strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "{JPN}MIU: It's no fun to battle if you\n"
	.string "{JPN}don't have two POKEMON.$"

Route123_Text_YukiIntro:
	.string "{JPN}YUKI: Okay!\n"
	.string "{JPN}We're beating the TRAINER's POKEMON!$"

Route123_Text_YukiDefeat:
	.string "{JPN}YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "{JPN}YUKI: Why are you so strong?\n"
	.string "{JPN}We've never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "{JPN}YUKI: It's no fun to battle if you\n"
	.string "{JPN}don't have two POKEMON.$"

Route123_Text_KindraIntro:
	.string "{JPN}MT. PYRE...\n"
	.string "{JPN}Where the spirits of POKEMON sleep...\l"
	.string "{JPN}Will your POKEMON sleep?$"

Route123_Text_KindraDefeat:
	.string "{JPN}Overflowing with vitality...$"

Route123_Text_KindraPostBattle:
	.string "{JPN}MT. PYRE...\n"
	.string "{JPN}Where the spirits of POKEMON sleep...\p"
	.string "{JPN}It must overflow with a power that\n"
	.string "{JPN}soothes spirits...$"

Route123_Text_FernandoIntro:
	.string "{JPN}I'll turn your lights out while\n"
	.string "{JPN}I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "{JPN}Hey, hold it!\n"
	.string "{JPN}I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "{JPN}You're rock steady.\n"
	.string "{JPN}I'd like to write a tune about you.$"

Route123_Text_FernandoRegister:
	.string "{JPN}The next time, lend your ears to\n"
	.string "{JPN}the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "{JPN}Today's the day I'm going to do it!\n"
	.string "{JPN}I'll turn out your lights before\l"
	.string "{JPN}I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "{JPN}Hey, hold it!\n"
	.string "{JPN}I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "{JPN}I thought you'd be so enthralled\n"
	.string "{JPN}by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "{JPN}This is my awesome BUG POKEMON!\n"
	.string "{JPN}My big brother got it for me.$"

Route123_Text_DavisDefeat:
	.string "{JPN}Waaaah!\n"
	.string "{JPN}You meanie!$"

Route123_Text_DavisPostBattle:
	.string "{JPN}Don't tell my brother I lost.\n"
	.string "{JPN}You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "{JPN}My confidence will get a boost by\n"
	.string "{JPN}beating someone obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "{JPN}There goes my confidence...$"

Route123_Text_JazmynPostBattle:
	.string "{JPN}They say that you can't judge a person\n"
	.string "{JPN}by their appearance.\p"
	.string "{JPN}But often, their looks don't lie...$"

Route123_Text_FrederickIntro:
	.string "{JPN}Hello, child!\n"
	.string "{JPN}Can you spare some time?$"

Route123_Text_FrederickDefeat:
	.string "{JPN}Ah, a mighty capable child!\n"
	.string "{JPN}Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "{JPN}Contribute to your allowance?\n"
	.string "{JPN}Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro:
	.string "{JPN}I have to tell you, BIRD POKEMON\n"
	.string "{JPN}are my obsession!\p"
	.string "{JPN}Birds are cool!\n"
	.string "{JPN}They're the best!$"

Route123_Text_AlbertoDefeat:
	.string "{JPN}Even in defeat, BIRD POKEMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "{JPN}I gather BIRD POKEMON feathers that\n"
	.string "{JPN}scatter during battles.\p"
	.string "{JPN}I'm going to make a hat with\n"
	.string "{JPN}BIRD POKEMON feathers.$"

Route123_Text_EdIntro:
	.string "{JPN}When there are no TRAINERS around,\n"
	.string "{JPN}I let my POKEMON battle each other.\l"
	.string "{JPN}I watch them.$"

Route123_Text_EdDefeat:
	.string "{JPN}I kind of like your POKEMON.$"

Route123_Text_EdPostBattle:
	.string "{JPN}Hehe, I'm swiping your battling ideas!\n"
	.string "{JPN}I think they'll make me better.$"

Route123_Text_JonasIntro:
	.string "{JPN}I lay in ambush, and a TRAINER has\n"
	.string "{JPN}landed in my trap!$"

Route123_Text_JonasDefeat:
	.string "{JPN}If you don't lose, how am I supposed\n"
	.string "{JPN}to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "{JPN}I'm going to ambush a weaker-looking\n"
	.string "{JPN}TRAINER next time.$"

Route123_Text_KayleyIntro:
	.string "{JPN}I just bought this parasol.\n"
	.string "{JPN}My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "{JPN}You're better than me by about\n"
	.string "{JPN}five times!$"

Route123_Text_KayleyPostBattle:
	.string "{JPN}Using accessories effectively is\n"
	.string "{JPN}the secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "{JPN}Hey, are you lost at sea?\p"
	.string "{JPN}If you can beat my POKEMON,\n"
	.string "{JPN}I can serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "{JPN}I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:
	.string "{JPN}Many people lose their bearings at sea.\p"
	.string "{JPN}If you're that sort, you should refer\n"
	.string "{JPN}to the POKeNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "{JPN}Hm! You're riding a POKEMON instead\n"
	.string "{JPN}of swimming yourself...\p"
	.string "{JPN}I am envious!$"

Route124_Text_RolandDefeat:
	.string "{JPN}Oh!\n"
	.string "{JPN}I can't...$"

Route124_Text_RolandPostBattle:
	.string "{JPN}I'm getting chilled...\n"
	.string "{JPN}I've been in the water too long...\p"
	.string "{JPN}I wish I could ride a POKEMON like you...$"

Route124_Text_JennyIntro:
	.string "{JPN}If you just float in the sea like\n"
	.string "{JPN}this, POKEMON come around to play.$"

Route124_Text_JennyDefeat:
	.string "{JPN}Oh, darn.\n"
	.string "{JPN}I've gone and lost.$"

Route124_Text_JennyPostBattle:
	.string "{JPN}While swimming, I noticed that some\n"
	.string "{JPN}POKEMON attack, and some just watch.\p"
	.string "{JPN}I guess POKEMON have personalities\n"
	.string "{JPN}of their own.$"

Route124_Text_JennyRegister:
	.string "{JPN}It's only on a whim, but maybe I'll get\n"
	.string "{JPN}you to register me in your POKeNAV.$"

Route124_Text_JennyRematchIntro:
	.string "{JPN}If you just float in the sea like this,\n"
	.string "{JPN}TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "{JPN}That's strange...\n"
	.string "{JPN}I lost again...$"

Route124_Text_JennyPostRematch:
	.string "{JPN}This has nothing to do with anything,\n"
	.string "{JPN}but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "{JPN}I'm growing bored of swimming...\n"
	.string "{JPN}How about a battle?$"

Route124_Text_GraceDefeat:
	.string "{JPN}I had no idea that you were\n"
	.string "{JPN}this strong!$"

Route124_Text_GracePostBattle:
	.string "{JPN}All the effort you put in must have\n"
	.string "{JPN}made you this strong.$"

Route124_Text_ChadIntro:
	.string "{JPN}Fufufufu... I dive deep underwater\n"
	.string "{JPN}to go deep under cover.\l"
	.string "{JPN}Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:
	.string "{JPN}Glub, glub, glub...\n"
	.string "{JPN}I'm sinking...$"

Route124_Text_ChadPostBattle:
	.string "{JPN}I have it on good authority that\n"
	.string "{JPN}there's a DIVE spot around here.\p"
	.string "{JPN}It gives me the urge to go deep\n"
	.string "{JPN}again...$"

Route124_Text_LilaIntro:
	.string "{JPN}LILA: Sigh...\p"
	.string "{JPN}Here I am in the sea, but who's with me?\n"
	.string "{JPN}My little brother!\p"
	.string "{JPN}Let's battle so I won't have to dwell\n"
	.string "{JPN}on that!$"

Route124_Text_LilaDefeat:
	.string "{JPN}LILA: ROY! It's your fault we lost!\n"
	.string "{JPN}You're in for it later!$"

Route124_Text_LilaPostBattle:
	.string "{JPN}LILA: Sigh...\p"
	.string "{JPN}If only it wasn't my little brother\n"
	.string "{JPN}next to me, but a nice boyfriend...$"

Route124_Text_LilaNotEnoughMons:
	.string "{JPN}LILA: You're planning to battle us?\n"
	.string "{JPN}Not unless you have two POKEMON.$"

Route124_Text_RoyIntro:
	.string "{JPN}ROY: My big sister is tough at POKEMON!\p"
	.string "{JPN}Don't cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "{JPN}ROY: Uh-oh...\n"
	.string "{JPN}My big sister will chew me out...$"

Route124_Text_RoyPostBattle:
	.string "{JPN}ROY: My big sister is really scary\n"
	.string "{JPN}when she gets angry.\p"
	.string "{JPN}That's why she doesn't have a\n"
	.string "{JPN}boyfriend.$"

Route124_Text_LilaRoyRegister:
	.string "{JPN}ROY: Will you battle with us again?\n"
	.string "{JPN}But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "{JPN}ROY: Did you want to battle us?\n"
	.string "{JPN}Bring two POKEMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "{JPN}LILA: Sigh...\p"
	.string "{JPN}Here I am in the sea, but who's with me?\n"
	.string "{JPN}My little brother!\p"
	.string "{JPN}Oh, hi, it's been a while. Let's battle\n"
	.string "{JPN}so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "{JPN}LILA: ROY!\n"
	.string "{JPN}It's your fault we lost again!\p"
	.string "{JPN}We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "{JPN}LILA: Sigh...\p"
	.string "{JPN}If I had a nice boyfriend, we'd beat\n"
	.string "{JPN}anyone with lovely combinations...$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "{JPN}LILA: You're planning to battle us?\n"
	.string "{JPN}Not unless you have two POKEMON.$"

Route124_Text_RoyRematchIntro:
	.string "{JPN}ROY: If we lose, I'll catch heck.\n"
	.string "{JPN}I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "{JPN}ROY: Uh-oh...\n"
	.string "{JPN}My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "{JPN}ROY: My big sister is really scary\n"
	.string "{JPN}when she gets angry.\p"
	.string "{JPN}She's going to make me train really\n"
	.string "{JPN}hard with POKEMON later...$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "{JPN}ROY: Did you want to battle us?\n"
	.string "{JPN}Bring two POKEMON, then.$"

Route124_Text_DeclanIntro:
	.string "{JPN}Here I am swimming by my lonesome\n"
	.string "{JPN}on this wide, beautiful sea.\p"
	.string "{JPN}There's no other word for it.\n"
	.string "{JPN}This is pathetic!$"

Route124_Text_DeclanDefeat:
	.string "{JPN}I'm feeling blue.\n"
	.string "{JPN}Blue as the sky...$"

Route124_Text_DeclanPostBattle:
	.string "{JPN}I should chat up lady SWIMMERS\n"
	.string "{JPN}and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "{JPN}I'm not going to lose to some\n"
	.string "{JPN}surfer TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "{JPN}I've only got sweat in my eyes!\n"
	.string "{JPN}I am not crying!$"

Route124_Text_IsabellaPostBattle:
	.string "{JPN}You can find pretty colored shards\n"
	.string "{JPN}of things around here.$"

Route125_Text_NolenIntro:
	.string "{JPN}I heard you approaching, so I hung\n"
	.string "{JPN}around for you!$"

Route125_Text_NolenDefeat:
	.string "{JPN}I surrender!$"

Route125_Text_NolenPostBattle:
	.string "{JPN}Sound travels faster in water than\n"
	.string "{JPN}it does through air.$"

Route125_Text_StanIntro:
	.string "{JPN}Hey, there!\n"
	.string "{JPN}Check out my sweet POKEMON!$"

Route125_Text_StanDefeat:
	.string "{JPN}I floundered...$"

Route125_Text_StanPostBattle:
	.string "{JPN}I was blown away by HORSEA's charm,\n"
	.string "{JPN}so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "{JPN}I'm tired of swimming.\n"
	.string "{JPN}Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:
	.string "{JPN}You're too much!$"

Route125_Text_TanyaPostBattle:
	.string "{JPN}Whew...\n"
	.string "{JPN}Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:
	.string "{JPN}How would you like to take on the\n"
	.string "{JPN}WATER-type POKEMON I raised?$"

Route125_Text_SharonDefeat:
	.string "{JPN}Lost it...$"

Route125_Text_SharonPostBattle:
	.string "{JPN}Your power... You're the real deal.\n"
	.string "{JPN}I'm amazed!$"

Route125_Text_ErnestIntro:
	.string "{JPN}Ahoy! I'm a buff, tough SAILOR!\n"
	.string "{JPN}I've braved the world's seas!$"

Route125_Text_ErnestDefeat:
	.string "{JPN}Gwrroooar!\n"
	.string "{JPN}I couldn't win!$"

Route125_Text_ErnestPostBattle:
	.string "{JPN}The tide ebbs and flows inside the\n"
	.string "{JPN}SHOAL CAVE.\p"
	.string "{JPN}By the way, it's about six hours from\n"
	.string "{JPN}high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "{JPN}Register me in your POKeNAV,\n"
	.string "{JPN}and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro:
	.string "{JPN}It's high time I get my payback\n"
	.string "{JPN}from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "{JPN}I couldn't win!\n"
	.string "{JPN}I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "{JPN}The SHOAL CAVE...\p"
	.string "{JPN}There are places you can and can't\n"
	.string "{JPN}get to depending on the rise and fall\l"
	.string "{JPN}of the tide.\p"
	.string "{JPN}By the way, it's about six hours from\n"
	.string "{JPN}high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "{JPN}KIM: A funny old man lives in the\n"
	.string "{JPN}SHOAL CAVE. Someone told me.\l"
	.string "{JPN}Are you going to see him, too?$"

Route125_Text_KimDefeat:
	.string "{JPN}KIM: I thought we would win.$"

Route125_Text_KimPostBattle:
	.string "{JPN}KIM: A funny old man lives in the\n"
	.string "{JPN}SHOAL CAVE, doesn't he?\p"
	.string "{JPN}Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "{JPN}KIM: No, no, no! You need two POKEMON,\n"
	.string "{JPN}or it's just no good!$"

Route125_Text_IrisIntro:
	.string "{JPN}IRIS: KIM, can you tell me what we're\n"
	.string "{JPN}looking for out here?$"

Route125_Text_IrisDefeat:
	.string "{JPN}IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "{JPN}IRIS: KIM, are we really going into\n"
	.string "{JPN}the SHOAL CAVE?\l"
	.string "{JPN}We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:
	.string "{JPN}IRIS: Oh, we could never, ever do\n"
	.string "{JPN}anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "{JPN}Why would a BIRDKEEPER like me\n"
	.string "{JPN}come out to the sea?$"

Route125_Text_PresleyDefeat:
	.string "{JPN}Okay.\n"
	.string "{JPN}I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle:
	.string "{JPN}I put a message in a bottle and put\n"
	.string "{JPN}it out to sea.\p"
	.string "{JPN}I'm sure that a girl SWIMMER will\n"
	.string "{JPN}find it!$"

Route125_Text_AuronIntro:
	.string "{JPN}Hey! Was it you throwing garbage\n"
	.string "{JPN}into the sea?$"

Route125_Text_AuronDefeat:
	.string "{JPN}Oh, you weren't throwing trash into\n"
	.string "{JPN}the sea.$"

Route125_Text_AuronPostBattle:
	.string "{JPN}I found an unsightly bottle bobbing\n"
	.string "{JPN}in the waves earlier.\p"
	.string "{JPN}It angers me that someone would\n"
	.string "{JPN}pollute the sea!$"

Route126_Text_BarryIntro:
	.string "{JPN}Swimming is a full-body workout!\n"
	.string "{JPN}You will get fit!$"

Route126_Text_BarryDefeat:
	.string "{JPN}I admit it!\n"
	.string "{JPN}You win!$"

Route126_Text_BarryPostBattle:
	.string "{JPN}Thanks to my daily swimming routine...\n"
	.string "{JPN}Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:
	.string "{JPN}This towering white mountain of rock\n"
	.string "{JPN}is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "{JPN}I was done in?$"

Route126_Text_DeanPostBattle:
	.string "{JPN}I can't find the entrance to\n"
	.string "{JPN}SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:
	.string "{JPN}Ufufufufu!\n"
	.string "{JPN}I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "{JPN}My fantasy burst as if it were a bubble!\n"
	.string "{JPN}Blub, blub, blub...$"

Route126_Text_NikkiPostBattle:
	.string "{JPN}You thrashed me... I want to\n"
	.string "{JPN}disappear in a wave of despair...$"

Route126_Text_BrendaIntro:
	.string "{JPN}Hello, kiddo!\n"
	.string "{JPN}Want a battle with me?$"

Route126_Text_BrendaDefeat:
	.string "{JPN}Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "{JPN}I love frolicking with POKEMON in\n"
	.string "{JPN}the sea like this!$"

Route126_Text_PabloIntro:
	.string "{JPN}Check out this sculpted body!\n"
	.string "{JPN}I'm more cut than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "{JPN}Whoops! Too strong!\n"
	.string "{JPN}Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "{JPN}Losing to you stimulated my senses!\n"
	.string "{JPN}I'll train myself and POKEMON harder!$"

Route126_Text_PabloRegister:
	.string "{JPN}Yep, you're not bad at all!\n"
	.string "{JPN}I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro:
	.string "{JPN}Check out this beautiful body!\n"
	.string "{JPN}I'm more shapely than a SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "{JPN}Whoops! Really too strong!\n"
	.string "{JPN}Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "{JPN}I'm going to train even harder!\n"
	.string "{JPN}You're a great motivator!\l"
	.string "{JPN}You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "{JPN}I couldn't even swim last year,\n"
	.string "{JPN}but now I'm a decent SWIMMER.\p"
	.string "{JPN}I think I'm capable of anything now.$"

Route126_Text_LeonardoDefeat:
	.string "{JPN}Sheesh, getting greedy didn't do\n"
	.string "{JPN}a thing for me.$"

Route126_Text_LeonardoPostBattle:
	.string "{JPN}If you practice at something,\n"
	.string "{JPN}you will get better at it.\p"
	.string "{JPN}You're young--don't be afraid to\n"
	.string "{JPN}try all sorts of things!$"

Route126_Text_IsobelIntro:
	.string "{JPN}If seawater gets up your nose,\n"
	.string "{JPN}doesn't it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "{JPN}Ack! Why, you...\n"
	.string "{JPN}Glub!$"

Route126_Text_IsobelPostBattle:
	.string "{JPN}Ooh, I choked on some water!\n"
	.string "{JPN}It's bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "{JPN}I'm throwing my whole heart\n"
	.string "{JPN}into this!$"

Route126_Text_SiennaDefeat:
	.string "{JPN}You had more heart!$"

Route126_Text_SiennaPostBattle:
	.string "{JPN}I need to cool down now...\n"
	.string "{JPN}I think I'll go for a dive.$"

Route127_Text_CamdenIntro:
	.string "{JPN}I can see it in your face.\n"
	.string "{JPN}You want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "{JPN}Awawawawawa...$"

Route127_Text_CamdenPostBattle:
	.string "{JPN}A well-played match leaves me feeling\n"
	.string "{JPN}refreshed and serene.$"

Route127_Text_DonnyIntro:
	.string "{JPN}Do you have a rival whom you just\n"
	.string "{JPN}hate to lose against?$"

Route127_Text_DonnyDefeat:
	.string "{JPN}Arrrgh!\n"
	.string "{JPN}I hate losing!$"

Route127_Text_DonnyPostBattle:
	.string "{JPN}If you have a rival, don't you get the\n"
	.string "{JPN}feeling that you have to keep getting\l"
	.string "{JPN}better?$"

Route127_Text_JonahIntro:
	.string "{JPN}Through fishing, I have attained a\n"
	.string "{JPN}state of becalmed serenity...\p"
	.string "{JPN}Please, allow me to demonstrate...$"

Route127_Text_JonahDefeat:
	.string "{JPN}Though I have lost, my heart remains\n"
	.string "{JPN}calm...$"

Route127_Text_JonahPostBattle:
	.string "{JPN}It matters not that I catch nothing.\n"
	.string "{JPN}The line remains in the water...$"

Route127_Text_HenryIntro:
	.string "{JPN}Whoops! Don't tell me I snagged\n"
	.string "{JPN}a SURFING POKEMON?$"

Route127_Text_HenryDefeat:
	.string "{JPN}I can't keep up!$"

Route127_Text_HenryPostBattle:
	.string "{JPN}It'd be a handful if I hooked\n"
	.string "{JPN}your tough POKEMON!$"

Route127_Text_RogerIntro:
	.string "{JPN}Well, hey! This is a match between\n"
	.string "{JPN}a POKEMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:
	.string "{JPN}No! My line's all tangled!\n"
	.string "{JPN}The party's over!$"

Route127_Text_RogerPostBattle:
	.string "{JPN}My fishing line's doing a dance!\n"
	.string "{JPN}The tangle tango! Hahaha, snarl!$"

Route127_Text_AidanIntro:
	.string "{JPN}BIRD POKEMON have excellent vision.\n"
	.string "{JPN}They spot prey from great heights.$"

Route127_Text_AidanDefeat:
	.string "{JPN}Whew... I give up.$"

Route127_Text_AidanPostBattle:
	.string "{JPN}There're lots of diving spots in\n"
	.string "{JPN}the sea around here.\p"
	.string "{JPN}You can spot them easily from the sky\n"
	.string "{JPN}because of their darker color.$"

Route127_Text_KojiIntro:
	.string "{JPN}Run in your bare feet.\n"
	.string "{JPN}That will toughen up your soles!$"

Route127_Text_KojiDefeat:
	.string "{JPN}Yowch!\n"
	.string "{JPN}I got a pebble under a toenail!$"

Route127_Text_KojiPostBattle:
	.string "{JPN}Going barefoot feels great.\n"
	.string "{JPN}But your RUNNING SHOES are cool, too.$"

Route127_Text_KojiRegister:
	.string "{JPN}This is what I do to people who beat me!\n"
	.string "{JPN}I hope we can do this again.$"

Route127_Text_KojiRematchIntro:
	.string "{JPN}I still run in my bare feet daily.\n"
	.string "{JPN}My soles are tough!$"

Route127_Text_KojiRematchDefeat:
	.string "{JPN}Yowch!\n"
	.string "{JPN}Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch:
	.string "{JPN}Want to go barefoot for a while?\n"
	.string "{JPN}So I can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "{JPN}We should have a slow and methodical\n"
	.string "{JPN}match.$"

Route127_Text_AthenaDefeat:
	.string "{JPN}You didn't give me the chance to\n"
	.string "{JPN}do any strategizing.$"

Route127_Text_AthenaPostBattle:
	.string "{JPN}When I'm surrounded by the blue sea\n"
	.string "{JPN}and sky, it feels as if time slows down.$"

Route128_Text_IsaiahIntro:
	.string "{JPN}EVER GRANDE CITY is still a long ways\n"
	.string "{JPN}away...$"

Route128_Text_IsaiahDefeat:
	.string "{JPN}My first victory seems to be far\n"
	.string "{JPN}away, too...$"

Route128_Text_IsaiahPostBattle:
	.string "{JPN}My whole life has been about losing,\n"
	.string "{JPN}but I will never give up!$"

Route128_Text_IsaiahRegister:
	.string "{JPN}I know I'm not good now, but I think\n"
	.string "{JPN}I can win eventually.\p"
	.string "{JPN}Please register me in your POKeNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "{JPN}I'm still feeling good. I'll keep on\n"
	.string "{JPN}swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "{JPN}I've yet to taste my first victory...$"

Route128_Text_IsaiahPostRematch:
	.string "{JPN}I'll eventually reach EVER GRANDE CITY\n"
	.string "{JPN}where I can eventually win...$"

Route128_Text_KatelynIntro:
	.string "{JPN}You have to swim, cycle, and then run\n"
	.string "{JPN}a marathon in a triathlon.\p"
	.string "{JPN}It's a grueling race that consists\n"
	.string "{JPN}of three events.$"

Route128_Text_KatelynDefeat:
	.string "{JPN}A POKEMON battle is grueling, too...$"

Route128_Text_KatelynPostBattle:
	.string "{JPN}I have to ride a BIKE next, but...\n"
	.string "{JPN}I'm about to throw in the towel...$"

Route128_Text_KatelynRegister:
	.string "{JPN}Well, I may as well make the best\n"
	.string "{JPN}of this. I'd like a rematch sometime.$"

Route128_Text_KatelynRematchIntro:
	.string "{JPN}A triathlon is long. But I guess the\n"
	.string "{JPN}road to become the POKEMON CHAMPION\l"
	.string "{JPN}is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:
	.string "{JPN}A POKEMON battle really is harsh\n"
	.string "{JPN}and unforgiving...$"

Route128_Text_KatelynPostRematch:
	.string "{JPN}You should give serious thought to\n"
	.string "{JPN}challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "{JPN}We've been working so hard to mount\n"
	.string "{JPN}a POKEMON LEAGUE challenge...\p"
	.string "{JPN}We can't afford to lose now!$"

Route128_Text_AlexaDefeat:
	.string "{JPN}Oh!\n"
	.string "{JPN}How could this happen?!$"

Route128_Text_AlexaPostBattle:
	.string "{JPN}After all I've done to get here,\n"
	.string "{JPN}I won't give up after one setback.$"

Route128_Text_RubenIntro:
	.string "{JPN}There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:
	.string "{JPN}This can't be!$"

Route128_Text_RubenPostBattle:
	.string "{JPN}There probably is no stronger TRAINER\n"
	.string "{JPN}than you!$"

Route128_Text_WayneIntro:
	.string "{JPN}I want to visit EVER GRANDE, so I\n"
	.string "{JPN}caught myself a POKEMON that knows\l"
	.string "{JPN}the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:
	.string "{JPN}I'm crestfallen!$"

Route128_Text_WaynePostBattle:
	.string "{JPN}Awww, phooey!\p"
	.string "{JPN}My POKEMON knows WATERFALL, but\n"
	.string "{JPN}I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "{JPN}You're looking awfully tough.\n"
	.string "{JPN}I wonder if I can win?$"

Route128_Text_HarrisonDefeat:
	.string "{JPN}Ouch!\n"
	.string "{JPN}I guess it was impossible to win.$"

Route128_Text_HarrisonPostBattle:
	.string "{JPN}There are tough TRAINERS galore\n"
	.string "{JPN}around EVER GRANDE.\p"
	.string "{JPN}Do you think I may be out\n"
	.string "{JPN}of my league?$"

Route128_Text_CarleeIntro:
	.string "{JPN}The sunlight seems to be more harsh\n"
	.string "{JPN}in this area.$"

Route128_Text_CarleeDefeat:
	.string "{JPN}I couldn't see very well because of\n"
	.string "{JPN}the sun's glare.$"

Route128_Text_CarleePostBattle:
	.string "{JPN}I should go back soon.\n"
	.string "{JPN}I need to reapply my sunscreen.$"

Route129_Text_ChaseIntro:
	.string "{JPN}This is my first triathlon.\n"
	.string "{JPN}I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "{JPN}Wroooaaar!\n"
	.string "{JPN}I failed to win!$"

Route129_Text_ChasePostBattle:
	.string "{JPN}If I'm all tensed up, I won't be able to\n"
	.string "{JPN}give it my all.$"

Route129_Text_AllisonIntro:
	.string "{JPN}I'm in the middle of a triathlon,\n"
	.string "{JPN}but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat:
	.string "{JPN}I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "{JPN}Do you know what's the greatest thing\n"
	.string "{JPN}about triathlons?\p"
	.string "{JPN}Testing the limits of your own\n"
	.string "{JPN}strength and endurance against\l"
	.string "{JPN}Mother Nature!$"

Route129_Text_ReedIntro:
	.string "{JPN}Say hey, hey!\n"
	.string "{JPN}Let's get on with it!$"

Route129_Text_ReedDefeat:
	.string "{JPN}Beat, I'm beaten.\n"
	.string "{JPN}That's it, done!$"

Route129_Text_ReedPostBattle:
	.string "{JPN}There's nothing for a loser.\n"
	.string "{JPN}Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "{JPN}What's the hurry?\n"
	.string "{JPN}Let's take it slow and easy.$"

Route129_Text_TishaDefeat:
	.string "{JPN}Oh, my.\n"
	.string "{JPN}I wanted to relax a little more...$"

Route129_Text_TishaPostBattle:
	.string "{JPN}Don't you hate making mistakes when\n"
	.string "{JPN}you're in a rush?\p"
	.string "{JPN}That's why I try to take things\n"
	.string "{JPN}slowly.$"

Route129_Text_ClarenceIntro:
	.string "{JPN}Surfing isn't as easy as it seems,\n"
	.string "{JPN}isn't that right?$"

Route129_Text_ClarenceDefeat:
	.string "{JPN}Winning sure isn't easy.$"

Route129_Text_ClarencePostBattle:
	.string "{JPN}You have your sights on the POKEMON\n"
	.string "{JPN}LEAGUE? Keep at it!$"

Route130_Text_RodneyIntro:
	.string "{JPN}What a surprise! I didn't expect to\n"
	.string "{JPN}see a TRAINER out in the sea.\p"
	.string "{JPN}I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "{JPN}This kid's awfully tough...$"

Route130_Text_RodneyPostBattle:
	.string "{JPN}Your eyes have that look of someone\n"
	.string "{JPN}who's experienced harsh challenges\l"
	.string "{JPN}and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "{JPN}In the deep blue sea,\n"
	.string "{JPN}my shattered blue heart finds\l"
	.string "{JPN}comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "{JPN}Like the vast blue sea,\n"
	.string "{JPN}the world of POKEMON spans\l"
	.string "{JPN}depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "{JPN}The world's children dream\n"
	.string "{JPN}of one day becoming\l"
	.string "{JPN}the POKEMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "{JPN}Floating on the open sea like this...\n"
	.string "{JPN}It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "{JPN}I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "{JPN}Swimming and battling like this...\n"
	.string "{JPN}I'm one happy guy...$"

Route131_Text_RichardIntro:
	.string "{JPN}The sea is teeming with POKEMON.\n"
	.string "{JPN}It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:
	.string "{JPN}POKEMON raised by TRAINERS are\n"
	.string "{JPN}seriously tough...$"

Route131_Text_RichardPostBattle:
	.string "{JPN}Gasp... Gasp...\n"
	.string "{JPN}I'm wiped out...\p"
	.string "{JPN}The going's easy. It's the leaving\n"
	.string "{JPN}that's the hard part.\p"
	.string "{JPN}Will I have any energy left to make\n"
	.string "{JPN}the return trip?$"

Route131_Text_HermanIntro:
	.string "{JPN}The sea... The sea... The sea...\n"
	.string "{JPN}The sea as far as these eyes can see!\l"
	.string "{JPN}I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "{JPN}Bleah!$"

Route131_Text_HermanPostBattle:
	.string "{JPN}Bored I am by the sea, but swim I must.\p"
	.string "{JPN}I'm a born swimmer!\n"
	.string "{JPN}That's what I am.$"

Route131_Text_SusieIntro:
	.string "{JPN}Hi, sweetie, wait!\n"
	.string "{JPN}We should battle, you and I!$"

Route131_Text_SusieDefeat:
	.string "{JPN}You're tough in spite of the way\n"
	.string "{JPN}you look!$"

Route131_Text_SusiePostBattle:
	.string "{JPN}Did you see a guy over there who whines\n"
	.string "{JPN}that he's bored of the sea?\p"
	.string "{JPN}That's all talk.\n"
	.string "{JPN}He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:
	.string "{JPN}Why do men love bathing suits so much?\p"
	.string "{JPN}They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "{JPN}I'm out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "{JPN}Maybe it's not my bathing suit that\n"
	.string "{JPN}makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "{JPN}RELI: We'll work together as siblings\n"
	.string "{JPN}to take you on!$"

Route131_Text_ReliDefeat:
	.string "{JPN}RELI: We couldn't win even though we\n"
	.string "{JPN}worked together...$"

Route131_Text_ReliPostBattle:
	.string "{JPN}RELI: The people of PACIFIDLOG are\n"
	.string "{JPN}together with the sea and POKEMON from\l"
	.string "{JPN}the time they are born.$"

Route131_Text_ReliNotEnoughMons:
	.string "{JPN}RELI: You don't have two POKEMON?\n"
	.string "{JPN}We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "{JPN}IAN: I'm doing my best together with\n"
	.string "{JPN}my sis!$"

Route131_Text_IanDefeat:
	.string "{JPN}IAN: I did my best with my sis,\n"
	.string "{JPN}but we still couldn't win...$"

Route131_Text_IanPostBattle:
	.string "{JPN}IAN: You know how PACIFIDLOG is\n"
	.string "{JPN}a floating town?\p"
	.string "{JPN}So, wherever there is the sea,\n"
	.string "{JPN}that's a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "{JPN}IAN: If you have two POKEMON,\n"
	.string "{JPN}we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "{JPN}If you can beat me, I'll give you some\n"
	.string "{JPN}great information!$"

Route131_Text_TaliaDefeat:
	.string "{JPN}Oh?\n"
	.string "{JPN}Did I lose?$"

Route131_Text_TaliaPostBattle:
	.string "{JPN}There is an odd place nearby.\n"
	.string "{JPN}There's a huge tower there.\l"
	.string "{JPN}Why don't you go take a look?$"

Route131_Text_KevinIntro:
	.string "{JPN}The people of PACIFIDLOG are\n"
	.string "{JPN}a peaceful bunch.\p"
	.string "{JPN}They never get angry.\n"
	.string "{JPN}That goes for me, too.$"

Route131_Text_KevinDefeat:
	.string "{JPN}Oops!$"

Route131_Text_KevinPostBattle:
	.string "{JPN}Tch! ...Oh, wait.\n"
	.string "{JPN}I'm not angry. Honestly!\p"
	.string "{JPN}But, boy, you're strong!\n"
	.string "{JPN}Hahaha!$"

Route132_Text_GilbertIntro:
	.string "{JPN}I used to catch colds all the time as\n"
	.string "{JPN}a kid, but I became totally fit after\l"
	.string "{JPN}I started swimming.$"

Route132_Text_GilbertDefeat:
	.string "{JPN}I crave more power...$"

Route132_Text_GilbertPostBattle:
	.string "{JPN}TRAINERS travel the fields and\n"
	.string "{JPN}mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:
	.string "{JPN}I try not to swim where the currents\n"
	.string "{JPN}are too strong.$"

Route132_Text_DanaDefeat:
	.string "{JPN}Oh, please, no!$"

Route132_Text_DanaPostBattle:
	.string "{JPN}If I get swept away, I'll lose all my\n"
	.string "{JPN}sense of place...$"

Route132_Text_RonaldIntro:
	.string "{JPN}Win or lose, you'll never know until\n"
	.string "{JPN}you try!$"

Route132_Text_RonaldDefeat:
	.string "{JPN}Waah!\n"
	.string "{JPN}I sank in defeat!$"

Route132_Text_RonaldPostBattle:
	.string "{JPN}I never battle when I know I'll win.\n"
	.string "{JPN}I like to battle at the razor's edge of\l"
	.string "{JPN}victory and defeat!$"

Route132_Text_KiyoIntro:
	.string "{JPN}I contemplate POKEMON 24 hours a day.\n"
	.string "{JPN}How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "{JPN}I lose.\n"
	.string "{JPN}I will concede defeat.$"

Route132_Text_KiyoPostBattle:
	.string "{JPN}Urggh...\n"
	.string "{JPN}You're a POKEMON fanatic, aren't you?\p"
	.string "{JPN}You must contemplate POKEMON 24 hours\n"
	.string "{JPN}a day, don't you?$"

Route132_Text_MakaylaIntro:
	.string "{JPN}I'm always with my husband,\n"
	.string "{JPN}but I can win even without him.$"

Route132_Text_MakaylaDefeat:
	.string "{JPN}Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "{JPN}That young man over there looks just\n"
	.string "{JPN}like my husband when he was young.\p"
	.string "{JPN}He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "{JPN}Someone's been watching me intently.\n"
	.string "{JPN}Was it you?$"

Route132_Text_JonathanDefeat:
	.string "{JPN}Wow!\n"
	.string "{JPN}That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "{JPN}I can't shake this feeling that\n"
	.string "{JPN}someone's watching me.\p"
	.string "{JPN}I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "{JPN}Now where could my wife have gone?\n"
	.string "{JPN}I'm always with her.\l"
	.string "{JPN}I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "{JPN}Ah, I see that I couldn't manage\n"
	.string "{JPN}to win on my own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "{JPN}My wife must be looking for me.\n"
	.string "{JPN}I'd best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "{JPN}I liked training here by myself.\n"
	.string "{JPN}It's awful that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "{JPN}Okay! I won't complain about other\n"
	.string "{JPN}people being here.$"

Route132_Text_DarcyPostBattle:
	.string "{JPN}I suppose I can partner up with that\n"
	.string "{JPN}old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "{JPN}Did the currents carry you here, too?\n"
	.string "{JPN}This must have been fated.\l"
	.string "{JPN}Let's battle!$"

Route133_Text_FranklinDefeat:
	.string "{JPN}Strong!\n"
	.string "{JPN}Too much so!$"

Route133_Text_FranklinPostBattle:
	.string "{JPN}It's just my luck that a tough TRAINER\n"
	.string "{JPN}like you would drift here...\l"
	.string "{JPN}I must be cursed...$"

Route133_Text_DebraIntro:
	.string "{JPN}I've led a life of woe and misery...\n"
	.string "{JPN}I've been cast away, and this is where\l"
	.string "{JPN}I've drifted...$"

Route133_Text_DebraDefeat:
	.string "{JPN}Another loss...$"

Route133_Text_DebraPostBattle:
	.string "{JPN}A life adrift...\n"
	.string "{JPN}I don't want it anymore!$"

Route133_Text_LindaIntro:
	.string "{JPN}Welcome!\n"
	.string "{JPN}I've been expecting you!$"

Route133_Text_LindaDefeat:
	.string "{JPN}No! Please!$"

Route133_Text_LindaPostBattle:
	.string "{JPN}A strong child TRAINER...\n"
	.string "{JPN}That's so annoying!$"

Route133_Text_WarrenIntro:
	.string "{JPN}I want to win like everyone else, but I\n"
	.string "{JPN}won't raise POKEMON like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "{JPN}Darn it!\n"
	.string "{JPN}My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "{JPN}It's way more fun to do things the way\n"
	.string "{JPN}I want than to be like everybody else.\l"
	.string "{JPN}I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "{JPN}I came all the way out here with my\n"
	.string "{JPN}BIRD POKEMON.$"

Route133_Text_BeckDefeat:
	.string "{JPN}You...\n"
	.string "{JPN}You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "{JPN}I'd like to go back to FORTREE,\n"
	.string "{JPN}but I've grown to like this place, too.$"

Route133_Text_MollieIntro:
	.string "{JPN}I must have battled thousands\n"
	.string "{JPN}of times. I've lost count.$"

Route133_Text_MollieDefeat:
	.string "{JPN}I may have lost thousands of times,\n"
	.string "{JPN}but a loss still stings.$"

Route133_Text_MolliePostBattle:
	.string "{JPN}Keep at this, youngster. So you can\n"
	.string "{JPN}become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "{JPN}Young people are too happy to go with\n"
	.string "{JPN}the flow. They're without direction.$"

Route133_Text_ConorDefeat:
	.string "{JPN}You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "{JPN}Don't let others lead you astray.\n"
	.string "{JPN}Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "{JPN}Even those POKEMON that can swim are\n"
	.string "{JPN}carried along by the rapid currents.$"

Route134_Text_JackDefeat:
	.string "{JPN}Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "{JPN}I think POKEMON enjoy the fast-running\n"
	.string "{JPN}currents around these parts.$"

Route134_Text_LaurelIntro:
	.string "{JPN}My LUVDISC are looking for a fun\n"
	.string "{JPN}match. Will you join us?$"

Route134_Text_LaurelDefeat:
	.string "{JPN}Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "{JPN}There's a collector who's after\n"
	.string "{JPN}the SCALES of LUVDISC.$"

Route134_Text_AlexIntro:
	.string "{JPN}Okeydokey! That's enough rest, gang!\n"
	.string "{JPN}It's time for a match!$"

Route134_Text_AlexDefeat:
	.string "{JPN}Tuckered out again...$"

Route134_Text_AlexPostBattle:
	.string "{JPN}My BIRD POKEMON get tired quickly after\n"
	.string "{JPN}a long flight...$"

Route134_Text_HitoshiIntro:
	.string "{JPN}You're a POKEMON TRAINER.\n"
	.string "{JPN}No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:
	.string "{JPN}... ... ... ... ... ...\n"
	.string "{JPN}... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:
	.string "{JPN}It was I who challenged you, and yet\n"
	.string "{JPN}I lost. I am deeply shamed...$"

Route134_Text_AaronIntro:
	.string "{JPN}The savage tide in this area serves to\n"
	.string "{JPN}make us stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "{JPN}I willingly concede defeat.$"

Route134_Text_AaronPostBattle:
	.string "{JPN}We will return for more training at\n"
	.string "{JPN}METEOR FALLS.\p"
	.string "{JPN}If you'd like, you should go, too.\n"
	.string "{JPN}It will definitely toughen you up!$"

Route134_Text_KelvinIntro:
	.string "{JPN}O-our boat!\n"
	.string "{JPN}The tide carried it away!$"

Route134_Text_KelvinDefeat:
	.string "{JPN}Awawawawah!\n"
	.string "{JPN}Please, stop! Please!$"

Route134_Text_KelvinPostBattle:
	.string "{JPN}If we can't SURF, how are we supposed\n"
	.string "{JPN}to get home?\p"
	.string "{JPN}Actually, I know a fainted POKEMON\n"
	.string "{JPN}can still SURF, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "{JPN}Can your POKEMON dodge our\n"
	.string "{JPN}lightning-quick attacks?$"

Route134_Text_MarleyDefeat:
	.string "{JPN}I never knew such a technique existed!\n"
	.string "{JPN}You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "{JPN}I haven't lost my passion for speed.\n"
	.string "{JPN}I will try harder.$"

Route134_Text_ReynaIntro:
	.string "{JPN}My POKEMON can't be taken down\n"
	.string "{JPN}easily!$"

Route134_Text_ReynaDefeat:
	.string "{JPN}You're kidding!\n"
	.string "{JPN}Explain how I lost!$"

Route134_Text_ReynaPostBattle:
	.string "{JPN}Haha!\n"
	.string "{JPN}You won, all right!\p"
	.string "{JPN}I'll work my way back up by taking on\n"
	.string "{JPN}TRAINERS I happen to meet!$"

Route134_Text_HudsonIntro:
	.string "{JPN}Listen, have you seen another SAILOR\n"
	.string "{JPN}around here?$"

Route134_Text_HudsonDefeat:
	.string "{JPN}Now, that's something!$"

Route134_Text_HudsonPostBattle:
	.string "{JPN}Our boat drifted out to sea.\p"
	.string "{JPN}My buddy's a timid fellow, so I'm\n"
	.string "{JPN}worried about him.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "{JPN}The battery isn't charged enough.\p"
	.string "{JPN}No. of steps required to fully\n"
	.string "{JPN}charge the battery: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "{JPN}There are no Trainers within range\n"
	.string "{JPN}who can battle...\p"
	.string "{JPN}The VS Seeker was turned off.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "{JPN}The other Trainers don't appear\n"
	.string "{JPN}to be ready for battle.\p"
	.string "{JPN}Let's wait till later.{PAUSE_UNTIL_PRESS}$"
