export const TARGET_REPO = {
  owner: "koziyagoukei",
  repo: "PokeEm-expansion-CanuseJP",
  branch: "frontier-hack",
};

export const REQUIRED_PATHS = [
  "src/data/battle_frontier/battle_frontier_mons.h",
  "include/constants/battle_frontier_mons.h",
  "src/data/battle_frontier/battle_frontier_trainer_mons.h",
  "src/data/moves_info.h",
  "src/data/items.h",
  "src/data/abilities.h",
  "src/data/pokemon/frontier_full_learnsets.h",
];

export const OPTIONAL_PATHS = [
  "src/battle_factory.c",
];

export const FRONTIER_MON_FIELDS = [
  "nickname",
  "species",
  "moves",
  "heldItem",
  "ev",
  "iv",
  "ability",
  "lvl",
  "ball",
  "friendship",
  "nature",
  "gender",
  "isShiny",
  "teraType",
  "gigantamaxFactor",
  "shouldUseDynamax",
  "dynamaxLevel",
  "tags",
];

export const TYPE_LABELS: Record<string, string> = {
  TYPE_NONE: "なし",
  TYPE_NORMAL: "ノーマル",
  TYPE_FIGHTING: "かくとう",
  TYPE_FLYING: "ひこう",
  TYPE_POISON: "どく",
  TYPE_GROUND: "じめん",
  TYPE_ROCK: "いわ",
  TYPE_BUG: "むし",
  TYPE_GHOST: "ゴースト",
  TYPE_STEEL: "はがね",
  TYPE_FIRE: "ほのお",
  TYPE_WATER: "みず",
  TYPE_GRASS: "くさ",
  TYPE_ELECTRIC: "でんき",
  TYPE_PSYCHIC: "エスパー",
  TYPE_ICE: "こおり",
  TYPE_DRAGON: "ドラゴン",
  TYPE_DARK: "あく",
  TYPE_FAIRY: "フェアリー",
  TYPE_STELLAR: "ステラ",
};

export const CATEGORY_LABELS: Record<string, string> = {
  DAMAGE_CATEGORY_PHYSICAL: "物理",
  DAMAGE_CATEGORY_SPECIAL: "特殊",
  DAMAGE_CATEGORY_STATUS: "変化",
};

export const NATURE_LABELS: Record<string, string> = {
  NATURE_HARDY: "がんばりや",
  NATURE_LONELY: "さみしがり",
  NATURE_BRAVE: "ゆうかん",
  NATURE_ADAMANT: "いじっぱり",
  NATURE_NAUGHTY: "やんちゃ",
  NATURE_BOLD: "ずぶとい",
  NATURE_DOCILE: "すなお",
  NATURE_RELAXED: "のんき",
  NATURE_IMPISH: "わんぱく",
  NATURE_LAX: "のうてんき",
  NATURE_TIMID: "おくびょう",
  NATURE_HASTY: "せっかち",
  NATURE_SERIOUS: "まじめ",
  NATURE_JOLLY: "ようき",
  NATURE_NAIVE: "むじゃき",
  NATURE_MODEST: "ひかえめ",
  NATURE_MILD: "おっとり",
  NATURE_QUIET: "れいせい",
  NATURE_BASHFUL: "てれや",
  NATURE_RASH: "うっかりや",
  NATURE_CALM: "おだやか",
  NATURE_GENTLE: "おとなしい",
  NATURE_SASSY: "なまいき",
  NATURE_CAREFUL: "しんちょう",
  NATURE_QUIRKY: "きまぐれ",
};

export const BALL_LABELS: Record<string, string> = {
  BALL_POKE: "モンスターボール",
  BALL_GREAT: "スーパーボール",
  BALL_ULTRA: "ハイパーボール",
  BALL_MASTER: "マスターボール",
  BALL_PREMIER: "プレミアボール",
  BALL_HEAL: "ヒールボール",
  BALL_NET: "ネットボール",
  BALL_NEST: "ネストボール",
  BALL_DIVE: "ダイブボール",
  BALL_DUSK: "ダークボール",
  BALL_TIMER: "タイマーボール",
  BALL_QUICK: "クイックボール",
  BALL_REPEAT: "リピートボール",
  BALL_LUXURY: "ゴージャスボール",
  BALL_LEVEL: "レベルボール",
  BALL_LURE: "ルアーボール",
  BALL_MOON: "ムーンボール",
  BALL_FRIEND: "フレンドボール",
  BALL_LOVE: "ラブラブボール",
  BALL_FAST: "スピードボール",
  BALL_HEAVY: "ヘビーボール",
  BALL_DREAM: "ドリームボール",
  BALL_SAFARI: "サファリボール",
  BALL_SPORT: "コンペボール",
  BALL_PARK: "パークボール",
  BALL_BEAST: "ウルトラボール",
  BALL_CHERISH: "プレシャスボール",
  BALL_STRANGE: "ストレンジボール",
  BALL_RANDOM: "ランダム",
};

export const GENDER_LABELS: Record<string, string> = {
  "0": "デフォルト",
  TRAINER_MON_MALE: "オス",
  TRAINER_MON_FEMALE: "メス",
  TRAINER_MON_RANDOM_GENDER: "ランダム",
};

export const HIDDEN_POWER_TYPES = [
  "TYPE_FIGHTING",
  "TYPE_FLYING",
  "TYPE_POISON",
  "TYPE_GROUND",
  "TYPE_ROCK",
  "TYPE_BUG",
  "TYPE_GHOST",
  "TYPE_STEEL",
  "TYPE_FIRE",
  "TYPE_WATER",
  "TYPE_GRASS",
  "TYPE_ELECTRIC",
  "TYPE_PSYCHIC",
  "TYPE_ICE",
  "TYPE_DRAGON",
  "TYPE_DARK",
];
