#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("くん");
const u8 gText_ExpandedPlaceholder_Chan[] = _("ちゃん");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("サファイア");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("ルビー");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("エメラルド");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("アクアだん");
const u8 gText_ExpandedPlaceholder_Magma[] = _("マグマだん");
const u8 gText_ExpandedPlaceholder_Archie[] = _("アオギリ");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("マツブサ");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("カイオーガ");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("グラードン");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("ユウキ");
const u8 gText_ExpandedPlaceholder_May[] = _("ハルカ");
const u8 gText_ExpandedPlaceholder_Red[] = _("グリーン");
const u8 gText_ExpandedPlaceholder_Green[] = _("グリーン");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("タマゴ");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("ポケモン");
const u8 gText_Player[] = _("しゅじんこう"); // Unused
const u8 gText_Pokedex[] = _("ずかん"); // Unused
const u8 gText_Time[] = _("じかん");
const u8 gText_Badges[] = _("バッジ"); // Unused
const u8 gText_AButton[] = _("Aボタン"); // Unused
const u8 gText_BButton[] = _("Bボタン"); // Unused
const u8 gText_RButton[] = _("Rボタン"); // Unused
const u8 gText_LButton[] = _("Lボタン"); // Unused
const u8 gText_Start[] = _("スタート"); // Unused
const u8 gText_Select[] = _("セレクト"); // Unused
const u8 gText_ControlPad[] = _("じゅうじキー"); // Unused
const u8 gText_LButtonRButton[] = _("Lボタン  Rボタン"); // Unused
const u8 gText_Controls[] = _("そうさ"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}つぎ");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}つぎ {B_BUTTON}もどる");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}つぎ {B_BUTTON}やめる");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}{B_BUTTON}やめる");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}おわる");
const u8 gText_Boy[] = _("おとこのこ");
const u8 gText_Girl[] = _("おんなのこ");
const u8 gText_ThisIsAPokemon[] = _("これが ポケモンだよ。{PAUSE 96}$");
const u8 gText_5MarksPokemon[] = _("？？？？？ ポケモン");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 12}？？'？？");
const u8 gText_UnkHeightMetric[] = _("？？？.？ m");
const u8 gText_UnkWeight[] = _("？？？？.？ lbs.");
const u8 gText_UnkWeightMetric[] = _("？？？.？ kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       ポケモン"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 12}    '    ");
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("なきごえ");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("おおきさくらべ ");
const u8 gText_PokedexRegistration[] = _("ずかんに とうろく した。");
const u8 gText_HTHeight[] = _("たかさ");
const u8 gText_WTWeight[] = _("おもさ");
const u8 gText_SearchingPleaseWait[] = _("さがしています...\nおまちください。");
const u8 gText_SearchCompleted[] = _("さがしおわりました。");
const u8 gText_NoMatchingPkmnWereFound[] = _("あてはまる ポケモンは\nみつかりませんでした。");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("えらんだ じょうけんで\nポケモンを さがします。");
const u8 gText_SwitchPokedexListings[] = _("ずかんの ならびを かえます。");
const u8 gText_ReturnToPokedex[] = _("ずかんに もどります。");
const u8 gText_SelectPokedexMode[] = _("ずかんの モードを えらびます。");
const u8 gText_SelectPokedexListingMode[] = _("ずかんの ならびかたを えらびます。");
const u8 gText_ListByFirstLetter[] = _("なまえの さいしょで ならべます。\nみつけた ポケモンのみ。");
const u8 gText_ListByBodyColor[] = _("からだの いろで ならべます。\nみつけた ポケモンのみ。");
const u8 gText_ListByType[] = _("タイプで ならべます。\nつかまえた ポケモンのみ。");
const u8 gText_ExecuteSearchSwitch[] = _("さがす/きりかえを します。");
const u8 gText_DexHoennTitle[] = _("ホウエンずかん");
const u8 gText_DexNatTitle[] = _("ぜんこくずかん");
const u8 gText_DexSortNumericalTitle[] = _("ばんごうじゅん");
const u8 gText_DexSortAtoZTitle[] = _("なまえじゅん");
const u8 gText_DexSortHeaviestTitle[] = _("おもいじゅん");
const u8 gText_DexSortLightestTitle[] = _("かるいじゅん");
const u8 gText_DexSortTallestTitle[] = _("たかいじゅん");
const u8 gText_DexSortSmallestTitle[] = _("ひくいじゅん");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("あか");
const u8 gText_DexSearchColorBlue[] = _("あお");
const u8 gText_DexSearchColorYellow[] = _("きいろ");
const u8 gText_DexSearchColorGreen[] = _("みどり");
const u8 gText_DexSearchColorBlack[] = _("くろ");
const u8 gText_DexSearchColorBrown[] = _("ちゃいろ");
const u8 gText_DexSearchColorPurple[] = _("むらさき");
const u8 gText_DexSearchColorGray[] = _("はいいろ");
const u8 gText_DexSearchColorWhite[] = _("しろ");
const u8 gText_DexSearchColorPink[] = _("ピンク");
const u8 gText_DexHoennDescription[] = _("ホウエンちほうの ずかん");
const u8 gText_DexNatDescription[] = _("ぜんこくばんの ずかん");
const u8 gText_DexSortNumericalDescription[] = _("ポケモンを ばんごうじゅんに\nならべます。");
const u8 gText_DexSortAtoZDescription[] = _("みつけた ポケモンと つかまえた\nポケモンを なまえじゅんに ならべます。");
const u8 gText_DexSortHeaviestDescription[] = _("つかまえた ポケモンを おもい\nじゅんに ならべます。");
const u8 gText_DexSortLightestDescription[] = _("つかまえた ポケモンを かるい\nじゅんに ならべます。");
const u8 gText_DexSortTallestDescription[] = _("つかまえた ポケモンを たかい\nじゅんに ならべます。");
const u8 gText_DexSortSmallestDescription[] = _("つかまえた ポケモンを ひくい\nじゅんに ならべます。");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("していなし");
const u8 gText_DexSearchTypeNone[] = _("なし");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("えいこうの へやへ ようこそ！");
const u8 gText_HOFDexRating[] = _("みつけた ポケモン: {STR_VAR_1}！\nつかまえた ポケモン: {STR_VAR_2}！\pオダマキはかせの ずかんひょうか！\pオダマキはかせ: どれどれ...\p");
const u8 gText_HOFDexSaving[] = _("レポート しています...\nでんげんを きらないでください。");
const u8 gText_HOFCorrupted[] = _("えいこうの へやの データが\nこわれています。");
const u8 gText_HOFNumber[] = _("えいこうの へや {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("リーグ チャンピオン！\nおめでとう！");
const u8 gText_Number[] = _("{NO} ");
const u8 gText_Level[] = _("レベル ");
const u8 gText_IdNumberSlash[] = _("ばんごう/"); // Unused
const u8 gText_Name[] = _("なまえ");
const u8 gText_IDNumber[] = _("ばんごう");
const u8 gText_BirchInTrouble[] = _("オダマキはかせが こまっている！\nポケモンを だして たすけよう！");
const u8 gText_ConfirmStarterChoice[] = _("この ポケモンに しますか？");
const u8 gText_Pokemon4[] = _("ポケモン"); // Unused
const u8 gText_FlyToWhere[] = _("どこへ とびますか？");
const u8 gMenuText_Use[] = _("つかう");
const u8 gMenuText_Toss[] = _("すてる");
const u8 gMenuText_Register[] = _("とうろく");
const u8 gMenuText_Give[] = _("わたす");
const u8 gMenuText_Confirm[] = _("けってい");
const u8 gText_Cancel[] = _("もどる");
const u8 gText_Cancel2[] = _("もどる");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("なし");
const u8 gText_FiveMarks[] = _("？？？？？");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("ー");
const u8 gText_TwoDashes[] = _("ーー");
const u8 gText_ThreeDashes[] = _("ーーー");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{ENG}{LV}{AUTO}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 1}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("まえの メニューに\nもどります。");
const u8 gText_WhatWouldYouLike[] = _("どうしますか？");
const u8 gMenuText_Give2[] = _("わたす");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" きのみ"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1}まい");
const u8 gText_CloseBag[] = _("バッグを とじる");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}を\nえらびました。");
const u8 gText_CantWriteMail[] = _("ここでは メールを\nかけません。");
const u8 gText_NoPokemon[] = _("ポケモンが\nいません。");
const u8 gText_MoveVar1Where[] = _("{STR_VAR_1}を\nどこへ うごかしますか？");
const u8 gText_Var1CantBeHeld[] = _("{STR_VAR_1}は もたせられません。");
const u8 gText_TossHowManyVar1s[] = _("{STR_VAR_1}を\nいくつ すてますか？");
const u8 gText_ThrewAwayVar2Var1s[] = _("{STR_VAR_2}こ {STR_VAR_1}を\nすてました。");
const u8 gText_ConfirmTossItems[] = _("{STR_VAR_2}こ {STR_VAR_1}を\nすてても いいですか？");
const u8 gText_DadsAdvice[] = _("パパの ことば...\n{PLAYER}！ ものごとには\lタイミングが ある！{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER}は\n{STR_VAR_2}を つかった。{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("むしよけスプレーの こうかが\nまだ のこっています。{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("ルアーの こうかが\nまだ のこっています。{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("ボックスが いっぱいです。{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("フィールド");
const u8 gText_TheBattle[] = _("せんとう");
const u8 gText_ThePokemonList[] = _("ポケモンリスト");
const u8 gText_TheShop[] = _("ショップ");
const u8 gText_ThePC[] = _("PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("{STR_VAR_1}へ\nもどります。");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS]      = COMPOUND_STRING("どうぐ"),
    [POCKET_POKE_BALLS] = COMPOUND_STRING("ボール"),
    [POCKET_TM_HM]      = COMPOUND_STRING("わざマシン"),
    [POCKET_BERRIES]    = COMPOUND_STRING("きのみ"),
    [POCKET_KEY_ITEMS]  = COMPOUND_STRING("たいせつなもの")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 3}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 17}{STR_VAR_1}{CLEAR 5}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("かう");
const u8 gText_ShopSell[] = _("うる");
const u8 gText_ShopQuit[] = _("やめる");
const u8 gText_ThatItemIsSoldOut[] = _("すみません それは うりきれです。{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("うりきれ");
const u8 gText_InBagVar1[] = _("バッグ: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("かいものを やめます。");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}ですね？\nいくつ ほしいですか？");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}ですね？\nいくつ ほしいですか？");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}ですね？ {STR_VAR_2}こで\n{STR_VAR_3}円です。");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}ですね？\n{STR_VAR_2}円です。 かいますか？");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("{STR_VAR_1}ですね？\n{STR_VAR_2}円です。 いいですか？");
const u8 gText_HereYouGoThankYou[] = _("はい どうぞ！\nありがとうございます。");
const u8 gText_ThankYouIllSendItHome[] = _("ありがとうございます！\nおうちの PCへ おくります。");
const u8 gText_ThanksIllSendItHome[] = _("ありがとう！\nおうちの PCへ おくります。");
const u8 gText_YouDontHaveMoney[] = _("おかねが たりません。{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("これいじょう もてません。{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("{STR_VAR_1}が いっぱいです。{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("ほかに なにか ありますか？");
const u8 gText_CanIHelpWithAnythingElse[] = _("ほかに なにか ありますか？");
const u8 gText_ThrowInPremierBall[] = _("プレミアボールも おつけします。{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("プレミアボール {STR_VAR_1}こも おつけします。{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}ですか？\nそれは かいとれません。{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}ですね？\nいくつ うりますか？");
const u8 gText_ICanPayVar1[] = _("{STR_VAR_1}円で かいとれます。\nいいですか？");
const u8 gText_TurnedOverVar1ForVar2[] = _("{STR_VAR_2}を わたして\n{STR_VAR_1}円 もらった。");
const u8 gText_PokedollarVar1[] = _("{STR_VAR_1}円");
const u8 gText_HP3[] = _("HP");
const u8 gText_SpAtk3[] = _("とくこう");
const u8 gText_SpDef3[] = _("とくぼう");
const u8 gText_WontHaveEffect[] = _("こうかが ありません。{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("がったいする ポケモンを えらんでください。");
const u8 gText_CantBeUsedOnPkmn[] = _("その ポケモンには\nつかえません。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1}は こうたい\nできません！{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1}は すでに\nせんとうに でています！{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1}は すでに\nえらばれています。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1}は たたかう\nげんきが ありません！{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("{STR_VAR_1}の ポケモンと\nこうたい できません！{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("タマゴは たたかえません！{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("あたらしい バッジを もらうまで\nつかえません。{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("{STR_VAR_1}ひきまで しか\nはいれません。{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("はずした メールを\nPCへ おくりますか？");
const u8 gText_MailSentToPC[] = _("メールを PCへ おくりました。{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("PCの メールボックスが いっぱいです。{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("メールを はずすと\nぶんが きえます。 いいですか？");
const u8 gText_RemoveMailBeforeItem[] = _("どうぐを もたせるには\nメールを はずしてください。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1}に {STR_VAR_2}を\nもたせました。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1}は すでに\n{STR_VAR_2}を もっています。\p2つの どうぐを\nいれかえますか？");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1}は なにも\nもっていません。{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{STR_VAR_1}から\n{STR_VAR_2}を うけとった。{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("ポケモンから メールを\nうけとりました。{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_2}を うけとり\n{STR_VAR_1}を もたせました。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("この ポケモンは どうぐを\nもっています。 メールは もてません。{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("メールボックスから\nメールを うつしました。{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("バッグが いっぱいです。\nどうぐを はずせませんでした。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1}は\n{STR_VAR_2}を おぼえた！");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1}は\n{STR_VAR_2}を おぼえた！{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1}と {STR_VAR_2}は\nあいません。\p{STR_VAR_2}は\nおぼえられません。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1}は {STR_VAR_2}を\nおぼえたい。\pしかし {STR_VAR_1}は すでに\n4つの わざを おぼえている。\pほかの わざを わすれて\n{STR_VAR_2}を おぼえますか？");
const u8 gText_StopLearningMove2[] = _("{STR_VAR_2}を おぼえるのを\nやめますか？");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1}は\n{STR_VAR_2}を おぼえなかった。{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("どの わざを わすれますか？{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1 {PAUSE 15}2 そして{PAUSE 15}... {PAUSE 15}... {PAUSE 15}... {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}ポカン！\p{STR_VAR_1}は {STR_VAR_2}の\nつかいかたを わすれた。\pそして...{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1}は すでに\n{STR_VAR_2}を おぼえています。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}の HPが\n{STR_VAR_2}かいふくした。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1}の どくが\nなおった。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1}の まひが\nなおった。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1}は めを さました。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}の やけどが なおった。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}の しもやけが なおった。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1}の こおりが とけた。{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("PPが かいふくした。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1}は げんきに なった。{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1}は げんきに なった。{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}の PPが ふえた。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1}は\nレベル {STR_VAR_2}に あがった。");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1}は {STR_VAR_2}の けいけんちを もらった！{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1}は {STR_VAR_2}の けいけんちを もらい\nレベル {STR_VAR_3}に あがった！");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}の {STR_VAR_2}の\nきそポイントが あがった。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1}は なついた。\n{STR_VAR_2}の きそポイントが さがった！{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1}は あなたが だいすき！\n{STR_VAR_2}の きそポイントが さがった！{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1}は なついた。\n{STR_VAR_2}の きそポイントは さがらない！{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1}の こんらんが\nとけた。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1}の メロメロが\nとけた。{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1}は へんしんした！{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("この {STR_VAR_1}を\nすてますか？");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1}を\nすてました。{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("どの ポケモンに おしえますか？"); // Unused
const u8 gText_ChoosePokemon[] = _("ポケモンを えらんでください。");
const u8 gText_MoveToWhere[] = _("どこへ うごかしますか？");
const u8 gText_TeachWhichPokemon[] = _("どの ポケモンに おしえますか？");
const u8 gText_UseOnWhichPokemon[] = _("どの ポケモンに つかいますか？");
const u8 gText_GiveToWhichPokemon[] = _("どの ポケモンに わたしますか？");
const u8 gText_DoWhatWithPokemon[] = _("この ポケモンを どうしますか？");
const u8 gText_NothingToCut[] = _("いあいぎり できる ものが ない。");
const u8 gText_CantSurfHere[] = _("ここでは なみのり できません。");
const u8 gText_AlreadySurfing[] = _("すでに なみのり しています。");
const u8 gText_CantUseHere[] = _("ここでは つかえません。");
const u8 gText_RestoreWhichMove[] = _("どの わざを かいふくしますか？");
const u8 gText_BoostPp[] = _("どの わざの PPを ふやしますか？");
const u8 gText_DoWhatWithItem[] = _("どうぐを どうしますか？");
const u8 gText_NoPokemonForBattle[] = _("たたかえる ポケモンが いません！");
const u8 gText_ChoosePokemon2[] = _("ポケモンを えらんでください。");
const u8 gText_NotEnoughHp[] = _("HPが たりません...");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1}ひきの ポケモンが ひつようです。");
const u8 gText_PokemonCantBeSame[] = _("おなじ ポケモンは えらべません。");
const u8 gText_NoIdenticalHoldItems[] = _("おなじ もちものは えらべません。");
const u8 gText_CurrentIsTooFast[] = _("ながれが はやすぎる！");
const u8 gText_DoWhatWithMail[] = _("メールを どうしますか？");
const u8 gText_ChoosePokemonCancel[] = _("ポケモンを えらぶか もどる。");
const u8 gText_ChoosePokemonConfirm[] = _("ポケモンを えらんで けってい。");
const u8 gText_SendWhichMonToPC[] = _("どの ポケモンを PCへ おくりますか？");
const u8 gText_MoveItemWhere[] = _("どうぐを どこへ うごかしますか？");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}の {STR_VAR_2}と\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}の {STR_VAR_2}を いれかえた！{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("じてんしゃで たのしもう！");
const u8 gText_InUseAlready_PM[] = _("すでに つかっています。");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1}は すでに\n{STR_VAR_2}を もっています。");
const u8 gText_WhichAppliance[] = _("どの かでんを\nたのみますか？");
const u8 gText_NoUse[] = _("つかえない。");
const u8 gText_Able[] = _("できる");
const u8 gText_First_PM[] = _("1ばんめ");
const u8 gText_Second_PM[] = _("2ばんめ");
const u8 gText_Third_PM[] = _("3ばんめ");
const u8 gText_Able2[] = _("できる");
const u8 gText_NotAble[] = _("だめ");
const u8 gText_Able3[] = _("できる！");
const u8 gText_NotAble2[] = _("だめ！");
const u8 gText_Learned[] = _("おぼえた");
const u8 gText_Have[] = _("ある");
const u8 gText_DontHave[] = _("ない");
const u8 gText_Fourth[] = _("4ばんめ");
const u8 gText_PkmnCantParticipate[] = _("その ポケモンは さんか できません。{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("さんかを やめますか？");
const u8 gText_CancelBattle[] = _("しょうぶを やめますか？");
const u8 gText_ReturnToWaitingRoom[] = _("まちあいしつに もどりますか？");
const u8 gText_CancelChallenge[] = _("ちょうせんを やめますか？");
const u8 gText_EscapeFromHere[] = _("ここから ぬけだして\n{STR_VAR_1}へ もどりますか？");
const u8 gText_ReturnToHealingSpot[] = _("さいごに かいふくした\n{STR_VAR_1}へ もどりますか？");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}{JPN}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("たたかえる ポケモンは\nそれだけです。");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("その ポケモンは いま\nこうかん できません。");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("その ポケモンは\nこうかん できません。");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("タマゴは いま\nこうかん できません。");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("あいての ポケモンは いま\nこうかん できません。");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("あいては その ポケモンを\nうけとれません。");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("その トレーナーとは いま\nこうかん できません。");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("あいてが ほしい ポケモンでは\nありません。");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("それは タマゴでは ありません。");
const u8 gText_Register[] = _("とうろく");
const u8 gText_Attack3[] = _("こうげき");
const u8 gText_Defense3[] = _("ぼうぎょ");
const u8 gText_SpAtk4[] = _("とくこう");
const u8 gText_SpDef4[] = _("とくぼう");
const u8 gText_Speed2[] = _("すばやさ");
const u8 gText_HP4[] = _("HP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("OT/");
const u8 gText_RentalPkmn[] = _("レンタルポケモン");
const u8 gText_TypeSlash[] = _("タイプ/");
const u8 gText_Power[] = _("いりょく");
const u8 gText_Accuracy2[] = _("めいちゅう");
const u8 gText_Appeal[] = _("アピール");
const u8 gText_Jam[] = _("ジャマ");
const u8 gText_Status[] = _("じょうたい");
const u8 gText_ExpPoints[] = _("けいけんち");
const u8 gText_NextLv[] = _("つぎまで");
const u8 gText_RibbonsVar1[] = _("リボン: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("イベント"); // Unused
const u8 gText_Switch[] = _("いれかえ");
const u8 gText_PkmnInfo[] = _("じょうほう");
const u8 gText_PkmnSkills[] = _("のうりょく");
const u8 gText_BattleMoves[] = _("わざ");
const u8 gText_ContestMoves[] = _("コンテスト");
const u8 gText_Info[] = _("じょうほう");
const u8 gText_EggWillTakeALongTime[] = _("この タマゴが かえるには\nまだ かなり かかりそう。");
const u8 gText_EggWillTakeSomeTime[] = _("なにが うまれるかな？\nまだ すこし かかりそう。");
const u8 gText_EggWillHatchSoon[] = _("ときどき うごいている。\nもうすぐ うまれそう！");
const u8 gText_EggAboutToHatch[] = _("なかから おとが する。\nもう うまれそう！");
const u8 gText_HMMovesCantBeForgotten2[] = _("ひでんわざは いま\nわすれられません。");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で であった。");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で うまれた。");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \nこうかんで やってきた。");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nうんめいの であいを した。");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で であったようだ。");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nどこかで であった。");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nどこかで うまれた。");
const u8 gText_OddEggFoundByCouple[] = _("そだてやふうふが みつけた\nふしぎな ポケモンの タマゴ。");
const u8 gText_PeculiarEggNicePlace[] = _("いい ばしょで もらった\nふしぎな ポケモンの タマゴ。");
const u8 gText_PeculiarEggTrade[] = _("こうかんで やってきた\nふしぎな ポケモンの タマゴ。");
const u8 gText_EggFromHotSprings[] = _("おんせんで もらった\nポケモンの タマゴ。");
const u8 gText_EggFromTraveler[] = _("たびびとから もらった\nふしぎな ポケモンの タマゴ。");
const u8 gText_ApostropheSBase[] = _("の ベース");
const u8 gText_OkayToDeleteFromRegistry[] = _("{STR_VAR_1}を\nとうろくから けしますか？");
const u8 gText_RegisteredDataDeleted[] = _("とうろくデータを けしました。{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("とうろくが ありません。{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("とうろくけし");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("かざる");
const u8 gText_PutAway[] = _("しまう");
const u8 gText_Toss2[] = _("すてる");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("えらんだ もようがえグッズを だす。");
const u8 gText_StoreChosenDecorInPC[] = _("えらんだ もようがえグッズを PCへ しまう。");
const u8 gText_ThrowAwayUnwantedDecors[] = _("いらない もようがえグッズを すてる。");
const u8 gText_NoDecorations[] = _("もようがえグッズが ありません。{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("つくえ");
const u8 gText_Chair[] = _("いす");
const u8 gText_Plant[] = _("うえき");
const u8 gText_Ornament[] = _("おきもの");
const u8 gText_Mat[] = _("マット");
const u8 gText_Poster[] = _("ポスター");
const u8 gText_Doll[] = _("ぬいぐるみ");
const u8 gText_Cushion[] = _("クッション");
const u8 gText_Gold[] = _("きん");
const u8 gText_Silver[] = _("ぎん");
const u8 gText_PlaceItHere[] = _("ここに おきますか？");
const u8 gText_CantBePlacedHere[] = _("ここには おけません。");
const u8 gText_CancelDecorating[] = _("もようがえを やめますか？");
const u8 gText_InUseAlready[] = _("すでに つかっています。");
const u8 gText_NoMoreDecorations[] = _("これいじょう おけません。\nおけるのは {STR_VAR_1}こまでです。");
const u8 gText_NoMoreDecorations2[] = _("これいじょう おけません。\nおけるのは {STR_VAR_1}こまでです。");
const u8 gText_MustBePlacedOnDesk[] = _("ここには おけません。\nつくえ などの うえに おいてください。"); // Unused
const u8 gText_CantPlaceInRoom[] = _("この もようがえグッズは\nじぶんの へやには おけません。");
const u8 gText_CantThrowAwayInUse[] = _("この もようがえグッズは つかっています。\nすてられません。");
const u8 gText_DecorationWillBeDiscarded[] = _("この {STR_VAR_1}を すてます。\nいいですか？");
const u8 gText_DecorationThrownAway[] = _("もようがえグッズを すてました。");
const u8 gText_StopPuttingAwayDecorations[] = _("もようがえグッズを しまうのを\nやめますか？");
const u8 gText_NoDecorationHere[] = _("ここに もようがえグッズは ありません。");
const u8 gText_ReturnDecorationToPC[] = _("この もようがえグッズを PCへ もどしますか？");
const u8 gText_DecorationReturnedToPC[] = _("もようがえグッズを PCへ もどしました。");
const u8 gText_NoDecorationsInUse[] = _("つかっている もようがえグッズは ありません。{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("どうぐが ありません。{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("ここに メールは ありません。{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("{STR_VAR_1}の メールを\nどうしますか？");
const u8 gText_MessageWillBeLost[] = _("ぶんが きえます。\nいいですか？");
const u8 gText_BagIsFull[] = _("バッグが いっぱいです。{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("ぶんを けして メールを\nバッグに もどしました。{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("パパ");
const u8 gText_Mom[] = _("ママ");
const u8 gText_CoolnessContest[] = _("かっこよさ コンテスト");
const u8 gText_BeautyContest[] = _("うつくしさ コンテスト");
const u8 gText_CutenessContest[] = _("かわいさ コンテスト");
const u8 gText_SmartnessContest[] = _("かしこさ コンテスト");
const u8 gText_ToughnessContest[] = _("たくましさ コンテスト");
const u8 gText_Information[] = _("おしらせ");
const u8 gText_Yes[] = _("はい");
const u8 gText_No[] = _("いいえ");
const u8 gText_Lv50[] = _("レベル 50");
const u8 gText_OpenLevel[] = _("オープンレベル");
const u8 gText_BattleFrontier[] = _("バトルフロンティア");
const u8 gText_Cool[] = _("かっこよさ");
const u8 gText_Beauty[] = _("うつくしさ");
const u8 gText_Cute[] = _("かわいさ");
const u8 gText_Smart[] = _("かしこさ");
const u8 gText_Tough[] = _("たくましさ");
const u8 gText_Normal[] = _("ノーマル");
const u8 gText_Super[] = _("スーパー");
const u8 gText_Hyper[] = _("ハイパー");
const u8 gText_Master[] = _("マスター");
const u8 gText_SomeonesPC[] = _("だれかの PC");
const u8 gText_LanettesPC[] = _("マユミの PC");
const u8 gText_BillsPc[] = _("マサキの PC");
const u8 gText_PlayersPC[] = _("{PLAYER}の PC");
const u8 gText_HallOfFame[] = _("えいこうの へや");
const u8 gText_LogOff[] = _("やめる");
const u8 gText_Single2[] = _("シングル");
const u8 gText_Double2[] = _("ダブル");
const u8 gText_Multi[] = _("マルチ");
const u8 gText_MultiLink[] = _("マルチリンク");
const u8 gText_MenuOptionPokedex[] = _("ずかん");
const u8 gText_MenuOptionPokemon[] = _("ポケモン");
const u8 gText_MenuOptionBag[] = _("バッグ");
const u8 gText_MenuOptionPokenav[] = _("ポケナビ");
const u8 gText_MenuOptionSave[] = _("レポート");
const u8 gText_MenuOptionOption[] = _("せってい");
const u8 gText_MenuOptionExit[] = _("とじる");
const u8 gText_SouthernIsland[] = _("みなみのことう");
const u8 gText_BirthIsland[] = _("たんじょうのしま");
const u8 gText_FarawayIsland[] = _("さいはてのことう");
const u8 gText_NavelRock[] = _("へそのいわ");
const u8 gText_NormalTagMatch[] = _("ふつうタッグ");
const u8 gText_VarietyTagMatch[] = _("いろいろタッグ");
const u8 gText_UniqueTagMatch[] = _("ユニークタッグ");
const u8 gText_ExpertTagMatch[] = _("エキスパートタッグ");
const u8 gText_BattleBasics[] = _("しょうぶの きほん");
const u8 gText_PokemonNature[] = _("ポケモンの せいかく");
const u8 gText_PokemonMoves[] = _("ポケモンの わざ");
const u8 gText_Underpowered[] = _("ちからぶそく");
const u8 gText_WhenInDanger[] = _("ピンチの とき");
const u8 gText_BattlePokemon[] = _("ポケモンと たたかう");
const u8 gText_BattleTrainers[] = _("トレーナーと たたかう");
const u8 gText_1F[] = _("1F");
const u8 gText_2F[] = _("2F");
const u8 gText_3F[] = _("3F");
const u8 gText_4F[] = _("4F");
const u8 gText_5F[] = _("5F");
const u8 gText_6F[] = _("6F");
const u8 gText_7F[] = _("7F");
const u8 gText_8F[] = _("8F");
const u8 gText_9F[] = _("9F");
const u8 gText_10F[] = _("10F");
const u8 gText_11F[] = _("11F");
const u8 gText_B1F[] = _("B1F");
const u8 gText_B2F[] = _("B2F");
const u8 gText_B3F[] = _("B3F");
const u8 gText_B4F[] = _("B4F");
const u8 gText_Rooftop[] = _("おくじょう");
const u8 gText_ElevatorNowOn[] = _("ただいま:");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("ランキングホール");
const u8 gText_ExchangeService[] = _("こうかんサービス");
const u8 gText_SlateportCity[] = _("カイナシティ");
const u8 gText_Exit[] = _("おわる");
const u8 gText_YourPartysFull[] = _("てもちが いっぱいです！{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("てもち");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("ことばを 4つ くみあわせて");
const u8 gText_AndMakeYourProfile[] = _("プロフィールを つくります。");
const u8 gText_CombineSixWordsOrPhrases[] = _("ことばを 6つ くみあわせて");
const u8 gText_AndMakeAMessage[] = _("メッセージを つくります。");
const u8 gText_FindWordsThatDescribeYour[] = _("いまの きもちを あらわす");
const u8 gText_FeelingsRightNow[] = _("ことばを みつけましょう。");
const u8 gText_WithFourPhrases[] = _("ことば 4つで "); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("ことばを 9つ くみあわせて");
const u8 gText_AndMakeAMessage2[] = _("メッセージを つくります。");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("ことばを 1つだけ かえて");
const u8 gText_AndImproveTheBardsSong[] = _("うたを よくします。");
const u8 gText_YourProfile[] = _("プロフィール");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("しょうぶを はじめるときの きもち");
const u8 gText_WhatYouSayIfYouWin[] = _("しょうぶに かったときの ことば");
const u8 gText_WhatYouSayIfYouLose[] = _("しょうぶに まけたときの ことば");
const u8 gText_TheAnswer[] = _("こたえ");
const u8 gText_TheMailMessage[] = _("メールの ぶん");
const u8 gText_TheMailSalutation[] = _("メールの あいさつ"); // Unused
const u8 gText_TheBardsSong2[] = _("あたらしい うた");
const u8 gText_CombineTwoWordsOrPhrases[] = _("ことばを 2つ くみあわせて");
const u8 gText_AndMakeATrendySaying[] = _("はやりの ことばを つくります。");
const u8 gText_TheTrendySaying[] = _("はやりの ことば");
const u8 gText_IsAsShownOkay[] = _("このとおりで いいですか？");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("ことばを 2つ くみあわせて");
const u8 gText_ToTeachHerAGoodSaying[] = _("いい ことばを おしえます。");
const u8 gText_FindWordsWhichFit[] = _("トレーナーの イメージに");
const u8 gText_TheTrainersImage[] = _("あう ことばを みつけます。");
const u8 gText_TheImage[] = _("イメージ:");
const u8 gText_OutOfTheListedChoices[] = _("ならんだ こたえから");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("クイズの こたえを えらびます！");
const u8 gText_AndCreateAQuiz[] = _("クイズを つくります！");
const u8 gText_PickAWordOrPhraseAnd[] = _("ことばを えらんで");
const u8 gText_SetTheQuizAnswer[] = _("クイズの こたえに します。");
const u8 gText_TheAnswerColon[] = _("こたえ:");
const u8 gText_TheQuizColon[] = _("クイズ:"); // Unused
const u8 gText_ApprenticePhrase[] = _("でしの ことば:");
const u8 gText_QuitEditing[] = _("へんしゅうを やめますか？");
const u8 gText_StopGivingPkmnMail[] = _("ポケモンに メールを わたすのを\nやめますか？");
const u8 gText_AndFillOutTheQuestionnaire[] = _("アンケートに こたえます。");
const u8 gText_LetsReplyToTheInterview[] = _("インタビューに こたえよう！");
const u8 gText_AllTextBeingEditedWill[] = _("へんしゅうちゅうの ことばは");
const u8 gText_BeDeletedThatOkay[] = _("すべて きえます。いいですか？");
const u8 gText_QuitEditing2[] = _("へんしゅうを やめますか？"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("へんしゅうした ことばは のこりません。"); // Unused
const u8 gText_IsThatOkay[] = _("いいですか？"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("ことばを いれてください。"); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("ぜんぶの ことばは けせません。");
const u8 gText_OnlyOnePhrase[] = _("かえられる ことばは 1つだけです。");
const u8 gText_OriginalSongWillBeUsed[] = _("もとの うたを つかいます。");
const u8 gText_ThatsTrendyAlready[] = _("それは もう はやっています！"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("ことばを 2つ くみあわせます。");
const u8 gText_QuitGivingInfo[] = _("じょうほうを わたすのを やめますか？"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("ポケモンに メールを わたすのを\nやめますか？"); // Unused
const u8 gText_CreateAQuiz2[] = _("クイズを つくろう！"); // Unused
const u8 gText_SetTheAnswer[] = _("こたえを きめよう！"); // Unused
const u8 gText_CancelSelection[] = _("せんたくを やめますか？"); // Unused
const u8 gText_Profile[] = _("プロフィール");
const u8 gText_AtTheBattlesStart[] = _("しょうぶを はじめるとき:");
const u8 gText_UponWinningABattle[] = _("しょうぶに かったとき:");
const u8 gText_UponLosingABattle[] = _("しょうぶに まけたとき:");
const u8 gText_TheBardsSong[] = _("うた");
const u8 gText_WhatsHipAndHappening[] = _("なにが はやってる？");
const u8 gText_Interview[] = _("インタビュー");
const u8 gText_GoodSaying[] = _("いい ことば");
const u8 gText_FansQuestion[] = _("ファンの しつもん");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("でしの ことば");
const u8 gText_Questionnaire[] = _("アンケート");
const u8 gText_YouCannotQuitHere[] = _("ここでは やめられません。");
const u8 gText_SectionMustBeCompleted[] = _("ここは さいごまで いれてください。");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}の クイズ");
const u8 gText_Lady[] = _("おねえさん");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("クイズの もんだいを よんだら");
const u8 gText_QuestionPressTheAButton[] = _("Aボタンを おしてください。");
const u8 gText_TheQuizAnswerIs[] = _("クイズの こたえは？");
const u8 gText_LikeToQuitQuiz[] = _("この クイズへの ちょうせんを");
const u8 gText_ChallengeQuestionMark[] = _("やめますか？");
const u8 gText_IsThisQuizOK[] = _("この クイズで いいですか？");
const u8 gText_CreateAQuiz[] = _("クイズを つくろう！");
const u8 gText_SelectTheAnswer[] = _("こたえを えらぼう！");
const u8 gText_LyricsCantBeDeleted[] = _("うたの ことばは けせません。");
const u8 gText_PokemonLeague[] = _("ポケモンリーグ");
const u8 gText_PokemonCenter[] = _("ポケモンセンター");
const u8 gText_Coolness[] = _("かっこよさ ");
const u8 gText_Beauty3[] = _("うつくしさ ");
const u8 gText_Cuteness[] = _("かわいさ ");
const u8 gText_Smartness[] = _("かしこさ ");
const u8 gText_Toughness[] = _("たくましさ ");

const u8 gText_SaveFailedCheckingBackup[] = _("レポートに しっぱい。\nよびの メモリを しらべています...\n{COLOR RED}やく 1ぷん かかります");
const u8 gText_BackupMemoryDamaged[] = _("よびメモリが こわれているか\nでんちが きれています。\nあそべますが レポートは できません。");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}このまま あそべません。\nタイトルに もどります...");
const u8 gText_CheckCompleted[] = _("チェック しゅうりょう。\nもういちど レポートします。\nおまちください。");
const u8 gText_SaveCompleteGameCannotContinue[] = _("レポート しました。\n{COLOR RED}このまま あそべません。\nタイトルに もどります。");
const u8 gText_SaveCompletePressA[] = _("レポート しました。\n{COLOR RED}Aボタンを おしてください。");

const u8 gText_Ferry[] = _("ふね");
const u8 gText_SecretBase[] = _("ひみつきち");
const u8 gText_Hideout[] = _("アジト");
const u8 gText_ResetRTCConfirmCancel[] = _("とけいを なおしますか？\nA: けってい B: やめる");
const u8 gText_PresentTime[] = _("いまの ゲームない じかん");
const u8 gText_PreviousTime[] = _("まえの ゲームない じかん");
const u8 gText_PleaseResetTime[] = _("じかんを なおしてください。");
const u8 gText_ClockHasBeenReset[] = _("とけいを なおしました。\nデータを ほぞんします。おまちください。");
const u8 gText_SaveCompleted[] = _("レポート しました。");
const u8 gText_SaveFailed[] = _("レポート しっぱい...");
const u8 gText_NoSaveFileCantSetTime[] = _("レポートが ないので\nじかんを なおせません。");
const u8 gText_InGameClockUsable[] = _("ゲームない とけいの ちょうせいが\nつかえるように なりました。");
const u8 gText_Spicy2[] = _("からい");
const u8 gText_Dry2[] = _("しぶい");
const u8 gText_Sweet2[] = _("あまい");
const u8 gText_Bitter2[] = _("にがい");
const u8 gText_Sour2[] = _("すっぱい");
const u8 gText_Single[] = _("シングル");
const u8 gText_Double[] = _("ダブル");
const u8 gText_Knockout[] = _("ノックアウト");
const u8 gText_Mixed[] = _("ミックス");
const u8 gText_First[] = _("1ばんめ");
const u8 gText_Second[] = _("2ばんめ");
const u8 gText_Third[] = _("3ばんめ");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1}は たおれた...\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1}は どくに たえた。\nどくが きえた！\p");
#endif
const u8 gText_Marco[] = _("MARCO");
const u8 gText_TrainerCardName[] = _("なまえ: ");
const u8 gText_TrainerCardIDNo[] = _("ばんごう");
const u8 gText_TrainerCardMoney[] = _("おこづかい");
const u8 gText_PokeDollar[] = _("円"); // Unused
const u8 gText_TrainerCardPokedex[] = _("ずかん");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" てん"); // Unused
const u8 gText_TrainerCardTime[] = _("じかん");
const u8 gJPText_BattlePoints[] = _("ゲ？ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{STR_VAR_1}の トレーナーカード");
const u8 gText_HallOfFameDebut[] = _("えいこうの へや デビュー  ");
const u8 gText_LinkBattles[] = _("つうしん しょうぶ");
const u8 gText_LinkCableBattles[] = _("ケーブル しょうぶ");
const u8 gText_WinsLosses[] = _("かち:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  まけ:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("ポケモン こうかん");
const u8 gText_UnionTradesAndBattles[] = _("ユニオン こうかん/しょうぶ");
const u8 gText_BerryCrush[] = _("きのみクラッシュ");
const u8 gText_WaitingTrainerFinishReading[] = _("あいてが トレーナーカードを\nよみおわるまで まっています。");
const u8 gText_PokeblocksWithFriends[] = _("ともだちと ポロック");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("ともだちと コンテスト");
const u8 gText_BattlePtsWon[] = _("もらった BP");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("バトルタワー");
const u8 gText_WinsStraight[] = _("かち/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  れんしょう/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("バトルタワー");
const u8 gText_BattleDome[] = _("バトルドーム");
const u8 gText_BattlePalace[] = _("バトルパレス");
const u8 gText_BattleFactory[] = _("バトルファクトリー");
const u8 gText_BattleArena[] = _("バトルアリーナ");
const u8 gText_BattlePike[] = _("バトルチューブ");
const u8 gText_BattlePyramid[] = _("バトルピラミッド");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} シングル");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} ダブル");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} マルチ");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} つうしん");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("わたす");
const u8 gText_NoNeed[] = _("いらない");
const u8 gText_AnnouncingResults[] = _("けっかを はっぴょうします！");
const u8 gText_PreliminaryResults[] = _("よせんの けっかです！");
const u8 gText_Round2Results[] = _("2かいめの けっかです！");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_1}の {STR_VAR_2}が かった！");
const u8 gText_CommunicationStandby[] = _("つうしん たいきちゅう...");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("おおもじ");
const u8 gText_Lower[] = _("こもじ");
const u8 gText_Others[] = _("そのほか");
const u8 gText_Symbols[] = _("きごう");
const u8 gText_Register2[] = _("とうろく");
const u8 gText_Exit2[] = _("おわる");
const u8 gText_QuitChatting[] = _("チャットを やめますか？");
const u8 gText_RegisterTextWhere[] = _("どこに ことばを とうろくしますか？");
const u8 gText_RegisterTextHere[] = _("ここに ことばを とうろくしますか？");
const u8 gText_InputText[] = _("ことばを いれてください。");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0}が チャットに はいった！");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0}が チャットを でた。");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("チャットを でています...");
const u8 gText_LeaderLeftEndingChat[] = _("リーダーの {DYNAMIC 0}が でたので\nチャットを おわります。");
const u8 gText_RegisteredTextChangedOKToSave[] = _("とうろくした ことばを かえました。\nレポートして いいですか？");
const u8 gText_AlreadySavedFile_Chat[] = _("すでに レポートが あります。\nうわがきして いいですか？");
const u8 gText_SavingDontTurnOff_Chat[] = _("レポート しています...\nでんげんを きらないでください。");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0}は レポートした。");
const u8 gText_IfLeaderLeavesChatEnds[] = _("リーダーが でると チャットは\nおわります。いいですか？");
const u8 gText_Hello[] = _("こんにちは");
const u8 gText_Pokemon2[] = _("ポケモン");
const u8 gText_Trade[] = _("こうかん");
const u8 gText_Battle[] = _("しょうぶ");
const u8 gText_Lets[] = _("やろう");
const u8 gText_Ok[] = _("OK！");
const u8 gText_Sorry[] = _("ごめん");
const u8 gText_YaySmileEmoji[] = _("やった{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("ありがとう");
const u8 gText_ByeBye[] = _("バイバイ！");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1}が タマゴから うまれた！");
const u8 gText_NicknameHatchPrompt[] = _("うまれた {STR_VAR_1}に\nニックネームを つけますか？");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("きのみクラッシュを はじめますか？\nつかう きのみを えらんでください。\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("みんなが きのみを えらぶまで\nおまちください。");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}{STR_VAR_1}の きのみのこなを\nつくりました。{RESUME_MUSIC}\pきのみのこなの ごうけいは\n{STR_VAR_2}です。\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("けっかを レポートに\nきろくしています。\lおまちください。");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("もういちど きのみクラッシュを しますか？");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("きのみを もっていません。\nゲームを やめます。");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("メンバーが ぬけました。\nゲームを やめます。");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("じかんぎれ。\pいい こなは つくれませんでした...\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("つうしん たいきちゅう...");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("かい");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1}のみ");
ALIGNED(4) const u8 gText_TimeColon[] = _("じかん:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("おす はやさ:");
ALIGNED(4) const u8 gText_Silkiness[] = _("なめらかさ:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _("ふん ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("びょう");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("かい/びょう");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("おした かいすう ランキング");
ALIGNED(4) const u8 gText_CrushingResults[] = _("クラッシュ けっか");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("きれいさ ランキング");
ALIGNED(4) const u8 gText_CoopRankings[] = _("きょうりょく ランキング");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("おす ちから ランキング");
const u8 gText_BerryCrush2[] = _("きのみクラッシュ");
const u8 gText_PressingSpeedRankings[] = _("おす はやさ ランキング");
const u8 gText_Var1Players[] = _("{STR_VAR_1}にん");
const u8 gText_SymbolsEarned[] = _("もっている シンボル");
const u8 gText_BattleRecord[] = _("しょうぶの きろく");
const u8 gText_BattlePoints[] = _("バトルポイント");
const u8 gText_UnusedCancel[] = _("やめる"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("バトルフロンティアマップを みる。");
const u8 gText_CheckTrainerCard[] = _("トレーナーカードを みる。");
const u8 gText_ViewRecordedBattle[] = _("きろくした しょうぶを みる。");
const u8 gText_PutAwayFrontierPass[] = _("フロンティアパスを しまう。");
const u8 gText_CurrentBattlePoints[] = _("いまの バトルポイント。");
const u8 gText_CollectedSymbols[] = _("あつめた シンボル。");
const u8 gText_BattleTowerAbilitySymbol[] = _("バトルタワー アビリティシンボル");
const u8 gText_BattleDomeTacticsSymbol[] = _("バトルドーム タクティクスシンボル");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("バトルパレス スピリットシンボル");
const u8 gText_BattleArenaGutsSymbol[] = _("バトルアリーナ ガッツシンボル");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("バトルファクトリー ノウレッジシンボル");
const u8 gText_BattlePikeLuckSymbol[] = _("バトルチューブ ラックシンボル");
const u8 gText_BattlePyramidBraveSymbol[] = _("バトルピラミッド ブレイブシンボル");
const u8 gText_ThereIsNoBattleRecord[] = _("しょうぶの きろくは ありません。");
const u8 gText_BattleTower3[] = _("バトルタワー");
const u8 gText_BattleDome2[] = _("バトルドーム");
const u8 gText_BattlePalace2[] = _("バトルパレス");
const u8 gText_BattleArena2[] = _("バトルアリーナ");
const u8 gText_BattleFactory2[] = _("バトルファクトリー");
const u8 gText_BattlePike2[] = _("バトルチューブ");
const u8 gText_BattlePyramid2[] = _("バトルピラミッド");
const u8 gText_BattleTowerDesc[] = _("あいてを たおして てっぺんを めざせ！\nちからが ためされます。");
const u8 gText_BattleDomeDesc[] = _("トーナメントを かちぬけ！\nさくせんが ためされます。");
const u8 gText_BattlePalaceDesc[] = _("ポケモンの しょうぶを みまもれ！\nこころが ためされます。");
const u8 gText_BattleArenaDesc[] = _("ポケモンと くんで かちぬけ！\nこんじょうが ためされます。");
const u8 gText_BattleFactoryDesc[] = _("レンタルポケモンで かちを めざせ！\nちしきが ためされます。");
const u8 gText_BattlePikeDesc[] = _("3つの みちから えらんで すすめ！\nうんが ためされます。");
const u8 gText_BattlePyramidDesc[] = _("たんけんして てっぺんを めざせ！\nゆうきが ためされます。");
const u8 gText_Powder[] = _("こな");
const u8 gText_BerryPickingRecords[] = _("ドードリオの きのみどり きろく");
const u8 gText_BerriesPicked[] = _("とった きのみ:");
const u8 gText_BestScore[] = _("ベストスコア:");
const u8 gText_BerriesInRowFivePlayers[] = _("5にんで れんぞくして\nとった きのみ:");
const u8 gText_BerryPickingResults[] = _("きのみどりの けっか はっぴょう！");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 3}10P{CLEAR_TO 43}30P{CLEAR_TO 83}50P{CLEAR_TO 119}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("ランキング はっぴょう！");
const u8 gText_AnnouncingPrizes[] = _("しょうひん はっぴょう！");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("1ばんの ひとは\nこの {DYNAMIC 0}を もらえます！");
const u8 gText_CantHoldAnyMore[] = _("これいじょう もてません！");
const u8 gText_FilledStorageSpace[] = _("しまう ばしょが いっぱいです。");
const u8 gText_WantToPlayAgain[] = _("もういちど あそびますか？");
const u8 gText_SomeoneDroppedOut[] = _("だれかが ぬけました。\nつうしんを やめます。");
const u8 gText_SpacePoints[] = _(" てん");
const u8 gText_CommunicationStandby3[] = _("つうしん たいきちゅう...");
const u8 gText_SpacePoints2[] = _(" てん");
const u8 gText_SpaceTimes3[] = _("かい");
const u8 gText_PkmnJumpRecords[] = _("ポケモンジャンプ きろく");
const u8 gText_JumpsInARow[] = _("れんぞくジャンプ:");
const u8 gText_BestScore2[] = _("ベストスコア:");
const u8 gText_ExcellentsInARow[] = _("れんぞくエクセレント:");
const u8 gText_AwesomeWonF701F700[] = _("すごい スコア！\n{DYNAMIC 1} {DYNAMIC 0}を もらった！");
const u8 gText_FilledStorageSpace2[] = _("しまう ばしょが いっぱいです。");
const u8 gText_CantHoldMore[] = _("これいじょう もてません！");
const u8 gText_WantToPlayAgain2[] = _("もういちど あそびますか？");
const u8 gText_SomeoneDroppedOut2[] = _("だれかが ぬけました。\nつうしんを やめます。");
const u8 gText_CommunicationStandby4[] = _("つうしん たいきちゅう...");
const u8 gText_LinkContestResults[] = _("{PLAYER}の つうしんコンテスト けっか");
const u8 gText_1st[] = _("1ばん");
const u8 gText_2nd[] = _("2ばん");
const u8 gText_3rd[] = _("3ばん");
const u8 gText_4th[] = _("4ばん");
const u8 gText_Friend[] = _("ともだち");
const u8 gText_Pokemon3[] = _("ポケモン"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}{JPN}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS} で\nふしぎなもらいものを よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の メニューから\n'つうしん'を えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("'ゲームボーイアドバンスとつうしん'\nを せんたく してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の 'つうしん'を\nえらんで Aボタンを おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの よみこみを\nちゅうし しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん ちゅう です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん エラーです\nせつぞくを たしかめて ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん エラーです\nはじめから やりなおして ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS} に\nカードを よみこませて ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん しゅうりょう？");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな トレーナーが\nホウエンに やってきた？");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ エラー です\nデータが ほぞん できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}の シングルルーム けっか");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}の ダブルルーム けっか");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}の マルチルーム けっか");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}の つうしんマルチルーム けっか");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}の シングルトーナメント けっか");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}の ダブルトーナメント けっか");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}の シングルホール けっか");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}の ダブルホール けっか");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}の バトルチョイス けっか");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}の セットKOトーナメント けっか");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}の バトルスワップ シングル けっか");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}の バトルスワップ ダブル けっか");
const u8 gText_BattleQuestResults[] = _("{PLAYER}の バトルクエスト けっか");
const u8 gText_Lv502[] = _("レベル 50");
const u8 gText_OpenLv[] = _("オープン レベル");
const u8 gText_WinStreak[] = _("れんしょう: {STR_VAR_1}");
const u8 gText_Current[] = _("いま");
const u8 gText_Record[] = _("きろく");
const u8 gText_Prev[] = _("まえ");
const u8 gText_RentalSwap[] = _("レンタル/スワップ");
const u8 gText_Total[] = _("ごうけい");
const u8 gText_ClearStreak[] = _("れんぞくクリア: {STR_VAR_1}");
const u8 gText_Championships[] = _("ゆうしょう: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("クリアした へや: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("クリアかいすう:{CLEAR 5}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("れんぞくKO: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("かいすう: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("クリアした かい: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("レベル 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("オープンレベル");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("れんしょう: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("れんぞくクリア: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("クリアした へや: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("れんぞくKO: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("クリアした かい: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _("と {STR_VAR_2}しゅの ポケモンは\nつかえません");
const u8 gText_FrontierFacilityIncluding[] = _("。\pたとえば ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" は つかえません");

const u8 gText_YesNo[] = _("はい\nいいえ");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("ばあ！");
const u8 gText_CommErrorCheckConnections[] = _("つうしん エラー...\nせつぞくを たしかめてから\nでんげんを いれなおしてください。");
const u8 gText_CommErrorEllipsis[] = _("つうしん エラー...");
const u8 gText_MoveCloserToLinkPartner[] = _("つうしんあいてに ちかづいてください。\nあいだに ものを おかないでください。");
const u8 gText_ABtnRegistrationCounter[] = _("Aボタン: とうろくカウンター");
const u8 gText_ABtnTitleScreen[] = _("Aボタン: タイトル");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}にん つうしん");
const u8 gText_BronzeCard[] = _("ブロンズ");
const u8 gText_CopperCard[] = _("カッパー");
const u8 gText_SilverCard[] = _("シルバー");
const u8 gText_GoldCard[] = _("ゴールド");
const u8 gText_Day[] = _("にち");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("けってい");
const u8 gText_Days[] = _("にち"); // Unused
const u8 gText_TimeColon2[] = _("じかん:"); // Unused
const u8 gText_GameTime[] = _("ゲームじかん"); // Unused
const u8 gText_RTCTime[] = _("RTCじかん"); // Unused
const u8 gText_UpdatedTime[] = _("なおした じかん"); // Unused
const u8 gText_MenuPokedex[] = _("ずかん");
const u8 gText_MenuPokemon[] = _("ポケモン");
const u8 gText_MenuBag[] = _("バッグ");
const u8 gText_MenuPokenav[] = _("ナビ");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("レポート");
const u8 gText_MenuOption[] = _("せってい");
const u8 gText_MenuExit[] = _("とじる");
const u8 gText_MenuRetire[] = _("やめる");
const u8 gText_MenuRest[] = _("やすむ");
const u8 gText_MenuDexNav[] = _("サーチ");
const u8 gText_SafariBallStock[] = _("サファリボール\nのこり: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nボール  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("バトルピラミッド\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("1かい");
const u8 gText_Floor2[] = _("2かい");
const u8 gText_Floor3[] = _("3かい");
const u8 gText_Floor4[] = _("4かい");
const u8 gText_Floor5[] = _("5かい");
const u8 gText_Floor6[] = _("6かい");
const u8 gText_Floor7[] = _("7かい");
const u8 gText_Peak[] = _("ちょうじょう");
const u8 gText_LinkStandby2[] = _("つうしん たいきちゅう...\n... ... Bボタン: やめる");
const u8 gText_PressAToLoadEvent[] = _("Aボタンで イベントを よみこむ。\n... ... Bボタン: やめる");
const u8 gText_LoadingEvent[] = _("イベントを よみこみちゅう...");
const u8 gText_DontRemoveCableTurnOff[] = _("ケーブルを ぬかないでください。\nでんげんを きらないでください。");
const u8 gText_EventSafelyLoaded[] = _("イベントを よみこみました。");
const u8 gText_LoadErrorEndingSession[] = _("よみこみ エラー。\nおわります。");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("ホウエン");
const u8 gText_DexNational[] = _("ぜんこく");
const u8 gText_PokedexDiploma[] = _("プレイヤー: {CLEAR 16}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nあなたが {STR_VAR_1}ずかんを\nみごとに かんせい させたことを\nここに しるします。\n\n{CLEAR_TO 66}{COLOR RED}{SHADOW LIGHT_RED}ゲームフリーク");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ？ムフリ？ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("ホウエン");
const u8 gText_Kanto[] = _("カントー");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2}を\n{STR_VAR_1}へ おくります。");
const u8 gText_ByeByeVar1[] = _("バイバイ {STR_VAR_2}！");
const u8 gText_XSentOverY[] = _("{STR_VAR_1}は {STR_VAR_3}を おくった。");
const u8 gText_TakeGoodCareOfX[] = _("{STR_VAR_3}を たいせつに してね！");

const u8 gText_ThreeQuestionMarks[] = _("？？？");
const u8 gText_MaxHP[] = _("さいだいHP");
const u8 gText_Attack[] = _("こうげき");
const u8 gText_Defense[] = _("ぼうぎょ");
const u8 gText_Speed[] = _("すばやさ");
const u8 gText_SpAtk[] = _("とくこう");
const u8 gText_SpDef[] = _("とくぼう");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("ー");
const u8 gText_MixingRecords[] = _("レコードを まぜています...");
const u8 gText_RecordMixingComplete[] = _("レコードを まぜおわりました。\nおまちいただき ありがとう。");
const u8 gText_RentalPkmn2[] = _("レンタルポケモン");
const u8 gText_SelectFirstPkmn[] = _("1ひきめの ポケモンを えらんでください。");
const u8 gText_SelectSecondPkmn[] = _("2ひきめの ポケモンを えらんでください。");
const u8 gText_SelectThirdPkmn[] = _("3ひきめの ポケモンを えらんでください。");
const u8 gText_Rent[] = _("かりる");
const u8 gText_Summary[] = _("つよさ");
const u8 gText_Others2[] = _("そのほか");
const u8 gText_Deselect[] = _("はずす");
const u8 gText_TheseThreePkmnOkay[] = _("この 3ひきで いいですか？");
const u8 gText_Yes2[] = _("はい");
const u8 gText_No2[] = _("いいえ");
const u8 gText_CantSelectSamePkmn[] = _("おなじ ポケモンは えらべません。");
const u8 gText_PkmnSwap[] = _("ポケモンスワップ");
const u8 gText_SelectPkmnToSwap[] = _("いれかえる ポケモンを えらんでください。");
const u8 gText_SelectPkmnToAccept[] = _("うけとる ポケモンを えらんでください。");
const u8 gText_Swap[] = _("いれかえ");
const u8 gText_Summary2[] = _("つよさ");
const u8 gText_Rechoose[] = _("えらびなおす");
const u8 gText_QuitSwapping[] = _("スワップを やめますか？");
const u8 gText_Yes3[] = _("はい");
const u8 gText_No3[] = _("いいえ");
const u8 gText_PkmnForSwap[] = _("スワップする ポケモン");
const u8 gText_Cancel3[] = _("やめる");
const u8 gText_Swap2[] = _("いれかえ"); // Unused
const u8 gText_Accept[] = _("うけとる"); // Unused
const u8 gText_AcceptThisPkmn[] = _("この ポケモンを うけとりますか？");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("おなじ ポケモンが てもちに います。");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("しゅじんこう");
const u8 gText_SavingBadges[] = _("バッジ");
const u8 gText_SavingPokedex[] = _("ずかん");
const u8 gText_SavingTime[] = _("じかん");
const u8 gText_WirelessCommStatus[] = _("ワイヤレス つうしん じょうきょう");
const u8 gText_PeopleTrading[] = _("こうかん している ひと:");
const u8 gText_PeopleBattling[] = _("しょうぶ している ひと:");
const u8 gText_PeopleInUnionRoom[] = _("ユニオンルームに いる ひと:");
const u8 gText_PeopleCommunicating[] = _("つうしん している ひと:");
const u8 gText_F700Players[] = _("{DYNAMIC 0}にん");
const u8 gText_F701Players[] = _("{DYNAMIC 1}にん");
const u8 gText_F702Players[] = _("{DYNAMIC 2}にん");
const u8 gText_F703Players[] = _("{DYNAMIC 3}にん");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("ふしぎなカード");
ALIGNED(4) const u8 gText_WonderNews[] = _("ふしぎなニュース");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("ワイヤレスつうしん");
ALIGNED(4) const u8 gText_Friend2[] = _("ともだち");
ALIGNED(4) const u8 gText_Exit3[] = _("おわる");
ALIGNED(4) const u8 gText_Receive[] = _("うけとる");
ALIGNED(4) const u8 gText_Send[] = _("おくる");
ALIGNED(4) const u8 gText_Toss[] = _("すてる");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("いろいろな イベントを\nワイヤレスつうしんで とりこみます。");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("もっている ふしぎなカードを よみます。");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("とどいた ニュースを よみます。");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("タイトルに もどります。");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("ふしぎなカードが ないので\nあたらしい カードを いれます。");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("ふしぎなニュースが ないので\nあたらしい ニュースを いれます。");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("ふしぎなカードを どこで\nよみますか？");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("ふしぎなニュースを どこで\nよみますか？");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("つうしん たいきちゅう...\nBボタン: やめる"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("つうしんちゅう...");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("つうしん しゅうりょう。");
ALIGNED(4) const u8 gText_CommunicationError[] = _("つうしん エラー。");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("つうしんを やめました。");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("ふしぎなカードを すてて\nあたらしい カードを いれますか？");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("カードの おくりものを まだ\nうけとっていません。 それでも いれますか？");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("{STR_VAR_1}から\nふしぎなカードを うけとりました。");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("{STR_VAR_1}から\nふしぎなニュースを うけとりました。");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("あたらしい ふしぎなカードを\nうけとりました。");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("あたらしい ふしぎなニュースを\nうけとりました。");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("あたらしい スタンプを うけとりました。");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("あたらしい トレーナーが やってきました。");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("その ふしぎなカードは\nすでに もっています。");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("その ふしぎなニュースは\nすでに もっています。");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("その スタンプは\nすでに もっています。");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("スタンプを おす ばしょが\nもう ありません。");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("きろくを ワイヤレスつうしんで\nおくりました。");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("この トレーナーから\nふしぎなカードは うけとれません。");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("この トレーナーから\nふしぎなニュースは うけとれません。");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("なにも おくられませんでした...");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("ふしぎなカードを\nどうしますか？");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("ふしぎなニュースを\nどうしますか？");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("ふしぎなカードを おくっています...");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("ふしぎなニュースを おくっています...");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("ふしぎなカードを\n{STR_VAR_1}へ おくりました。");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("ふしぎなニュースを\n{STR_VAR_1}へ おくりました。");
ALIGNED(4) const u8 gText_StampSentTo[] = _("スタンプを {STR_VAR_1}へ おくりました。");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("おくりものを {STR_VAR_1}へ おくりました。");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("あいては おなじ ふしぎなカードを\nすでに もっています。");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("あいては おなじ ふしぎなニュースを\nすでに もっています。");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("あいては おなじ スタンプを\nすでに もっています。");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("あいてが つうしんを やめました。");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("この トレーナーに ふしぎな おくりものは\nおくれません。");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("カードを すてると\nイベントは おきません。いいですか？");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("この ニュースを すてても\nいいですか？");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("おくりものを まだ うけとっていません。\nすてても いいですか？");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("データを ほぞんします。\nおまちください。");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("レポート しました。\nAボタンを おしてください。");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("ふしぎなカードを すてました。");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("ふしぎなニュースを すてました。");
ALIGNED(4) const u8 gText_MysteryGift[] = _("ふしぎな おくりもの");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}OK {B_BUTTON}おわる");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}OK {B_BUTTON}やめる");
const u8 gText_PlayersBattleResults[] = _("{PLAYER}の しょうぶ けっか");
const u8 gText_TotalRecordWLD[] = _("ごうけい かち:{STR_VAR_1} まけ:{STR_VAR_2} ひきわけ:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 83}かち{CLEAR_TO 128}まけ{CLEAR_TO 176}ひきわけ");
const u8 gText_CommunicationStandby5[] = _("つうしん たいきちゅう...");
const u8 gDaycareText_GetAlongVeryWell[] = _("2ひきの なかは\nとても よい ようです。");
const u8 gDaycareText_GetAlong[] = _("2ひきの なかは よい ようです。");
const u8 gDaycareText_DontLikeOther[] = _("2ひきの なかは\nあまり よくない ようです。");
const u8 gDaycareText_PlayOther[] = _("2ひきは おたがいより\nほかの ポケモンと あそびたいようです。");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("おわる");
const u8 gText_Lv[] = _("{ENG}{LV}{AUTO}");
const u8 gText_TimeBoard[] = _("タイムボード");
const u8 gText_TimeCleared[] = _("クリアタイム ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1}ふん {STR_VAR_2}.{STR_VAR_3}びょう");
const u8 gText_TrainerHill1F[] = _("1F");
const u8 gText_TrainerHill2F[] = _("2F");
const u8 gText_TrainerHill3F[] = _("3F");
const u8 gText_TrainerHill4F[] = _("4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("{STR_VAR_1}に どの {STR_VAR_3}を\nおしえますか？");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("{STR_VAR_2}を おしえますか？");
const u8 gText_MoveRelearnerTeachMoveConfirmUseTm[] = _("{STR_VAR_2}を おしえますか？\n{STR_VAR_3}を 1つ つかいます。");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1}は\n{STR_VAR_2}を おぼえた！");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1}は {STR_VAR_2}を\nおぼえたい。\pしかし {STR_VAR_1}は 4つまでしか\nわざを おぼえられない。\pふるい わざを わすれて\n{STR_VAR_2}を おぼえますか？");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("{STR_VAR_2}を おしえるのを\nやめますか？");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1 {PAUSE 15}2 そして {PAUSE 15}... {PAUSE 15}... {PAUSE 15}... {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}ポカン！\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1}は {STR_VAR_3}を わすれた。\pそして...\p{STR_VAR_1}は {STR_VAR_2}を おぼえた。");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1}は\n{STR_VAR_2}を おぼえなかった。"); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("{STR_VAR_1}に あたらしい わざを\nおしえるのを やめますか？");
const u8 gText_MoveRelearnerStop[] = _("{STR_VAR_1}に あたらしい わざを\nおぼえさせるのを やめますか？");;
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("どの わざを わすれますか？\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("しょうぶの わざ");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("コンテストわざ");
const u8 gText_MoveRelearnerType[] = _("タイプ/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("いりょく/");
const u8 gText_MoveRelearnerAccuracy[] = _("めいちゅう/");
const u8 gText_MoveRelearnerAppeal[] = _("アピール");
const u8 gText_MoveRelearnerJam[] = _("ジャマ");
const u8 gText_ClearAllSaveData[] = _("すべての レポートを けしますか？");
const u8 gText_ClearingData[] = _("データを けしています...\nおまちください。");
const u8 gText_IsThisTheCorrectTime[] = _("この じかんで いいですか？");
const u8 gText_Confirm3[] = _("けってい");
const u8 gText_Cancel4[] = _("やめる");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("つうしん たいきちゅう...\nあいての せんたくを まっています。");
const u8 gText_BattleWasRefused[] = _("しょうぶを ことわられました。{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("しょうぶを ことわりました。{PAUSE 60}");
const u8 gText_NoWeather[] = _("てんきなし"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("はれ"); // Unused
const u8 gText_Sunny2[] = _("はれ2"); // Unused
const u8 gText_Rain[] = _("あめ"); // Unused
const u8 gText_Snow[] = _("ゆき"); // Unused
const u8 gText_Lightning[] = _("かみなり"); // Unused
const u8 gText_Fog[] = _("きり"); // Unused
const u8 gText_VolcanoAsh[] = _("かざんばい"); // Unused
const u8 gText_Sandstorm[] = _("すなあらし"); // Unused
const u8 gText_Fog2[] = _("きり2"); // Unused
const u8 gText_Seafloor[] = _("かいてい"); // Unused
const u8 gText_Cloudy[] = _("くもり"); // Unused
const u8 gText_Sunny3[] = _("はれ3"); // Unused
const u8 gText_HeavyRain[] = _("おおあめ"); // Unused
const u8 gText_Seafloor2[] = _("かいてい2"); // Unused
const u8 gText_DelAll[] = _("ぜんぶけす");
const u8 gText_Cancel5[] = _("やめる");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("クイズ");
const u8 gText_Answer[] = _("こたえ");
const u8 gText_PokeBalls[] = _("ボール");
const u8 gText_Berry[] = _("きのみ");
const u8 gText_Berries[] = _("きのみ");
const u8 gText_ExpShareOn[] = _("けいけんちそうちを オンに しました。{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("けいけんちそうちを オフに しました。{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("ゴースト");
const u8 gText_Boulderbadge[] = _("グレーバッジ");
const u8 gText_Cascadebadge[] = _("ブルーバッジ");
const u8 gText_Thunderbadge[] = _("オレンジバッジ");
const u8 gText_Rainbowbadge[] = _("レインボーバッジ");
const u8 gText_Soulbadge[] = _("ピンクバッジ");
const u8 gText_Marshbadge[] = _("ゴールドバッジ");
const u8 gText_Volcanobadge[] = _("クリムゾンバッジ");
const u8 gText_Earthbadge[] = _("グリーンバッジ");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("オーキド: ポケモンを よく しることは\nとても たいせつじゃ。\p");
const u8 gText_OakThisIsListOfPokemon[] = _("これは あなたの ポケモンリストじゃ \n{PLAYER}。\pここでは ポケモンの のうりょくや\nわざを みられる。\pどうぐを つかう ポケモンを\nえらぶことも できるぞ。{PAUSE_UNTIL_PRESS}");
