#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("サファイア");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("ルビー");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("エメラルド");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("アクア");
const u8 gText_ExpandedPlaceholder_Magma[] = _("マグマ");
const u8 gText_ExpandedPlaceholder_Archie[] = _("アオギリ");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("マツブサ");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("カイオーガ");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("グラードン");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("ユウキ");
const u8 gText_ExpandedPlaceholder_May[] = _("ハルカ");
const u8 gText_ExpandedPlaceholder_Red[] = _("あか");
const u8 gText_ExpandedPlaceholder_Green[] = _("みどり");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("タマゴ");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("ポケモン");
const u8 gText_Player[] = _("しゅじんこう"); // Unused
const u8 gText_Pokedex[] = _("POKeDEX"); // Unused
const u8 gText_Time[] = _("プレイじかん");
const u8 gText_Badges[] = _("もっているバッジ"); // Unused
const u8 gText_AButton[] = _("エーボタン"); // Unused
const u8 gText_BButton[] = _("ビーボタン"); // Unused
const u8 gText_RButton[] = _("アールボタン"); // Unused
const u8 gText_LButton[] = _("エルボタン"); // Unused
const u8 gText_Start[] = _("スタートボタン"); // Unused
const u8 gText_Select[] = _("セレクトボタン"); // Unused
const u8 gText_ControlPad[] = _("じゅうじボタン"); // Unused
const u8 gText_LButtonRButton[] = _("Lボタン Rボタン"); // Unused
const u8 gText_Controls[] = _("そうさ せつめい"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}NEXT");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}NEXT {B_BUTTON}BACK");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}NEXT {B_BUTTON}CANCEL");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}{B_BUTTON}CANCEL");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}EXIT");
const u8 gText_Boy[] = _("おとこ");
const u8 gText_Girl[] = _("おんな");
const u8 gText_ThisIsAPokemon[] = _("ハスボー だすよ{PAUSE 96}$");
const u8 gText_5MarksPokemon[] = _("????? POKEMON");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 12}??'??");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("???.?kg");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       POKEMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 12}    '    ");
const u8 gText_EmptyWeight[] = _("   . kg"); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("なきごえ");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("の おおきさくらべ");
const u8 gText_PokedexRegistration[] = _("POKeDEX registration completed.");
const u8 gText_HTHeight[] = _("HT");
const u8 gText_WTWeight[] = _("WT");
const u8 gText_SearchingPleaseWait[] = _("Searching...\nPlease wait.");
const u8 gText_SearchCompleted[] = _("けんさくが しゅうりょう しました!");
const u8 gText_NoMatchingPkmnWereFound[] = _("No matching POKEMON were found.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Search for POKEMON based on\nselected parameters.");
const u8 gText_SwitchPokedexListings[] = _("Switch POKeDEX listings.");
const u8 gText_ReturnToPokedex[] = _("Return to the POKeDEX.");
const u8 gText_SelectPokedexMode[] = _("Select the POKeDEX mode.");
const u8 gText_SelectPokedexListingMode[] = _("Select the POKeDEX listing mode.");
const u8 gText_ListByFirstLetter[] = _("List by the first letter in the name.\nSpotted POKEMON only.");
const u8 gText_ListByBodyColor[] = _("List by body color.\nSpotted POKEMON only.");
const u8 gText_ListByType[] = _("List by type.\nOwned POKEMON only.");
const u8 gText_ExecuteSearchSwitch[] = _("けんさく/きりかえを じっこうします");
const u8 gText_DexHoennTitle[] = _("ホウエン ずかん");
const u8 gText_DexNatTitle[] = _("ぜんこく ずかん");
const u8 gText_DexSortNumericalTitle[] = _("ばんごう じゅん");
const u8 gText_DexSortAtoZTitle[] = _("ごじゅうおん じゅん");
const u8 gText_DexSortHeaviestTitle[] = _("おもい じゅん");
const u8 gText_DexSortLightestTitle[] = _("かるい じゅん");
const u8 gText_DexSortTallestTitle[] = _("たかい じゅん");
const u8 gText_DexSortSmallestTitle[] = _("ひくい じゅん");
const u8 gText_DexSearchAlphaABC[] = _("あいうえお");
const u8 gText_DexSearchAlphaDEF[] = _("かきくけこ");
const u8 gText_DexSearchAlphaGHI[] = _("さしすせそ");
const u8 gText_DexSearchAlphaJKL[] = _("たちつてと");
const u8 gText_DexSearchAlphaMNO[] = _("なにぬねの");
const u8 gText_DexSearchAlphaPQR[] = _("はひふへほ");
const u8 gText_DexSearchAlphaSTU[] = _("まみむめも");
const u8 gText_DexSearchAlphaVWX[] = _("らりるれろ");
const u8 gText_DexSearchAlphaYZ[] = _("やゆよわをん");
const u8 gText_DexSearchColorRed[] = _("あか");
const u8 gText_DexSearchColorBlue[] = _("あお");
const u8 gText_DexSearchColorYellow[] = _("きいろ");
const u8 gText_DexSearchColorGreen[] = _("みどり");
const u8 gText_DexSearchColorBlack[] = _("くろ");
const u8 gText_DexSearchColorBrown[] = _("ちゃいろ");
const u8 gText_DexSearchColorPurple[] = _("むらさき");
const u8 gText_DexSearchColorGray[] = _("はいいろ");
const u8 gText_DexSearchColorWhite[] = _("しろ");
const u8 gText_DexSearchColorPink[] = _("ピンク");
const u8 gText_DexHoennDescription[] = _("HOENN region's POKeDEX");
const u8 gText_DexNatDescription[] = _("National edition POKeDEX");
const u8 gText_DexSortNumericalDescription[] = _("POKEMON are listed according to their\nnumber.");
const u8 gText_DexSortAtoZDescription[] = _("Spotted and owned POKEMON are listed\nalphabetically.");
const u8 gText_DexSortHeaviestDescription[] = _("Owned POKEMON are listed from the\nheaviest to the lightest.");
const u8 gText_DexSortLightestDescription[] = _("Owned POKEMON are listed from the\nlightest to the heaviest.");
const u8 gText_DexSortTallestDescription[] = _("Owned POKEMON are listed from the\ntallest to the smallest.");
const u8 gText_DexSortSmallestDescription[] = _("Owned POKEMON are listed from the\nsmallest to the tallest.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("してい しない");
const u8 gText_DexSearchTypeNone[] = _("なし");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("でんどういり おめでとう!");
const u8 gText_HOFDexRating[] = _("Spotted POKEMON: {STR_VAR_1}!\nOwned POKEMON: {STR_VAR_2}!\pPROF. BIRCH's POKeDEX rating!\pPROF. BIRCH: Let's see...\p");
const u8 gText_HOFDexSaving[] = _("SAVING...\nDON'T TURN OFF THE POWER.");
const u8 gText_HOFCorrupted[] = _("でんどういりの きろくが こわれています!");
const u8 gText_HOFNumber[] = _("HALL OF FAME No. {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("リーグ チャンピオン! おめでとう!");
const u8 gText_Number[] = _("ばんめ");
const u8 gText_Level[] = _("Lv");
const u8 gText_IdNumberSlash[] = _("IDNo./"); // Unused
const u8 gText_Name[] = _("なまえ   ");
const u8 gText_IDNumber[] = _("IDNo.");
const u8 gText_BirchInTrouble[] = _("PROF. BIRCH is in trouble!\nRelease a POKEMON and rescue him!");
const u8 gText_ConfirmStarterChoice[] = _("Do you choose this POKEMON?");
const u8 gText_Pokemon4[] = _("POKEMON"); // Unused
const u8 gText_FlyToWhere[] = _("どこへ とびますか?");
const u8 gMenuText_Use[] = _("つかう");
const u8 gMenuText_Toss[] = _("すてる");
const u8 gMenuText_Register[] = _("とうろく");
const u8 gMenuText_Give[] = _("もたせる");
const u8 gMenuText_Confirm[] = _("けってい");
const u8 gText_Cancel[] = _("もどる");
const u8 gText_Cancel2[] = _("もどる");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("なし");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("ー");
const u8 gText_TwoDashes[] = _("ーー");
const u8 gText_ThreeDashes[] = _("ーーー");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 1}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("まえに もどります!");
const u8 gText_WhatWouldYouLike[] = _("なにを しますか?");
const u8 gMenuText_Give2[] = _("もたせる");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _("のみ"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} COINS");
const u8 gText_CloseBag[] = _("バッグをとじる");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}\nis selected.");
const u8 gText_CantWriteMail[] = _("ここで メールを\nかくことは できません!");
const u8 gText_NoPokemon[] = _("There is no\nPOKEMON.");
const u8 gText_MoveVar1Where[] = _("Move the\n{STR_VAR_1}\nwhere?");
const u8 gText_Var1CantBeHeld[] = _("The {STR_VAR_1} can't be held.");
const u8 gText_TossHowManyVar1s[] = _("Toss out how many\n{STR_VAR_1}?");
const u8 gText_ThrewAwayVar2Var1s[] = _("Threw away {STR_VAR_2}\n{STR_VAR_1}.");
const u8 gText_ConfirmTossItems[] = _("Is it okay to\nthrow away {STR_VAR_2}\n{STR_VAR_1}?");
const u8 gText_DadsAdvice[] = _("DAD's advice...\n{PLAYER}, there's a time and place for\leverything!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} used the\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("But the effects of a REPEL\nlingered from earlier.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("But the effects of a Lure\nlingered from earlier.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("The BOX is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("フィールド");
const u8 gText_TheBattle[] = _("せんとう");
const u8 gText_ThePokemonList[] = _("the POKEMON LIST");
const u8 gText_TheShop[] = _("ショップ");
const u8 gText_ThePC[] = _("パソコン");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Return to\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS]      = COMPOUND_STRING("どうぐ"),
    [POCKET_POKE_BALLS] = COMPOUND_STRING("POKe BALLS"),
    [POCKET_TM_HM]      = COMPOUND_STRING("わざマシン"),
    [POCKET_BERRIES]    = COMPOUND_STRING("きのみ"),
    [POCKET_KEY_ITEMS]  = COMPOUND_STRING("たいせつなもの")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 3}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 17}{STR_VAR_1}{CLEAR 5}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("かいに きた");
const u8 gText_ShopSell[] = _("うりに きた");
const u8 gText_ShopQuit[] = _("よむのを やめる");
const u8 gText_ThatItemIsSoldOut[] = _("I'm sorry, but that item is sold out.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("SOLD OUT");
const u8 gText_InBagVar1[] = _("IN BAG: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("かいもの を やめます");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Certainly.\nHow many would you like?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}? Certainly.\nHow many would you like?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? And you wanted {STR_VAR_2}?\nThat will be ¥{STR_VAR_3}.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}, is it?\nThat'll be ¥{STR_VAR_2}. Do you want it?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("You wanted {STR_VAR_1}?\nThat'll be ¥{STR_VAR_2}. Will that be okay?");
const u8 gText_HereYouGoThankYou[] = _("はい まいど!\nありがとう ございます");
const u8 gText_ThankYouIllSendItHome[] = _("どうも ありがとう!\nじたくの パソコンに おくって おきますね!");
const u8 gText_ThanksIllSendItHome[] = _("どうも ありがとう!\nじたくの パソコンに おくって おくね!");
const u8 gText_YouDontHaveMoney[] = _("You don't have enough money.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("You have no more room for this\nitem.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("The space for {STR_VAR_1} is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("その ほかに わたしどもで\nなにか おちからに なれることは?");
const u8 gText_CanIHelpWithAnythingElse[] = _("その ほかに\nなにか ちからに なれることは?");
const u8 gText_ThrowInPremierBall[] = _("I'll throw in a PREMIER BALL, too.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("I'll throw in {STR_VAR_1} PREMIER BALLS, too.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Oh, no.\nI can't buy that.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nHow many would you like to sell?");
const u8 gText_ICanPayVar1[] = _("I can pay ¥{STR_VAR_1}.\nWould that be okay?");
const u8 gText_TurnedOverVar1ForVar2[] = _("Turned over the {STR_VAR_2}\nand received ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("HP");
const u8 gText_SpAtk3[] = _("とくこう");
const u8 gText_SpDef3[] = _("とくぼう");
const u8 gText_WontHaveEffect[] = _("It won't have any effect.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Choose ポケモン to fuse with.");
const u8 gText_CantBeUsedOnPkmn[] = _("This can't be used on\nthat POKEMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} can't be switched\nout!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} is already\nin battle!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} has already been\nselected.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} has no energy\nleft to battle!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("You can't switch {STR_VAR_1}'s\nPOKEMON with one of yours!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("An EGG can't battle!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("This can't be used until a new\nBADGE is obtained.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("No more than {STR_VAR_1} POKEMON\nmay enter.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("とった メールを パソコンに\nてんそうしますか?");
const u8 gText_MailSentToPC[] = _("The MAIL was sent to your PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("Your PC's MAILBOX is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("メールを とると メッセージが\nきえてしまいますが よろしいですか?");
const u8 gText_RemoveMailBeforeItem[] = _("MAIL must be removed before\nholding an item.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} was given the\n{STR_VAR_2} to hold.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} is already holding\none {STR_VAR_2}.\pWould you like to switch the\ntwo items?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} isn't holding\nanything.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("Received the {STR_VAR_2}\nfrom {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("MAIL was taken from the\nPOKEMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("The {STR_VAR_2} was taken and\nreplaced with the {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("This POKEMON is holding an\nitem. It cannot hold MAIL.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("MAIL was transferred from\nthe MAILBOX.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("The BAG is full. The POKEMON's\nitem could not be removed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} and {STR_VAR_2}\nare not compatible.\p{STR_VAR_2} can't be\nlearned.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} wants to learn the\nmove {STR_VAR_2}.\pHowever, {STR_VAR_1} already\nknows four moves.\pShould a move be deleted and\nreplaced with {STR_VAR_2}?");
const u8 gText_StopLearningMove2[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Which move should be forgotten?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2, and{PAUSE 15}... {PAUSE 15}... {PAUSE 15}... {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p{STR_VAR_1} forgot how to\nuse {STR_VAR_2}.\pAnd...{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} already knows\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}'s HP was restored\nby {STR_VAR_2} point(s).{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} was cured of its\npoisoning.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} was cured of\nparalysis.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} woke up.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}'s burn was healed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}'s frostbite was healed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} was thawed out.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("PP was restored.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} became healthy.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}'s PP increased.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} was elevated to\nLv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points\nand was elevated to Lv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}'s base {STR_VAR_2}\nstat was raised.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} turned friendly.\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} adores you!\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} turned friendly.\nThe base {STR_VAR_2} can't fall!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} snapped out of its\nconfusion.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} got over its\ninfatuation.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} transformed!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("Throw away this\n{STR_VAR_1}?");
const u8 gText_ItemThrownAway[] = _("The {STR_VAR_1}\nwas thrown away.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("Teach which POKEMON?"); // Unused
const u8 gText_ChoosePokemon[] = _("Choose a POKEMON.");
const u8 gText_MoveToWhere[] = _("どこに いどうしますか?");
const u8 gText_TeachWhichPokemon[] = _("Teach which POKEMON?");
const u8 gText_UseOnWhichPokemon[] = _("Use on which POKEMON?");
const u8 gText_GiveToWhichPokemon[] = _("Give to which POKEMON?");
const u8 gText_DoWhatWithPokemon[] = _("Do what with this ポケモン?");
const u8 gText_NothingToCut[] = _("きれるものが ありません!");
const u8 gText_CantSurfHere[] = _("ここでは のれません");
const u8 gText_AlreadySurfing[] = _("すでに なみのり しています");
const u8 gText_CantUseHere[] = _("ここでは つかえません");
const u8 gText_RestoreWhichMove[] = _("どれを かいふくする?");
const u8 gText_BoostPp[] = _("どれを ふやす?");
const u8 gText_DoWhatWithItem[] = _("もちものを どうしますか?");
const u8 gText_NoPokemonForBattle[] = _("No POKEMON for battle!");
const u8 gText_ChoosePokemon2[] = _("Choose a POKEMON.");
const u8 gText_NotEnoughHp[] = _("Not enough HP...");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1} POKEMON are needed.");
const u8 gText_PokemonCantBeSame[] = _("POKEMON can't be the same.");
const u8 gText_NoIdenticalHoldItems[] = _("おなじ どうぐを もってます");
const u8 gText_CurrentIsTooFast[] = _("ながれが はやくて ダメだ!");
const u8 gText_DoWhatWithMail[] = _("メールを どうしますか?");
const u8 gText_ChoosePokemonCancel[] = _("Choose POKEMON or CANCEL.");
const u8 gText_ChoosePokemonConfirm[] = _("Choose POKEMON and confirm.");
const u8 gText_SendWhichMonToPC[] = _("Send which POKEMON to the PC?");
const u8 gText_MoveItemWhere[] = _("Move item to where?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}'s {STR_VAR_2} and\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}'s {STR_VAR_2} were swapped!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("サイクリングを たのしもう!");
const u8 gText_InUseAlready_PM[] = _("すでに おかれて います!");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} is already holding\none {STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("Order which\nappliance?");
const u8 gText_NoUse[] = _("つかえません");
const u8 gText_Able[] = _("でられます");
const u8 gText_First_PM[] = _("いちばんめ");
const u8 gText_Second_PM[] = _("にばんめ");
const u8 gText_Third_PM[] = _("さんばんめ");
const u8 gText_Able2[] = _("でられます");
const u8 gText_NotAble[] = _("でられません");
const u8 gText_Able3[] = _("おぼえられる!");
const u8 gText_NotAble2[] = _("おぼえられない");
const u8 gText_Learned[] = _("もうおぼえてる");
const u8 gText_Have[] = _("もっている");
const u8 gText_DontHave[] = _("もっていない");
const u8 gText_Fourth[] = _("よんばんめ");
const u8 gText_PkmnCantParticipate[] = _("That POKEMON can't participate.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("さんかを やめますか?");
const u8 gText_CancelBattle[] = _("たいせんを やめますか?");
const u8 gText_ReturnToWaitingRoom[] = _("ひかえしつに もどりますか?");
const u8 gText_CancelChallenge[] = _("ちょうせんを やめますか?");
const u8 gText_EscapeFromHere[] = _("Want to escape from here and return\nto {STR_VAR_1}?");
const u8 gText_ReturnToHealingSpot[] = _("Want to return to the healing spot\nused last in {STR_VAR_1}?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか?");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("That's your only\nPOKEMON for battle.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("That POKEMON can't be traded\nnow.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("That POKEMON can't be traded.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("タマゴは いま\nこうかんに だせません");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("The other TRAINER's POKEMON\ncan't be traded now.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("The other TRAINER can't accept\nthat POKEMON now.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("その あいてとは いまは \nこうかん できません");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("That isn't the type of POKEMON\nthat the other TRAINER wants.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("それは タマゴでは ありません");
const u8 gText_Register[] = _("とうろく");
const u8 gText_Attack3[] = _("こうげき");
const u8 gText_Defense3[] = _("ぼうぎょ");
const u8 gText_SpAtk4[] = _("とくこう");
const u8 gText_SpDef4[] = _("とくぼう");
const u8 gText_Speed2[] = _("すばやさ");
const u8 gText_HP4[] = _("HP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("おや/");
const u8 gText_RentalPkmn[] = _("RENTAL POKEMON");
const u8 gText_TypeSlash[] = _("タイプ/");
const u8 gText_Power[] = _("いりょく");
const u8 gText_Accuracy2[] = _("めいちゅう");
const u8 gText_Appeal[] = _("アピール");
const u8 gText_Jam[] = _("ジャマ");
const u8 gText_Status[] = _("じょうたい");
const u8 gText_ExpPoints[] = _("けいけんち");
const u8 gText_NextLv[] = _("つぎまで");
const u8 gText_RibbonsVar1[] = _("リボン: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("イベント"); // Unused
const u8 gText_Switch[] = _("いれかえ");
const u8 gText_PkmnInfo[] = _("じょうほう");
const u8 gText_PkmnSkills[] = _("のうりょく");
const u8 gText_BattleMoves[] = _("わざ");
const u8 gText_ContestMoves[] = _("コンテスト");
const u8 gText_Info[] = _("じょうほう");
const u8 gText_EggWillTakeALongTime[] = _("この タマゴは\nうまれるまで かなり かかりそう");
const u8 gText_EggWillTakeSomeTime[] = _("なにが うまれて くるのかな?\nうまれる まで まだまだ かかりそう");
const u8 gText_EggWillHatchSoon[] = _("ときどき うごいて いるようだ\nうまれる まで もうちょっと かな?");
const u8 gText_EggAboutToHatch[] = _("なかから おとが きこえてくる\nもうすぐ うまれそう!");
const u8 gText_HMMovesCantBeForgotten2[] = _("それは たいせつなわざです\nわすれさせることは できません!");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nmet at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nhatched at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nobtained in a trade.");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nobtained in a fateful\nencounter at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nprobably met at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nmet somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nhatched somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("An odd POKEMON EGG found\nby the DAY CARE couple.");
const u8 gText_PeculiarEggNicePlace[] = _("A peculiar POKEMON EGG\nobtained at the nice place.");
const u8 gText_PeculiarEggTrade[] = _("A peculiar POKEMON EGG\nobtained in a trade.");
const u8 gText_EggFromHotSprings[] = _("A POKEMON EGG obtained\nat the hot springs.");
const u8 gText_EggFromTraveler[] = _("An odd POKEMON EGG\nobtained from a traveler.");
const u8 gText_ApostropheSBase[] = _(" きち");
const u8 gText_OkayToDeleteFromRegistry[] = _("Is it okay to delete {STR_VAR_1}\nfrom the REGISTRY?");
const u8 gText_RegisteredDataDeleted[] = _("The registered data was deleted.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("There is no REGISTRY.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("とうろく かいじょ");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("グッズを おく");
const u8 gText_PutAway[] = _("グッズを もどす");
const u8 gText_Toss2[] = _("すてる");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("えらんだ グッズを へやに おきます!");
const u8 gText_StoreChosenDecorInPC[] = _("えらんだ グッズを パソコンに もどします!");
const u8 gText_ThrowAwayUnwantedDecors[] = _("いらなくなった グッズを すてます!");
const u8 gText_NoDecorations[] = _("There are no decorations.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("つくえ");
const u8 gText_Chair[] = _("いす");
const u8 gText_Plant[] = _("はちうえ");
const u8 gText_Ornament[] = _("おきもの");
const u8 gText_Mat[] = _("マット");
const u8 gText_Poster[] = _("ポスター");
const u8 gText_Doll[] = _("ぬいぐるみ");
const u8 gText_Cushion[] = _("クッション");
const u8 gText_Gold[] = _("ゴールド");
const u8 gText_Silver[] = _("シルバー");
const u8 gText_PlaceItHere[] = _("ここに おきますか?");
const u8 gText_CantBePlacedHere[] = _("ここには おけません!");
const u8 gText_CancelDecorating[] = _("おくのを やめますか?");
const u8 gText_InUseAlready[] = _("すでに おかれて います!");
const u8 gText_NoMoreDecorations[] = _("No more decorations can be placed.\nThe most that can be placed are {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("No more decorations can be placed.\nThe most that can be placed are {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("ここには おけません!\nつくえの うえなどに おいてください!"); // Unused
const u8 gText_CantPlaceInRoom[] = _("この グッズは\nじぶんの へやには おけません!");
const u8 gText_CantThrowAwayInUse[] = _("このグッズは おかれて いるので\nすてる ことが できません!");
const u8 gText_DecorationWillBeDiscarded[] = _("This {STR_VAR_1} will be discarded.\nIs that okay?");
const u8 gText_DecorationThrownAway[] = _("グッズを すてました!");
const u8 gText_StopPuttingAwayDecorations[] = _("もどすのを やめますか?");
const u8 gText_NoDecorationHere[] = _("ここに グッズは ありません!");
const u8 gText_ReturnDecorationToPC[] = _("このグッズを パソコンに もどしますか?");
const u8 gText_DecorationReturnedToPC[] = _("グッズを パソコンに もどしました!");
const u8 gText_NoDecorationsInUse[] = _("There are no decorations in use.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("There are no items.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("There's no MAIL here.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("What would you like to do with\n{STR_VAR_1}'s MAIL?");
const u8 gText_MessageWillBeLost[] = _("ないようは きえてしまいますが\nよろしいですか?");
const u8 gText_BagIsFull[] = _("The BAG is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("The MAIL was returned to the BAG\nwith its message erased.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("パパ");
const u8 gText_Mom[] = _("ママ");
const u8 gText_CoolnessContest[] = _("かっこよさコンテスト");
const u8 gText_BeautyContest[] = _("うつくしさコンテスト");
const u8 gText_CutenessContest[] = _("かわいさコンテスト");
const u8 gText_SmartnessContest[] = _("かしこさコンテスト");
const u8 gText_ToughnessContest[] = _("たくましさコンテスト");
const u8 gText_Information[] = _("とうろく せつめい");
const u8 gText_Yes[] = _("はい");
const u8 gText_No[] = _("いいえ");
const u8 gText_Lv50[] = _("レベル50");
const u8 gText_OpenLevel[] = _("オープンレベル");
const u8 gText_BattleFrontier[] = _("バトルフロンティア");
const u8 gText_Cool[] = _("かっこいい");
const u8 gText_Beauty[] = _("うつくしい");
const u8 gText_Cute[] = _("かわいい");
const u8 gText_Smart[] = _("かしこそうな");
const u8 gText_Tough[] = _("たくましい");
const u8 gText_Normal[] = _("ノーマル");
const u8 gText_Super[] = _("スーパー");
const u8 gText_Hyper[] = _("ハイパー");
const u8 gText_Master[] = _("マスター");
const u8 gText_SomeonesPC[] = _("だれかのパソコン");
const u8 gText_LanettesPC[] = _("マユミのパソコン");
const u8 gText_BillsPc[] = _("BILL'S PC");
const u8 gText_PlayersPC[] = _("{PLAYER}'s PC");
const u8 gText_HallOfFame[] = _("でんどういり");
const u8 gText_LogOff[] = _("スイッチをきる");
const u8 gText_Single2[] = _("シングル");
const u8 gText_Double2[] = _("ダブル");
const u8 gText_Multi[] = _("マルチ");
const u8 gText_MultiLink[] = _("つうしんマルチ");
const u8 gText_MenuOptionPokedex[] = _("POKeDEX");
const u8 gText_MenuOptionPokemon[] = _("POKEMON");
const u8 gText_MenuOptionBag[] = _("バッグ");
const u8 gText_MenuOptionPokenav[] = _("POKeNAV");
const u8 gText_MenuOptionSave[] = _("レポート");
const u8 gText_MenuOptionOption[] = _("せってい");
const u8 gText_MenuOptionExit[] = _("やめる");
const u8 gText_SouthernIsland[] = _("みなみのことう");
const u8 gText_BirthIsland[] = _("たんじょうのしま");
const u8 gText_FarawayIsland[] = _("さいはてのことう");
const u8 gText_NavelRock[] = _("へそのいわ");
const u8 gText_NormalTagMatch[] = _("NORMAL TAG MATCH");
const u8 gText_VarietyTagMatch[] = _("VARIETY TAG MATCH");
const u8 gText_UniqueTagMatch[] = _("UNIQUE TAG MATCH");
const u8 gText_ExpertTagMatch[] = _("EXPERT TAG MATCH");
const u8 gText_BattleBasics[] = _("たたかいのきほん");
const u8 gText_PokemonNature[] = _("POKEMON NATURE");
const u8 gText_PokemonMoves[] = _("POKEMON MOVES");
const u8 gText_Underpowered[] = _("ちからをはっきできない");
const u8 gText_WhenInDanger[] = _("ピンチになったら");
const u8 gText_BattlePokemon[] = _("BATTLE POKEMON");
const u8 gText_BattleTrainers[] = _("たたかう トレーナー");
const u8 gText_1F[] = _("1F");
const u8 gText_2F[] = _("2F");
const u8 gText_3F[] = _("3F");
const u8 gText_4F[] = _("4F");
const u8 gText_5F[] = _("5かい");
const u8 gText_6F[] = _("6かい");
const u8 gText_7F[] = _("7かい");
const u8 gText_8F[] = _("8かい");
const u8 gText_9F[] = _("9かい");
const u8 gText_10F[] = _("10かい");
const u8 gText_11F[] = _("11かい");
const u8 gText_B1F[] = _("ビ1かい");
const u8 gText_B2F[] = _("ビ2かい");
const u8 gText_B3F[] = _("ビ3かい");
const u8 gText_B4F[] = _("ビ4かい");
const u8 gText_Rooftop[] = _("おくじょう");
const u8 gText_ElevatorNowOn[] = _("げんざいのフロア");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("ランキングホール");
const u8 gText_ExchangeService[] = _("ひきかえサービス");
const u8 gText_SlateportCity[] = _("カイナシティ");
const u8 gText_Exit[] = _("おわる");
const u8 gText_YourPartysFull[] = _("Your party's full!{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("てもちポケモン");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("4つの ことばを くみあわせて");
const u8 gText_AndMakeYourProfile[] = _("プロフィールを つくろう!");
const u8 gText_CombineSixWordsOrPhrases[] = _("6つの ことばで メッセージを つくろう!");
const u8 gText_AndMakeAMessage[] = _("メッセージを つくろう!");
const u8 gText_FindWordsThatDescribeYour[] = _("いまの きもちに ぴったりあう");
const u8 gText_FeelingsRightNow[] = _("ことばを みつけよう!");
const u8 gText_WithFourPhrases[] = _("4つの ことばで"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("9つの ことばを くみあわせて");
const u8 gText_AndMakeAMessage2[] = _("メッセージを つくろう!");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("ことばを 1つだけ いれかえて");
const u8 gText_AndImproveTheBardsSong[] = _("オヤジのうたを よくして あげよう!");
const u8 gText_YourProfile[] = _("プロフィールは");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("たいせんが はじまるときの きもちは");
const u8 gText_WhatYouSayIfYouWin[] = _("たいせんに かったときの あいさつは");
const u8 gText_WhatYouSayIfYouLose[] = _("たいせんに まけたときの あいさつは");
const u8 gText_TheAnswer[] = _("こたえは");
const u8 gText_TheMailMessage[] = _("メールに のせる メッセージは");
const u8 gText_TheMailSalutation[] = _("はがきに のせる あいさつは"); // Unused
const u8 gText_TheBardsSong2[] = _("あたらしい うたは");
const u8 gText_CombineTwoWordsOrPhrases[] = _("2つの ことばを くみあわせて");
const u8 gText_AndMakeATrendySaying[] = _("はやらせたい ことばを つくろう!");
const u8 gText_TheTrendySaying[] = _("はやらせたい ことばは");
const u8 gText_IsAsShownOkay[] = _("これで いいですか?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("2つの ことばを くみあわせて");
const u8 gText_ToTeachHerAGoodSaying[] = _("いい ことばを おしえてあげよう!");
const u8 gText_FindWordsWhichFit[] = _("トレーナーの イメージに");
const u8 gText_TheTrainersImage[] = _("ぴったりの ことばを みつけよう!");
const u8 gText_TheImage[] = _("イメージは");
const u8 gText_OutOfTheListedChoices[] = _("ことばの なかから");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("クイズの こたえを えらぼう!");
const u8 gText_AndCreateAQuiz[] = _("クイズを つくろう!");
const u8 gText_PickAWordOrPhraseAnd[] = _("ことばの なかから ひとつを えらんで");
const u8 gText_SetTheQuizAnswer[] = _("クイズの こたえを つくろう!");
const u8 gText_TheAnswerColon[] = _("こたえは");
const u8 gText_TheQuizColon[] = _("クイズは"); // Unused
const u8 gText_ApprenticePhrase[] = _("でしの きめゼリフは");
const u8 gText_QuitEditing[] = _("へんしゅうを やめますか?");
const u8 gText_StopGivingPkmnMail[] = _("Stop giving the POKEMON MAIL?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("ショップの アンケートに こたえよう!");
const u8 gText_LetsReplyToTheInterview[] = _("インタビューに こたえよう!");
const u8 gText_AllTextBeingEditedWill[] = _("へんしゅうちゅうの ことばを");
const u8 gText_BeDeletedThatOkay[] = _("ぜんぶ けしても いいですか?");
const u8 gText_QuitEditing2[] = _("へんしゅうを やめますか?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("へんしゅうした ことばは ほぞん"); // Unused
const u8 gText_IsThatOkay[] = _("されませんが いいですか?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("なにか ことばを いれてください!"); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("ことばを ぜんぶ けすことは できません!");
const u8 gText_OnlyOnePhrase[] = _("かえられる ことばは 1つ までです!");
const u8 gText_OriginalSongWillBeUsed[] = _("うたを もとに もどします!");
const u8 gText_ThatsTrendyAlready[] = _("それは もう はやっています!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("2つの ことばを くみあわせてください!");
const u8 gText_QuitGivingInfo[] = _("ことばを おしえるのを やめますか?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("Stop giving the POKEMON MAIL?"); // Unused
const u8 gText_CreateAQuiz2[] = _("もんだいを つくってください!"); // Unused
const u8 gText_SetTheAnswer[] = _("こたえを えらんでください!"); // Unused
const u8 gText_CancelSelection[] = _("もとにもどして いいですか?"); // Unused
const u8 gText_Profile[] = _("プロフィール");
const u8 gText_AtTheBattlesStart[] = _("たいせんが はじまるとき");
const u8 gText_UponWinningABattle[] = _("たいせんに かったとき");
const u8 gText_UponLosingABattle[] = _("たいせんに まけたとき");
const u8 gText_TheBardsSong[] = _("オヤジのうた");
const u8 gText_WhatsHipAndHappening[] = _("はやっている ものは?");
const u8 gText_Interview[] = _("インタビュー");
const u8 gText_GoodSaying[] = _("いい ことば");
const u8 gText_FansQuestion[] = _("ファンのしつもん");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは?"); // Unused
const u8 gText_ApprenticesPhrase[] = _("でしの きめゼリフ");
const u8 gText_Questionnaire[] = _("アンケート");
const u8 gText_YouCannotQuitHere[] = _("ここでは とちゅうで");
const u8 gText_SectionMustBeCompleted[] = _("やめることは できません!");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}'s quiz");
const u8 gText_Lady[] = _("おねえ");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("もんだいを よんだら");
const u8 gText_QuestionPressTheAButton[] = _("Aボタンを おしてね!");
const u8 gText_TheQuizAnswerIs[] = _("クイズの こたえは?");
const u8 gText_LikeToQuitQuiz[] = _("クイズの チャレンジを");
const u8 gText_ChallengeQuestionMark[] = _("あきらめますか?");
const u8 gText_IsThisQuizOK[] = _("クイズは これで いいですか?");
const u8 gText_CreateAQuiz[] = _("もんだいを つくってください!");
const u8 gText_SelectTheAnswer[] = _("こたえを えらんでください!");
const u8 gText_LyricsCantBeDeleted[] = _("かしを けすことは できません!");
const u8 gText_PokemonLeague[] = _("POKEMON LEAGUE");
const u8 gText_PokemonCenter[] = _("POKEMON CENTER");
const u8 gText_Coolness[] = _("かっこよさ");
const u8 gText_Beauty3[] = _("うつくしさ");
const u8 gText_Cuteness[] = _("かわいさ");
const u8 gText_Smartness[] = _("かしこさ");
const u8 gText_Toughness[] = _("たくましさ");

const u8 gText_SaveFailedCheckingBackup[] = _("Save failed. Checking the backup\nmemory... Please wait.\n{COLOR RED}Time required: about 1 minute");
const u8 gText_BackupMemoryDamaged[] = _("バックアップきのうの こしょう または じゅみょうが\nきました。セーブすることは できませんが このまま\nゲームを あそぶことはできます");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}Game play cannot be continued.\nReturning to the title screen...");
const u8 gText_CheckCompleted[] = _("けんさが しゅうりょうしました!\nもういちど レポートを かきこみます\nしばらくおまちください");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Save completed.\n{COLOR RED}Game play cannot be continued.\nReturning to the title screen.");
const u8 gText_SaveCompletePressA[] = _("Save completed.\n{COLOR RED}Please press the A Button.");

const u8 gText_Ferry[] = _("れんらくせん");
const u8 gText_SecretBase[] = _("ひみつきち");
const u8 gText_Hideout[] = _("アジト");
const u8 gText_ResetRTCConfirmCancel[] = _("RTCを リセットします\nAで けってい Bで キャンセル");
const u8 gText_PresentTime[] = _("げんざいの ゲームない じかん");
const u8 gText_PreviousTime[] = _("ぜんかいの ゲームない じかん");
const u8 gText_PleaseResetTime[] = _("じかんを さいせってい してください");
const u8 gText_ClockHasBeenReset[] = _("じかんを さいせってい しました!\nレポートを かいています おまちください");
const u8 gText_SaveCompleted[] = _("レポートを かきこみました!");
const u8 gText_SaveFailed[] = _("Save failed...");
const u8 gText_NoSaveFileCantSetTime[] = _("レポートが ないので\nじかんの せっていは できません!");
const u8 gText_InGameClockUsable[] = _("ゲームない じかんの しゅうせい システムが\nつかえる ように なりました!");
const u8 gText_Spicy2[] = _("から");
const u8 gText_Dry2[] = _("しぶ");
const u8 gText_Sweet2[] = _("あま");
const u8 gText_Bitter2[] = _("にが");
const u8 gText_Sour2[] = _("すっぱ");
const u8 gText_Single[] = _("シングル");
const u8 gText_Double[] = _("ダブル");
const u8 gText_Knockout[] = _("バタンキュー");
const u8 gText_Mixed[] = _("MIXED");
const u8 gText_First[] = _("first");
const u8 gText_Second[] = _("second");
const u8 gText_Third[] = _("third");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} fainted...\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} survived the poisoning.\nThe poison faded away!\p");
#endif
const u8 gText_Marco[] = _("コウジ");
const u8 gText_TrainerCardName[] = _("なまえ");
const u8 gText_TrainerCardIDNo[] = _("IDNo.");
const u8 gText_TrainerCardMoney[] = _("おこづかい");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKeDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _("てん"); // Unused
const u8 gText_TrainerCardTime[] = _("プレイじかん");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{STR_VAR_1}'s TRAINER CARD");
const u8 gText_HallOfFameDebut[] = _("はじめてのでんどういり ");
const u8 gText_LinkBattles[] = _("つうしんたいせん");
const u8 gText_LinkCableBattles[] = _("ケーブルたいせん");
const u8 gText_WinsLosses[] = _("W:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  L:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("POKEMON TRADES");
const u8 gText_UnionTradesAndBattles[] = _("ユニオンたいせんとこうかん");
const u8 gText_BerryCrush[] = _("きのみクラッシュ");
const u8 gText_WaitingTrainerFinishReading[] = _("あいてが カードを みおわるのを\nまっています");
const u8 gText_PokeblocksWithFriends[] = _("ポロックS W/FRIENDS");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("ともだちとコンテスト ゆうしょう");
const u8 gText_BattlePtsWon[] = _("かちとった バトルポイント");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("バトルタワー");
const u8 gText_WinsStraight[] = _("W/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  STRAIGHT/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("バトルタワー");
const u8 gText_BattleDome[] = _("バトルドーム");
const u8 gText_BattlePalace[] = _("バトルパレス");
const u8 gText_BattleFactory[] = _("バトルファクトリー");
const u8 gText_BattleArena[] = _("バトルアリーナ");
const u8 gText_BattlePike[] = _("バトルチューブ");
const u8 gText_BattlePyramid[] = _("バトルピラミッド");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} SINGLE");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DOUBLE");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} LINK");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("もたせるべき");
const u8 gText_NoNeed[] = _("もたせない");
const u8 gText_AnnouncingResults[] = _("けっか はっぴょう!");
const u8 gText_PreliminaryResults[] = _("1じしんさの けっか!");
const u8 gText_Round2Results[] = _("2じしんさの けっか!");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_1}'s {STR_VAR_2} won!");
const u8 gText_CommunicationStandby[] = _("Communication standby...");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("ひらがな");
const u8 gText_Lower[] = _("カタカナ");
const u8 gText_Others[] = _("べつのにする");
const u8 gText_Symbols[] = _("きごう");
const u8 gText_Register2[] = _("とうろく");
const u8 gText_Exit2[] = _("おわる");
const u8 gText_QuitChatting[] = _("チャットを やめますか?");
const u8 gText_RegisterTextWhere[] = _("どこに とうろくしますか?");
const u8 gText_RegisterTextHere[] = _("ここに とうろくしますか?");
const u8 gText_InputText[] = _("ことばを いれて ください!");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} joined the chat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} left the chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Exiting the chat...");
const u8 gText_LeaderLeftEndingChat[] = _("The LEADER, {DYNAMIC 0}, has\nleft, ending the chat.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("とうろくが かわりました\nポケモンレポートに かきこみますか?");
const u8 gText_AlreadySavedFile_Chat[] = _("まえに かかれた レポートに\nうえから かいても いいですか?");
const u8 gText_SavingDontTurnOff_Chat[] = _("SAVING...\nDON'T TURN OFF THE POWER.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} saved the game.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("リーダーが やめると かいさん\nになりますが よろしいですか?");
const u8 gText_Hello[] = _("こんにちは");
const u8 gText_Pokemon2[] = _("ポケモン");
const u8 gText_Trade[] = _("こうかん");
const u8 gText_Battle[] = _("バトル");
const u8 gText_Lets[] = _("しよう!");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("ごめん..");
const u8 gText_YaySmileEmoji[] = _("YAY{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("サンキュー");
const u8 gText_ByeBye[] = _("バイバイ!");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} hatched from the EGG!");
const u8 gText_NicknameHatchPrompt[] = _("Would you like to nickname the newly\nhatched {STR_VAR_1}?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Are you ready to BERRY-CRUSH?\nPlease pick a BERRY for use.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("ほかの メンバーが きのみを\nえらぶまで おまちください");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}You ended up with {STR_VAR_1} units of\nsilky-smooth BERRY POWDER.{RESUME_MUSIC}\pYour total amount of BERRY POWDER\nis {STR_VAR_2}.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Recording your game results in the\nsave file.\lPlease wait.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("きのみクラッシュで もういちど\nあそびますか?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("つかう きのみが ありません\nゲームを しゅうりょうします");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("ぬけた メンバーが いるので\nゲームを しゅうりょうします");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Time's up.\pGood BERRY POWDER could not be\nmade...\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Communication standby...");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("かい");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1} BERRY");
ALIGNED(4) const u8 gText_TimeColon[] = _("じかん");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("おすはやさ");
ALIGNED(4) const u8 gText_Silkiness[] = _("サラサラぐあい");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _("ふん");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("びょう");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("かい/びょう");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("おした かいすう ランキング");
ALIGNED(4) const u8 gText_CrushingResults[] = _("つぶした けっか");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("ていねいさ ランキング");
ALIGNED(4) const u8 gText_CoopRankings[] = _("たすけあい ランキング");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("おすつよさ ランキング");
const u8 gText_BerryCrush2[] = _("きのみクラッシュ");
const u8 gText_PressingSpeedRankings[] = _("おすはやさ ランキング!");
const u8 gText_Var1Players[] = _("{STR_VAR_1} PLAYERS");
const u8 gText_SymbolsEarned[] = _("てにいれた シンボル");
const u8 gText_BattleRecord[] = _("たいせんの きろく");
const u8 gText_BattlePoints[] = _("バトルポイント");
const u8 gText_UnusedCancel[] = _("もどる "); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("バトルフロンティアの マップを みます");
const u8 gText_CheckTrainerCard[] = _("トレーナーカードを みます");
const u8 gText_ViewRecordedBattle[] = _("きろくした たいせんを みます");
const u8 gText_PutAwayFrontierPass[] = _("フロンティアパスを とじます");
const u8 gText_CurrentBattlePoints[] = _("いま たまっている バトルポイントです");
const u8 gText_CollectedSymbols[] = _("ここに シンボルを あつめます");
const u8 gText_BattleTowerAbilitySymbol[] = _("バトルタワー アビリティシンボル");
const u8 gText_BattleDomeTacticsSymbol[] = _("バトルドーム タクティクスシンボル");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("バトルパレス スピリットシンボル");
const u8 gText_BattleArenaGutsSymbol[] = _("バトルアリーナ ガッツシンボル");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("バトルファクトリー ノウレッジシンボル");
const u8 gText_BattlePikeLuckSymbol[] = _("バトルチューブ ラックシンボル");
const u8 gText_BattlePyramidBraveSymbol[] = _("バトルピラミッド ブレイブシンボル");
const u8 gText_ThereIsNoBattleRecord[] = _("げんざい たいせんきろくは ありません");
const u8 gText_BattleTower3[] = _("バトルタワー");
const u8 gText_BattleDome2[] = _("バトルドーム");
const u8 gText_BattlePalace2[] = _("バトルパレス");
const u8 gText_BattleArena2[] = _("バトルアリーナ");
const u8 gText_BattleFactory2[] = _("バトルファクトリー");
const u8 gText_BattlePike2[] = _("バトルチューブ");
const u8 gText_BattlePyramid2[] = _("バトルピラミッド");
const u8 gText_BattleTowerDesc[] = _("かちぬき ひたすら うえを めざす。\nさいのうを ためされる。");
const u8 gText_BattleDomeDesc[] = _("トーナメントを かちぬく。\nせんじゅつを ためされる。");
const u8 gText_BattlePalaceDesc[] = _("Watch your POKEMON battle!\nYour spirit will be tested.");
const u8 gText_BattleArenaDesc[] = _("Win battles with teamed-up POKEMON!\nYour guts will be tested.");
const u8 gText_BattleFactoryDesc[] = _("Aim for victory using rental POKEMON!\nYour knowledge will be tested.");
const u8 gText_BattlePikeDesc[] = _("3つの みちから 1つえらび かちすすむ。\nうんを ためされる。");
const u8 gText_BattlePyramidDesc[] = _("ちょうじょうを めざし ぼうけんする。\nゆうきを ためされる。");
const u8 gText_Powder[] = _("きのみのこな");
const u8 gText_BerryPickingRecords[] = _("ドードリオのきのみどりの きろく");
const u8 gText_BerriesPicked[] = _("きのみをとった かいすう");
const u8 gText_BestScore[] = _("さいこう とくてん");
const u8 gText_BerriesInRowFivePlayers[] = _("5にんで きのみを\nつづけてとった かいすう");
const u8 gText_BerryPickingResults[] = _("きのみの けっか はっぴょう!!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 3}10P{CLEAR_TO 43}30P{CLEAR_TO 83}50P{CLEAR_TO 119}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("じゅんいの はっぴょう!!");
const u8 gText_AnnouncingPrizes[] = _("しょうひんの はっぴょう!!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("The first-place winner gets\nthis {DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("{DYNAMIC 0}は いっぱいです..");
const u8 gText_FilledStorageSpace[] = _("{DYNAMIC 0}が いっぱいに\nなってしまった!");
const u8 gText_WantToPlayAgain[] = _("もういちど あそびますか?");
const u8 gText_SomeoneDroppedOut[] = _("だれかがぬけました\nつうしんを しゅうりょうします");
const u8 gText_SpacePoints[] = _("てん");
const u8 gText_CommunicationStandby3[] = _("Communication standby...");
const u8 gText_SpacePoints2[] = _("てん");
const u8 gText_SpaceTimes3[] = _("かい");
const u8 gText_PkmnJumpRecords[] = _("POKEMON JUMP RECORDS");
const u8 gText_JumpsInARow[] = _("さいこう ジャンプかいすう");
const u8 gText_BestScore2[] = _("さいこう とくてん");
const u8 gText_ExcellentsInARow[] = _("れんぞく EXCELLENT");
const u8 gText_AwesomeWonF701F700[] = _("Awesome score! You've\nwon {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("{DYNAMIC 0}が いっぱいに\nなってしまった!");
const u8 gText_CantHoldMore[] = _("{DYNAMIC 0}は いっぱいです..");
const u8 gText_WantToPlayAgain2[] = _("もういちど あそびますか?");
const u8 gText_SomeoneDroppedOut2[] = _("だれかがぬけました\nつうしんを しゅうりょうします");
const u8 gText_CommunicationStandby4[] = _("Communication standby...");
const u8 gText_LinkContestResults[] = _("{PLAYER}'s Link Contest Results");
const u8 gText_1st[] = _("1い");
const u8 gText_2nd[] = _("2い");
const u8 gText_3rd[] = _("3い");
const u8 gText_4th[] = _("4い");
const u8 gText_Friend[] = _("someone");
const u8 gText_Pokemon3[] = _("POKEMON"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS} で\nふしぎなもらいものを よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の メニューから\n'つうしん'を えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("'ゲームボーイアドバンスとつうしん'\nを せんたく してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の 'つうしん'を\nえらんで Aボタンを おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの よみこみを\nちゅうし しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん ちゅう です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん エラーです\nせつぞくを たしかめて ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん エラーです\nはじめから やりなおして ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS} に\nカードを よみこませて ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん しゅうりょう!");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな トレーナーが\nホウエンに やってきた!");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ エラー です\nデータが ほぞん できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}'s Single Battle Room Results");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}'s Double Battle Room Results");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}'s Multi Battle Room Results");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}'s Link Multi Battle Room Results");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}'s Single Battle Tourney Results");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}'s Double Battle Tourney Results");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}'s Single Battle Hall Results");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}'s Double Battle Hall Results");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}'s Battle Choice Results");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}'s Set KO Tourney Results");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}'s Battle Swap Single Results");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}'s Battle Swap Double Results");
const u8 gText_BattleQuestResults[] = _("{PLAYER}'s Battle Quest Results");
const u8 gText_Lv502[] = _("レベル50");
const u8 gText_OpenLv[] = _("オープンレベル");
const u8 gText_WinStreak[] = _("Win streak: {STR_VAR_1}");
const u8 gText_Current[] = _("げんざい");
const u8 gText_Record[] = _("さいこう");
const u8 gText_Prev[] = _("ぜんかい");
const u8 gText_RentalSwap[] = _("レンタル/こうかん");
const u8 gText_Total[] = _("つうさん");
const u8 gText_ClearStreak[] = _("Clear streak: {STR_VAR_1}");
const u8 gText_Championships[] = _("Championships: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Rooms cleared: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Times cleared:{CLEAR 5}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("KOs in a row: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Times: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Floors cleared: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("レベル50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("オープンレベル");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Win streak: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Clear streak: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Rooms cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("KOs in a row: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Floors cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1"), _("2"), _("3")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" and {STR_VAR_2} of the POKEMON species\nyou caught are inelegible");
const u8 gText_FrontierFacilityIncluding[] = _(".\pThese include ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" are inelegible");

const u8 gText_YesNo[] = _("はい \nいいえ");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("いないいないばあー");
const u8 gText_CommErrorCheckConnections[] = _("Communication error...\nPlease check all connections,\nthen turn the power OFF and ON.");
const u8 gText_CommErrorEllipsis[] = _("Communication error...");
const u8 gText_MoveCloserToLinkPartner[] = _(" つうしんあいてと ちかづいて ください\nしょうがいぶつが ないように してください");
const u8 gText_ABtnRegistrationCounter[] = _("Aボタンで うけつけに もどります");
const u8 gText_ABtnTitleScreen[] = _("Aボタンで タイトルに もどります");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}P LINK");
const u8 gText_BronzeCard[] = _("ブロンズ");
const u8 gText_CopperCard[] = _("カッパー");
const u8 gText_SilverCard[] = _("シルバー");
const u8 gText_GoldCard[] = _("ゴールド");
const u8 gText_Day[] = _("にち");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("けってい");
const u8 gText_Days[] = _("Days"); // Unused
const u8 gText_TimeColon2[] = _("じかん"); // Unused
const u8 gText_GameTime[] = _("Game time"); // Unused
const u8 gText_RTCTime[] = _("RTC time"); // Unused
const u8 gText_UpdatedTime[] = _("Updated time"); // Unused
const u8 gText_MenuPokedex[] = _("ずかん");
const u8 gText_MenuPokemon[] = _("ポケモン");
const u8 gText_MenuBag[] = _("バッグ");
const u8 gText_MenuPokenav[] = _("ナビ");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("レポート");
const u8 gText_MenuOption[] = _("せってい");
const u8 gText_MenuExit[] = _("とじる");
const u8 gText_MenuRetire[] = _("やめる");
const u8 gText_MenuRest[] = _("やすむ");
const u8 gText_MenuDexNav[] = _("サーチ");
const u8 gText_SafariBallStock[] = _("SAFARI BALLS\nStock: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBALLS  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Battle Pyramid\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("げんざい 1だんめ");
const u8 gText_Floor2[] = _("げんざい 2だんめ");
const u8 gText_Floor3[] = _("げんざい 3だんめ");
const u8 gText_Floor4[] = _("げんざい 4だんめ");
const u8 gText_Floor5[] = _("げんざい 5だんめ");
const u8 gText_Floor6[] = _("げんざい 6だんめ");
const u8 gText_Floor7[] = _("げんざい 7だんめ");
const u8 gText_Peak[] = _("げんざい ちょうじょう");
const u8 gText_LinkStandby2[] = _("Link standby...\n... ... B Button: Cancel");
const u8 gText_PressAToLoadEvent[] = _("Press the A Button to load event.\n... ... B Button: Cancel");
const u8 gText_LoadingEvent[] = _("Loading event...");
const u8 gText_DontRemoveCableTurnOff[] = _("つうしんケーブルを ぬかないで ください\nでんげんを きらないで ください");
const u8 gText_EventSafelyLoaded[] = _("できごとの よみこみが\nせいじょうに しゅうりょう しました");
const u8 gText_LoadErrorEndingSession[] = _("エラーがはっせいしました\nしゅうりょうします");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("ホウエンちほう");
const u8 gText_DexNational[] = _("ぜんこく");
const u8 gText_PokedexDiploma[] = _("PLAYER: {CLEAR 16}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nThis document certifies\nthat you have successfully\ncompleted your\n{STR_VAR_1} POKeDEX.\n\n{CLEAR_TO 66}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("ホウエンちほう");
const u8 gText_Kanto[] = _("KANTO");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} will be\nsent to {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("Bye-bye, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} sent over {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Take good care of {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_MaxHP[] = _("さいだいHP");
const u8 gText_Attack[] = _("こうげき");
const u8 gText_Defense[] = _("ぼうぎょ");
const u8 gText_Speed[] = _("すばやさ");
const u8 gText_SpAtk[] = _("とくこう");
const u8 gText_SpDef[] = _("とくぼう");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("ー");
const u8 gText_MixingRecords[] = _("Mixing records...");
const u8 gText_RecordMixingComplete[] = _("しゅうりょう しました\nおつかれさまでした");
const u8 gText_RentalPkmn2[] = _("RENTAL POKEMON");
const u8 gText_SelectFirstPkmn[] = _("Select the first POKEMON.");
const u8 gText_SelectSecondPkmn[] = _("Select the second POKEMON.");
const u8 gText_SelectThirdPkmn[] = _("Select the third POKEMON.");
const u8 gText_Rent[] = _("レンタルする");
const u8 gText_Summary[] = _("つよさ");
const u8 gText_Others2[] = _("べつのにする");
const u8 gText_Deselect[] = _("はずす");
const u8 gText_TheseThreePkmnOkay[] = _("Are these three POKEMON OK?");
const u8 gText_Yes2[] = _("はい");
const u8 gText_No2[] = _("いいえ");
const u8 gText_CantSelectSamePkmn[] = _("Can't select same ポケモン.");
const u8 gText_PkmnSwap[] = _("POKEMON SWAP");
const u8 gText_SelectPkmnToSwap[] = _("Select POKEMON to swap.");
const u8 gText_SelectPkmnToAccept[] = _("Select POKEMON to accept.");
const u8 gText_Swap[] = _("てばなす");
const u8 gText_Summary2[] = _("つよさをみる");
const u8 gText_Rechoose[] = _("べつのにする");
const u8 gText_QuitSwapping[] = _("こうかんを ちゅうし しますか?");
const u8 gText_Yes3[] = _("はい");
const u8 gText_No3[] = _("いいえ");
const u8 gText_PkmnForSwap[] = _("ポケモン FOR SWAP");
const u8 gText_Cancel3[] = _("もどる ");
const u8 gText_Swap2[] = _("てばなす"); // Unused
const u8 gText_Accept[] = _("うけとる"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Accept this POKEMON?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Same ポケモン in party already.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("しゅじんこう");
const u8 gText_SavingBadges[] = _("もっているバッジ");
const u8 gText_SavingPokedex[] = _("POKeDEX");
const u8 gText_SavingTime[] = _("プレイじかん");
const u8 gText_WirelessCommStatus[] = _("ワイヤレス つうしん じょうきょう");
const u8 gText_PeopleTrading[] = _("こうかん しているひと");
const u8 gText_PeopleBattling[] = _("たいせん しているひと");
const u8 gText_PeopleInUnionRoom[] = _("ユニオンルームに いるひと");
const u8 gText_PeopleCommunicating[] = _("つうしん しているひと");
const u8 gText_F700Players[] = _("{DYNAMIC 0} players");
const u8 gText_F701Players[] = _("{DYNAMIC 1} players");
const u8 gText_F702Players[] = _("{DYNAMIC 2} players");
const u8 gText_F703Players[] = _("{DYNAMIC 3} players");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("ふしぎなカード");
ALIGNED(4) const u8 gText_WonderNews[] = _("ふしぎなニュース");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("ジョイスポット");
ALIGNED(4) const u8 gText_Friend2[] = _("ともだち");
ALIGNED(4) const u8 gText_Exit3[] = _("おわる");
ALIGNED(4) const u8 gText_Receive[] = _("よみこむ");
ALIGNED(4) const u8 gText_Send[] = _("おくる");
ALIGNED(4) const u8 gText_Toss[] = _("すてる");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("ワイヤレスで いろいろな できごとを\nよみこみます");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("もっている ふしぎなカードを\nみることが できます");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("おくられてきた ニュースを\nみることが できます");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("タイトルに もどります");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("ふしぎなカードを もっていないので\nあたらしく カードを よみこみます");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("ふしぎなニュースを もっていないので\nあたらしく ニュースを よみこみます");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("どちらから ふしぎなカードを\nよみこみ ますか?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("どちらから ふしぎなニュースを\nよみこみ ますか?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Communication standby...\nB Button: Cancel"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Communicating...");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("つうしんが しゅうりょう しました");
ALIGNED(4) const u8 gText_CommunicationError[] = _("つうしんに しっぱい しました");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("つうしんを キャンセル しました");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("いまの ふしぎなカードを すてて\nあたらしい カードを よみこみますか?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("まだ カードの おくりものを もらって\nませんが ほんとうに よみこみますか?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("A WONDER CARD has been received\nfrom {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("A WONDER NEWS item has been\nreceived from {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("あたらしい ふしぎなカードが\nおくられて きました!");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("あたらしい ニュースが\nおくられて きました!");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("あたらしい スタンプが\nおくられて きました!");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("あたらしい トレーナーが\nおくられて きました!");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("おなじ ふしぎなカードを\nすでに もっています");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("おなじ ニュースを\nすでに もっています");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("おなじ スタンプを\nすでに もっています");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("スタンプが いっぱい なので\nもう おせません!");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("じぶんの きろくを\nジョイスポットに よみこませ ました!");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("この あいて からは ふしぎなカードを\nうけとれません!");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("この あいて からは ニュースを\nうけとれません!");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Nothing was sent over...");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("カードを どうしますか?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("ニュースを どうしますか?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Sending your WONDER CARD...");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Sending your WONDER NEWS item...");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Your WONDER CARD has been sent\nto {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Your WONDER NEWS item has been\nsent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("A STAMP has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("A GIFT has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("あいてが おなじ\nふしぎなカードを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("あいてが おなじ\nニュースを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("あいてが おなじ\nスタンプを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("あいてが つうしんを \nキャンセル しました");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("この あいて には\nふしぎなおくりものを わたせません");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("カードをすてると できごとも\nなくなりますが よいですか?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("ほんとうに ニュースを\nすてても よいですか?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("おくりものを もらってません\nが ほんとうに すてますか?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("レポートを かいています\nしばらく おまちください");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("レポートを かきこみました!\nAボタンを おしてください");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("ふしぎなカードを すてました");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("ニュースを すてました");
ALIGNED(4) const u8 gText_MysteryGift[] = _("ふしぎな おくりもの");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK {B_BUTTON}EXIT");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK {B_BUTTON}CANCEL");
const u8 gText_PlayersBattleResults[] = _("{PLAYER}'s BATTLE RESULTS");
const u8 gText_TotalRecordWLD[] = _("TOTAL RECORD W:{STR_VAR_1} L:{STR_VAR_2} D:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 83}WIN{CLEAR_TO 128}LOSE{CLEAR_TO 176}DRAW");
const u8 gText_CommunicationStandby5[] = _("Communication standby...");
const u8 gDaycareText_GetAlongVeryWell[] = _("2ひきの なかは\nとっても よい ようじゃ");
const u8 gDaycareText_GetAlong[] = _("2ひきの なかは\nまずまずの ようじゃ");
const u8 gDaycareText_DontLikeOther[] = _("2ひきの なかは\nそれほど よくないがなぁ");
const u8 gDaycareText_PlayOther[] = _("The two prefer to play with other\nPOKEMON than each other.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("おわる");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("タイムボード");
const u8 gText_TimeCleared[] = _("クリアタイム");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.");
const u8 gText_TrainerHill1F[] = _("1F");
const u8 gText_TrainerHill2F[] = _("2F");
const u8 gText_TrainerHill3F[] = _("3F");
const u8 gText_TrainerHill4F[] = _("4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("Teach which {STR_VAR_3} to\n{STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("Teach {STR_VAR_2}?");
const u8 gText_MoveRelearnerTeachMoveConfirmUseTm[] = _("Teach {STR_VAR_2}?\nThis will consume one {STR_VAR_3}.");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} is trying to learn\n{STR_VAR_2}.\pBut {STR_VAR_1} can't learn more\nthan four moves.\pDelete an older move to make\nroom for {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2, and {PAUSE 15}... {PAUSE 15}... {PAUSE 15}... {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} forgot {STR_VAR_3}.\pAnd...\p{STR_VAR_1} learned {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Give up trying to teach a new\nmove to {STR_VAR_1}?");
const u8 gText_MoveRelearnerStop[] = _("Stop trying to learn new\nmoves for {STR_VAR_1}?");;
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Which move should be\nforgotten?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("たたかうわざ");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("コンテストわざ");
const u8 gText_MoveRelearnerType[] = _("タイプ/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("いりょく/");
const u8 gText_MoveRelearnerAccuracy[] = _("めいちゅう/");
const u8 gText_MoveRelearnerAppeal[] = _("アピール");
const u8 gText_MoveRelearnerJam[] = _("ぼうがい");
const u8 gText_ClearAllSaveData[] = _("すべての セーブデータエリアを\nクリア しますか?");
const u8 gText_ClearingData[] = _("Clearing data...\nPlease wait.");
const u8 gText_IsThisTheCorrectTime[] = _("この じかんで よろしいですか?");
const u8 gText_Confirm3[] = _("けってい");
const u8 gText_Cancel4[] = _("もどる ");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Communication standby...\nAwaiting another player to choose.");
const u8 gText_BattleWasRefused[] = _("The battle was refused.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Refused the battle.{PAUSE 60}");
const u8 gText_NoWeather[] = _("NO WEATHER"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SUNNY"); // Unused
const u8 gText_Sunny2[] = _("SUNNY2"); // Unused
const u8 gText_Rain[] = _("RAIN"); // Unused
const u8 gText_Snow[] = _("ゆきやま"); // Unused
const u8 gText_Lightning[] = _("いなずま"); // Unused
const u8 gText_Fog[] = _("FOG"); // Unused
const u8 gText_VolcanoAsh[] = _("VOLCANO ASH"); // Unused
const u8 gText_Sandstorm[] = _("すなあらし"); // Unused
const u8 gText_Fog2[] = _("FOG2"); // Unused
const u8 gText_Seafloor[] = _("かいてい"); // Unused
const u8 gText_Cloudy[] = _("CLOUDY"); // Unused
const u8 gText_Sunny3[] = _("SUNNY3"); // Unused
const u8 gText_HeavyRain[] = _("HEAVY RAIN"); // Unused
const u8 gText_Seafloor2[] = _("SEAFLOOR2"); // Unused
const u8 gText_DelAll[] = _("DEL. ALL");
const u8 gText_Cancel5[] = _("もどる ");
const u8 gText_Ok2[] = _("ふつう");
const u8 gText_Quiz[] = _("QUIZ");
const u8 gText_Answer[] = _("ANSWER");
const u8 gText_PokeBalls[] = _("POKe BALLS");
const u8 gText_Berry[] = _("きのみ");
const u8 gText_Berries[] = _("きのみ");
const u8 gText_ExpShareOn[] = _("The Exp. Share has been turned on.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("The Exp. Share has been turned off.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("ゴースト");
const u8 gText_Boulderbadge[] = _("BOULDERBADGE");
const u8 gText_Cascadebadge[] = _("CASCADEBADGE");
const u8 gText_Thunderbadge[] = _("THUNDERBADGE");
const u8 gText_Rainbowbadge[] = _("RAINBOWBADGE");
const u8 gText_Soulbadge[] = _("SOULBADGE");
const u8 gText_Marshbadge[] = _("MARSHBADGE");
const u8 gText_Volcanobadge[] = _("VOLCANOBADGE");
const u8 gText_Earthbadge[] = _("EARTHBADGE");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("OAK: It's important to get to know\nyour POKEMON thoroughly.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("This is a list of your POKEMON,\n{PLAYER}.\pOpen this to check the skills\nand moves of your POKEMON.\pYou also choose POKEMON here if\nyou want to use an item on one.{PAUSE_UNTIL_PRESS}");
