SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "{JPN}おおきな ふねを つくる というのは\nのりものを つくる というよりも\lたてものを つくるのに にているんだよ"
	.string ""
	.string "$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "{JPN}おもたい てつで できている ふねが\nうみに うくなんて ふしぎ だろう?\pあれは 「ふりょく」 という げんりを\nおうよう しているんだ"
	.string ""
	.string ""
	.string "$"
