SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "{JPN}ジムリーダー アダンさまに おしえてもらった\nかれいな テクニックを みせたげる!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "{JPN}アダンさま ごめんね……$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "{JPN}すべての ゆかに ヒビを いれると\nなにかが おこるわよ$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "{JPN}せっかく ここまで これたのに\nあたしに まけるから\lアダンさまに あえないわね!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "{JPN}つよい じゃない!!\nかわいい みために だまされたわ$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "{JPN}あなたなら アダンさまと たたかっても\nいちげきで やられなくて すむかもね$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "{JPN}アダンさまの たたかう すがた……\pその うつくしさに こころ うばわれ\nわたくしも ポケモンを はじめましてよ$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "{JPN}たたかう すがたの\nうつくしさで まけましたわ……$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "{JPN}あなたさまの たたかう すがたも\nすばらしくってよ\pああっ……!\nポケモンに であえて よかったですわ$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "{JPN}おねえさんが しょうぶの きびしさ\nいろいろと おしえて あげちゃおっかな$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "{JPN}なんだ\nつよいんだ$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "{JPN}いいこと おしえて あげるね\pアダンさまに あいたいのなら\nすべての ゆかを 1かいずつ\lあるいて いけば いいの$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "{JPN}ホウエンちほうで いちばん\nレベルの たかい ポケモンジム……\pそれが ここ ルネジムよ!$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "{JPN}なんて レベルの たかい……$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "{JPN}レベルの たかい ジムに いることに\nまんぞく しないで\lほかにも しゅぎょうに いくほうが\lつよくなれそうだし なにより たのしそうね$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "{JPN}アダンさまと いっしょに\nポケモンを きたえて いるの\pかんたんに たおせると おもわないでね$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "{JPN}たおされちゃった……$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "{JPN}あなた みどころ あると おもうの\nいっしょに ここで ポケモン きたえない?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "{JPN}こおりの うえでの ひとふでがき\pそれが できる トレーナーは\nエレガントに うつくしいのよ!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "{JPN}ちょっとー!?$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "{JPN}あたりまえ だけど\nポケモンの つよさに\lおとなも こどもも かんけい ないよ$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "{JPN}ポケモンと いっしょに いると\nじかんが あっ というまに すぎるのよ!$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "{JPN}あっ!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "{JPN}まけた しょうぶも\nあっ というまに わすれたい……$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "{JPN}すっごく めずらしい ポケモンちゃんで\nたたかって あげても いいわよー!$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "{JPN}ちょっと!\nポケモンちゃんも ちゃんと みてくれた?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "{JPN}わたしが このジムに いるのは\nアダンさんが わたしの ポケモンちゃんを\lほめて くれたから なのよぉ\pあーあ ダンナに であうまえに\nアダンさんに であっていれば いまごろは…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "{JPN}うふふ……\nその ひっしな おかおが ステキよ$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "{JPN}あら\nてかげん しすぎて しまいましたわ……$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "{JPN}あなたでは アダンさまには\nきっと はが たちませんわよ うふふ……$"
